import { hash } from "../etsy/contracts";
import { LISTING_DIMENSIONS, listingAttributes, listingFactsHash, listingImageReviewHash, type ListingInput, type ListingProposal, type ListingReview } from "./contracts";
import { prepareListingTask, reviewListing, type ListingExecution, type ListingRole } from "./runtime";
export const listingFixtureId = (n: number) => `17000000-1111-4111-8111-${String(n).padStart(12,"0")}`;
/** Explicitly synthetic example. No provider, artifact, material or asset exists. */
export function listingFixture(now = Date.parse("2026-10-01T10:00:00Z")) {
  const id = listingFixtureId;
  const input: ListingInput = { version: "1.0.0", evidenceMode: "synthetic", factsVerifiedAt: new Date(now-60_000).toISOString(), productType: "original_design_on_base_product", aiAssisted: true,
    product: { version: "1.0", id:id(1),businessId:id(2),goalId:id(3),workflowRunId:id(4),productIdentity:"synthetic-fern-shirt",candidateId:id(5),decisionId:id(6),creativeApprovalId:id(7),creativeRunId:id(8),printfulResourceId:id(9),printfulReceiptId:id(10),productFactsHash:"a".repeat(64),approvedAt:new Date(now-60_000).toISOString(),expiresAt:new Date(now+3_600_000).toISOString(),title:"Synthetic product input",description:"Synthetic seed data only",quantity:3,priceMinor:3295,currency:"NZD",taxonomyId:482,shippingProfileId:21,readinessStateId:22,productionPartnerIds:[23],tags:["fern shirt"],materials:["cotton"],properties:[{propertyId:100,valueIds:[200],values:["White"],scaleId:null}],images:[{assetId:id(11),sha256:"b".repeat(64),storagePath:`${id(2)}/${id(8)}/version-1.png`,mediaType:"image/png",altText:"Finished white cotton shirt with a green fern print"}] },
    sources: [{id:id(30),businessId:id(2),recordId:id(10),recordType:"printful_receipt",verifiedAt:new Date(now-60_000).toISOString(),snapshotHash:"",snapshot:{garment:"A white cotton T-shirt with a green fern print on the front.",production:"The seller's design is printed to order by Printful, the declared production partner."}},
      {id:id(31),businessId:id(2),recordId:id(7),recordType:"creative_approval",verifiedAt:new Date(now-60_000).toISOString(),snapshotHash:"",snapshot:{aiDesign:"The seller used AI tools to create the original fern illustration."}}],
    facts: [{id:"garment",statement:"A white cotton T-shirt with a green fern print on the front.",kind:"product",evidence:[{sourceId:id(30),pointer:"/garment"}]},
      {id:"production",statement:"The seller's design is printed to order by Printful, the declared production partner.",kind:"production",evidence:[{sourceId:id(30),pointer:"/production"}]},
      {id:"ai-design",statement:"The seller used AI tools to create the original fern illustration.",kind:"rights",evidence:[{sourceId:id(31),pointer:"/aiDesign"}]}],
    disclosures: [{key:"production_partner",text:"Printed to order by our production partner, Printful.",factIds:["production"]},{key:"ai",text:"This original illustration was created with the assistance of AI tools.",factIds:["ai-design"]}],
    imagery: [{assetId:id(11),sha256:"b".repeat(64),productFactsHash:"a".repeat(64),kind:"finished_product_mockup",finishedProductShown:true,reviewArtifactId:id(12),reviewedAt:new Date(now-30_000).toISOString(),altText:"Finished white cotton shirt with a green fern print",reviewResultHash:"",reviewResult:{businessId:id(2),outcome:"PASS",observedProduct:"The reviewed synthetic image shows the entire finished white cotton shirt with the green fern print centered on the front. It is a garment mockup rather than standalone artwork.",productMatches:true,finishedProductShown:true,imageRightsVerified:true}}] };
  for(const source of input.sources) source.snapshotHash=hash(source.snapshot);
  input.product.productFactsHash=listingFactsHash(input);input.imagery[0].productFactsHash=input.product.productFactsHash;input.imagery[0].reviewResultHash=listingImageReviewHash(input.imagery[0]);
  const proposal: ListingProposal = {version:"1.0.0",title:{text:"Green Fern Print T-Shirt, White Cotton",factIds:["garment"]},description:[{text:"A green fern illustration is printed on the front of this white cotton T-shirt.",factIds:["garment"]}],tags:[{text:"fern shirt",factIds:["garment"]},{text:"botanical tee",factIds:["garment"]}],attributes:structuredClone(listingAttributes(input.product)),imageOrder:[id(11)],disclosureKeys:["production_partner","ai"]};
  const reasons: Record<typeof LISTING_DIMENSIONS[number],string> = {title:"The title identifies the white cotton shirt and fern print supported by garment.",description:"The paragraph describes only the garment and front print in the verified product fact.",tags:"Both tags describe the documented fern shirt without unsupported audience or material claims.",attributes:"Category, cotton material and White property exactly preserve the approved product snapshot.",imageOrder:"The lead mockup is bound to the exact finished white shirt, fern print and reviewed image hash.",disclosures:"The description includes both exact production-partner and AI-item disclosures from the facts.",factualClaims:"Every copy unit is entailed by garment; no shipping, certification, sales or rights promise was added."};
  const review: ListingReview = {version:"1.0.0",verdict:"APPROVE",checks:Object.fromEntries(LISTING_DIMENSIONS.map(d=>[d,{status:"passed",rationale:reasons[d]}])) as ListingReview["checks"]};
  const execution = (role:ListingRole, output:ListingProposal|ListingReview):ListingExecution => {
    const prepared=prepareListingTask(input,role,id(role==="specialist"?20:21),role==="reviewer"?proposal:undefined,now,role==="reviewer"?execution("specialist",proposal):undefined);
    return {version:"1.0.0",mode:input.evidenceMode==="synthetic"?"synthetic":"live_model",taskId:prepared.context.taskContract.id,workerKey:`listing.${role}`,workerVersion:"1.0.0",providerModelId:prepared.request.model.providerModelId,providerRequestId:`synthetic-${role}`,requestHash:prepared.requestHash,outputHash:hash(output),completedAt:new Date(now).toISOString()};
  };
  return {input,proposal,review,now,execution,record:()=>reviewListing(input,proposal,review,execution("specialist",proposal),execution("reviewer",review),now)};
}
