import Link from "next/link";
import { notFound } from "next/navigation";
import type { WorkspaceIntent, WorkspaceSearch } from "@/lib/core-ui/workspace-context";
import { workspaceValue } from "@/lib/core-ui/workspace-context";
import { carryWorkspace } from "@/lib/core-ui/workspace-navigation";
import { consoleObject, consoleValidId } from "@/lib/core-ui/console-collections";
import { ConsoleShell } from "./console-shell";
import "./console-workspace.css";
const text = (v: unknown, fallback = "Not recorded") => typeof v === "string" && v ? v : fallback;
const obj = (v: unknown): Record<string, unknown> => consoleObject(v) ? v : {};
const rows = (v: unknown) => Array.isArray(v) ? v.filter(consoleObject) : [];
function Facts({ item }: { item: Record<string, unknown> }) { return <dl className="r08Facts">{Object.entries(item).filter(([, v]) => v !== undefined && (v === null || ["string", "number", "boolean"].includes(typeof v))).map(([k, v]) => <div key={k}><dt>{k.replace(/([A-Z])/g, " $1")}</dt><dd>{v === null ? "Unknown / not recorded" : String(v)}</dd></div>)}</dl>; }
export async function ConsoleOwnerRecords({ scope, query, view }: { scope: WorkspaceIntent; query: WorkspaceSearch; view: "products-catalog" | "decision-log" | "knowledge" }) {
  const { context, businessId, state } = scope, questId = state?.selected?.id;
  const type = workspaceValue(query, "type");
  if (view === "products-catalog" && type && !["products", "listings"].includes(type)) notFound();
  const dataset = view === "decision-log" ? "decisions" : type === "listings" ? "listings" : "products";
  const title = view === "knowledge" ? "Knowledge" : view === "decision-log" ? "Decisions" : dataset === "listings" ? "Listings" : "Products";
  const pageText = workspaceValue(query, "page") ?? "1", search = workspaceValue(query, "q") ?? "", selected = workspaceValue(query, "selected");
  if (!/^[1-9]\d{0,3}$/.test(pageText) || search.length > 120 || /[\u0000-\u001f\u007f]/.test(search) || selected && (selected.length > 100 || view !== "decision-log" && !consoleValidId(selected))) notFound();
  const page = Number(pageText), offset = (page - 1) * 25;
  const params = new URLSearchParams({ view }); if (businessId) params.set("business", businessId); if (questId) params.set("quest", questId); if (view === "products-catalog") params.set("type", dataset);
  if (search) params.set("q", search); if (page > 1) params.set("page", String(page)); if (selected) params.set("selected", selected);
  const url = (changes: Record<string, string | null>) => { const p = new URLSearchParams(params); for (const [key, value] of Object.entries(changes)) { if (value === null) p.delete(key); else p.set(key, value); } return carryWorkspace(`/dashboard?${p}`, context.readSearch); };
  let items: Record<string, unknown>[] = [], detail: Record<string, unknown> | null = null, total: number | null = null, unavailable = scope.unavailable, missing = false;
  if (businessId && !unavailable) {
    if (view === "knowledge") {
      const base = () => context.supabase.from("installed_packs").select("id,business_id,root_pack_id,status,created_at", { count: "exact" }).eq("business_id", businessId);
      const [list, exact] = await Promise.all([base().order("created_at", { ascending: false }).order("id", { ascending: false }).range(offset, offset + 24), selected ? context.supabase.from("installed_packs").select("id,business_id,root_pack_id,status,created_at,snapshot", { count: "exact" }).eq("business_id", businessId).eq("id", selected).maybeSingle() : null]);
      unavailable = !!list.error || !Array.isArray(list.data) || !Number.isSafeInteger(list.count) || list.data.length !== Math.min(25, Math.max(0, (list.count ?? 0) - offset)) || !!exact?.error;
      if (!unavailable) {
        items = list.data!; total = list.count; detail = exact?.data ?? null; missing = !!selected && !detail;
        const ids = [...new Set([...items, ...(detail ? [detail] : [])].map(i => String(i.root_pack_id)))];
        const packs = ids.length ? await context.supabase.from("packs").select("id,name,version,status").in("id", ids).limit(26) : { data: [], error: null };
        if (packs.error || packs.data?.length !== ids.length) unavailable = true;
        else if (packs.data?.some(p => typeof p.name !== "string" || typeof p.version !== "string")) unavailable = true;
        else items = items.map(i => ({ ...i, title: packs.data?.find(p => p.id === i.root_pack_id)?.name ?? "Pack unavailable", packVersion: packs.data?.find(p => p.id === i.root_pack_id)?.version, qualification: packs.data?.find(p => p.id === i.root_pack_id)?.status }));
      }
    } else {
      const result = await context.supabase.rpc("r08_owner_read", { p_business_id: businessId, p_goal_id: questId ?? null, p_dataset: dataset, p_query: { limit: 25, offset, query: search, ...(selected ? { selectedId: selected } : {}) } });
      const data = obj(result.data), selection = obj(data.selection);
      unavailable = !!result.error || data.businessId !== businessId || data.goalId !== (questId ?? null) || data.dataset !== dataset || !Number.isSafeInteger(data.total) || Number(data.total) < 0 || data.limit !== 25 || data.offset !== offset || !Array.isArray(data.items) || data.items.length !== Math.min(25, Math.max(0, Number(data.total) - offset)) || rows(data.items).some(i => i.businessId !== businessId || typeof i.id !== "string") || !["none", "found", "missing"].includes(String(selection.status)) || (selected ? selection.status === "none" : selection.status !== "none") || (selection.status === "found" && (obj(selection.item).id !== selected || obj(selection.item).businessId !== businessId));
      if (!unavailable) { items = rows(data.items); total = Number(data.total); detail = selection.status === "found" ? obj(selection.item) : null; missing = selection.status === "missing"; }
    }
  }
  return <ConsoleShell active={view} context={context} navigationBusinessId={businessId ?? undefined}><section className="r08Workspace"><header><h1>{title}</h1><p>{context.businesses.find(b => b.id === businessId)?.name ?? "Choose a Business"} · {questId ? `Quest ${state?.selected?.title}` : "Business records without a selected Quest"}</p></header>
    <nav className="r08Links">{businessId ? <Link href={carryWorkspace(`/dashboard?view=overview&business=${businessId}`, context.readSearch)}>Selected Quest overview</Link> : <Link href="/dashboard">Choose Business</Link>}{questId && businessId ? <Link href={`/dashboard?view=${view}&business=${businessId}${view === "products-catalog" ? `&type=${dataset}` : ""}`}>All Business records</Link> : null}{view === "products-catalog" ? <><Link href={url({ type: "products", selected: null, page: null })}>Product packages</Link><Link href={url({ type: "listings", selected: null, page: null })}>Linked Listings</Link><Link href={carryWorkspace(`/dashboard?view=research&business=${businessId}`, context.readSearch)}>Candidate research</Link></> : view === "decision-log" ? <><Link href={carryWorkspace(`/dashboard?view=decisions&business=${businessId}`, context.readSearch)}>Needs owner queue</Link><Link href={carryWorkspace(`/dashboard?view=activity&business=${businessId}`, context.readSearch)}>Underlying audit events</Link></> : null}</nav>
    {view !== "knowledge" ? <form className="r08Scope" method="get">{[...params].filter(([k]) => !["q", "page"].includes(k)).map(([k, v]) => <input key={k} type="hidden" name={k} value={v}/>)}<label>Search saved {title.toLowerCase()}<input name="q" defaultValue={search} maxLength={120}/></label><button type="submit">Search</button></form> : null}
    <div className="r08Scroll" tabIndex={0} role="region" aria-label={`${title} records and exact detail`}>
      {view === "knowledge" ? <p className="r08Warning">Existing packs only. Reviewed reusable learning and its application are unavailable until R09. An installation is not proof of review, fresh sources or live capability qualification.</p> : view === "products-catalog" ? <p className="r08Warning">Readiness catalog: saved packages and provider associations only. Product identity, exact selling variants, account fees and supported fulfilment remain unqualified until R13–R15. Nothing here is labelled sale-ready.</p> : <p>Searchable saved automated and human decisions. Owner notices retain their original request and acknowledgment; resolved does not mean execution resumed or charges settled.</p>}
      {unavailable ? <p role="alert">This scoped read is unavailable or incomplete. No empty result or replacement selection is claimed.</p> : null}
      <div className="r08Split"><div><ul className="r08Records">{items.map(item => <li key={text(item.id)}><Link href={url({ selected: text(item.id) })}>{text(item.title, text(item.label, "Saved pack"))}</Link><p>{text(item.kind, "Installed pack")} · {text(item.status, text(item.readiness, "Recorded"))} · {text(item.at, text(item.created_at))}</p><p>{text(item.reason, text(item.actor, ""))}</p><small>{text(item.id)}</small></li>)}</ul>{!items.length && !unavailable ? <p>No saved {title.toLowerCase()} match this exact scope.</p> : null}</div>
      {selected ? <section className="r08Card" aria-label="Exact selected record"><header><h2>Exact selected record</h2><Link href={url({ selected: null })}>Close detail</Link></header>{missing ? <p>This exact record is not in this Business/Quest. No substitute was selected.</p> : detail ? <><h3 className="r08Title">{text(detail.title, view === "knowledge" ? "Installed pack snapshot" : "Saved record")}</h3><p>{text(detail.status, text(detail.readiness, "Recorded"))} · {text(detail.actor, "Exact saved evidence")}</p>{detail.reason ? <p>{text(detail.reason)}</p> : null}<details className="r08Exact"><summary>Exact saved identities</summary><Facts item={detail}/></details>
        {detail.workflowRunId ? <Link href={carryWorkspace(`/dashboard?view=work&business=${businessId}&selected=${detail.workflowRunId}&episode=${detail.workflowRunId}`, context.readSearch)}>Exact episode and Agents</Link> : null}
        {dataset === "products" && view !== "knowledge" ? <><Link href={carryWorkspace(`/dashboard?view=library&type=records&business=${businessId}&selected=${detail.id}`, context.readSearch)}>Exact package artifact</Link><h3>Readiness blockers</h3><ul>{Array.isArray(detail.blockers) ? detail.blockers.map(b => <li key={String(b)}>{String(b)}</li>) : null}</ul><h3>Linked Listings · {String(detail.listingCount ?? "Unknown")}</h3>{rows(detail.listings).map(l => <p key={text(l.id)}><Link href={url({ type: "listings", selected: text(l.id), page: null })}>Saved draft {text(l.id)} · {text(l.status)}</Link></p>)}{Number(detail.listingCount) > 25 ? <p>25 linked drafts loaded. Use Linked Listings for bounded full history.</p> : null}</> : null}
        {dataset === "listings" && view !== "knowledge" ? <><Link href={url({ type: "products", selected: text(detail.packageArtifactId), page: null })}>Exact source Product Package</Link><p>Draft: {text(detail.draftReadback)}. Fees: {text(detail.feeReady)}. Fulfilment: {text(detail.fulfilmentReady)}. Public selling: not ready.</p><h3>Supplier/store/variant association</h3>{consoleObject(detail.supplier) ? <Facts item={detail.supplier}/> : <p>No matching supplier resource and receipt association is recorded. Store, variant and supplier settings remain unknown.</p>}</> : null}
        {detail.kind === "owner_notice" ? <Link href={carryWorkspace(`/dashboard?view=decisions&business=${businessId}&decision=${detail.recordId}`, context.readSearch)}>Exact owner action and resume conditions</Link> : null}
        {view === "knowledge" ? <><h3>Version, sources and freshness</h3>{rows(obj(detail.snapshot).releases).map(release => { const manifest = obj(release.manifest); return <section key={text(release.id)}><h4>{text(manifest.name)} · {text(manifest.version)}</h4><p>Saved qualification: {text(release.status)} · Business installation: {text(detail.status)}</p>{rows(manifest.knowledge).map((k, index) => <details className="r08Exact" key={index}><summary>{text(k.name, text(k.key, "Knowledge module"))} · {text(k.version)}</summary><p>{typeof k.verifiedAt === "string" && Number.isFinite(Date.parse(k.verifiedAt)) && typeof k.freshnessDays === "number" ? Date.parse(k.verifiedAt) + k.freshnessDays * 86400000 < Date.now() ? "Stale saved source window" : "Within declared source window; not continuously refreshed" : "Freshness unknown"}. Review acceptance is not established by this installation.</p><pre tabIndex={0} aria-label="Exact saved Knowledge sources and freshness">{JSON.stringify(k, null, 2)}</pre></details>)}</section>; })}<p>Historical workflow snapshots remain pinned. This read does not install or update Knowledge.</p><Link href={`/dashboard/packs?business=${businessId}`}>Pack tools</Link></> : null}
        <details className="r08Exact"><summary>Saved evidence and provenance</summary><pre tabIndex={0} aria-label="Exact saved record evidence">{JSON.stringify(detail, null, 2)}</pre></details>
      </> : <p>Exact record unavailable</p>}</section> : null}</div>
    </div><footer className="r08Pager"><span>{total === null ? "Count unavailable" : `${items.length ? offset + 1 : 0}–${offset + items.length} of ${total}`} · page {page}</span><nav className="r08Links">{page > 1 ? <Link href={url({ page: String(page - 1) })}>Previous</Link> : null}{total !== null && offset + items.length < total ? <Link href={url({ page: String(page + 1) })}>Next</Link> : null}</nav></footer>
  </section></ConsoleShell>;
}
