import Link from "next/link";
import { notFound } from "next/navigation";
import type { WorkspaceIntent, WorkspaceSearch } from "@/lib/core-ui/workspace-context";
import { carryWorkspace } from "@/lib/core-ui/workspace-navigation";
import { verifyOwnerBusiness } from "@/lib/core-ui/owner-business";
import { loadKnowledgePage } from "@/lib/core-ui/console-knowledge-data";
import { knowledgeObject, knowledgeQuery, knowledgeSections, unavailableKnowledgePage, type KnowledgeSection } from "@/lib/core-ui/console-knowledge-query";
import { ConsoleShell } from "./console-shell";
import { KnowledgeForm } from "./console-knowledge-forms";
import "./console-workspace.css";
import "./console-knowledge-workspace.css";

const text = (value: unknown, fallback = "Not recorded") => typeof value === "string" && value ? value : fallback;
const object = (value: unknown) => knowledgeObject(value) ? value : {};
const rows = (value: unknown): Record<string, unknown>[] => Array.isArray(value) ? value.filter(knowledgeObject) : [];
const strings = (value: unknown): string[] => Array.isArray(value) ? value.filter((item): item is string => typeof item === "string") : [];
const labels: Record<KnowledgeSection, string> = { installed: "Installed packs", proposals: "Private proposals", releases: "Reviewed guidance", applications: "Business applications", usage: "Historical usage" };
const safeSource = (value: unknown) => { try { const url = new URL(String(value)); return ["https:", "http:"].includes(url.protocol) && !url.username && !url.password ? url.href : null; } catch { return null; } };
function List({ value, empty = "None recorded" }: { value: unknown; empty?: string }) { const items = strings(value); return items.length ? <ul>{items.map((item, index) => <li key={index}>{item}</li>)}</ul> : <p>{empty}</p>; }
function Facts({ values }: { values: Record<string, unknown> }) { return <dl className="r08Facts">{Object.entries(values).map(([key, value]) => <div key={key}><dt>{key}</dt><dd>{value === null || value === undefined ? "Not recorded" : String(value)}</dd></div>)}</dl>; }
function Exact({ record }: { record: Record<string, unknown> }) { return <details className="r08Exact"><summary>Exact saved identities and provenance</summary><pre tabIndex={0} aria-label="Exact Knowledge record">{JSON.stringify(record, null, 2)}</pre></details>; }
function Process() { return <section aria-label="Knowledge review process"><h2>Private evidence → reviewed guidance</h2><ol><li>Submit a provisional lesson with immutable evidence from this Business</li><li>A trusted platform reviewer examines evidence, conflicting sources and generalizability</li><li>Redact private Business, customer and account content. If redaction removes necessary proof, keep the lesson private or unqualified</li><li>Platform promotion creates an immutable reviewed version with scope, limitations, source dates and expiry</li><li>Deliberately apply an exact reviewed version to this Business for future plan selection</li></ol><p>Review and promotion are unavailable to ordinary owners. This workspace cannot self-qualify a lesson. Re-review needs new evidence and a new version; dated snapshots are not continuously refreshed.</p></section>; }
function InstalledDetail({ item }: { item: Record<string, unknown> }) { return <><h3>Installed pack snapshot</h3><p>{text(item.title)} · {text(item.version)} · {text(item.status)}</p><p>Installed {text(item.activated_at)}. Installation alone does not prove learned-lesson review, current sources or live capability qualification.</p><h3>Version, sources and freshness</h3>{rows(object(item.snapshot).releases).map((release, index) => { const manifest = object(release.manifest); return <section key={text(release.id, String(index))}><h4>{text(manifest.name)} · {text(manifest.version)}</h4><p>Saved qualification: {text(release.status)}</p>{rows(manifest.knowledge).map((knowledge, index) => <details className="r08Exact" key={index}><summary>{text(knowledge.name, text(knowledge.key, "Knowledge module"))} · {text(knowledge.version)}</summary><p>{typeof knowledge.verifiedAt === "string" && Number.isFinite(Date.parse(knowledge.verifiedAt)) && typeof knowledge.freshnessDays === "number" ? Date.parse(knowledge.verifiedAt) + knowledge.freshnessDays * 86400000 < Date.now() ? "Stale saved source window" : "Within declared source window; not continuously refreshed" : "Freshness unknown"}. Review acceptance is not established by this installation.</p><pre tabIndex={0} aria-label="Exact saved Knowledge sources and freshness">{JSON.stringify(knowledge, null, 2)}</pre></details>)}</section>; })}<p>Historical workflow snapshots remain pinned. Reading this snapshot does not install or update Knowledge.</p></>; }
function Guidance({ content }: { content: Record<string, unknown> }) { return <><h3>Reusable guidance</h3><p>{text(content.guidance)}</p><h3>Why it applies</h3><p>{text(content.scope)}</p><h3>Limitations</h3><List value={content.limitations}/><h3>Conflicting evidence</h3><List value={content.conflicts} empty="No conflicts recorded in this reviewed version; this is not proof that none exist"/><h3>Generalizability evidence</h3>{typeof content.generalizability === "string" ? <p>{content.generalizability}</p> : <List value={content.generalizability} empty="Inspect the exact reviewed provenance for the recorded generalizability assessment"/>}</>; }

export async function ConsoleKnowledgeWorkspace({ scope, query: search }: { scope: WorkspaceIntent; query: WorkspaceSearch }) {
  let query; try { query = knowledgeQuery(search); } catch { notFound(); }
  const { context, businessId, state } = scope;
  if (businessId && !scope.unavailable && !await verifyOwnerBusiness(context, businessId)) notFound();
  const page = businessId && !scope.unavailable ? await loadKnowledgePage(context, businessId, query) : unavailableKnowledgePage();
  const businessName = context.businesses.find(business => business.id === businessId)?.name ?? "Selected Business";
  const params = new URLSearchParams({ view: "knowledge", type: query.section });
  if (businessId) params.set("business", businessId);
  if (query.page > 1) params.set("page", String(query.page));
  if (query.search) params.set("q", query.search);
  if (query.selectedId) params.set("selected", query.selectedId);
  const href = (changes: Record<string, string | null> = {}) => { const next = new URLSearchParams(params); for (const [key, value] of Object.entries(changes)) { if (value === null) next.delete(key); else next.set(key, value); } return carryWorkspace(`/dashboard?${next}`, context.readSearch); };
  const item = page.detail, content = object(item?.content), head = object(item?.application);
  const form = businessId ? { businessId, ownerId: context.userId, businessName, returnTo: href() } : null;
  const releaseSelectable = item?.status === "current";
  const applicationReleaseStatus = text(item?.releaseStatus, text(item?.status));
  const outcome = typeof search.outcome === "string" ? search.outcome : null;
  const confirmedOutcome = item && query.selectedId === item.id && (query.section === "proposals" && outcome === "propose" ? "Private proposal saved. Platform review and safe redaction are required before reuse." : query.section === "applications" && ["apply", "rollback", "remove"].includes(outcome ?? "") && item.operation === outcome ? item.isCurrent !== true ? "Saved application verified. The current Business selection has since changed; inspect its history before continuing." : outcome === "remove" ? "Guidance removed from future selection for this Business. Historical pins remain unchanged." : item.status !== "applied" ? "Saved application verified. This version is now unavailable for new work; inspect its current review status." : "Exact reviewed version selected for future work in this Business. Historical and in-flight pins remain unchanged." : null);
  return <ConsoleShell active="knowledge" context={context} navigationBusinessId={businessId ?? undefined}><section className="r08Workspace r09Workspace">
    <header className="r09Header"><div><h1>Knowledge</h1><p>{businessName} · Business-wide knowledge{state?.selected ? ` · from Quest ${state.selected.title}` : ""}</p></div><Link href={businessId ? carryWorkspace(`/dashboard?view=overview&business=${businessId}`, context.readSearch) : "/dashboard"}>Back to overview</Link></header>
    <nav className="r09Tabs" aria-label="Knowledge collections">{knowledgeSections.map(section => <Link key={section} aria-current={section === query.section ? "page" : undefined} href={href({ type: section, selected: null, page: null, q: null })}>{labels[section]}</Link>)}</nav>
    <p className="r09Boundary">Private evidence stays in its Business. Reuse transfers information only, never account access, rules, budgets, authorization or qualification.</p>
    {query.section !== "installed" ? <form className="r09Search" method="get">{[...new URL(href(), "https://owner.invalid").searchParams].filter(([key]) => !["q", "page"].includes(key)).map(([key, value]) => <input key={key} type="hidden" name={key} value={value}/>)}<label>Search {labels[query.section].toLowerCase()}<input name="q" defaultValue={query.search} maxLength={120}/></label><button type="submit">Search</button></form> : null}
    {confirmedOutcome ? <p role="status" className="r09Outcome">{confirmedOutcome}</p> : null}
    {!page.available ? <p role="alert" className="r08Warning">This scoped read is unavailable or incomplete. No empty result or replacement selection is claimed.</p> : null}
    <div className="r09Body"><section className="r09ListPane" tabIndex={0} aria-label={`${labels[query.section]} bounded records`}>
      <h2>{labels[query.section]}</h2>
      {query.section === "installed" ? <p>Installed pack snapshots and their historical source windows. Learned guidance and its deliberate applications are separate collections.</p> : query.section === "proposals" ? <p>Business-private provisional findings. A successful local experiment is not reusable qualification.</p> : query.section === "releases" ? <p>Reviewed, redacted, immutable versions. External sources remain dated snapshots with their own verification and expiry.</p> : query.section === "applications" ? <p>Append-only Business selections. Apply, rollback and removal affect future selection; earlier work keeps its pins.</p> : <p>Exact historical snapshots show which version was pinned to a plan and its tasks. Actual use requires a matching request or decision receipt. Current release changes do not rewrite these pins.</p>}
      {query.section === "proposals" && form && page.available ? <details className="r09Propose"><summary>Propose a private lesson</summary><KnowledgeForm key={`${businessId}:new`} {...form} proposal={{ proposalId: null, expectedVersion: 0 }}/></details> : null}
      <ul className="r09List">{page.items.map(record => <li key={text(record.id)} data-knowledge-record={text(record.id)}><Link aria-current={query.selectedId === record.id ? "true" : undefined} href={href({ selected: text(record.id) })}>{text(record.title, query.section === "usage" ? `Plan version ${String(record.planVersion ?? "unknown")}` : `${text(record.packKey, "Saved Knowledge")} · ${text(record.version, "no selected version")}`)}</Link><p>{query.section === "usage" ? `${Number.isSafeInteger(record.knowledgeCount) ? record.knowledgeCount : rows(record.knowledge).length} pinned versions` : `${text(record.status)}${record.version ? ` · v${record.version}` : ""}`}</p><small>{text(record.createdAt, text(record.activated_at, text(record.reviewedAt)))}{record.isCurrent === true ? " · current selection" : ""}</small></li>)}</ul>
      {!page.items.length && page.available ? <p className="r09Empty">No saved {labels[query.section].toLowerCase()} match this exact Business and search.</p> : null}
    </section>
    <section className="r09Detail" tabIndex={0} aria-label="Exact selected Knowledge record" data-knowledge-detail={item ? text(item.id) : undefined}>
      {query.selectedId ? <header><h2>Exact selected record</h2><Link href={href({ selected: null })}>Close detail</Link></header> : null}
      {page.selection === "missing" ? <p>This exact record is not available in this Business. No substitute was selected.</p> : !page.available ? <p>Exact record unavailable. Reload when this scoped read is available.</p> : !item ? <><Process/><p>Select a record to inspect its exact evidence, version and history.</p></> : <>
        {query.section === "installed" ? <><InstalledDetail item={item}/><Link href={`/dashboard/packs?business=${businessId}`}>Pack tools and installation history</Link></> : null}
        {query.section === "proposals" ? <>
          <h3>{text(item.title)} · private v{String(item.version)}</h3><p className="r09Status">Review status: {text(item.status)} · never applied as unreviewed guidance</p>
          <p>{text(item.lesson)}</p><h3>Proposed scope</h3><p>{text(item.scope)}</p><h3>Declared limitations</h3><List value={item.limitations}/>
          <h3>Private evidence references</h3><ul>{strings(item.artifactIds).map(id => <li key={id}><Link href={`/dashboard?view=library&type=records&business=${businessId}&selected=${id}`}>Exact owned artifact {id}</Link></li>)}</ul>
          <Facts values={{ "Evidence fingerprint": item.evidenceHash, "Review reference": item.reviewId, "Review reason": item.reviewReason }}/>
          {item.status === "rejected" || item.status === "needs_evidence" ? <p className="r08Warning">This version cannot be reused. Rejected redaction or missing proof requires new evidence and another trusted review; ownership does not override it.</p> : null}
          <details className="r08Exact"><summary>Review and promotion process</summary><Process/></details>
          {form ? <details className="r09Propose"><summary>Revise as a new private version</summary><KnowledgeForm key={text(item.id)} {...form} proposal={{ proposalId: text(item.proposalId), expectedVersion: Number(item.version), title: text(item.title), lesson: text(item.lesson), scope: text(item.scope), limitations: strings(item.limitations), artifactIds: strings(item.artifactIds) }}/></details> : null}
        </> : null}
        {query.section === "releases" ? <>
          <h3>{text(item.title)} · v{text(item.version)}</h3><p className="r09Status">{item.status === "withdrawn" ? "Withdrawn · blocked for new selection" : item.status === "expired" ? "Stale / expired · blocked for new selection" : "Reviewed version · source window is dated"}</p>
          <Guidance content={content}/>
          <Facts values={{ "Reviewed at": item.reviewedAt, "Review expires": item.expiresAt, "Reviewer identity": item.reviewerIdentity, "Reviewer fingerprint": item.reviewerFingerprint, "Manifest hash": item.manifestHash, "Content hash": item.contentHash }}/>
          <h3>Source verification and conflicts</h3><ul>{rows(item.sources).map((source, index) => { const url = safeSource(source.url); return <li key={index}>{url ? <a href={url} target="_blank" rel="noreferrer">{text(source.title, url)}</a> : text(source.title, "Source URL unavailable")}<p>{text(source.stance)} · verified {text(source.verifiedAt)} · expires {text(source.expiresAt)}</p><small>Content fingerprint {text(source.contentHash)}</small></li>; })}</ul>
          {item.supersedesReleaseId ? <p>Supersedes <Link href={href({ selected: text(item.supersedesReleaseId) })}>the exact previous release</Link>. {text(item.supersessionReason)}</p> : null}
          <p>{head.releaseId === item.id ? "This exact version is currently selected for this Business." : head.id ? "This Business has an existing selection. Applying here deliberately replaces that selection for future work." : "This Business has not selected this guidance. Viewing it does not apply it."}</p>
          {form && releaseSelectable && head.releaseId !== item.id ? <KnowledgeForm key={`${businessId}:${item.id}:apply`} {...form} mutation={{ operation: "apply", label: "Apply this version", versionLabel: `${text(item.title)} v${text(item.version)}`, payload: { releaseId: item.id, expectedApplicationId: head.id ?? null } }}/>: !releaseSelectable ? <p className="r08Warning">New application is unavailable. A trusted platform review must publish a current version; historical pins stay intact.</p> : null}
        </> : null}
        {query.section === "applications" ? <>
          <h3>{text(item.packKey)} · {text(item.version, "no selected version")}</h3><p className="r09Status">{text(item.operation)} · {text(item.status)} · {item.isCurrent === true ? "current Business selection" : "historical Business selection"}</p><h3>Why this Business selected it</h3><p>{text(item.reason)}</p>
          <Facts values={{ "Application id": item.id, "Created": item.createdAt, "Exact release": item.releaseId, "Installed snapshot": item.installationId }}/>
          {item.releaseId ? <Link href={href({ type: "releases", selected: text(item.releaseId) })}>Inspect exact reviewed version</Link> : <p>Future selection was removed. Earlier plans still retain their original reviewed version.</p>}
          {item.previousApplicationId ? <p><Link href={href({ selected: text(item.previousApplicationId) })}>Previous exact Business application</Link></p> : null}
          {form && item.isCurrent !== true && item.releaseId && head.id && !["expired", "withdrawn"].includes(applicationReleaseStatus) ? <KnowledgeForm key={`${businessId}:${item.id}:rollback`} {...form} mutation={{ operation: "rollback", label: "Roll back to this version", versionLabel: `${text(item.packKey)} v${text(item.version)}`, payload: { applicationId: item.id, expectedApplicationId: head.id } }}/>: null}
          {form && item.isCurrent === true && item.releaseId ? <KnowledgeForm key={`${businessId}:${item.id}:remove`} {...form} mutation={{ operation: "remove", label: "Remove future selection", versionLabel: `${text(item.packKey)} v${text(item.version)}`, payload: { packKey: item.packKey, expectedApplicationId: item.id } }}/>: null}
          {["expired", "withdrawn"].includes(applicationReleaseStatus) ? <p className="r08Warning">This version is now stale or withdrawn. It cannot be selected for new work; its historical use is preserved.</p> : null}
          <p><Link href={href({ type: "usage", selected: null, page: null, q: null })}>Inspect historical plan usage</Link></p>
        </> : null}
        {query.section === "usage" ? <>
          <h3>Exact plan v{String(item.planVersion)} · pinned guidance</h3><Facts values={{ "Business": item.businessId, "Quest": item.goalId, "Plan": item.planId, "Plan created": item.createdAt }}/>
          <p>These are the exact frozen guidance versions selected when this plan was created. Later application, rollback, removal or withdrawal does not change them. A pin records the guidance available to the plan; actual influence requires a matching execution or decision receipt.</p>
          <Link href={`/dashboard?view=overview&business=${businessId}&quest=${text(item.goalId)}`}>Open this plan’s Quest</Link>
          <h3>Linked episode and task pins</h3>
          {rows(item.runs).length ? <ul>{rows(item.runs).map((run, index) => <li key={`${text(run.workflowRunId)}:${index}`}><Link href={`/dashboard?view=work&business=${businessId}&quest=${text(item.goalId)}&selected=${text(run.workflowRunId)}&episode=${text(run.workflowRunId)}`}>Exact pinned episode {text(run.workflowRunId)}</Link>{run.taskContractId ? <p><Link href={`/dashboard/workflows/${text(run.workflowRunId)}?business=${businessId}&quest=${text(item.goalId)}&panel=tasks&task=${text(run.taskContractId)}`}>Exact task contract {text(run.taskContractId)}</Link></p> : <p>No task contract pin recorded for this episode</p>}</li>)}</ul> : <p>No linked execution or task pin is recorded for this historical plan.</p>}
          {rows(item.runs).length === 64 ? <p>64 linked episode/task references loaded. <Link href={`/dashboard?view=work&business=${businessId}&quest=${text(item.goalId)}`}>Browse all Quest episodes</Link> for the bounded full history.</p> : null}
          {rows(item.knowledge).map((pin, index) => <article className="r09Pin" key={text(pin.releaseId, String(index))}><h3>{text(pin.packKey)} · pinned v{text(pin.packVersion, text(pin.version))}</h3><p>Original application reason: {text(pin.applicationReason, text(pin.reason, "Inspect the exact originating application"))}</p><p>Current source status: {text(pin.currentStatus, "Inspect reviewed version for current availability")}. Original expiry: {text(pin.expiresAt)}</p><Guidance content={object(pin.content)}/><Facts values={{ "Application": pin.applicationId, "Release": pin.releaseId, "Manifest hash": pin.manifestHash, "Content hash": pin.contentHash }}/><Link href={href({ type: "applications", selected: text(pin.applicationId) })}>Exact originating application</Link>{" · "}<Link href={href({ type: "releases", selected: text(pin.releaseId) })}>Exact reviewed version and current status</Link></article>)}
          {!rows(item.knowledge).length ? <p>This historical plan contains no reviewed learned-guidance pins. No influence is inferred from current Business selection.</p> : null}
        </> : null}
        <Exact record={item}/>
      </>}
    </section></div>
    <footer className="r08Pager r09Pager"><span>{page.total === null ? "Count unavailable" : `${page.items.length ? query.offset + 1 : 0}–${query.offset + page.items.length} of ${page.total}`} · page {query.page}</span><nav aria-label="Knowledge record pages">{query.page > 1 ? <Link href={href({ page: String(query.page - 1) })}>Previous</Link> : null}{page.total !== null && query.offset + page.items.length < page.total && query.page < 401 ? <Link href={href({ page: String(query.page + 1) })}>Next</Link> : null}</nav></footer>
  </section></ConsoleShell>;
}
