import Link from "next/link";
import type { ListingWorkspaceData } from "@/listing/server";
import { startListingPreparation, stopListingPreparation, closeExpiredListingPreparation, startListingQualification, stopListingQualification } from "./listing-actions";
const money=(value:number)=>new Intl.NumberFormat("en-US",{style:"currency",currency:"USD",minimumFractionDigits:2,maximumFractionDigits:4}).format(value/1_000_000);
const labels:Record<string,string>={title:"Title",description:"Description",tags:"Tags",attributes:"Attributes",imageOrder:"Image order",disclosures:"Disclosures",factualClaims:"Factual claims"};
export function ListingWorkspace({data}:{data:ListingWorkspaceData}) {
  return <section className="etsyPanel listingWorkspace"><p className="coreEyebrow">Listing Specialist · Independent review</p><h2>Prepare accurate listing copy</h2>
    <p>Build a title, description and tags from verified product facts, preserve attributes, order reviewed finished-product images and include required disclosures. A separate model checks all seven areas before a draft package can be offered below.</p>
    <p className="etsyMuted">This creates a reviewed package in Agent Labs. Creating an Etsy draft still needs your separate approval. Publication, orders and purchases remain unavailable.</p>
    {data.unavailable && <p role="alert">Listing records could not be verified. New runs are paused; existing histories and charges may still exist.</p>}
    {!data.configured && <p className="etsyMuted">Secure listing setup is not available yet. No account access or paid run has been requested.</p>}
    {!data.qualified && <p className="etsyMuted">Live qualification is still required for these exact specialist and reviewer versions. Synthetic evaluations do not authorize model spending or qualify a real product.</p>}
    {data.qualificationQuoteUnavailable&&<p role="alert">The current model-price check is unavailable. No worker evaluation can start without a fresh complete quote.</p>}
    {data.qualificationQuote&&<article className="etsyProduct"><h3>Qualify these listing workers</h3><p>Evaluate five fixed test cases with real model responses: accurate copy, resistance to source instructions, an acceptable proposal, unsupported claims and unresolved image evidence. These cases use synthetic product data and cannot create a product or Etsy draft.</p><p>Conservative five-call estimate: {money(data.qualificationQuote.maximumEstimateMicrousd)}. This is a separate allowance from product research, design and listing preparation.</p>
      <form action={startListingQualification}><input type="hidden" name="businessId" value={data.businessId}/><input type="hidden" name="suiteHash" value={data.qualificationQuote.suiteHash}/><input type="hidden" name="qualificationLaunchNonce" value={data.qualificationLaunchNonce??""}/><label className="listingBudget">Total evaluation limit (USD)<input type="number" name="qualificationBudgetUsd" min="0.01" max="1" step="0.01" required defaultValue={Math.max(0.01,Math.ceil(data.qualificationQuote.maximumEstimateMicrousd/10_000)/100).toFixed(2)}/></label><label className="etsyConsent"><input type="checkbox" name="qualificationConsent" required/>Approve this one five-call evaluation with OpenRouter’s OpenAI and Anthropic model providers within the limit above. Stop after a failed or uncertain case; no retry, product creation or Etsy action is approved.</label><button className="coreButton" disabled={!data.configured||data.unavailable}>Start worker qualification</button></form></article>}
    {(data.qualificationRuns??[]).map(run=><article className="etsyProduct" key={run.id}><h3>{run.status==="passed"?"Worker evaluation passed":run.status==="failed"?"Worker evaluation failed":run.status==="cancelled"?"Worker evaluation stopped":"Worker evaluation in progress"}</h3><p>Approved total: {money(run.maximumMicrousd)}. A passing evaluation qualifies only these pinned worker/model/policy versions; real products still need verified sources.</p>{run.costs.map(cost=><p className="etsyMuted" key={cost.caseKey}>{cost.caseKey.replaceAll("_"," ")}: {cost.settled&&cost.reportedMicrousd!==null?`${money(cost.reportedMicrousd)} reported cost`:`${money(cost.reservedMicrousd)} reserved; charge ${cost.settled?"unresolved":"not yet settled"}`}</p>)}<Link href={`/dashboard/workflows/${run.workflowRunId}?business=${data.businessId}`}>View evaluation history</Link>{["queued","running"].includes(run.status)&&<form action={stopListingQualification}><input type="hidden" name="businessId" value={data.businessId}/><input type="hidden" name="qualificationRunId" value={run.id}/><button className="coreButton" disabled={data.unavailable}>Stop further evaluation calls</button></form>}</article>)}
    {!data.sources.length && <div className="etsyEmpty"><h3>No eligible verified listing input</h3><p>A current reviewed product decision, production-approved asset, verified Printful product and authentic source records must arrive from the upstream workflow. Finished-product photos or eligible mockups need their own resolved visual review; raw artwork does not meet that requirement.</p>{data.sourceBlocker && <p>An available input could not pass its source, freshness or quote checks. It has not been substituted with a synthetic example.</p>}<div className="etsyLinks"><Link href={`/dashboard/products?business=${data.businessId}`}>Review products</Link><Link href={`/dashboard/printful?business=${data.businessId}`}>Printful readiness</Link></div></div>}
    {data.sources.map(source=><article className="etsyProduct" key={source.id}><h3>{source.title}</h3><p>Conservative estimate: {money(source.quote.maximumEstimateMicrousd)} for at most two calls. One specialist and one independent reviewer; a failed or uncertain call is not automatically retried.</p><p className="etsyMuted">Input valid until {new Date(source.expiresAt).toISOString().replace("T"," ").slice(0,16)} UTC. Fresh prices are checked again before starting and before each call.</p>
      <form action={startListingPreparation}><input type="hidden" name="businessId" value={data.businessId}/><input type="hidden" name="sourceArtifactId" value={source.id}/><input type="hidden" name="inputHash" value={source.inputHash}/>
        <label className="listingBudget">Total spending limit (USD)<input type="number" name="listingBudgetUsd" min="0.01" max="1" step="0.01" required defaultValue={Math.max(0.01,Math.ceil(source.quote.maximumEstimateMicrousd/10_000)/100).toFixed(2)}/></label>
        <label className="etsyConsent"><input type="checkbox" name="listingConsent" required/>Approve one bounded listing-preparation run within this total limit, sharing these product facts and image-review records with OpenRouter’s OpenAI and Anthropic model providers. This grants no Etsy, image-generation or publication action.</label>
        <button className="coreButton coreButtonPrimary" disabled={!data.configured||!data.qualified||data.unavailable}>Start listing preparation</button></form></article>)}
    <h3>Listing preparation history</h3>
    {data.unavailable?<p className="etsyMuted">Listing history is unavailable until the records can be checked.</p>:!data.runs.length?<p className="etsyMuted">No listing-preparation runs are recorded.</p>:data.runs.map(run=><article className="etsyProduct" key={run.id}><h4>{run.status==="completed"?"Reviewed package ready":run.status==="rejected"?"Review rejected the package":run.status==="needs_evidence"?"More evidence required":run.status==="cancelled"?"Stopped":run.status==="failed"?"Run stopped with a failure":"Listing preparation in progress"}</h4>
      <p>{run.phase==="specialist"?"Specialist copy":run.phase==="reviewer"?"Independent review":"Package verification"} · Approved total: {money(run.maximumMicrousd)}</p>
      {run.costs.map(cost=><p className="etsyMuted" key={cost.role}>{cost.role==="specialist"?"Specialist":"Reviewer"}: {cost.settled&&cost.reportedMicrousd!==null?`${money(cost.reportedMicrousd)} reported cost`:`${money(cost.reservedMicrousd)} reserved; charge ${cost.settled?"unresolved":"not yet settled"}`}</p>)}
      {run.review&&<details><summary>Read the independent review: {run.review.verdict.replaceAll("_"," ")}</summary>{Object.entries(run.review.checks).map(([key,check])=><p key={key}><strong>{labels[key]??key}: {check.status.replaceAll("_"," ")}</strong><br/>{check.rationale}</p>)}</details>}
      {run.proposal&&<details><summary>Read the proposed listing copy</summary><p><strong>{run.proposal.title.text}</strong></p>{run.proposal.description.map((paragraph,index)=><p key={index}>{paragraph.text}</p>)}<p>Tags: {run.proposal.tags.map(t=>t.text).join(", ")}</p><p className="etsyMuted">Required disclosures are appended to the final package from the verified source.</p></details>}
      <div className="etsyLinks"><Link href={`/dashboard/workflows/${run.workflowRunId}?business=${data.businessId}`}>View workflow and receipts</Link></div>
      {["queued","running"].includes(run.status)&&<div className="etsyActions"><form action={stopListingPreparation}><input type="hidden" name="businessId" value={data.businessId}/><input type="hidden" name="listingRunId" value={run.id}/><button className="coreButton" disabled={data.unavailable}>Stop further calls</button></form><form action={closeExpiredListingPreparation}><input type="hidden" name="businessId" value={data.businessId}/><input type="hidden" name="listingRunId" value={run.id}/><button className="coreButton" disabled={data.unavailable||!run.expired}>Close if expired</button></form></div>}
      <p className="etsyMuted">Stopping prevents later calls. An in-flight request may still incur a charge; its receipt and reserved allowance are preserved.</p></article>)}
    <Link className="coreButton" href={`/dashboard/etsy?business=${encodeURIComponent(data.businessId)}`}>Refresh listing status</Link>
  </section>;
}
