import Link from "next/link";
import { hash, type EtsyProductPackage } from "@/etsy/contracts";
import { connectEtsy, disconnectEtsy, createEtsyDraft, reconcileEtsyDraft, stopEtsyDraft } from "./actions";

export type EtsyWorkspaceData = {
  businessId: string; businessName: string; configured: boolean; unavailable: boolean;
  connection: { id: string; shopName: string; status: string; currency: string } | null;
  packages: EtsyProductPackage[];
  runs: { id: string; title: string; status: string; reason: string | null; listingId: number | null; approvedAt: string; stopped: boolean }[];
};
export function EtsyWorkspace({ data }: { data: EtsyWorkspaceData }) {
  const connected = data.connection?.status === "connected";
  return <div className="etsyWorkspace">
    <section className="etsyPanel"><p className="coreEyebrow">{data.businessName} · Drafts only</p><h2>Connect your Etsy shop</h2>
      <p>Prepare listings from approved products. This step only creates drafts. Any later publication and listing charges require the separate publication process; orders and purchases are unavailable.</p>
      {data.unavailable && <p role="alert">Etsy records could not be loaded. Existing connections and drafts may still exist. Actions are paused until the records can be checked.</p>}
      {connected ? <><p><strong>{data.connection!.shopName}</strong> · {data.connection!.currency}</p><form action={disconnectEtsy}><input type="hidden" name="businessId" value={data.businessId} /><button className="coreButton" disabled={data.unavailable}>Disconnect and stop draft work</button></form><small>Disconnect removes Agent Labs&apos; stored access. You can also revoke this application in Etsy&apos;s account settings. Existing Etsy drafts are retained.</small></>
        : <form action={connectEtsy}><input type="hidden" name="businessId" value={data.businessId} /><label className="etsyConsent"><input type="checkbox" name="accountConsent" required disabled={!data.configured || data.unavailable} />Connect this Business to my Etsy shop for shop/listing reads and draft preparation. Etsy’s consent screen grants listing write access. Draft preparation remains separate from any publication approval.</label><button className="coreButton coreButtonPrimary" disabled={!data.configured || data.unavailable}>Connect Etsy securely</button>{!data.configured && <p className="etsyMuted">Secure connection setup is not available yet. No account access has been requested.</p>}</form>}
    </section>
    <section className="etsyPanel"><p className="coreEyebrow">Approved products</p><h2>Prepare an Etsy draft</h2>
      <p className="etsyMuted">Creating an Etsy draft does not create or verify a Printful variant mapping. An ecommerce-linked store alone does not establish the exact supplier link or manual order-confirmation setting. Agent Labs has no automatic order sync or fulfilment path yet; that remains later Stage 22 work.</p>
      {!data.packages.length ? <div className="etsyEmpty"><h3>No qualified Product Package available</h3><p>A real draft needs a current reviewed product decision, a production-approved asset, a verified Printful product with current facts and a saved configuration receipt, and an independently reviewed listing package. Finished-product photos or eligible mockups need their own verified image evidence; raw artwork is not a product mockup. Synthetic examples and technical image tests do not satisfy these requirements.</p><div className="etsyLinks"><Link href="/dashboard/products">Review products</Link><Link href="/dashboard/artifacts">Review artwork</Link><Link href="/dashboard/printful">Printful readiness</Link></div></div>
        : data.packages.map(p => <article className="etsyProduct" key={p.id}><h3>{p.title}</h3><p>{new Intl.NumberFormat("en-NZ", { style: "currency", currency: p.currency }).format(p.priceMinor / 100)} · {p.quantity} available · {p.images.length} reviewed image{p.images.length === 1 ? "" : "s"}</p><details><summary>Review listing details</summary><p>{p.description}</p><p>Tags: {p.tags.join(", ")}</p><p>Materials: {p.materials.join(", ")}</p>{p.images.map((image, index) => <p key={image.assetId}>Image {index + 1}: {image.altText}</p>)}</details><p className="etsyMuted">Approval valid until {new Date(p.expiresAt).toISOString().replace("T", " ").slice(0, 16)} UTC</p><form action={createEtsyDraft}><input type="hidden" name="businessId" value={data.businessId} /><input type="hidden" name="packageId" value={p.id} /><input type="hidden" name="packageHash" value={hash(p)} /><label className="etsyConsent"><input type="checkbox" name="draftConsent" required />Approve this product and price for one Etsy draft in this shop.</label><label className="etsyConsent"><input type="checkbox" name="assetConsent" required />Share this product’s approved images and listing details with Etsy. This does not approve publication or spending.</label><button className="coreButton coreButtonPrimary" disabled={!connected || data.unavailable}>Create draft</button></form></article>)}
    </section>
    <section className="etsyPanel"><p className="coreEyebrow">Durable progress</p><h2>Draft activity</h2>{!data.runs.length ? <p className="etsyMuted">No draft runs are recorded for this Business.</p> : data.runs.map(run => <article className="etsyProduct" key={run.id}><h3>{run.title}</h3><p>{run.status === "verified" ? "Draft verified by reading Etsy" : run.stopped ? "Stopped" : run.status === "running" ? "Preparing draft" : "Verification needed"}</p>{run.listingId && <a href={`https://www.etsy.com/your/shops/me/listing-editor/edit/${run.listingId}`} target="_blank" rel="noreferrer">View draft on Etsy</a>}{run.status !== "verified" && !run.stopped && <div className="etsyActions"><form action={reconcileEtsyDraft}><input type="hidden" name="businessId" value={data.businessId} /><input type="hidden" name="runId" value={run.id} /><button className="coreButton" disabled={data.unavailable || !connected}>Check draft and continue</button></form><form action={stopEtsyDraft}><input type="hidden" name="businessId" value={data.businessId} /><input type="hidden" name="runId" value={run.id} /><button className="coreButton" disabled={data.unavailable}>Stop</button></form></div>}<p className="etsyMuted">{run.reason === "uncertain_image_identity" ? "An image upload may have completed, but its Etsy identity was not received. It will not be uploaded again." : run.status === "needs_owner" ? "A provider result or prerequisite could not be verified. Existing drafts and upload history are preserved." : "Duplicate draft requests use the original record. This draft action never publishes; any later publication appears in its separate history."}</p></article>)}</section>
  </div>;
}
