import test from 'node:test';import assert from 'node:assert/strict';
import {recordEtsySteelBoundedPending} from '../.core-tests/browser/etsy-steel-accounting.js';
import {discoveryV2Hash as hash} from '../.core-tests/products/discovery-v2-hash.js';
const id=n=>`78000000-0000-4000-8000-${String(n).padStart(12,'0')}`,h=x=>hash(x);
function fixture(){
 const scopeHash=h('scope'),q={providerProjectId:id(2),providerAccountHash:h('account'),routeHash:h('route'),tariffHash:h('tariff'),qualificationHash:h('qualified'),maximumSessionMs:30000,maximumSessionMicrounits:'1000',revoked:false,usageBound:{version:'r12.steel-usage-bound.1',maximumProxyBytes:0,tariffCoversSessionAndProfileLifecycle:true,captchaDisabled:true,extraServicesDisabled:true}};
 const body={operationId:id(1),scopeHash,status:'terminal'},terminalReceipt={...body,receiptHash:h(body)},calls=[];
 const usage={version:'etsy.steel-terminal-usage.1',sessionId:id(1),providerProjectId:id(2),providerStatus:'released',providerTimeoutMs:30000,durationMs:1500,proxyBytesUsed:0,proxySource:null,solveCaptcha:false};let usageEvidence;
 const input={operationId:id(1),providerProjectId:id(2),routeHash:q.routeHash,requestedTimeoutMs:30000,maximumMicrounits:'2000',terminalReceipt,release:{sessionId:id(1),released:true,terminalReadback:true,observersDisposed:true,disposalProofHash:h('actual-disposal')},extraServicesDisabled:true,readUsage:async()=>usage,rpc:async(op,payload)=>{calls.push([op,payload]);if(op==='read')return{operationId:id(1),operationMaximumMicrounits:'2000',scopeHash,requestHash:h('request'),qualification:q};if(op==='bind_session')return{operationId:id(1),usageIdentityHash:h('identity')};if(op==='receipt')return{persisted:true,receiptHash:payload.receiptHash};if(op==='evidence'){if(payload.kind==='usage_bound')usageEvidence=payload.content;return{evidenceHash:h(payload.content)};}if(op==='reconcile')return{accepted:usageEvidence.withinQualifiedLimits,accounting:{status:'qualified_bounded_pending',maximumMicrounits:'2000',actualMicrounits:null}};throw Error(op);}};
 return{input,q,usage,calls};
}
test('actual usage and disposal create exact proof joins while full reserve remains pending',async()=>{const f=fixture(),r=await recordEtsySteelBoundedPending(f.input);assert.equal(r.accepted,true);assert.equal(r.result.accounting.maximumMicrounits,'2000');assert.equal(r.result.accounting.actualMicrounits,null);const u=f.calls.find(([op,p])=>op==='evidence'&&p.kind==='usage_bound')[1].content;assert.equal(u.maximumMicrounits,'1000');assert.equal(u.durationMs,1500);assert.equal(f.calls.at(-1)[1].billingProofHash,null);});
for(const [label,mutate]of[['missing duration',f=>f.usage.durationMs=null],['missing captcha',f=>f.usage.solveCaptcha=null],['proxy',f=>f.usage.proxyBytesUsed=1],['overrun',f=>f.usage.durationMs=30001],['timeout mismatch',f=>f.usage.providerTimeoutMs=31000],['unqualified route',f=>f.q.usageBound=null],['revoked route',f=>f.q.revoked=true],['unknown extras',f=>f.input.extraServicesDisabled=false]])test(label+' persists honest unbounded evidence, never claims pending qualification',async()=>{const f=fixture();mutate(f);const r=await recordEtsySteelBoundedPending(f.input);assert.equal(r.accepted,false);assert.equal(f.calls.at(-1)[0],'reconcile');});
test('missing actual disposal or mismatched reservation cannot write evidence',async()=>{for(const change of[f=>f.input.release.observersDisposed=false,f=>f.input.maximumMicrounits='1000',f=>f.usage.sessionId=id(8)]){const f=fixture();change(f);await assert.rejects(recordEtsySteelBoundedPending(f.input));assert.equal(f.calls.some(([op])=>['bind_session','receipt','evidence'].includes(op)),false);}});
test('forged terminal scope cannot be recorded',async()=>{const f=fixture(),body={operationId:id(1),scopeHash:h('other'),status:'terminal'};f.input.terminalReceipt={...body,receiptHash:h(body)};await assert.rejects(recordEtsySteelBoundedPending(f.input));assert.equal(f.calls.some(([op])=>op==='receipt'),false);});
