/** Actual server action and bounded GET helper with inert auth/RPC/provider IO.
 * No deployed invocation, SQL publication, tariff or live key is qualified. */
import test from 'node:test';import assert from 'node:assert/strict';
import {createRequire} from 'node:module';import {readFileSync} from 'node:fs';import {resolve} from 'node:path';import ts from 'typescript';
const require=createRequire(import.meta.url),core=process.env.R12_STEEL_READBACK_CORE_DIR??'.core-tests';
const c=require(resolve(core,'accounts/etsy-steel-readback-contracts.js')),helper=require(resolve(core,'browser/etsy-steel-config-readback.js')),deadline=require(resolve(core,'core/request-deadline.js'));
const id=n=>`93000000-0000-4000-8000-${String(n).padStart(12,'0')}`,hash=c.steelReadbackHash,ROOT='inert-readback-owner-root-no-provider-access';
const original={VERCEL_ENV:process.env.VERCEL_ENV,R05_ADMISSION_SERVER_KEY:process.env.R05_ADMISSION_SERVER_KEY};Object.assign(process.env,{VERCEL_ENV:'production',R05_ADMISSION_SERVER_KEY:ROOT});test.after(()=>{for(const[k,v]of Object.entries(original))if(v===undefined)delete process.env[k];else process.env[k]=v;});
function fixture(o={}){
 const now=Date.now(),businessId=id(1),ownerId=id(2),project=id(3),session=id(4),calls=[],gets=[];
 const deployment={environment:'production',deploymentId:'dpl_inert_readback_owner',releaseCommitSha:'1'.repeat(40)},config={apiKey:'inert-provider-key',baseUrl:'https://api.steel.dev'};
 const key=ROOT;
 const configuration={version:'r12.steel-runtime-configuration.1',provider:'steel',baseUrl:config.baseUrl,region:null,providerProjectId:project,...deployment};
 const body={version:'r12.steel-config-readback-target.1',businessId,ownerId,providerProjectId:project,knownSessionId:session,knownBefore:new Date(now-1000).toISOString(),observedTerminalState:'Completed',expectedCreatedAt:null,expectedProviderStatus:null,configuration,configurationHash:hash(configuration),deploymentEvidenceHash:hash('deployment'),routeReviewHash:hash('route review'),tariffEvidenceHash:hash('tariff evidence'),validFrom:new Date(now-500).toISOString(),expiresAt:new Date(now+60000).toISOString(),...o.target};
 const target={...body,targetHash:hash(body)};let status='ready',claim=null,proof=null;
 const safe=()=>({version:'r12.owner-steel-config-readback.1',businessId,targetHash:target.targetHash,status,observedAt:proof?.observedAt??null,proofHash:proof?hash(proof):null});
 const context={userId:ownerId,supabase:{auth:{getClaims:async()=>({data:{claims:{sub:o.wrongClaims?id(9):ownerId}},error:null})},rpc:async(name,args)=>{
  calls.push({name,args:structuredClone(args)});assert.equal(args.p_business_id,businessId);
  if(name==='r12_owner_steel_config_readback')return{data:safe(),error:null};
  assert.equal(name,'r12_steel_config_readback_server');assert.equal(args.p_server_key,key);const p=args.p_payload;
  assert.equal(p.targetHash,target.targetHash);
  if(o.authorityDenial===args.p_operation)return{data:null,error:{code:'42501',message:'PRIVATE root detail '+ROOT,details:'PRIVATE credential metadata'}};
  if(args.p_operation==='claim'){
   if(status!=='ready')return{data:{version:'r12.steel-config-readback-claim-response.1',targetHash:target.targetHash,mayFetch:false,status:safe()},error:null};
   status='pending';const b={version:'r12.steel-config-readback-claim.1',id:id(5),targetHash:target.targetHash,submissionId:p.submissionId,expiresAt:new Date(Date.now()+19000).toISOString()};claim={id:b.id,hash:hash(b),expiresAt:b.expiresAt};
   if(o.lostClaim)return{data:null,error:Error('inert lost claim acknowledgment')};
   return{data:{version:'r12.steel-config-readback-claim-response.1',targetHash:target.targetHash,mayFetch:true,claim,target,...o.claimResponse},error:null};
  }
  if(args.p_operation==='cancel'){if(status!=='verified')status='cancelled';return{data:safe(),error:null};}
  assert.equal(p.claimId,claim.id);assert.equal(p.claimHash,claim.hash);
  if(args.p_operation==='fail'){assert.equal(p.reason,'provider_readback_unverified');status='failed';return{data:safe(),error:null};}
  assert.equal(args.p_operation,'record');assert.equal(p.proof.requestedSessionId,session);assert.equal(p.proof.returnedProjectId,project);assert.equal(p.proof.configurationHash,target.configurationHash);assert.doesNotMatch(JSON.stringify(p),/private-debug|PRIVATE_COOKIE|inert-provider-key/);
  if(o.recordUnavailable)return{data:null,error:Error('inert unavailable record')};proof=p.proof;status='verified';return o.lostRecord?{data:null,error:Error('inert lost record acknowledgment')}:{data:safe(),error:null};
 }}};
 const deps={'server-only':{},'node:crypto':require('node:crypto'),'../lib/core-ui/owner-business':{verifyOwnerBusiness:async()=>!o.foreignOwner},'../core/request-deadline':deadline,'./etsy-steel-readback-contracts':c,'../browser/providers/steel':{getSteelConfig:()=>({...config,...o.config})},'../browser/etsy-steel-create-binding':{getSteelCreateDeployment:()=>({...deployment,...o.deployment})},'../browser/etsy-steel-config-readback':{qualifySteelExistingSessionReadback:(expected,options)=>helper.qualifySteelExistingSessionReadback(expected,{...options,fetcher:async(address,init)=>{gets.push({address,init});assert.equal(init.method,'GET');assert.equal(address,'https://api.steel.dev/v1/sessions/'+session);if(o.fetcher)return o.fetcher(address,init);return Response.json({id:session,projectId:project,status:'released',createdAt:new Date(now-60000).toISOString(),debugUrl:'https://example.invalid/private-debug',cookies:'PRIVATE_COOKIE',...o.provider});}})}};
 const loaded={exports:{}},code=ts.transpileModule(readFileSync('src/accounts/etsy-steel-readback-owner-server.ts','utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText;
 new Function('require','module','exports',code)(name=>{assert.ok(Object.hasOwn(deps,name),name);return deps[name];},loaded,loaded.exports);
 return{api:loaded.exports,context,businessId,target,calls,gets,safe,run:signal=>loaded.exports.runSteelConfigReadback(context,businessId,target.targetHash,signal)};
}
test('same-owner action records one genuine helper GET and exposes only safe status',async()=>{const f=fixture(),r=await f.run();assert.equal(r.status,'verified');assert.equal(f.gets.length,1);assert.deepEqual(Object.keys(r).sort(),['businessId','observedAt','proofHash','status','targetHash','version']);assert.deepEqual(f.calls.map(x=>x.args.p_operation),['claim','record']);assert.doesNotMatch(JSON.stringify(r),/93000000-0000-4000-8000-000000000004|credentialBindingHash|configurationHash|endpoint|private-debug|PRIVATE_COOKIE/);});
for(const o of [{foreignOwner:true},{wrongClaims:true}])test('foreign owner or mismatched claims cannot call SQL or provider',async()=>{const f=fixture(o);await assert.rejects(f.run());assert.deepEqual(f.calls,[]);assert.deepEqual(f.gets,[]);});
for(const [name,target]of [['expired',{expiresAt:new Date(Date.now()-1000).toISOString()}],['wrong owner',{ownerId:id(9)}],['wrong configuration hash',{configurationHash:hash('wrong')}],['unknown terminal observation',{observedTerminalState:'Live'}],['future independent observation',{knownBefore:new Date(Date.now()+30000).toISOString()}]])test(`invalid ${name} target never reaches provider`,async()=>{const f=fixture({target}),r=await f.run();assert.equal(r.status,'pending');assert.equal(f.gets.length,0);});
for(const [name,o]of [['deployment',{deployment:{deploymentId:'dpl_changed'}}],['API origin',{config:{baseUrl:'https://example.invalid'}}]])test(`changed actual ${name} fails before GET`,async()=>{const f=fixture(o);assert.equal((await f.run()).status,'failed');assert.equal(f.gets.length,0);});
for(const [name,provider]of [['project',{projectId:id(9)}],['missing project',{projectId:null}],['session',{id:id(9)}],['live status',{status:'live'}],['creation after known-before',{createdAt:new Date(Date.now()+60000).toISOString()}]])test(`provider ${name} mismatch records only failed status`,async()=>{const f=fixture({provider}),r=await f.run();assert.equal(r.status,'failed');assert.equal(r.proofHash,null);assert.equal(f.gets.length,1);assert.equal(f.calls.some(x=>x.args.p_operation==='record'),false);});
test('malformed provider response is bounded and saved as failed without private text',async()=>{const f=fixture({fetcher:async()=>new Response('not JSON private sentinel')});assert.equal((await f.run()).status,'failed');assert.equal(f.gets.length,1);});
test('saved result and duplicate invocation never make another GET',async()=>{const f=fixture(),a=await f.run(),b=await f.run();assert.deepEqual(a,b);assert.equal(f.gets.length,1);});
test('lost claim acknowledgment reads status without GET or repeated claim',async()=>{const f=fixture({lostClaim:true});assert.equal((await f.run()).status,'pending');assert.equal((await f.run()).status,'pending');assert.equal(f.gets.length,0);assert.equal(f.calls.filter(x=>x.args.p_operation==='claim').length,2);});
test('lost record acknowledgment reads the saved result without resend',async()=>{const f=fixture({lostRecord:true});assert.equal((await f.run()).status,'verified');assert.equal(f.gets.length,1);assert.equal(f.calls.filter(x=>x.args.p_operation==='record').length,1);});
test('unknown record result stays pending and cannot repeat provider request',async()=>{const f=fixture({recordUnavailable:true});assert.equal((await f.run()).status,'pending');assert.equal((await f.run()).status,'pending');assert.equal(f.gets.length,1);});
test('cancellation before claim performs no RPC or provider request',async()=>{const f=fixture(),stop=new AbortController();stop.abort();await assert.rejects(f.run(stop.signal));assert.equal(f.calls.length,0);assert.equal(f.gets.length,0);});
test('explicit same-owner cancellation before claim makes later invocation nonfetching',async()=>{const f=fixture();assert.equal((await f.api.cancelSteelConfigReadback(f.context,f.businessId,f.target.targetHash)).status,'cancelled');assert.equal((await f.run()).status,'cancelled');assert.equal(f.gets.length,0);});
test('abort during provider read records cancellation and late response cannot record proof',async()=>{const stop=new AbortController();let started,finish;const gate=new Promise(r=>{started=r;});const f=fixture({fetcher:()=>new Promise(r=>{finish=r;started();})});const task=f.run(stop.signal);await gate;stop.abort();assert.equal((await task).status,'cancelled');finish(Response.json({}));assert.equal(f.calls.some(x=>x.args.p_operation==='record'),false);assert.equal(f.gets.length,1);});
test('safe status rejects private fields and verified claims without exact proof/time',()=>{const f=fixture();for(const change of [{sessionId:id(4)},{credentialBindingHash:hash('private')},{status:'verified'},{status:'unknown'},{businessId:id(9)}])assert.throws(()=>c.validateSteelReadbackStatus({...f.safe(),...change},f.businessId,f.target.targetHash));});
test('owner cannot substitute target hash or private fields through action parameters',async()=>{const f=fixture();await assert.rejects(f.api.runSteelConfigReadback(f.context,f.businessId,'https://example.invalid'));assert.equal(f.calls.length,0);assert.equal(f.gets.length,0);});

test('status and claim validators reject custom coercion or accessor objects without reading accessors',()=>{const f=fixture();assert.throws(()=>c.validateSteelReadbackStatus({...f.safe(),status:{toString:()=> 'ready'}},f.businessId));let read=false;const raw={targetHash:f.target.targetHash,mayFetch:false,status:f.safe()};Object.defineProperty(raw,'version',{enumerable:true,get(){read=true;return 'r12.steel-config-readback-claim-response.1';}});assert.throws(()=>c.validateSteelReadbackClaim(raw,{businessId:f.businessId,ownerId:id(2),targetHash:f.target.targetHash,submissionId:id(8)}));assert.equal(read,false);});
test('missing deployed server root fails before private claim or provider access',async()=>{const f=fixture(),saved=process.env.R05_ADMISSION_SERVER_KEY;delete process.env.R05_ADMISSION_SERVER_KEY;try{await assert.rejects(f.run());assert.equal(f.calls.length,0);assert.equal(f.gets.length,0);}finally{process.env.R05_ADMISSION_SERVER_KEY=saved;}});
test('stale valid-format target hash cannot reach the provider',async()=>{const f=fixture();await assert.rejects(f.api.runSteelConfigReadback(f.context,f.businessId,hash('stale target')));assert.equal(f.gets.length,0);});
test('concurrent owner requests share one immutable claim and one GET',async()=>{let started,complete;const entered=new Promise(r=>{started=r;});const f=fixture({fetcher:()=>new Promise(r=>{complete=r;started();})});const first=f.run();await entered;const second=await f.run();assert.equal(second.status,'pending');assert.equal(f.gets.length,1);complete(Response.json({id:id(4),projectId:id(3),status:'released',createdAt:new Date(Date.parse(f.target.knownBefore)-60000).toISOString()}));assert.equal((await first).status,'verified');assert.equal(f.gets.length,1);});

test('target validity is capped at exactly24hours like SQL',()=>{const f=fixture(),from=Date.parse(f.target.validFrom),{targetHash,...base}=f.target;void targetHash;const body={...base,expiresAt:new Date(from+86400000).toISOString()},valid={...body,targetHash:hash(body)},expected={businessId:f.businessId,ownerId:id(2),targetHash:valid.targetHash};assert.equal(c.validateSteelReadbackTarget(valid,expected).targetHash,valid.targetHash);const changed={...body,expiresAt:new Date(from+86400001).toISOString()},over={...changed,targetHash:hash(changed)};assert.throws(()=>c.validateSteelReadbackTarget(over,{...expected,targetHash:over.targetHash}));});

for(const reason of ['wrong','revoked','delegated'])test(`definite ${reason} root denial is a safe authority error before GET`,async()=>{const f=fixture({authorityDenial:'claim'});await assert.rejects(f.run(),error=>error.message==='Steel configuration readback authority is unavailable.'&&!/PRIVATE|inert-readback/.test(String(error)));assert.equal(f.gets.length,0);assert.deepEqual(f.calls.map(x=>x.args.p_operation),['claim']);});
test('definite cancellation authority denial is not reported as an unchanged ready result',async()=>{const f=fixture({authorityDenial:'cancel'});await assert.rejects(f.api.cancelSteelConfigReadback(f.context,f.businessId,f.target.targetHash),/authority is unavailable/);assert.equal(f.gets.length,0);assert.equal(f.calls.length,1);});
test('definite record authority denial remains explicit after the single GET',async()=>{const f=fixture({authorityDenial:'record'});await assert.rejects(f.run(),/authority is unavailable/);assert.equal(f.gets.length,1);assert.deepEqual(f.calls.map(x=>x.args.p_operation),['claim','record']);});
