import test from 'node:test';
import assert from 'node:assert/strict';
import {createRequire} from 'node:module';
import {resolve} from 'node:path';
const require=createRequire(import.meta.url),{qualifySteelExistingSessionReadback:readback}=require(resolve(process.env.R12_STEEL_READBACK_CORE_DIR??'.core-tests','browser/etsy-steel-config-readback.js'));
const NOW=Date.parse('2026-10-10T16:00:00.000Z'),id=n=>`00000000-0000-4000-8000-${String(n).padStart(12,'0')}`;
const known={sessionId:id(1),providerProjectId:id(2),providerStatus:'released',observedTerminalState:'Completed',sessionCreatedAt:new Date(NOW-60000).toISOString(),knownBefore:new Date(NOW-1000).toISOString()};
function fixture(o={}){const requests=[],config={apiKey:'inert-readback-key',baseUrl:'https://api.steel.dev',region:null,...o.config},deployment={environment:'production',deploymentId:'dpl_inert_readback',releaseCommitSha:'1'.repeat(40),...o.deployment};
 const expected={...known,...o.expected},payload={id:known.sessionId,projectId:known.providerProjectId,status:known.providerStatus,createdAt:known.sessionCreatedAt,debugUrl:'https://example.invalid/private-debug',websocketUrl:'wss://example.invalid/private-token',cookies:[{value:'PRIVATE_SENTINEL'}],...o.payload};
 const options={config,deployment,now:()=>NOW,...o.options,fetcher:async(url,init)=>{requests.push({url,init});if(o.fetcher)return o.fetcher(url,init);return Response.json(payload);}};
 return{requests,config,deployment,expected,options,run:()=>readback(expected,options)};}
test('one exact terminal-session GET produces private evidence and a redacted summary only',async()=>{const f=fixture(),r=await f.run();assert.equal(f.requests.length,1);const q=f.requests[0];assert.equal(q.url,'https://api.steel.dev/v1/sessions/'+id(1));assert.deepEqual(Object.keys(q.init).sort(),['cache','credentials','headers','method','redirect','signal']);assert.equal(q.init.method,'GET');assert.equal(q.init.redirect,'error');assert.equal(q.init.credentials,'omit');assert.equal(q.init.headers['steel-api-key'],'inert-readback-key');assert.equal(r.privateEvidence.requestedSessionId,id(1));assert.equal(r.summary.projectAccessVerified,true);assert.equal(r.summary.exclusiveScopeVerified,false);assert.equal(r.summary.billingTariffVerified,false);assert.ok(!JSON.stringify(r.summary).includes(id(1)));assert.doesNotMatch(JSON.stringify(r),/private-debug|private-token|PRIVATE_SENTINEL|inert-readback-key/);assert.equal(r.configuration.environment,'production');assert.ok(Object.isFrozen(r.privateEvidence));assert.ok(Object.isFrozen(r.summary));assert.equal('credentialBindingHash'in r.summary,false);assert.equal('configurationHash'in r.summary,false);});
for(const [name,expected]of [['future knowledge',{knownBefore:new Date(NOW).toISOString()}],['new session',{sessionCreatedAt:new Date(NOW).toISOString()}],['not terminal',{providerStatus:'live'}],['invalid session',{sessionId:'https://example.invalid'}],['invalid project',{providerProjectId:'not-a-project'}],['unknown creation',{sessionCreatedAt:'-infinity'}],['noncanonical time',{knownBefore:'2026-10-10T15:59:59Z'}]])test(`rejects ${name} before GET`,async()=>{const f=fixture({expected});await assert.rejects(f.run(),/^Error: steel_existing_session_readback_unqualified$/);assert.equal(f.requests.length,0);});
for(const [name,payload]of [['wrong session',{id:id(3)}],['wrong project',{projectId:id(3)}],['missing project',{projectId:undefined}],['null project',{projectId:null}],['live session',{status:'live'}],['changed terminal status',{status:'failed'}],['changed creation',{createdAt:new Date(NOW-50000).toISOString()}]])test(`rejects ${name} without retry`,async()=>{const f=fixture({payload});await assert.rejects(f.run(),/readback_unqualified/);assert.equal(f.requests.length,1);});
for(const [name,change]of [['base URL',{config:{baseUrl:'https://example.invalid'}}],['empty key',{config:{apiKey:''}}],['key header injection',{config:{apiKey:'inert\r\ninvalid'}}],['deployment',{deployment:{deploymentId:'other'}}],['preview',{deployment:{environment:'preview'}}]])test(`rejects ${name} configuration before GET`,async()=>{const f=fixture(change);await assert.rejects(f.run(),/readback_unqualified/);assert.equal(f.requests.length,0);});
test('configuration fingerprint uses the same captured key/deployment despite injected mutation',async()=>{const baseline=await fixture().run();let f;f=fixture({fetcher:async(url,init)=>{f.config.apiKey='changed';f.deployment.releaseCommitSha='2'.repeat(40);f.expected.providerProjectId=id(3);assert.equal(init.headers['steel-api-key'],'inert-readback-key');return Response.json({id:id(1),projectId:id(2),status:'released',createdAt:known.sessionCreatedAt});}});const r=await f.run();assert.equal(r.privateEvidence.credentialBindingHash,baseline.privateEvidence.credentialBindingHash);assert.equal(r.privateEvidence.configurationHash,baseline.privateEvidence.configurationHash);});
for(const [name,fetcher]of [['HTTP denial',async()=>new Response('private failure',{status:403})],['redirect',async()=>{const r=Response.json({});Object.defineProperty(r,'redirected',{value:true});return r;}],['malformed JSON',async()=>new Response('{')],['oversize stream',async()=>new Response('x'.repeat(65537))]])test(`${name} produces only generic failure`,async()=>{const f=fixture({fetcher});await assert.rejects(f.run(),/^Error: steel_existing_session_readback_unqualified$/);assert.equal(f.requests.length,1);});
test('hanging oversize cancellation cannot keep qualification alive',async()=>{let cancelled=false;const f=fixture({fetcher:async()=>new Response(new ReadableStream({cancel(){cancelled=true;return new Promise(()=>{});}}),{headers:{'content-length':'65537'}})});await assert.rejects(f.run(),/readback_unqualified/);assert.equal(cancelled,true);});
test('caller abort bounds an uncooperative fetch and late completion cannot create proof',async()=>{const stop=new AbortController();let resolveFetch;const f=fixture({options:{signal:stop.signal},fetcher:()=>new Promise(r=>{resolveFetch=r;})});const result=f.run();stop.abort();await assert.rejects(result,/readback_unqualified/);resolveFetch(Response.json({}));assert.equal(f.requests.length,1);});
test('caller abort bounds a hanging body read and cancellation',async()=>{const stop=new AbortController();let opened;const gate=new Promise(r=>{opened=r;});const f=fixture({options:{signal:stop.signal},fetcher:async()=>new Response(new ReadableStream({start(){opened();},cancel(){return new Promise(()=>{});}}))});const result=f.run();await gate;stop.abort();await assert.rejects(result,/readback_unqualified/);assert.equal(f.requests.length,1);});
test('an already aborted request cannot access the provider',async()=>{const stop=new AbortController();stop.abort();const f=fixture({options:{signal:stop.signal}});await assert.rejects(f.run(),/readback_unqualified/);assert.equal(f.requests.length,0);});
test('failed terminal sessions use their exact independently known status',async()=>{const f=fixture({expected:{providerStatus:'failed'},payload:{status:'failed'}});assert.equal((await f.run()).privateEvidence.providerStatus,'failed');});

test('minute-precision dashboard observation does not fabricate prior exact creation time',async()=>{const f=fixture({expected:{sessionCreatedAt:undefined,providerStatus:undefined}});const r=await f.run();assert.equal(r.privateEvidence.sessionCreatedAt,known.sessionCreatedAt);assert.equal(r.summary.creationTimeSource,'provider_reported');assert.equal(r.summary.observedTerminalState,'Completed');assert.equal(r.summary.independentlyKnownBefore,known.knownBefore);});
test('provider-reported creation must predate the independent observation even without an exact prior pin',async()=>{const f=fixture({expected:{sessionCreatedAt:undefined},payload:{createdAt:known.knownBefore}});await assert.rejects(f.run(),/readback_unqualified/);});
test('a nonterminal dashboard observation cannot authorize the readback qualification',async()=>{const f=fixture({expected:{observedTerminalState:'Live'}});await assert.rejects(f.run(),/readback_unqualified/);assert.equal(f.requests.length,0);});
