import test from 'node:test';import assert from 'node:assert/strict';
import {buildEtsySteelHandoffDisclosure,validateEtsySteelHandoffScope,etsySteelHash as hash} from '../.core-tests/accounts/etsy-steel-handoff-contracts.js';
import {beginEtsySteelHandoff,openEtsySteelOwnerHandoff,finishEtsySteelHandoff} from '../.core-tests/accounts/etsy-steel-handoff-runtime.js';
const NOW=Date.parse('2026-10-10T12:00:00Z'),id=n=>`20000000-0000-4000-8000-${String(n).padStart(12,'0')}`,H=n=>n.toString(16).padStart(64,'0');
function scope(changes={}){const s={version:'etsy.steel-owner-handoff-scope.1',operationId:id(1),ownerId:id(2),businessId:id(3),goalId:id(4),authorityRootId:id(5),testEnvelopeId:id(10),testEnvelopeHash:H(10),providerProjectId:id(11),verificationOperationId:id(12),verificationMaximumMicrounits:'4000',verificationQuoteHash:H(12),accountId:id(6),accountRevision:id(7),expectedShopName:'Synthetic Owner Shop',expectedShopId:null,purpose:'etsy_insights_read_only',approvalId:id(8),approvalRevision:id(9),approvedAt:new Date(NOW-1000).toISOString(),approvalExpiresAt:new Date(NOW+900000).toISOString(),profileAccessExpiresAt:new Date(NOW+86400000).toISOString(),maximumSessionMs:60000,maximumBrowserMicrounits:'20000',currency:'USD',quoteHash:H(1),...changes};return{...s,disclosureHash:hash(buildEtsySteelHandoffDisclosure(s))};}
function fixture(){const s=scope(),owner={ownerId:s.ownerId,businessId:s.businessId},events=[],records=new Map(),receipts=[],candidates=[],consumed=new Set(),stop=new AbortController();let created=false;
 const session={providerKey:'steel',providerProjectId:s.providerProjectId,providerSessionId:s.operationId,profileId:id(91),debugUrl:`https://api.steel.dev/v1/sessions/${s.operationId}/player`,freshProfile:true,entryUrl:'https://www.etsy.com',async disconnectForOwner(){events.push('disconnect');return{version:'etsy.steel-owner-disconnect.1',sessionId:s.operationId,cdpDisconnected:true,observersDrained:true,inFlightCommandsSettled:true,appCaptureStopped:true,routeHandlersDrained:true,eventListenersRemoved:true};}};
 const d={vaultKey:'a'.repeat(64),signal:stop.signal,now:()=>NOW,monotonic:()=>0,registerCleanup(p){void p;},
 async admit(r){events.push('admit:'+r.operation);assert.equal(r.testEnvelopeHash,s.testEnvelopeHash);assert.equal(r.providerProjectId,s.providerProjectId);if(r.operation==='create'){if(created)throw Error('duplicate');created=true;}return{version:'etsy.steel-owner-handoff-permit.1',requestHash:hash(r),approval:'explicit_owner_persistent_access_and_budget',reservationId:id(70),reservationHash:H(70),reservedBrowserMicrounits:s.maximumBrowserMicrounits,expiresAt:new Date(NOW+10000).toISOString()};},
 async createSession(r){events.push('create');assert.equal(r.browserSessionId,s.operationId);return session;},
 async storeHandoff(r){events.push('store');assert.ok(events.includes('disconnect'));records.set(r.id,r);return{recordHash:r.recordHash,cleanupRegistered:true};},
 async loadHandoff(o,h){assert.deepEqual(o,owner);if(consumed.has(h))throw Error('consumed');return records.get(h);},
 async consumeHandoff(r,o,a){events.push('consume:'+a);assert.deepEqual(o,owner);if(consumed.has(r.id))throw Error('consumed');consumed.add(r.id);return{recordHash:r.recordHash,consumed:true};},
 async releaseSession(sid){events.push('release');return{sessionId:sid,released:true,terminalReadback:true};},
 async readProfile(pid){events.push('profile');return{id:pid,sourceSessionId:s.operationId,status:'READY'};},
 async saveProfileCandidate(c){candidates.push(c);return{candidateHash:c.candidateHash,bindingId:id(80),revision:id(81)};},
 async recordOutcome(r){receipts.push(r);},};return{s,owner,d,session,stop,events,records,receipts,candidates};}
test('bundled scope pins verification and disclosed recording risks',()=>{const s=scope();assert.deepEqual(validateEtsySteelHandoffScope(s),s);const d=buildEtsySteelHandoffDisclosure(s);assert.equal(d.recording,'provider_records_session');assert.equal(d.manualMfaMasking,'not_verified');assert.equal(d.verificationOperationId,s.verificationOperationId);assert.throws(()=>validateEtsySteelHandoffScope({...s,verificationMaximumMicrounits:'1'}));});
test('disconnect and encryption precede owner view; receipts contain no live URL',async()=>{const f=fixture(),r=await beginEtsySteelHandoff(f.s,f.d);assert.equal(r.status,'awaiting_owner');assert.doesNotMatch(JSON.stringify(r),/api.steel|account-v1|profileId|viewerUrl/);const stored=f.records.get(r.handoffId);assert.match(stored.envelope,/^account-v1\./);assert.doesNotMatch(stored.envelope,/api.steel/);const view=await openEtsySteelOwnerHandoff(f.owner,r.handoffId,f.d);assert.equal(view.viewerUrl,f.session.debugUrl);});
test('owner return consumes URL before release; READY remains unverified candidate',async()=>{const f=fixture(),start=await beginEtsySteelHandoff(f.s,f.d),r=await finishEtsySteelHandoff(f.owner,start.handoffId,'return',f.d);assert.equal(r.status,'profile_pending_verification');assert.ok(f.events.indexOf('consume:return')<f.events.indexOf('release'));assert.equal(f.candidates[0].accountIdentityVerified,false);assert.equal(f.candidates[0].testEnvelopeHash,f.s.testEnvelopeHash);await assert.rejects(openEtsySteelOwnerHandoff(f.owner,start.handoffId,f.d));});
test('owner Stop releases and preserves unsettled liability',async()=>{const f=fixture(),start=await beginEtsySteelHandoff(f.s,f.d);f.stop.abort();const r=await finishEtsySteelHandoff(f.owner,start.handoffId,'stop',f.d);assert.equal(r.status,'stopped');assert.equal(r.releaseState,'verified');assert.equal(r.liabilityState,'receipt_required');assert.equal(f.candidates.length,0);});
test('unconfirmed Stop consumption and release never claim stopped',async()=>{const f=fixture(),start=await beginEtsySteelHandoff(f.s,f.d);f.d.consumeHandoff=async()=>{throw Error('unknown');};f.d.releaseSession=async()=>({sessionId:f.s.operationId,released:false,terminalReadback:false});const r=await finishEtsySteelHandoff(f.owner,start.handoffId,'stop',f.d);assert.equal(r.status,'failed');assert.equal(r.releaseState,'unconfirmed');assert.equal(r.liabilityState,'unknown');});
for(const [name,mutate]of[['wrong project',f=>f.session.providerProjectId=id(99)],['wrong session',f=>f.session.providerSessionId=id(99)],['unsafe viewer',f=>f.session.debugUrl='https://untrusted.example'],['disconnect proof',f=>f.session.disconnectForOwner=async()=>({cdpDisconnected:false})]])test(name+' cannot publish handoff',async()=>{const f=fixture();mutate(f);const r=await beginEtsySteelHandoff(f.s,f.d);assert.equal(r.status,'failed');assert.equal(f.records.size,0);});
test('wrong owner cannot open a private live URL',async()=>{const f=fixture(),r=await beginEtsySteelHandoff(f.s,f.d);await assert.rejects(openEtsySteelOwnerHandoff({...f.owner,ownerId:id(90)},r.handoffId,f.d));});
test('duplicate create never dispatches again',async()=>{const f=fixture();await beginEtsySteelHandoff(f.s,f.d);const r=await beginEtsySteelHandoff(f.s,f.d);assert.equal(r.status,'failed');assert.equal(f.events.filter(e=>e==='create').length,1);});
test('missing durable cleanup storage cannot expose a viewer',async()=>{const f=fixture();f.d.storeHandoff=async r=>({recordHash:r.recordHash,cleanupRegistered:false});const r=await beginEtsySteelHandoff(f.s,f.d);assert.equal(r.status,'failed');assert.ok(f.events.includes('release'));});
