import test from 'node:test';import assert from 'node:assert/strict';
import {verificationFixture,NOW,id,H} from './helpers/etsy-insights-playwright-fixture.mjs';
import {verifyApprovedEtsySteelProfile} from '../.core-tests/accounts/etsy-steel-verification-runtime.js';
import {buildEtsySteelHandoffDisclosure,etsySteelHash as hash} from '../.core-tests/accounts/etsy-steel-handoff-contracts.js';
function fixture(options={}){
 const f=verificationFixture({...options,beforeNavigate:url=>f.request(url)}),v=f.authority.scope;
 let setup={version:'etsy.steel-owner-handoff-scope.1',operationId:v.setupOperationId,ownerId:v.ownerId,businessId:v.businessId,goalId:v.goalId,authorityRootId:v.authorityRootId,testEnvelopeId:v.testEnvelopeId,testEnvelopeHash:v.testEnvelopeHash,providerProjectId:v.providerProjectId,verificationOperationId:v.operationId,verificationMaximumMicrounits:v.maximumBrowserMicrounits,verificationQuoteHash:v.quoteHash,accountId:id(120),accountRevision:id(121),expectedShopName:v.expectedShopName,expectedShopId:null,purpose:'etsy_insights_read_only',approvalId:v.approvalId,approvalRevision:v.approvalRevision,approvedAt:new Date(NOW-1000).toISOString(),approvalExpiresAt:new Date(NOW+900000).toISOString(),profileAccessExpiresAt:v.profileAccessExpiresAt,maximumSessionMs:900000,maximumBrowserMicrounits:'50000',currency:'USD',quoteHash:H(125),disclosureHash:H(126)};
 setup={...setup,disclosureHash:hash(buildEtsySteelHandoffDisclosure(setup))};v.disclosureHash=setup.disclosureHash;f.authority.scopeHash=hash(v);
 const calls=[],stored=new Map(),q={providerProjectId:v.providerProjectId,providerAccountHash:H(130),routeHash:H(131),tariffHash:H(132),qualificationHash:H(133),maximumSessionMs:30000,maximumSessionMicrounits:'20000',revoked:false,usageBound:{version:'r12.steel-usage-bound.1',maximumProxyBytes:0,tariffCoversSessionAndProfileLifecycle:true,captchaDisabled:true,extraServicesDisabled:true}};
 const input={setupScope:setup,handoffReceiptHash:H(140),routeHash:q.routeHash,signal:f.stop.signal,now:()=>NOW,registerCleanup:f.input.registerCleanup,config:f.input.config,fetcher:f.input.fetcher,connect:f.input.connect,
  rpc:async(op,payload)=>{calls.push([op,payload]);if(op==='prepare'||op==='inputs')return f.authority;if(op==='admit')return{version:'etsy.steel-account-verification-permit.1',operationId:v.operationId,scopeHash:f.authority.scopeHash,reservationId:id(160),reservationHash:H(161),reservedBrowserMicrounits:v.maximumBrowserMicrounits,expiresAt:new Date(NOW+10000).toISOString()};if(op==='transport')return{allowed:true,operationId:v.operationId};if(op==='qualify_renderer'){const {qualificationHash,...body}=await f.verificationInput.qualifyRenderer(v);return{...body,qualificationHash:hash(body)};}if(op==='admit_renderer')return{accepted:true,allowed:true,sequence:payload.request.sequence};if(op==='verify'){assert.ok(stored.get('cleanup'));return{verified:true,binding:payload.binding};}if(op==='cleanup_complete'){stored.set('cleanup',payload);return{operationId:v.operationId,releaseVerified:true,billingStillRequiresLedger:true};}throw Error(op);},
  ledger:async(operationId,op,payload)=>{assert.equal(operationId,v.operationId);calls.push(['ledger:'+op,payload]);if(op==='read')return{operationId,operationMaximumMicrounits:'20000',scopeHash:f.authority.scopeHash,requestHash:H(150),qualification:q};if(op==='bind_session')return{operationId,usageIdentityHash:H(151)};if(op==='receipt'){const prior=stored.get('receipt');if(prior)assert.deepEqual(payload,prior);stored.set('receipt',payload);return{persisted:true,receiptHash:payload.receiptHash};}if(op==='evidence'){stored.set(payload.kind,payload.content);return{evidenceHash:hash(payload.content)};}if(op==='reconcile')return{accepted:stored.get('usage_bound').withinQualifiedLimits,accounting:{status:'qualified_bounded_pending'}};throw Error(op);}};
 return{f,input,calls,stored};
}
test('real verification port composes admitted no-query browser, held accounting and exact saved binding',async()=>{const x=fixture(),r=await verifyApprovedEtsySteelProfile(x.input);assert.equal(r.status,'verified');assert.equal(r.accountingConfirmed,true);assert.equal(x.f.events.filter(e=>e==='create').length,1);assert.equal(x.calls.filter(([op])=>op==='admit').length,1);assert.ok(x.calls.findIndex(([op])=>op==='ledger:reconcile')<x.calls.findIndex(([op])=>op==='verify'));assert.equal(r.binding.handoffReceiptHash,x.input.handoffReceiptHash);assert.equal(x.stored.get('usage_bound').durationMs,1000);assert.equal(x.calls.find(([op])=>op==='ledger:reconcile')[1].billingProofHash,null);assert.equal(x.f.getView(),'landing');});
test('wrong shop still records actual paid cleanup but never saves verified binding',async()=>{const x=fixture({shop:'Other Shop'}),r=await verifyApprovedEtsySteelProfile(x.input);assert.equal(r.status,'paused');assert.equal(r.binding,null);assert.equal(x.calls.some(([op])=>op==='verify'),false);assert.equal(x.stored.get('receipt').status,'paused');assert.equal(x.f.events.filter(e=>e==='create').length,1);});
test('missing actual provider usage keeps account verification unqualified',async()=>{const x=fixture({providerMetadata:{duration:null}}),r=await verifyApprovedEtsySteelProfile(x.input);assert.equal(r.status,'paused');assert.equal(r.accountingConfirmed,false);assert.equal(r.binding,null);assert.equal(x.calls.some(([op])=>op==='verify'),false);});
test('failed observer disposal cannot acquire account or bounded billing proof',async()=>{const x=fixture({disconnectFail:true}),r=await verifyApprovedEtsySteelProfile(x.input);assert.equal(r.status,'paused');assert.equal(r.accountingConfirmed,false);assert.equal(x.calls.some(([op])=>op==='verify'||op==='ledger:reconcile'),false);assert.equal(x.stored.get('receipt').liabilityState,'unknown');});

test('host registration must succeed before any RPC or browser work',()=>{const x=fixture();x.input.registerCleanup=()=>{throw Error('hosting refused');};assert.throws(()=>verifyApprovedEtsySteelProfile(x.input),/hosting refused/);assert.equal(x.calls.length,0);assert.equal(x.f.events.length,0);});
for(const key of ['authorityRootId','approvalId','approvalRevision','disclosureHash','expectedShopName','profileAccessExpiresAt'])test('verification rejects changed '+key+' before browser creation',async()=>{const x=fixture(),base=x.input.rpc;x.input.rpc=async(op,payload)=>{const r=await base(op,payload);if(op==='prepare')return{...r,scope:{...r.scope,[key]:key==='expectedShopName'?'Another shop':key==='profileAccessExpiresAt'?new Date(NOW+800000).toISOString():key==='disclosureHash'?H(999):id(999)}};return r;};await assert.rejects(verifyApprovedEtsySteelProfile(x.input),/verification_scope_changed/);assert.equal(x.f.events.includes('create'),false);});
for(const [name,patch]of[['expired',{expiresAt:new Date(NOW).toISOString()}],['overlong',{expiresAt:new Date(NOW+31000).toISOString()}],['wrong amount',{reservedBrowserMicrounits:'1'}],['extra field',{unexpected:true}]])test('invalid '+name+' reservation cannot create a provider session',async()=>{const x=fixture(),base=x.input.rpc;x.input.rpc=async(op,payload)=>{const r=await base(op,payload);return op==='admit'?{...r,...patch}:r;};const r=await verifyApprovedEtsySteelProfile(x.input);assert.equal(r.status,'paused');assert.equal(x.f.events.includes('create'),false);});
test('forged renderer qualification cannot create session',async()=>{const x=fixture(),base=x.input.rpc;x.input.rpc=async(op,payload)=>{const r=await base(op,payload);return op==='qualify_renderer'?{...r,qualificationHash:H(900)}:r;};const r=await verifyApprovedEtsySteelProfile(x.input);assert.equal(r.status,'paused');assert.equal(x.f.events.includes('create'),false);});
