import test from 'node:test';
import assert from 'node:assert/strict';
import {createHash} from 'node:crypto';
import {creativeHash} from '../.core-tests/creative/contracts.js';
import {resolveModelRoute} from '../.core-tests/models/registry.js';
import {executeFocusedCreativePhase} from '../.core-tests/creative/focused-runtime.js';
import {focusedCreativeDescriptor,qualifyFocusedCreativeReceipt,routeFocusedCreativeRequest} from '../.core-tests/creative/focused-runtime-contract.js';
import {OpenRouterImageAdapter} from '../.core-tests/creative/image-provider.js';
const id=n=>`cccccccc-cccc-4ccc-8ccc-${String(n).padStart(12,'0')}`;
const config={apiKey:'inert-untransmitted-live-credential',baseUrl:'https://openrouter.ai/api/v1',appUrl:'https://example.org',appName:'Inert Creative'};
const at=Date.parse('2026-10-07T00:00:00.000Z');
const stamp=n=>new Date(n).toISOString();
const json=(v,init={})=>new Response(JSON.stringify(v),{status:200,...init,headers:{'content-type':'application/json',...init.headers}});
const png=Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+/lX8AAAAASUVORK5CYII=','base64');
const catalog={id:'black-forest-labs/flux.2-klein-4b',endpoints:[{provider_name:'Black Forest Labs',provider_slug:'black-forest-labs',provider_tag:'black-forest-labs',supported_parameters:{aspect_ratio:{type:'enum',values:['1:1']},output_format:{type:'enum',values:['png','jpeg']},n:{type:'range',min:1,max:1},input_references:{type:'range',min:0,max:4},seed:{type:'boolean'}},allowed_passthrough_parameters:['steps','guidance','safety_tolerance'],supports_streaming:false,pricing:[{billable:'output_image',unit:'megapixel',cost_usd:.014}]}]};
function fixture(phase='brief:1',options={}){
 let clock=at,posts=0,gets=0,prepared=0,delayed=options.delayed??true;
 const events=[],files=new Map(),settled=new Map();let reserved=false,scope={version:'r12.focused-creative-scope.1',ownerId:id(1),businessId:id(2),creativeRunId:id(3),workflowRunId:id(4),approvalId:id(5),approvalHash:'a'.repeat(64),adoptionHash:'b'.repeat(64),installationId:id(6),installationSnapshotHash:'c'.repeat(64),startsAt:stamp(at-1000),expiresAt:stamp(at-1000+1800000),receiptUntil:stamp(at-1000+3600000),quoteHash:'d'.repeat(64),phaseCeilings:{'brief:1':50000,'screen:1':50000,'generate:1':70000,'review:1':50000},sourceDomains:['printful.com'],dataClassesByPhase:{'brief:1':['business_context'],'screen:1':['business_context'],'generate:1':['business_context'],'review:1':['business_context','private_image']},priceLimitsByPhase:{'brief:1':{prompt:2,completion:10,request:0},'screen:1':{prompt:1,completion:5,request:0},'review:1':{prompt:1,completion:5,request:0}}};
 const state={scope,phase:{binding:null,candidate:null,proof:null,receipt:null},dispatchedAt:null},settlementReceipts=new Map();
 const storage={upload:async(path,bytes)=>{events.push('upload');assert.equal(files.has(path),false);if(options.uploadError)return{error:Error('inert upload failure')};files.set(path,Buffer.from(bytes));return{error:null};},download:async path=>{events.push('download');const original=files.get(path),bytes=original?Buffer.from(original):null;if(bytes&&options.downloadMismatch)bytes[0]^=1;return{error:null,data:bytes?new Blob([bytes]):null};}};
 const store={storage,admit:async descriptor=>{events.push('admit');assert.deepEqual(descriptor.accounting,{kind:'creative',runId:id(3),callKey:phase});assert.equal(descriptor.liabilityMicrounits,String(scope.phaseCeilings[phase]));return id(8);},settle:async(key,amount,generationId,receipt)=>{events.push('settle');const old=settled.get(key);if(old)assert.deepEqual(old,{amount,generationId});else settled.set(key,{amount,generationId});assert.equal(receipt.version==='r12.focused-creative-candidate.1'||['focused_phase_rejected','focused_dispatch_denied'].includes(receipt.failure),true);settlementReceipts.set(key,structuredClone(receipt));},transition:async(operation,payload)=>{
 events.push(operation);
 if(operation==='r12_load')return structuredClone(state);
 if(operation==='reserve_call'){const shouldExecute=!reserved;reserved=true;if(options.expireBeforeSend)clock+=300001;return{shouldExecute,committedMicrousd:scope.phaseCeilings[phase]};}
 if(operation==='r12_bind'){assert.equal(payload.bindingHash,creativeHash(payload.binding));state.phase.binding=structuredClone(payload.binding);return{};}
 if(operation==='r12_send'){assert.equal(state.dispatchedAt,null);state.dispatchedAt=stamp(clock);return{shouldDispatch:true};}
 if(operation==='r12_observe'){assert.equal(payload.observationHash,creativeHash(payload.observation));return{};}
 if(operation==='r12_stage'){assert.equal(state.phase.candidate,null);state.phase.candidate=structuredClone(payload.candidate);state.phase.receipt={status:'awaiting_receipt',attempts:0,nextCheckAt:null,receiptExpiresAt:scope.receiptUntil};return{};}
 if(operation==='r12_claim'){const r=state.phase.receipt;if(r.attempts>=3||r.nextCheckAt&&Date.parse(r.nextCheckAt)>clock||Date.parse(r.receiptExpiresAt)<=clock)return{claimed:false};r.attempts++;r.status='checking_receipt';return{claimed:true,claimId:id(100+r.attempts)};}
 if(operation==='r12_record'){const r=state.phase.receipt;if(payload.proof){state.phase.proof=structuredClone(payload.proof);r.status='verified';}else{r.status=r.attempts>=3?'exhausted':payload.diagnostic.code==='receipt_invalid'?'terminal':'awaiting_receipt';r.nextCheckAt=payload.retryAfterAt;}return{};}
 if(operation==='r12_persist'){assert.ok(state.phase.proof);assert.equal(payload.proofHash,state.phase.proof.proofHash);events.push('persisted');return{};}
 throw Error(operation);
 }};
 const fetcher=async(url,init={})=>{
 if(String(url).includes('/images/models/'))return json(catalog);
 if(init.method==='POST'){posts++;events.push('POST');if(phase==='generate:1')return json({data:[{b64_json:(options.imageBytes??png).toString('base64')}],usage:{cost:.014}},{headers:options.omitGenerationHeader?{'x-request-id':'gen-generic-not-image-proof'}:{'x-generation-id':'gen-image-inert','x-request-id':'ordinary-request-id'}});
 return json({id:'gen-text-inert',model:phase==='brief:1'?'openai/gpt-5.6-luna-20260709':'anthropic/claude-4.5-haiku-20251001',provider:phase==='brief:1'?'Azure':'Amazon Bedrock',choices:[{finish_reason:'stop',message:{content:JSON.stringify({result:'A locally valid bounded output.'})}}],usage:{prompt_tokens:20,completion_tokens:10,total_tokens:30,cost:.00001}});}
 gets++;events.push('GET');assert.ok(state.phase.candidate,'Candidate is durable before GET');if(phase==='generate:1'){assert.equal(files.size,1);assert.equal(events.includes('inspect'),false);}
 if(delayed)return json({error:{message:'Awaiting immutable receipt'}},{status:404,headers:{'retry-after':options.retryAfter??'120'}});
 const route=phase==='generate:1'?{provider:'Black Forest Labs',model:'black-forest-labs/flux.2-klein-4b',generation:'gen-image-inert'}:phase==='brief:1'?{provider:'Azure',model:'openai/gpt-5.6-luna',generation:'gen-text-inert'}:{provider:'Amazon Bedrock',model:'anthropic/claude-haiku-4.5',generation:'gen-text-inert'};
 return json({data:{id:route.generation,provider_name:options.badProvider?'Other':route.provider,model:route.model,...(phase==='generate:1'?{api_type:'image',created_at:state.phase.candidate.receivedAt,total_cost:.014,num_media_completion:1,num_media_prompt:0}: {})}});
 };
 const prepare=async(_validationAt,binding)=>{prepared++;if(phase==='generate:1'){const prompt='One original botanical arrangement without any copied artwork, lettering or reference image.',body={model:'black-forest-labs/flux.2-klein-4b',prompt,aspect_ratio:'1:1',n:1,output_format:'png',size:'1024x1024',provider:{only:['black-forest-labs'],allow_fallbacks:false}},quote=binding?.request.quote??await new OpenRouterImageAdapter({modelId:body.model,config,fetcher,now:()=>clock}).preflight({prompt});return{kind:'image',prompt,quote,wireBody:JSON.stringify(body),requestHash:creativeHash(body),inspect:async(bytes,path,receivedAt)=>{events.push('inspect');assert.deepEqual(Buffer.from(bytes),png);assert.equal(path,`${id(2)}/${id(3)}/version-1.png`);return{originalBytesUnchanged:true,receivedAt};}};}
 const model=resolveModelRoute(phase==='brief:1'?'standard.default':'reviewer.independent').primary,quoteBody={version:'r12.focused-creative-dispatch-quote.1',callKey:phase,modelId:model.providerModelId,endpoint:phase==='brief:1'?'azure/us':'amazon-bedrock/us',verifiedAt:stamp(clock),validUntil:stamp(clock+300000),sourceQuoteHash:'e'.repeat(64),priceLimits:scope.priceLimitsByPhase[phase],maximumMicrousd:scope.phaseCeilings[phase]};
 return{kind:'text',dispatchQuote:binding?.dispatchQuote??{...quoteBody,quoteHash:creativeHash(quoteBody)},request:{model,messages:[{role:'user',content:'Return the exact bounded schema for this inert test.'}],schemaName:'creative_inert',outputSchema:{type:'object',additionalProperties:false,required:['result'],properties:{result:{type:'string'}}},maxOutputTokens:phase==='brief:1'?2500:1800},validateOutput:output=>assert.equal(output.result,'A locally valid bounded output.')};};
 const run=()=>executeFocusedCreativePhase({phase,businessId:id(2),creativeRunId:id(3),approvalHash:scope.approvalHash,store,prepare,config,fetcher,now:()=>clock});
 return{run,state,events,settled,settlementReceipts,files,counts:()=>({posts,gets,prepared}),advance:n=>clock+=n,undelay:()=>delayed=false,prepare};
}
test('delayed text receipt pauses and resumes the same existing creative reservation without a second paid POST',async()=>{const f=fixture();assert.equal((await f.run()).status,'waiting');assert.equal((await f.run()).status,'waiting');assert.deepEqual(f.counts(),{posts:1,gets:1,prepared:1});f.advance(120000);f.undelay();assert.deepEqual(await f.run(),{status:'advanced'});assert.equal(f.counts().posts,1);assert.equal(f.counts().gets,2);assert.equal(f.settled.size,1);assert.ok(f.events.indexOf('r12_stage')<f.events.indexOf('GET'));});
test('receipt Retry-After and three-claim exhaustion never regenerate or turn waiting into FatalError',async()=>{const f=fixture('screen:1',{retryAfter:'180'});const first=await f.run();assert.equal(Date.parse(first.wakeAt),at+180000);f.advance(120000);assert.equal((await f.run()).status,'waiting');assert.equal(f.counts().gets,1);f.advance(60000);await f.run();f.advance(180000);assert.deepEqual(await f.run(),{status:'blocked',reason:'exhausted'});f.advance(180000);assert.deepEqual(await f.run(),{status:'blocked',reason:'exhausted'});assert.equal(f.counts().posts,1);assert.equal(f.counts().gets,3);});
test('original image bytes are privately saved before receipt GET and inspected unchanged only after exact BFL proof',async()=>{const f=fixture('generate:1');assert.equal((await f.run()).status,'waiting');assert.ok(f.events.indexOf('upload')<f.events.indexOf('r12_stage'));assert.ok(f.events.indexOf('r12_stage')<f.events.indexOf('GET'));assert.equal(f.events.includes('inspect'),false);f.advance(120000);f.undelay();assert.deepEqual(await f.run(),{status:'advanced'});assert.equal(f.counts().posts,1);assert.equal(f.events.filter(x=>x==='upload').length,1);assert.deepEqual([...f.files.values()][0],png);assert.equal(f.settled.size,1);});
test('a gen-shaped generic image request id cannot stand in for same-response X-Generation-Id',async()=>{const f=fixture('generate:1',{omitGenerationHeader:true});await assert.rejects(f.run(),/unverified/);assert.equal(f.counts().posts,1);assert.equal(f.counts().gets,0);assert.equal(f.files.size,1);assert.equal(f.settlementReceipts.get('generate:1').sourcePreservation.downloadVerified,true);assert.equal((await f.run()).status,'blocked');assert.equal(f.counts().posts,1);});
test('oversized PNG and native WebP originals remain recoverable without acceptance, conversion or a second paid attempt',async()=>{
 const oversized=Buffer.alloc(3700001);png.copy(oversized);
 for(const [imageBytes,mediaType,suffix]of [[oversized,'image/png','.png'],[Buffer.from('RIFF0000WEBP','ascii'),'image/webp','.original.webp']]){
  const f=fixture('generate:1',{imageBytes});await assert.rejects(f.run(),/unverified/);
  const storagePath=`${id(2)}/${id(3)}/version-1${suffix}`;
  assert.deepEqual(f.files.get(storagePath),imageBytes);assert.deepEqual(f.settlementReceipts.get('generate:1').sourcePreservation,{storagePath,mediaType,bytes:imageBytes.length,sha256:createHash('sha256').update(imageBytes).digest('hex'),uploadConfirmed:true,downloadVerified:true});
  assert.equal(f.state.phase.candidate,null);assert.equal(f.counts().gets,0);assert.equal(f.events.includes('inspect'),false);assert.equal(f.events.includes('persisted'),false);assert.equal(f.settled.get('generate:1').amount,14000);
  assert.equal((await f.run()).status,'blocked');assert.equal(f.counts().posts,1);assert.equal(f.events.filter(x=>x==='upload').length,1);
 }
});
test('source-preservation metadata distinguishes failed upload and failed read-back without claiming verification',async()=>{
 for(const [options,uploadConfirmed]of [[{uploadError:true},false],[{downloadMismatch:true},true]]){
  const f=fixture('generate:1',options);await assert.rejects(f.run(),/unverified/);
  const source=f.settlementReceipts.get('generate:1').sourcePreservation;assert.equal(source.uploadConfirmed,uploadConfirmed);assert.equal(source.downloadVerified,false);assert.equal(source.sha256,createHash('sha256').update(png).digest('hex'));
  assert.equal(f.counts().gets,0);assert.equal(f.state.phase.candidate,null);assert.equal((await f.run()).status,'blocked');assert.equal(f.counts().posts,1);
 }
});
test('existing seven-megabyte raw-source ceiling still rejects provider bytes before storage',async()=>{
 const imageBytes=Buffer.alloc(7000001);png.copy(imageBytes);const f=fixture('generate:1',{imageBytes});await assert.rejects(f.run());
 assert.equal(f.files.size,0);assert.equal(f.events.includes('upload'),false);assert.equal(f.settlementReceipts.get('generate:1').sourcePreservation,null);assert.equal(f.counts().gets,0);
 assert.equal((await f.run()).status,'blocked');assert.equal(f.counts().posts,1);
});
test('wrong provider receipt is terminal and never persists locally valid model output',async()=>{const f=fixture('brief:1',{delayed:false,badProvider:true});assert.deepEqual(await f.run(),{status:'blocked',reason:'terminal'});assert.equal(f.events.includes('persisted'),false);assert.equal(f.counts().posts,1);});
test('image descriptor uses one image with zero text-output tokens and exact existing creative accounting',async()=>{const f=fixture('generate:1'),p=await f.prepare(),d=focusedCreativeDescriptor(f.state.scope,'generate:1',p.requestHash,p.wireBody);assert.equal(d.maximumOutputTokens,0);assert.equal(d.maximumOutputImages,1);assert.deepEqual(d.accounting,{kind:'creative',runId:id(3),callKey:'generate:1'});const b=JSON.parse(p.wireBody);b.n=2;assert.throws(()=>focusedCreativeDescriptor(f.state.scope,'generate:1',p.requestHash,JSON.stringify(b)));});
test('visual source/base64 bound is checked before dispatch and generic text phases cannot carry pixels',async()=>{const f=fixture(),p=await f.prepare();p.request.messages[0].images=[{mediaType:'image/png',base64:png.toString('base64')}];assert.throws(()=>routeFocusedCreativeRequest(f.state.scope,'brief:1',p.request));const model=resolveModelRoute('reviewer.independent').primary,r={...p.request,model,maxOutputTokens:1800};r.messages[0].images=[{mediaType:'image/png',base64:Buffer.alloc(3700001).toString('base64')}];assert.throws(()=>routeFocusedCreativeRequest(f.state.scope,'review:1',r));});
test('image receipt proof binds exact generation, BFL model and every supplied provider response',()=>{const c={callKey:'generate:1',generationId:'gen-image-proof',receivedAt:stamp(at),reportedMicrousd:14000};const raw={data:{api_type:'image',created_at:stamp(at),total_cost:.014,num_media_completion:1,num_media_prompt:0,id:c.generationId,provider_name:'Black Forest Labs',model:'black-forest-labs/flux.2-klein-4b',provider_responses:[{provider_name:'Black Forest Labs',model_permaslug:'black-forest-labs/flux.2-klein-4b',status:200}]}};assert.equal(qualifyFocusedCreativeReceipt(raw,c).requestedEndpoint,'black-forest-labs');for(const mutate of [r=>r.data.id='gen-other',r=>r.data.model='recraft/recraft-v4.1-pro',r=>r.data.provider_name='Other',r=>r.data.provider_responses[0].status=500,r=>r.data.provider_responses[0].provider_name='Other',r=>r.data.api_type='completions',r=>r.data.total_cost=.015,r=>r.data.created_at=stamp(at-1800001),r=>r.data.num_media_completion=2,r=>r.data.num_media_prompt=1]){const bad=structuredClone(raw);mutate(bad);assert.throws(()=>qualifyFocusedCreativeReceipt(bad,c));}});
test('durable workflow waits and resumes the same phase without exhausting four paid phases or failing the run',async()=>{const{readFileSync}=await import('node:fs');const{createRequire}=await import('node:module');const require=createRequire(import.meta.url),ts=require('typescript');let completed=0,calls=0,sleeps=0,failed=0;const phases=['brief:1','screen:1','generate:1','review:1'];const deps={workflow:{FatalError:class extends Error{},getWorkflowMetadata:()=>({workflowRunId:id(99)}),sleep:async date=>{assert.ok(date instanceof Date);sleeps++;}},'../creative/errors':{creativeFailureMessage:error=>error.message},'./creative-runtime-steps':{loadCreativeRun:async()=>({status:completed===4?'completed':'running',phaseKey:phases[completed],productionReady:completed===4,approval:{maximumGenerations:1}}),executeCreativePhase:async(_input,phase)=>{assert.equal(phase,phases[completed]);calls++;if(calls===1)return{status:'waiting',wakeAt:stamp(at+120000)};completed++;return{status:'advanced'};},failCreativeRun:async()=>failed++}};const m={exports:{}};new Function('require','module','exports',ts.transpileModule(readFileSync(new URL('../src/workflows/creative-runtime.ts',import.meta.url),'utf8'),{compilerOptions:{target:ts.ScriptTarget.ES2022,module:ts.ModuleKind.CommonJS}}).outputText)(key=>{assert.ok(key in deps);return deps[key];},m,m.exports);const result=await m.exports.creativeRuntimeWorkflow({creativeRunId:id(3)});assert.equal(result.status,'completed');assert.equal(calls,5);assert.equal(sleeps,1);assert.equal(failed,0);});
test('focused brief grammar stays narrow without changing legacy schemas or trimming UTF-8 artifacts',async()=>{const{focusedCreativeBriefSchema,validateFocusedCreativeBriefBytes}=await import('../.core-tests/creative/focused-brief.js');const{DESIGN_BRIEF_SCHEMA}=await import('../.core-tests/creative/packs.js');const{assertJsonSchemaValue}=await import('../.core-tests/workers/schema-validator.js');const before=structuredClone(DESIGN_BRIEF_SCHEMA),s=focusedCreativeBriefSchema(DESIGN_BRIEF_SCHEMA);assert.deepEqual(DESIGN_BRIEF_SCHEMA,before);assert.equal(s.properties.imagePrompt.maxLength,600);assert.equal(s.properties.style.maxLength,100);assert.equal(s.properties.forbiddenElements.maxItems,6);assert.throws(()=>assertJsonSchemaValue(s.properties.imagePrompt,'x'.repeat(601),'Focused image prompt'));assert.throws(()=>validateFocusedCreativeBriefBytes({imagePrompt:'🌿'.repeat(600)}),/2048-byte/);});
test('near-bound canonical image bytes serialize without a recursive base64 regex or provider call',async()=>{
 const{inspectFocusedTextWire}=await import('../.core-tests/creative/focused-runtime.js');const f=fixture('review:1'),p=await f.prepare(),bytes=Buffer.alloc(3699999);png.copy(bytes,0,0,8);const encoded=bytes.toString('base64');p.request.messages[0].images=[{mediaType:'image/png',base64:encoded}];const routed=routeFocusedCreativeRequest(f.state.scope,'review:1',p.request),body=await inspectFocusedTextWire(routed,config);assert.ok(Buffer.byteLength(body)<5000000);assert.ok(body.includes(encoded));assert.equal(f.counts().posts,0);
 for(const bad of [encoded.slice(0,-1)+' ',encoded.slice(0,-3)+'===',encoded.slice(0,-4)+'AB==']){p.request.messages[0].images[0].base64=bad;await assert.rejects(inspectFocusedTextWire(p.request,config));}
});

test('expired quote after reservation blocks transport and records a known zero without permitting a retry',async()=>{const f=fixture('brief:1',{expireBeforeSend:true});await assert.rejects(f.run(),/denied model dispatch/);assert.equal(f.counts().posts,0);assert.equal(f.counts().gets,0);assert.deepEqual(f.settled.get('brief:1'),{amount:0,generationId:null});await assert.rejects(f.run());assert.equal(f.counts().posts,0);});
