import test from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync,existsSync} from 'node:fs';
import {createRequire} from 'node:module';
import {runInNewContext} from 'node:vm';
const require=createRequire(import.meta.url),ts=require('typescript'),React=require('react');
const {renderToStaticMarkup}=require('react-dom/server');
function load(path,deps,globals={}){const code=ts.transpileModule(readFileSync(path,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022,jsx:ts.JsxEmit.ReactJSX,esModuleInterop:true}}).outputText;const m={exports:{}};runInNewContext(`(function(require,module,exports){${code}\n})`,globals)(name=>{assert.ok(name in deps,`Unexpected dependency ${name}`);return deps[name];},m,m.exports);return m.exports;}
const noop=async()=>{};
const {ListingWorkspace}=load('src/app/dashboard/etsy/listing-workspace.tsx',{'react/jsx-runtime':require('react/jsx-runtime'),'next/link':({children,href,...props})=>React.createElement('a',{href,...props},children),'./listing-actions':{startListingPreparation:noop,stopListingPreparation:noop,closeExpiredListingPreparation:noop,startListingQualification:noop,stopListingQualification:noop}});
const base={businessId:'fixture-business',configured:false,qualified:false,unavailable:false,sources:[],runs:[],sourceBlocker:false,qualificationRuns:[],qualificationQuote:null,qualificationQuoteUnavailable:false,qualificationLaunchNonce:null};
const render=data=>renderToStaticMarkup(React.createElement(ListingWorkspace,{data}));
test('missing setup, qualification and verified sources stay visible without executable controls',()=>{const html=render(base);assert.match(html,/Secure listing setup is not available/);assert.match(html,/Live qualification is still required/);assert.match(html,/No eligible verified listing input/);assert.doesNotMatch(html,/>Start listing preparation</);assert.match(html,/raw artwork does not meet/);assert.doesNotMatch(html,/type="text"|vaultKey|runtimeCapability|accessToken/);});
test('eligible source exposes exact separate paid scope and only hidden implementation identities',()=>{const html=render({...base,configured:true,qualified:true,sources:[{id:'fixture-source',title:'Verified fern shirt',inputHash:'a'.repeat(64),expiresAt:'2026-10-02T10:00:00Z',quote:{maximumEstimateMicrousd:220000}}]});assert.match(html,/<input(?=[^>]*name="listingConsent")(?=[^>]*required="")/);assert.match(html,/<input(?=[^>]*name="listingBudgetUsd")(?=[^>]*min="0.01")(?=[^>]*max="1")/);assert.match(html,/type="hidden" name="sourceArtifactId"/);assert.match(html,/value="0.22"/);assert.match(html,/OpenAI and Anthropic/);assert.match(html,/>Start listing preparation</);assert.doesNotMatch(html,/>Publish<|>Create Etsy draft</);});
test('rejected and needs-evidence histories are never rendered as package-ready',()=>{for(const [status,label] of [['rejected','Review rejected the package'],['needs_evidence','More evidence required']]){const html=render({...base,runs:[{id:'fixture-run',workflowRunId:'fixture-workflow',status,phase:'terminal',maximumMicrousd:500000,costs:[{role:'specialist',reservedMicrousd:200000,reportedMicrousd:100000,settled:true}],review:null,proposal:null}]});assert.ok(html.includes(label));assert.doesNotMatch(html,/Reviewed package ready|Stop further calls/);assert.match(html,/reported cost/);}});
test('cancelled and unknown-charge history keeps liability visible and offers no replay button',()=>{const html=render({...base,runs:[{id:'fixture-run',workflowRunId:'fixture-workflow',status:'cancelled',phase:'terminal',maximumMicrousd:500000,costs:[{role:'specialist',reservedMicrousd:200000,reportedMicrousd:null,settled:true}]}]});assert.match(html,/charge unresolved/);assert.match(html,/Stopping prevents later calls/);assert.doesNotMatch(html,/>Retry<|>Resume<|>Start again</);});
function actionHarness({duplicate=false,launchFails=false}={}){const calls=[];const deps={'next/navigation':{redirect:url=>{throw new Error(url);}},'next/cache':{revalidatePath:()=>{}},'workflow/api':{start:async(...args)=>{calls.push(['start',...args]);if(launchFails)throw new Error('fixture launch');}},'@/lib/core-ui/data':{requireOwnerUiContext:async()=>({owner:true})},'@/listing/server':{beginListingPreparation:async(...args)=>{calls.push(['begin',...args]);return{runId:'run',workflowRunId:'workflow',shouldStart:!duplicate,runtimeCapability:'fixture-private',launchNonce:'nonce'};},listingOwnerRpc:async(...args)=>{calls.push(['rpc',...args]);return{};},beginListingQualification:async(...args)=>{calls.push(['qualification',...args]);return{runId:'qualification',workflowRunId:'evaluation',shouldStart:!duplicate,runtimeCapability:'fixture-private',launchNonce:'nonce'};}},'@/workflows/listing-runtime':{listingRuntimeWorkflow:()=>{}},'@/workflows/listing-qualification-runtime':{listingQualificationWorkflow:()=>{}}};return{calls,...load('src/app/dashboard/etsy/listing-actions.ts',deps)};}
function form(){const f=new FormData();f.set('businessId','business');f.set('sourceArtifactId','source');f.set('inputHash','hash');f.set('listingBudgetUsd','0.50');return f;}
test('unapproved listing request stops before source loading, quotes or launch',async()=>{const h=actionHarness();await assert.rejects(h.startListingPreparation(form()),/listing-consent-required/);assert.equal(h.calls.length,0);});
test('invalid or over-cap numeric formats cannot reach the durable launch',async()=>{for(const amount of ['2','1.01','NaN','1e0','-0.50']){const h=actionHarness(),f=form();f.set('listingConsent','on');f.set('listingBudgetUsd',amount);await assert.rejects(h.startListingPreparation(f),/listing-budget-invalid/);assert.equal(h.calls.length,0);}});
test('approved start transmits one exact separate allowance and one durable workflow launch',async()=>{const h=actionHarness(),f=form();f.set('listingConsent','on');await assert.rejects(h.startListingPreparation(f),/\/dashboard\/workflows\/workflow/);assert.equal(h.calls.filter(c=>c[0]==='start').length,1);assert.equal(h.calls[0].at(-1),500000);});
test('duplicate launch reuses its original workflow without another execution',async()=>{const h=actionHarness({duplicate:true}),f=form();f.set('listingConsent','on');await assert.rejects(h.startListingPreparation(f),/\/dashboard\/workflows\/workflow/);assert.equal(h.calls.filter(c=>c[0]==='start').length,0);});
test('uncertain launch records the original nonce and never blindly resends',async()=>{const h=actionHarness({launchFails:true}),f=form();f.set('listingConsent','on');await assert.rejects(h.startListingPreparation(f),/listing-launch-uncertain/);assert.equal(h.calls.filter(c=>c[0]==='start').length,1);const rpc=h.calls.find(c=>c[0]==='rpc');assert.equal(rpc[3],'fail_launch');assert.equal(rpc[4].launchNonce,'nonce');});
test('stop and expiry close preserve Business scope and invoke no model launcher',async()=>{for(const action of ['stopListingPreparation','closeExpiredListingPreparation']){const h=actionHarness(),f=form();f.set('listingRunId','run');await assert.rejects(h[action](f),/business=business&message=listing-stopped/);assert.equal(h.calls.length,1);assert.equal(h.calls[0][0],'rpc');}});
test('qualification controls describe five live calls using synthetic test data and a separate allowance',()=>{const html=render({...base,configured:true,qualificationQuote:{suiteHash:'fixture-hash',maximumEstimateMicrousd:450000}});assert.match(html,/five fixed test cases with real model responses/);assert.match(html,/synthetic product data/);assert.match(html,/separate allowance from product research/);assert.match(html,/<input(?=[^>]*name="qualificationConsent")(?=[^>]*required="")/);assert.match(html,/>Start worker qualification</);assert.doesNotMatch(html,/>Start listing preparation</);});
test('qualification requires its own explicit consent even when listing consent is present',async()=>{const h=actionHarness(),f=form();f.set('listingConsent','on');await assert.rejects(h.startListingQualification(f),/qualification-consent-required/);assert.equal(h.calls.length,0);});
test('qualification dispatch uses the approved five-case budget and its distinct workflow',async()=>{const h=actionHarness(),f=form();f.set('qualificationConsent','on');f.set('qualificationBudgetUsd','0.75');f.set('suiteHash','current-suite');f.set('qualificationLaunchNonce','fixed-nonce');await assert.rejects(h.startListingQualification(f),/\/dashboard\/workflows\/evaluation/);assert.equal(h.calls[0][0],'qualification');assert.equal(h.calls[0].at(-2),750000);assert.equal(h.calls[0].at(-1),'fixed-nonce');assert.equal(h.calls.filter(c=>c[0]==='start').length,1);assert.equal(h.calls[1][2][0].qualificationRunId,'qualification');assert.equal('listingRunId' in h.calls[1][2][0],false);});

test('browser verifies separate native budget/consent controls and narrow/mobile layout',{skip:!process.env.CI||!existsSync('/usr/bin/google-chrome')},async()=>{
 const {chromium}=require('playwright-core');const browser=await chromium.launch({executablePath:'/usr/bin/google-chrome',headless:true,args:['--no-sandbox']});
 try{const page=await browser.newPage();const data={...base,configured:true,qualificationLaunchNonce:'fixture-nonce',qualificationQuote:{suiteHash:'fixture',maximumEstimateMicrousd:450000}};
 await page.setContent(`<style>body{margin:16px;background:#111;color:#fff}*{box-sizing:border-box}${readFileSync('src/app/dashboard/etsy/etsy.css','utf8')}</style>${render(data)}`);
 const form=page.locator('form').filter({has:page.getByRole('button',{name:'Start worker qualification',exact:true})});assert.equal(await form.evaluate(el=>el.checkValidity()),false);await page.locator('[name=qualificationConsent]').check();assert.equal(await form.evaluate(el=>el.checkValidity()),true);
 await page.locator('[name=qualificationBudgetUsd]').fill('1.01');assert.equal(await form.evaluate(el=>el.checkValidity()),false);await page.locator('[name=qualificationBudgetUsd]').fill('0.75');
 for(const width of [1280,390]){await page.setViewportSize({width,height:900});assert.equal(await page.getByRole('button',{name:'Start worker qualification',exact:true}).isVisible(),true);assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);}assert.equal(await page.getByRole('button',{name:'Start listing preparation',exact:true}).count(),0);
 }finally{await browser.close();}
});
