import test from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {createRequire} from 'node:module';
import {runInNewContext} from 'node:vm';
const require=createRequire(import.meta.url),ts=require('typescript');
function load(path,deps){const code=ts.transpileModule(readFileSync(path,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText;const m={exports:{}};runInNewContext(`(function(require,module,exports){${code}\n})`)(name=>{assert.ok(name in deps,`Unexpected dependency ${name}`);return deps[name];},m,m.exports);return m.exports;}
const contracts=require('../.core-tests/etsy/contracts.js');
function production(throwEarly=false){const calls=[],verified=[];const input={businessId:'business',listingRunId:'run',coreWorkflowRunId:'workflow',runtimeCapability:'fixture-capability'};let raw={id:'run',businessId:'business',workflowRunId:'workflow',sourceArtifactId:'source',outputArtifactId:'output',input:{},inputHash:'hash',knowledgeHash:'knowledge',workerHashes:{},status:'running',phase:'specialist',maximumMicrousd:100000,quote:{},taskIds:{},outputs:{},sourceEnvelope:'fixture-source-envelope',costs:{committedMicrousd:1},reason:null};const rpc=async(name,args)=>{calls.push({name,args});return{data:raw};};const exports=load('src/workflows/listing-runtime-steps.ts',{'workflow':{FatalError:class extends Error{}},'../lib/supabase/runtime':{createRuntimeClient:()=>({rpc})},'../etsy/contracts':contracts,'../listing/engine':{executeListingRun:async()=>{if(throwEarly)throw new Error('private model configuration');return{status:'completed'};}},'../listing/server':{assertRuntimeListingSource:value=>verified.push(value),issueListingEnvelopes:()=>({})}});return{calls,verified,input,exports,setRaw:value=>raw=value,raw};}
test('listing durable repository binds business, workflow and one-run capability on every RPC',async()=>{const f=production(),r=f.exports.listingRuntimeRepository(f.input,'runtime-workflow');const state=await r.load();await r.guard();await r.reserve({role:'specialist'});assert.ok(f.calls.every(c=>c.name==='listing_runtime_transition'&&c.args.p_business_id==='business'&&c.args.p_run_id==='run'&&c.args.p_runtime_capability==='fixture-capability'));assert.equal(f.calls[0].args.p_payload.runtimeRunId,'runtime-workflow');assert.equal(f.verified.length,2);assert.equal('costs' in state,false);assert.equal('sourceEnvelope' in state,false);assert.equal('reason' in state,false);assert.equal(f.exports.executeListingPreparation.maxRetries,0);});
test('wrong run scope fails before source verification or dispatch',async()=>{const f=production();f.setRaw({...f.raw,businessId:'foreign'});await assert.rejects(f.exports.listingRuntimeRepository(f.input,'runtime').guard(),/listing_runtime_scope_mismatch/);assert.equal(f.verified.length,0);});
test('qualification lane uses its separate RPC and exact case-state projection with no retry',async()=>{const calls=[],input={businessId:'business',qualificationRunId:'qual-run',coreWorkflowRunId:'workflow',runtimeCapability:'fixture-capability'};const raw={id:'qual-run',businessId:'business',workflowRunId:'workflow',status:'running',suiteHash:'suite',knowledgeHash:'policy',workerHashes:{},maximumMicrousd:100000,quote:{},taskIds:{},cases:{},costs:{committedMicrousd:1},reason:'private'};const exports=load('src/workflows/listing-qualification-runtime-steps.ts',{'workflow':{FatalError:class extends Error{}},'../lib/supabase/runtime':{createRuntimeClient:()=>({rpc:async(name,args)=>{calls.push({name,args});return{data:raw};}})},'../etsy/contracts':contracts,'../listing/qualification':{executeListingQualification:async()=>({status:'passed'})}});const r=exports.listingQualificationRepository(input,'runtime');const state=await r.load();await r.finish();assert.ok(calls.every(c=>c.name==='listing_qualification_transition'&&c.args.p_run_id==='qual-run'));assert.equal('costs' in state,false);assert.equal('reason' in state,false);assert.equal(exports.executeListingQualificationStep.maxRetries,0);assert.equal(calls.at(-1).args.p_operation,'finish');});
test('durable qualification workflow stops at five one-call steps and preserves early terminal results',async()=>{
 let calls=0;const deps={'workflow':{FatalError:class extends Error{},getWorkflowMetadata:()=>({workflowRunId:'runtime'})},'./listing-qualification-runtime-steps':{executeListingQualificationStep:async()=>({status:++calls===5?'passed':'running'})}};
 const {listingQualificationWorkflow}=load('src/workflows/listing-qualification-runtime.ts',deps);
 assert.equal((await listingQualificationWorkflow({})).status,'passed');assert.equal(calls,5);
 calls=0;deps['./listing-qualification-runtime-steps'].executeListingQualificationStep=async()=>{calls++;return{status:'failed'};};assert.equal((await listingQualificationWorkflow({})).status,'failed');assert.equal(calls,1);
});

test('early adapter/configuration failure records a safe terminal reason in both lanes',async()=>{
 const f=production(true);await assert.rejects(f.exports.executeListingPreparation(f.input,'runtime'),/^Error: Listing preparation stopped/);assert.equal(f.calls.length,1);assert.equal(f.calls[0].args.p_operation,'fail');assert.equal(f.calls[0].args.p_payload.reason,'listing_runtime_failed');
 const calls=[],input={businessId:'business',qualificationRunId:'qual-run',coreWorkflowRunId:'workflow',runtimeCapability:'fixture-capability'};
 const exports=load('src/workflows/listing-qualification-runtime-steps.ts',{'workflow':{FatalError:class extends Error{}},'../lib/supabase/runtime':{createRuntimeClient:()=>({rpc:async(name,args)=>{calls.push({name,args});return{data:{}};}})},'../etsy/contracts':contracts,'../listing/qualification':{executeListingQualification:async()=>{throw new Error('private setup detail');}}});
 await assert.rejects(exports.executeListingQualificationStep(input,'runtime'),/^Error: Listing worker qualification stopped/);assert.equal(calls.length,1);assert.equal(calls[0].args.p_operation,'fail');assert.equal(calls[0].args.p_payload.reason,'listing_qualification_runtime_failed');
});
