import { ownerBusiness, historyRead, historyResponse } from './helpers/history-fixtures.mjs';
import test from 'node:test';
import assert from 'node:assert/strict';
import {createRequire} from 'node:module';
import {readFileSync} from 'node:fs';
import {runInNewContext} from 'node:vm';
import {productFixture,id} from './printful-product-fixtures.mjs';
const require=createRequire(import.meta.url),ts=require('typescript'),P=require('../.core-tests/printful/production.js');
const plain=x=>JSON.parse(JSON.stringify(x));
function harness(options={}){
  const f=productFixture(),calls=[],providerCalls=[],downloads=[];
  const context={businesses:[{id:f.source.businessId}],supabase:{rpc:async(name,args)=>{calls.push({name,args});const response=options.rpc?await options.rpc(name,args,f):{data:{sources:[],runs:[]}};if(name==='r06_read'&&response?.data&&!('items' in response.data))return historyResponse(args,args.p_dataset==='printful_runs'?response.data.runs:response.data.sources);return response;},storage:{from:bucket=>({download:async path=>{downloads.push({bucket,path});return{data:new Blob([f.bytes])};}})}}};
  const deps={'../lib/core-ui/owner-business':ownerBusiness,'../lib/core-ui/history-read':historyRead,'server-only':{},'../core/existing-effect-read':require('../.core-tests/core/existing-effect-read.js'),'../lib/existing-effect-read-runtime':{requireExistingEffectReadEligibility:async()=>{throw new Error('existing_effect_read_not_authorized');}},'node:crypto':require('node:crypto'),'../creative/types':require('../.core-tests/creative/types.js'),'./production':P,'./contracts':require('../.core-tests/printful/contracts.js'),
    './product-adapter':{PrintfulProductAdapter:class{constructor(){providerCalls.push('adapter');}}},'./product-engine':{executePrintfulProduct:async()=>{providerCalls.push('engine');return f.state;}}};
  const code=ts.transpileModule(readFileSync('src/printful/server.ts','utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText,m={exports:{}};
  runInNewContext(`(function(require,module,exports){${code}\n})`,{process:{env:options.env??{PRINTFUL_PRODUCT_SERVER_KEY:'s'.repeat(32)}},Date,Uint8Array})(name=>{assert.ok(name in deps,name);return deps[name];},m,m.exports);
  return{...m.exports,f,context,calls,providerCalls,downloads};
}
test('workspace is owner scoped and keyless; absence never enables configuration',async()=>{const h=harness({env:{}});await assert.rejects(h.loadPrintfulProductWorkspace(h.context,id(99)),/owner_required/);assert.equal(h.calls.length,0);const view=await h.loadPrintfulProductWorkspace(h.context,h.f.source.businessId);assert.equal(view.unavailable,false);assert.equal(view.configured,false);assert.equal(view.executionAvailable,false);assert.equal(h.calls.length,2);assert.ok(h.calls.every(c=>c.name==='r06_read'&&!('p_server_key' in c.args)));assert.deepEqual(h.calls.map(c=>c.args.p_dataset),['printful_runs','printful_sources']);});
test('RPC failure is unavailable history rather than falsely empty successful state',async()=>{const h=harness({rpc:async()=>({error:{message:'private secret'}})});const view=await h.loadPrintfulProductWorkspace(h.context,h.f.source.businessId);assert.equal(view.unavailable,true);assert.doesNotMatch(JSON.stringify(view),/private secret/);});
test('catalog or account key cannot confer product write authority; no credentials opened',async()=>{for(const env of[{}, {ACCOUNTS_SERVER_KEY:'s'.repeat(32),ACCOUNTS_VAULT_KEY:'a'.repeat(64)}, {PRINTFUL_PRODUCT_SERVER_KEY:'s'.repeat(32),PRINTFUL_PRODUCT_ENABLED:'true',PRINTFUL_API_KEY:'secret'}]){const h=harness({env});await assert.rejects(h.resolvePrintfulProductWriteAuthority(h.context,h.f.source),/product_write_authority_unavailable/);assert.deepEqual(h.calls,[]);assert.deepEqual(h.providerCalls,[]);}});
test('Stop remains owner-authorized and keyless while all evidence mutations require the separate key',async()=>{const h=harness({env:{}});await h.productRpc(h.context,h.f.source.businessId,'cancel',{runId:h.f.state.id});assert.equal(h.calls[0].args.p_server_key,'');await assert.rejects(h.productRpc(h.context,h.f.source.businessId,'prepare',{}),/server_unavailable/);assert.equal(h.calls.length,1);});
test('source authentication rejects fixture mode, wrong hash and foreign Business',()=>{const h=harness(),source=h.f.source;for(const raw of[{source,sourceHash:P.productHash(source)},{source:{...source,evidenceMode:'live'},sourceHash:'a'.repeat(64)},{source:{...source,evidenceMode:'live',businessId:id(99)},sourceHash:'a'.repeat(64)}])assert.throws(()=>h.authenticateProductSource(raw,source.businessId));const live={...source,evidenceMode:'live'};assert.equal(h.authenticateProductSource({source:live,sourceHash:P.productHash(live)},source.businessId).source.id,source.id);});
test('even complete live-shaped trusted source and configuration checkbox cannot bypass absent placement producer',async()=>{const h=harness({rpc:async(_,{p_operation},f)=>{assert.equal(p_operation,'source');const source={...f.source,evidenceMode:'live'};return{data:{source,sourceHash:P.productHash(source)}};}}),source={...h.f.source,evidenceMode:'live'};await assert.rejects(h.beginPrintfulProduct(h.context,source.businessId,source.id,P.productHash(source),true),/placement_producer_required/);assert.deepEqual(h.calls.map(c=>c.args.p_operation),['source']);assert.deepEqual(h.providerCalls,[]);});
test('owner consent and exact source IDs are mandatory before any source query',async()=>{const h=harness();for(const [sourceId,sourceHash,consent]of[[h.f.source.id,h.f.state.sourceHash,false],['bad',h.f.state.sourceHash,true],[h.f.source.id,'bad',true]])await assert.rejects(h.beginPrintfulProduct(h.context,h.f.source.businessId,sourceId,sourceHash,consent),/review_required/);assert.equal(h.calls.length,0);});
test('unavailable production write seam releases acquired lease, never enters provider engine',async()=>{const h=harness({rpc:async(_,{p_operation},f)=>({data:p_operation==='acquire'?{state:f.state,revision:0}:{}})});await assert.rejects(h.runPrintfulProduct(h.context,h.f.source.businessId,h.f.state.id),/write_authority_unavailable/);assert.deepEqual(h.calls.map(c=>c.args.p_operation),['acquire','release']);assert.deepEqual(h.providerCalls,[]);});
test('read-only reconcile request cannot become a new start without a marker',async()=>{const h=harness({rpc:async(_,{p_operation},f)=>({data:p_operation==='acquire'?{state:f.state,revision:0}:{}})});await assert.rejects(h.runPrintfulProduct(h.context,h.f.source.businessId,h.f.state.id,true),/not_dispatched/);assert.deepEqual(h.calls.map(c=>c.args.p_operation),['acquire','release']);});
test('malformed acquired scope releases lease once without provider calls',async()=>{const h=harness({rpc:async(_,{p_operation},f)=>({data:p_operation==='acquire'?{state:{...f.state,businessId:id(99)},revision:0}:{}})});await assert.rejects(h.runPrintfulProduct(h.context,h.f.source.businessId,h.f.state.id),/scope_mismatch/);assert.deepEqual(h.calls.map(c=>c.args.p_operation),['acquire','release']);assert.deepEqual(h.providerCalls,[]);});
test('repository CAS merges concurrent stop state and does not trust stale local state',async()=>{let revision=0;const h=harness({rpc:async(_,{p_operation},f)=>({data:p_operation==='acquire'?{state:f.state,revision}:p_operation==='save'?{state:{...f.state,stopRequested:true},revision:++revision}:{}})}),repo=h.printfulProductRepository(h.context,h.f.source.businessId,h.f.state.id),state=await repo.acquire();await repo.save(state);assert.equal(state.stopRequested,true);assert.equal(h.calls[1].args.p_payload.revision,0);await repo.release();});
test('asset downloader binds full Business/creative path and uses existing owner storage client',async()=>{const h=harness(),repo=h.printfulProductRepository(h.context,h.f.source.businessId,h.f.state.id);const bytes=await repo.assetBytes(h.f.source);assert.equal(bytes.length,h.f.bytes.length);assert.deepEqual(h.downloads,[{bucket:'creative-assets',path:h.f.source.assetStoragePath}]);await assert.rejects(repo.assetBytes({...h.f.source,businessId:id(99)}),/asset_path_invalid/);});
test('persisted source survives JSON key reordering without changing foundation plan fingerprint',()=>{const h=harness(),source={...h.f.source,evidenceMode:'live'};const reorder=v=>Array.isArray(v)?v.map(reorder):v&&typeof v==='object'?Object.fromEntries(Object.entries(v).reverse().map(([k,x])=>[k,reorder(x)])):v;const sorted=reorder(plain(source));assert.equal(h.authenticateProductSource({source:sorted,sourceHash:P.productHash(source)},source.businessId).sourceHash,P.productHash(source));});

test('incomplete durable source projection is unavailable instead of NaN or fabricated review fields',async()=>{const h=harness({rpc:async(_,_args,f)=>({data:{sources:[{id:f.source.id,name:f.source.name,sourceHash:f.state.sourceHash,expiresAt:f.source.expiresAt}],runs:[]}})});const view=await h.loadPrintfulProductWorkspace(h.context,h.f.source.businessId);assert.equal(view.unavailable,true);assert.deepEqual(plain(view.sources),[]);});

test('Printful Needs You remains exact-type/Business scoped and reports incomplete reads',async()=>{
 const h=harness(),queries=[];let result={data:[{id:id(99),business_id:h.f.source.businessId,workflow_run_id:null,intervention_type:'printful.product.reconcile',status:'open'}],count:1};
 h.context.supabase.from=table=>{queries.push(['from',table]);return{select(...args){queries.push(['select',...args]);return this;},in(...args){queries.push(['in',...args]);return this;},eq(...args){queries.push(['eq',...args]);return this;},order(){return this;},async limit(){return result;}};};
 assert.equal((await h.loadPrintfulProductInterventions(h.context)).records.length,1);assert.ok(queries.some(q=>q[0]==='eq'&&q[1]==='intervention_type'&&q[2]==='printful.product.reconcile'));assert.ok(queries.some(q=>q[0]==='in'&&q[1]==='business_id'&&q[2][0]===h.f.source.businessId));
 for(const count of [2,null,undefined,-1]){result={data:[],count};assert.equal((await h.loadPrintfulProductInterventions(h.context)).unavailable,true);}
 result={data:[{business_id:id(999),intervention_type:'printful.product.reconcile',status:'open'}],count:1};assert.equal((await h.loadPrintfulProductInterventions(h.context)).records.length,0);
});
test('history link forwards only UUID intervention to authoritative owner resolution',async()=>{const h=harness();await h.loadPrintfulProductWorkspace(h.context,h.f.source.businessId,id(99));assert.equal(h.calls[0].args.p_query.interventionId,id(99));assert.equal((await h.loadPrintfulProductWorkspace(h.context,h.f.source.businessId,'../bad')).unavailable,true);assert.equal(h.calls.length,2);});
