import test from 'node:test';
import assert from 'node:assert/strict';
import { createRequire } from 'node:module';
const require=createRequire(import.meta.url);
const { DISCOVERY_V2_BUDGET:B, quoteDiscoveryV2, reserveDiscoveryV2, callDiscoveryV2, discoveryV2Model }=require('../.core-tests/products/discovery-v2-budget.js');
const { resolveModelRoute }=require('../.core-tests/models/registry.js');
const { ModelProviderError }=require('../.core-tests/models/types.js');
const scope={intentId:'11111111-1111-4111-8111-111111111111',maximumCollections:2,maximumMicrousd:1_000_000,policyHash:'a'.repeat(64)};
const quote=(modelId)=>({modelId,verifiedAt:new Date().toISOString(),source:B.pricingSource,inputPerMillion:modelId.includes('haiku')?1:0.4,cacheWritePerMillion:modelId.includes('haiku')?2:0.5,outputPerMillion:modelId.includes('haiku')?5:1.8});
const request=(key)=>key.startsWith('search:')?{model:resolveModelRoute('standard.default').primary,query:'Find dated public observations for original forest T-shirts.',allowedDomains:['etsy.com']}:{model:resolveModelRoute(key==='review:1'?'reviewer.independent':'standard.default').primary,maxOutputTokens:B.phases[key.split(':')[0]].outputTokens,schemaName:'discovery_v2',outputSchema:{type:'object'},messages:[{role:'user',content:'Scoped synthetic evidence only.'}],requestMetadata:{}};
function setup({reported=0.001,model,providerName}={}) {const calls=[],reservations=[],settlements=[];return {calls,reservations,settlements,ledger:{reserve:async r=>{reservations.push(r);return {shouldCall:true,totalReservedMicrousd:r.reservedMicrousd};},settle:async(...v)=>{settlements.push(v);}},provider:{invokeStructured:async r=>{calls.push(r);return response(r);},invokeWebSearch:async r=>{calls.push(r);return response(r);}}};function response(r){return {provider:providerName??('query'in r?'openrouter.exa':'openrouter'),providerModelId:model??r.model.providerModelId,providerRequestId:'real-shaped-test-request',output:{synthetic:true},latencyMs:1,metadata:{},usage:{reportedCostUsd:reported,inputTokens:1,outputTokens:1,totalTokens:2,cachedInputTokens:0,reasoningTokens:0,estimatedCostUsd:0.001}};}}
test('finite quote counts complete one/two collection pipelines and never implies a provider cap',()=>{const q=quoteDiscoveryV2(scope,{director:quote(discoveryV2Model('plan:1')),reviewer:quote(discoveryV2Model('review:1'))});assert.equal(q.maximumCalls,7);assert.equal(q.maximumEstimateMicrousd,530914);assert.equal(q.providerInvoiceGuarantee,false);const one=quoteDiscoveryV2({...scope,maximumCollections:1},{director:quote(discoveryV2Model('plan:1')),reviewer:quote(discoveryV2Model('review:1'))});assert.equal(one.maximumCalls,5);assert.equal(one.maximumEstimateMicrousd,370395);assert.equal(one.ceilings['search:2'],undefined);assert.throws(()=>quoteDiscoveryV2({...scope,maximumMicrousd:500000},{director:quote(discoveryV2Model('plan:1')),reviewer:quote(discoveryV2Model('review:1'))}),/complete finite discovery quote exceeds/);});
test('phase bounds, exact model, quote freshness and immutable collection count fail before reserve',()=>{const req=request('strategy:1');assert.throws(()=>reserveDiscoveryV2(scope,'strategy:1',{...req,maxOutputTokens:99999},quote(req.model.providerModelId)),/bound/);assert.throws(()=>reserveDiscoveryV2(scope,'strategy:1',req,{...quote(req.model.providerModelId),verifiedAt:'2000-01-01T00:00:00Z'}),/Fresh/);assert.throws(()=>reserveDiscoveryV2(scope,'review:1',req,quote(discoveryV2Model('review:1'))),/primary model/);assert.throws(()=>reserveDiscoveryV2({...scope,maximumCollections:1},'search:2',request('search:2'),quote(discoveryV2Model('search:2'))),/second collection/);assert.throws(()=>reserveDiscoveryV2(scope,'strategy:1',{...req,messages:[{role:'user',content:'x'.repeat(32768)}]},quote(req.model.providerModelId)),/bound/);});
test('paid call pins one provider and returned identity, settles before consuming output',async()=>{const f=setup();const response=await callDiscoveryV2({scope,key:'strategy:1',request:request('strategy:1'),ledger:f.ledger,provider:f.provider,prices:async m=>quote(m)});assert.equal(f.calls.length,1);assert.deepEqual(f.calls[0].providerOnly,['openai']);assert.equal(f.calls[0].requireReturnedModel,true);assert.equal(f.settlements[0][1],1000);assert.equal(response.metadata.discoveryBudget.unknownCharge,false);assert.equal(f.reservations[0].estimate.policyHash,scope.policyHash);});
test('replay, timeout and returned wrong model never start a fallback',async()=>{const f=setup();f.ledger.reserve=async()=>({shouldCall:false,totalReservedMicrousd:1});await assert.rejects(()=>callDiscoveryV2({scope,key:'strategy:1',request:request('strategy:1'),ledger:f.ledger,provider:f.provider,prices:async m=>quote(m)}),/already reserved/);assert.equal(f.calls.length,0);const mismatch=setup({model:'other/model'});await assert.rejects(()=>callDiscoveryV2({scope,key:'strategy:1',request:request('strategy:1'),ledger:mismatch.ledger,provider:mismatch.provider,prices:async m=>quote(m)}),/differs/);assert.equal(mismatch.calls.length,1);assert.equal(mismatch.settlements[0][1],1000);const timeout=setup();timeout.provider.invokeStructured=async()=>{timeout.calls.push('called');throw new Error('Timed out');};await assert.rejects(()=>callDiscoveryV2({scope,key:'plan:1',request:request('plan:1'),ledger:timeout.ledger,provider:timeout.provider,prices:async m=>quote(m)}),/Timed out/);assert.equal(timeout.calls.length,1);assert.equal(timeout.settlements[0][1],null);});
test('malformed paid response preserves known charge while unknown response remains explicit',async()=>{const f=setup();f.provider.invokeWebSearch=async()=>{throw new ModelProviderError('malformed_model_output','Malformed billed response',true,{providerReceipt:{providerRequestId:'paid-bad-search',usage:{reportedCostUsd:0.008}}});};await assert.rejects(()=>callDiscoveryV2({scope,key:'search:1',request:request('search:1'),ledger:f.ledger,provider:f.provider,prices:async m=>quote(m)}),/Malformed billed/);assert.deepEqual(f.settlements,[['search:1',8000,'paid-bad-search']]);const unknown=setup({reported:null});const r=await callDiscoveryV2({scope,key:'review:1',request:request('review:1'),ledger:unknown.ledger,provider:unknown.provider,prices:async m=>quote(m)});assert.equal(r.metadata.discoveryBudget.unknownCharge,true);assert.deepEqual(unknown.calls[0].providerOnly,['anthropic']);assert.equal(unknown.settlements[0][1],null);});
test('search uses one exact Exa-capable model, no duplicate provider attempt',async()=>{const f=setup();const r=await callDiscoveryV2({scope,key:'search:1',request:request('search:1'),ledger:f.ledger,provider:f.provider,prices:async m=>quote(m)});assert.equal(f.calls.length,1);assert.equal(r.provider,'openrouter.exa');assert.equal(f.reservations[0].reservedMicrousd,136600);assert.deepEqual(f.calls[0].providerOnly,['openai']);});

test('search transport preserves billed malformed receipts and verifies returned model on v2 only',async()=>{const {OpenRouterAdapter}=require('../.core-tests/models/openrouter.js');const bodies=[];const make=body=>new OpenRouterAdapter({config:{apiKey:'synthetic-test-only',baseUrl:'https://example.invalid/api/v1',appUrl:'https://example.invalid',appName:'Synthetic test'},fetcher:async(_url,options)=>{bodies.push(JSON.parse(options.body));return new Response(JSON.stringify(body),{status:200});}});const req={...request('search:1'),providerOnly:['openai'],requireReturnedModel:true};await assert.rejects(()=>make({id:'billed-malformed',model:req.model.providerModelId,usage:{cost:0.008},choices:[]}).invokeWebSearch(req),e=>{assert.equal(e.details.providerReceipt.providerRequestId,'billed-malformed');assert.equal(e.details.providerReceipt.usage.reportedCostUsd,0.008);return true;});assert.deepEqual(bodies[0].provider.only,['openai']);assert.equal(bodies[0].provider.allow_fallbacks,false);assert.equal(bodies[0].tools[0].parameters.max_uses,1);await assert.rejects(()=>make({id:'missing-model',usage:{cost:0.007}}).invokeWebSearch(req),/verifiable model identity/);});
test('structured v2 refuses missing actual model identity without losing known charge',async()=>{const {OpenRouterAdapter}=require('../.core-tests/models/openrouter.js');const adapter=new OpenRouterAdapter({config:{apiKey:'synthetic-test-only',baseUrl:'https://example.invalid/api/v1',appUrl:'https://example.invalid',appName:'Synthetic test'},fetcher:async()=>new Response(JSON.stringify({id:'billed-missing-model',usage:{cost:0.001},choices:[{message:{content:'{}'},finish_reason:'stop'}]}),{status:200})});await assert.rejects(()=>adapter.invokeStructured({...request('strategy:1'),requireReturnedModel:true}),e=>{assert.match(e.message,/verifiable model identity/);assert.equal(e.details.providerReceipt.usage.reportedCostUsd,0.001);return true;});});
test('mixed request shapes cannot execute a costly search under a structured-phase reservation',async()=>{for(const key of ['plan:1','select:1','strategy:1','review:1']){const f=setup();await assert.rejects(()=>callDiscoveryV2({scope,key,request:{...request(key),query:'A hidden higher-cost search',allowedDomains:['etsy.com']},ledger:f.ledger,provider:f.provider,prices:async m=>quote(m)}),/shape/);assert.equal(f.reservations.length,0);assert.equal(f.calls.length,0);}const f=setup();await assert.rejects(()=>callDiscoveryV2({scope,key:'search:1',request:{...request('search:1'),messages:[{role:'user',content:'Mixed structured transport'}]},ledger:f.ledger,provider:f.provider,prices:async m=>quote(m)}),/shape/);assert.equal(f.calls.length,0);});
test('price and ledger awaits cannot mutate the reserved scope, model, prompt or domains',async()=>{const f=setup(),sourceScope=structuredClone(scope),sourceRequest=request('search:1');const options={scope:sourceScope,key:'search:1',request:sourceRequest,ledger:f.ledger,provider:f.provider,prices:async m=>{sourceScope.maximumMicrousd=1;sourceRequest.allowedDomains[0]='unapproved.example';sourceRequest.model={...sourceRequest.model,providerModelId:'other/model'};options.key='review:1';return quote(m);}};const reserve=f.ledger.reserve;f.ledger.reserve=async r=>{sourceRequest.query='Changed after reservation';return reserve(r);};await callDiscoveryV2(options);assert.equal(f.calls[0].query,'Find dated public observations for original forest T-shirts.');assert.deepEqual(f.calls[0].allowedDomains,['etsy.com']);assert.equal(f.calls[0].model.providerModelId,'openai/gpt-5.6-luna');assert.equal(f.reservations[0].estimate.maximumMicrousd,scope.maximumMicrousd);assert.equal(f.settlements[0][0],'search:1');});
test('an explicitly wrong search upstream is rejected after known-charge settlement',async()=>{const f=setup(),original=f.provider.invokeWebSearch;f.provider.invokeWebSearch=async r=>({...await original(r),metadata:{actualUpstreamProvider:'Different provider'}});await assert.rejects(()=>callDiscoveryV2({scope,key:'search:1',request:request('search:1'),ledger:f.ledger,provider:f.provider,prices:async m=>quote(m)}),/upstream differs/);assert.equal(f.calls.length,1);assert.equal(f.settlements[0][1],1000);});
test('settlement persistence failure retains a sanitized known receipt for recovery without replay',async()=>{for(const malformed of [false,true]){const f=setup();f.ledger.settle=async()=>{throw new Error('database unavailable');};if(malformed)f.provider.invokeStructured=async()=>{throw new ModelProviderError('malformed_model_output','Malformed billed answer',true,{providerReceipt:{providerRequestId:'known-paid-id',usage:{reportedCostUsd:.00123}}});};await assert.rejects(()=>callDiscoveryV2({scope,key:'plan:1',request:request('plan:1'),ledger:f.ledger,provider:f.provider,prices:async m=>quote(m)}),e=>{assert.equal(e.details.settlementRecorded,false);assert.equal(e.details.attemptKey,'plan:1');assert.equal(e.details.providerReceipt.usage.reportedCostUsd,malformed?.00123:.001);assert.ok(e.details.providerReceipt.providerRequestId);return true;});}});
test('failure evidence retains actual or missing model identity instead of relabeling it as requested',async()=>{for(const actualModel of ['unexpected/model',null]){const f=setup(),originalReceipt={provider:'Observed provider',providerModelId:actualModel,upstreamProvider:'Observed upstream',providerRequestId:'original-receipt-id',latencyMs:12,usage:{inputTokens:23,outputTokens:7,reportedCostUsd:.0012345}};f.provider.invokeStructured=async()=>{throw new ModelProviderError('malformed_model_output','Malformed billed response',true,{providerReceipt:originalReceipt});};await assert.rejects(()=>callDiscoveryV2({scope,key:'plan:1',request:request('plan:1'),ledger:f.ledger,provider:f.provider,prices:async m=>quote(m)}),e=>{assert.deepEqual(e.details.providerReceipt,originalReceipt);assert.equal(e.details.requestedModel,'openai/gpt-5.6-luna');return true;});assert.equal(f.settlements[0][1],1235);}});
test('non-2xx transport preserves supplied accounting evidence with no assumed model identity',async()=>{const {OpenRouterAdapter}=require('../.core-tests/models/openrouter.js');const adapter=new OpenRouterAdapter({config:{apiKey:'synthetic-test-only',baseUrl:'https://example.invalid/api/v1',appUrl:'https://example.invalid',appName:'Synthetic test'},fetcher:async()=>new Response(JSON.stringify({id:'http-failure-receipt',error:{message:'Provider could not finish'},usage:{cost:.007,prompt_tokens:22}}),{status:502})});await assert.rejects(()=>adapter.invokeStructured({...request('plan:1'),requireReturnedModel:true}),e=>{assert.equal(e.details.providerReceipt.providerModelId,null);assert.equal(e.details.providerReceipt.providerRequestId,'http-failure-receipt');assert.equal(e.details.providerReceipt.usage.reportedCostUsd,.007);assert.equal(e.details.providerReceipt.usage.inputTokens,22);return true;});});

test('parsed wrong identity preserves the original actual receipt after settlement',async()=>{for(const field of ['providerModelId','provider','upstream']){const f=setup(),original=f.provider.invokeStructured;f.provider.invokeStructured=async request=>{const response=await original(request);if(field==='upstream')response.metadata.actualUpstreamProvider='Unexpected upstream';else response[field]='Unexpected identity';return response;};await assert.rejects(()=>callDiscoveryV2({scope,key:'plan:1',request:request('plan:1'),ledger:f.ledger,provider:f.provider,prices:async m=>quote(m)}),error=>{assert.equal(error.details.settlementRecorded,true);assert.equal(error.details.requestedModel,discoveryV2Model('plan:1'));assert.equal(error.details.providerReceipt[field==='upstream'?'upstreamProvider':field],field==='upstream'?'Unexpected upstream':'Unexpected identity');assert.equal(error.details.providerReceipt.usage.reportedCostUsd,.001);assert.ok(error.details.providerReceipt.providerRequestId);return true;});assert.equal(f.settlements.length,1);}});

test('paid schema failure retains bounded field/category diagnostics without rejected values or arbitrary property names',()=>{
  const {discoveryResponseFailure}=require('../.core-tests/products/discovery-v2-budget.js');
  const {JsonSchemaValidationError,validateJsonSchemaValue}=require('../.core-tests/workers/schema-validator.js');
  const privateValue='private rejected model text';
  const schema={type:'object',additionalProperties:false,required:['audience','focus'],properties:{audience:{type:'string',enum:['Declared audience']},focus:{type:'string',maxLength:5}}};
  const issues=validateJsonSchemaValue(schema,{audience:privateValue,focus:privateValue,[privateValue]:privateValue});
  const response={provider:'OpenAI',providerModelId:'openai/gpt-5.6-luna',providerRequestId:'synthetic-paid-receipt',latencyMs:8,metadata:{},output:{privateValue},usage:{reportedCostUsd:.001,inputTokens:3,outputTokens:4,totalTokens:7}};
  const error=discoveryResponseFailure(new JsonSchemaValidationError('Discovery plan did not match its JSON schema.',issues),response);
  assert.deepEqual(error.details.validationIssues,[{path:'$',category:'additional_property'},{path:'$.audience',category:'enum'},{path:'$.focus',category:'max_length'}]);
  assert.match(error.message,/\$\.audience:enum/);assert.match(error.message,/\$\.focus:max_length/);
  assert.equal(error.details.settlementRecorded,true);assert.equal(error.details.providerReceipt.providerRequestId,response.providerRequestId);
  assert.ok(!JSON.stringify(error.details).includes(privateValue));assert.ok(!error.message.includes(privateValue));
  const hostile=discoveryResponseFailure(new JsonSchemaValidationError('Discovery plan did not match its JSON schema.',Array.from({length:20},()=>({path:'$.bad/value',message:privateValue}))),response);
  assert.equal(hostile.details.validationIssues.length,8);assert.ok(hostile.message.length<=500);
  assert.ok(hostile.details.validationIssues.every(issue=>issue.path==='$'&&issue.category==='schema_mismatch'));
  assert.ok(!JSON.stringify(hostile.details).includes(privateValue));
});
