import {discoveryKnowledgeFixture} from './discovery-v2-fixtures.mjs';
import test from 'node:test';
import assert from 'node:assert/strict';
import {createRequire} from 'node:module';
const require=createRequire(import.meta.url);
const {collectDiscoverySourcesV2,selectDiscoveryEvidenceV2}=require('../.core-tests/products/discovery-v2-research.js');
const {validateProductEvidence}=require('../.core-tests/products/discovery.js');
const scope={intentId:'11111111-1111-4111-8111-111111111111',maximumCollections:1,maximumMicrousd:500000,policyHash:'a'.repeat(64)};
const queryId='22222222-2222-4222-8222-222222222222';
const request={query:'Compare original nature shirt customer observations in the declared markets.',allowedDomains:['etsy.com']};
const excerpt='Generic navigation and product information. '.repeat(9)+'A dated adult buyer describes the subtle forest print as a comfortable gift.';
function setup(){const calls=[],settlements=[];let selected;const ledger={reserve:async()=>({shouldCall:true,totalReservedMicrousd:100000}),settle:async(...s)=>{settlements.push(s);}};const answer=(r,output,provider)=>({output,provider,providerModelId:r.model.providerModelId,providerRequestId:'bounded-real-shaped-request',latencyMs:1,usage:{reportedCostUsd:.001,estimatedCostUsd:.001,inputTokens:1,outputTokens:1,totalTokens:2,cachedInputTokens:0,reasoningTokens:0},metadata:{searchRequests:1,engine:'exa'}});const provider={invokeWebSearch:async r=>{calls.push(['search',r]);return answer(r,{annotations:[{type:'url_citation',url_citation:{url:'https://www.etsy.com/listing/123/nature-shirt',title:'Synthetic exact source',content:excerpt}}]},'openrouter.exa');},invokeStructured:async r=>{calls.push(['select',r]);const parsed=JSON.parse(r.messages[1].content);return answer(r,selected??{selections:[{sourceKey:parsed.sources[0].sourceKey,quote:'A dated adult buyer describes the subtle forest print as a comfortable gift.'}],limitations:['no_sales_metrics']},'openrouter');}};return {knowledge:discoveryKnowledgeFixture(),calls,settlements,ledger,provider,setSelected:v=>selected=v,prices:async modelId=>({modelId,source:'https://openrouter.ai/api/v1/models',verifiedAt:new Date().toISOString(),inputPerMillion:.4,cacheWritePerMillion:.5,outputPerMillion:1.8})};}
test('v2 source and selection calls are separate, primary-only, metered and retain full excerpts',async()=>{const f=setup(),options={scope,ordinal:1,queryId,request,...f};const collection=await collectDiscoverySourcesV2(options);assert.equal(f.calls.length,1);assert.equal(collection.providerMetadata.intentId,scope.intentId);assert.equal(collection.providerMetadata.queryId,queryId);const before=structuredClone(collection);const result=await selectDiscoveryEvidenceV2({...options,collection});assert.equal(f.calls.length,2);assert.ok(f.calls[1][1].messages[1].content.includes('subtle forest print'));assert.deepEqual(collection,before);assert.ok(result.evidencePack.sources[0].excerpt.endsWith('comfortable gift.'));assert.equal(result.evidencePack.evidence[0].quote,'A dated adult buyer describes the subtle forest print as a comfortable gift.');assert.equal(result.receipt.actualProviderModelId,'openai/gpt-5.6-luna');assert.equal(result.receipt.primaryOnly,true);validateProductEvidence(result.evidencePack,request);assert.deepEqual(f.settlements.map(x=>x[0]),['search:1','select:1']);});
test('selection rejects forged collection scope before a call and fabricated evidence after preserving charge',async()=>{const f=setup(),options={scope,ordinal:1,queryId,request,...f};const collection=await collectDiscoverySourcesV2(options);const forged=structuredClone(collection);forged.providerMetadata.intentId='33333333-3333-4333-8333-333333333333';await assert.rejects(()=>selectDiscoveryEvidenceV2({...options,collection:forged}),/outside/);assert.equal(f.calls.length,1);f.setSelected({selections:[{sourceKey:'S1',quote:'Fabricated fact that does not exist in the retained source excerpt.'}],limitations:[]});await assert.rejects(()=>selectDiscoveryEvidenceV2({...options,collection}),/exact retained source span/);assert.equal(f.calls.length,2);assert.equal(f.settlements.length,2);});
test('a one-collection intent rejects the second query before a provider call',async()=>{const f=setup();await assert.rejects(()=>collectDiscoverySourcesV2({scope,ordinal:2,queryId,request,...f}),/ordinal/);assert.equal(f.calls.length,0);});
