import test from 'node:test';import assert from 'node:assert/strict';import {readFileSync} from 'node:fs';import ts from 'typescript';
const load=(file,deps={})=>{const m={exports:{}};new Function('require','module','exports',ts.transpileModule(readFileSync(file,'utf8'),{compilerOptions:{target:ts.ScriptTarget.ES2022,module:ts.ModuleKind.CommonJS}}).outputText)(name=>{assert.ok(Object.hasOwn(deps,name),`Unexpected ${name}`);return deps[name];},m,m.exports);return m.exports;};
const id=n=>`00000000-0000-4000-8000-${String(n).padStart(12,'0')}`,business=id(1),quest=id(2),episode=id(3),step=id(4),agent=id(5),artifact=id(6);
const navigation=load('src/lib/core-ui/workspace-navigation.ts');
const api=load('src/lib/core-ui/workspace-context.ts',{'server-only':{},'./console-collections':{consoleValidId:v=>typeof v==='string'&&/^[a-f0-9]{8}-[a-f0-9]{4}-[1-8][a-f0-9]{3}-[89ab][a-f0-9]{3}-[a-f0-9]{12}$/i.test(v),consoleObject:v=>v!==null&&typeof v==='object'&&!Array.isArray(v)}});
const intent=()=>({businessId:business,business:{revision:1,currentGoalId:quest},quests:[{id:quest,businessId:business}],total:1,limit:20,offset:0,selection:'explicit',selected:{id:quest,businessId:business,title:'Exact Quest',content:{objective:'Finite objective'}}});
function fixture(data=intent(),options={}){const calls=[];const context={userId:id(90),businesses:[{id:business,name:'Business'}],readSearch:`?business=${business}&quest=${quest}`,supabase:{rpc:async(name,args)=>{calls.push({name,args});return {data,error:options.error??null};},from(table){const call={table,ops:[]};calls.push(call);const q={select(...args){call.ops.push(['select',...args]);return q;},eq(...args){call.ops.push(['eq',...args]);return q;},limit(...args){call.ops.push(['limit',...args]);return q;},maybeSingle(){call.single=true;return q;},then(resolve,reject){const row=options.tables&&Object.hasOwn(options.tables,table)?options.tables[table]:{id:episode,business_id:business,quest_id:quest};return Promise.resolve({data:call.single?row:[row],count:1,error:null}).then(resolve,reject);}};return q;}}};return {context,calls};}
test('R08 navigation preserves Business plus exact provenance and drops children on parent changes',()=>{const source=new URLSearchParams({business,quest,episode,step,agent,sourceArtifact:artifact});const same=new URL(navigation.carryWorkspace('/dashboard?view=library',source),'https://x');for(const[k,v]of source)assert.equal(same.searchParams.get(k),v);
 const changed=new URL(navigation.carryWorkspace(`/dashboard?view=work&episode=${id(33)}`,source),'https://x');assert.equal(changed.searchParams.get('quest'),quest);for(const k of ['step','agent','sourceArtifact'])assert.equal(changed.searchParams.get(k),null);
 const other=new URL(navigation.carryWorkspace(`/dashboard?view=overview&business=${id(99)}`,source),'https://x');for(const k of ['quest','episode','step','agent','sourceArtifact'])assert.equal(other.searchParams.get(k),null);
});
test('R08 selected/current Quest is resolved before its RLS view filter/count/exact query',async()=>{const f=fixture();const result=await api.resolveWorkspace(f.context,{business,quest});assert.equal(result.unavailable,false);const read=await result.context.supabase.from('artifacts').select('id,business_id',{count:'exact'}).eq('id',artifact).limit(1);assert.equal(read.error,null);assert.ok(!Object.hasOwn(read.data[0],'quest_id'));const call=f.calls.find(c=>c.table==='r08_artifacts');assert.equal(call.table,'r08_artifacts');assert.deepEqual(call.ops.slice(0,2),[['select','id,business_id,quest_id',{count:'exact'}],['eq','quest_id',quest]]);assert.equal(f.calls[0].name,'r04_quest_read');});
test('R08 malformed, partial, mismatched and absent explicit Quest responses fail unavailable',async()=>{for(const change of [{selected:null},{selection:'current'},{limit:50},{offset:20},{total:2},{quests:[]},{selected:{...intent().selected,businessId:id(22)}}]){const f=fixture({...intent(),...change});const result=await api.resolveWorkspace(f.context,{business,quest});assert.equal(result.unavailable,true,JSON.stringify(change));assert.equal(result.state,null);}});
test('R08 never turns an ignored scope predicate into another Quest record',async()=>{const f=fixture(intent(),{tables:{r08_artifacts:{id:artifact,business_id:business,quest_id:id(100)}}});const scoped=api.withQuestScope(f.context,quest);const read=await scoped.supabase.from('artifacts').select('id').eq('id',artifact);assert.equal(read.data,null);assert.ok(read.error);});
test('R08 rejects mixed Step/Agent task linkage in the same episode',async()=>{const f=fixture(intent(),{tables:{r08_workflow_runs:{id:episode,business_id:business,quest_id:quest},workflow_stage_runs:{id:step},worker_runs:{id:agent,task_contract_id:id(8),worker_definition_id:id(9)},task_contracts:null}});await assert.rejects(api.resolveWorkspace(f.context,{business,quest,episode,step,agent}),/Agent outside Step/);});
test('R08 absent Quest stays explicitly empty without querying workflows',async()=>{const f=fixture({...intent(),selection:'none',selected:null,quests:[],total:0});const result=await api.resolveWorkspace(f.context,{business},true);assert.equal(result.state.selected,null);assert.equal(result.unavailable,false);assert.equal(f.calls.filter(c=>c.table).length,0);});
test('R08 ambiguous URL identities reject before data reads',async()=>{const f=fixture();await assert.rejects(api.resolveWorkspace(f.context,{business,quest:[quest,id(20)]}),/Ambiguous/);await assert.rejects(api.resolveWorkspace(f.context,{quest}),/Invalid/);await assert.rejects(api.resolveWorkspace(f.context,{business,quest,step}),/Invalid/);assert.equal(f.calls.length,0);});

test('R08 current Quest option accepts the empty native select value',async()=>{const state={...intent(),selection:'current'};const f=fixture(state);const result=await api.resolveWorkspace(f.context,{business,quest:''},true);assert.equal(result.unavailable,false);assert.equal(f.calls[0].args.p_goal_id,null);});
test('R08 exact Work navigation replaces a carried episode and removes stale artifact/Agent context',()=>{const source=new URLSearchParams({business,quest,episode,step,agent,sourceArtifact:artifact});const next=new URL(navigation.carryWorkspace(`/dashboard?view=work&selected=${id(20)}`,source),'https://x');assert.equal(next.searchParams.get('episode'),id(20));for(const key of ['step','agent','sourceArtifact'])assert.equal(next.searchParams.get(key),null);});

test('R08 all-Business records leave current Quest unresolved and count only this Business',async()=>{const f=fixture();f.context.readSearch=`?business=${business}`;const result=await api.resolveWorkspace(f.context,{business},false);assert.equal(result.businessId,business);assert.equal(result.state,null);assert.equal(result.unavailable,false);assert.equal(result.context.supabase,f.context.supabase);assert.equal(result.context.scopeBusinessId,business);assert.equal(result.context.needsYouCount,1);assert.equal(f.calls.length,1);assert.equal(f.calls[0].table,"owner_interventions");assert.ok(f.calls[0].ops.some(([op,key,value])=>op==="eq"&&key==="business_id"&&value===business));assert.equal(new URLSearchParams(result.context.readSearch).has("quest"),false);});
