import test from 'node:test';import assert from 'node:assert/strict';import {readFileSync} from 'node:fs';import {createRequire} from 'node:module';import {runInNewContext} from 'node:vm';
const require=createRequire(import.meta.url),ts=require('typescript'),C=require('../.core-tests/connections/contracts.js'),V=require('../.core-tests/accounts/vault.js');
const id=n=>`11000000-0000-4000-8000-${String(n).padStart(12,'0')}`;
function harness({refresh=true,fail=null,replay=null,format='setup',tamper=null}={}){
 const b=id(1),owner=id(2),session=id(3),window=id(4),op=id(5),conn=id(6),revision=id(7),generation=format==='setup'?revision:id(8),cutoff=new Date(Date.now()+86400000).toISOString();
 const env={VERCEL_ENV:'production',ACCOUNTS_SERVER_KEY:'inert-account-authority-123456789012345',ACCOUNTS_VAULT_KEY:'1'.repeat(64),ETSY_KEYSTRING:'inert-key-only',ETSY_SHARED_SECRET:'inert-secret-only'};
 const tokens={userId:100,accessToken:'100.inert-old-access',refreshToken:'100.inert-old-refresh',scopes:['shops_r','listings_r'],tokenExpiresAt:new Date(Date.now()+600000).toISOString()};
 const next={...tokens,accessToken:'100.inert-new-access',refreshToken:'100.inert-new-refresh',tokenExpiresAt:new Date(Date.now()+3300000).toISOString()},calls=[],effects=[];let saved=null;
 const identity={userId:100,shopId:200,shopName:'InertShop'},stored={...tokens,...identity,businessId:b,connectionId:conn,revision,bindingRevision:revision,generationId:generation,expiresAt:cutoff};if(tamper)Object.assign(stored,tamper);
 const envelope=V.sealAccountSecret(stored,{businessId:b,connectionId:conn,provider:format==='setup'?'etsy_r11_access':'etsy_r11_token',revision:generation},env.ACCOUNTS_VAULT_KEY);
 const context={userId:owner,businesses:[{id:b}],supabase:{auth:{getClaims:async()=>({data:{claims:{sub:owner,session_id:session}}})},rpc:async(name,args)=>{assert.equal(name,'r11_etsy_read_owner');calls.push({op:args.p_operation,payload:structuredClone(args.p_payload)});const p=args.p_payload;
  if(args.p_operation===fail)return{error:{message:'PRIVATE RAW TOKEN ERROR'}};
  if(args.p_operation==='begin')return{data:replay?{shouldDispatch:false,status:replay}:{shouldDispatch:true,status:'reserved',operationId:op,needsRefresh:refresh,connectionId:conn,bindingRevision:revision,generationId:generation,nextGenerationId:refresh?op:generation,format,envelope,tokenExpiresAt:tokens.tokenExpiresAt,localCutoff:cutoff,...identity}};
  if(args.p_operation==='mark_refresh'||args.p_operation==='mark_read'){const step=args.p_operation==='mark_refresh'?0:1;return{data:{shouldDispatch:true,attemptId:op,step,method:step===0?'POST':'GET',endpoint:step===0?'https://api.etsy.com/v3/public/oauth/token':'https://api.etsy.com/v3/application/shops/200/listings?state=draft&limit=1&offset=0',expiresAt:new Date(Date.now()+15000).toISOString()}};}
  if(args.p_operation==='rotate'){saved=p.envelope;return{data:{saved:true,generationId:op}};}
  if(args.p_operation==='complete')return{data:{verified:true,generationId:refresh?op:generation}};
  return{data:{closed:true,revoked:true}};
 }}};
 const deps={'server-only':{},'../lib/core-ui/owner-business':{verifyOwnerBusiness:async(c,requested)=>requested===b&&c.userId===owner},'../accounts/vault':V,'./server':{connectionQualificationConfigured:()=>env.VERCEL_ENV==='production'},'./contracts':C,'./etsy-refresh':{
  refreshReadOAuth:async(config,current,i,permit)=>{await permit(0,'https://api.etsy.com/v3/public/oauth/token','POST');effects.push('POST');if(fail==='provider-refresh')throw Error('PRIVATE TOKEN');assert.equal(current.refreshToken,tokens.refreshToken);return structuredClone(next);},
  readExactDraftStatus:async(config,current,i,permit)=>{if(refresh){assert.ok(saved,'Rotated custody must be saved before GET');assert.equal(current.accessToken,next.accessToken);}await permit(1,'https://api.etsy.com/v3/application/shops/200/listings?state=draft&limit=1&offset=0','GET');effects.push('GET');if(fail==='provider-get')throw Error('PRIVATE CONTENT');return{...identity,listingCount:0,totalDrafts:0,factsHash:'a'.repeat(64),verifiedAt:new Date().toISOString()};}
 }};
 const src=ts.transpileModule(readFileSync('src/connections/refresh-server.ts','utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText,m={exports:{}};
 runInNewContext(`(function(require,module,exports){${src}\n})`,{process:{env},Date})(n=>{assert.ok(n in deps,n);return deps[n];},m,m.exports);
 return{...m.exports,b,owner,window,op,conn,revision,context,env,tokens,next,calls,effects,saved:()=>saved};
}
test('R11 lazy expired/qualification path saves context-bound rotated custody before the useful read',async()=>{const h=harness(),out=await h.performEtsyDraftStatusRead(h.context,h.b,h.window,h.op);assert.equal(out.status,'succeeded');assert.deepEqual(h.effects,['POST','GET']);assert.deepEqual(h.calls.map(c=>c.op),['begin','mark_refresh','rotate','mark_read','complete']);assert.ok(!JSON.stringify(h.calls).includes(h.next.refreshToken));const clear=V.unsealAccountSecret(h.saved(),{businessId:h.b,connectionId:h.conn,provider:'etsy_r11_token',revision:h.op},h.env.ACCOUNTS_VAULT_KEY);assert.equal(clear.refreshToken,h.next.refreshToken);assert.equal(clear.bindingRevision,h.revision);assert.equal(clear.generationId,h.op);assert.throws(()=>V.unsealAccountSecret(h.saved(),{businessId:h.b,connectionId:h.conn,provider:'etsy_r11_access',revision:h.revision},h.env.ACCOUNTS_VAULT_KEY));});
for(const format of ['setup','generation'])test(`R11 fresh ${format} generation read never refreshes`,async()=>{const h=harness({refresh:false,format});assert.equal((await h.performEtsyDraftStatusRead(h.context,h.b,h.window,h.op)).status,'succeeded');assert.deepEqual(h.effects,['GET']);assert.equal(h.saved(),null);});
for(const replay of ['succeeded','reserved','busy','refresh_unverified','exhausted'])test(`R11 ${replay} admission result never repeats external effects`,async()=>{const h=harness({replay});assert.equal((await h.performEtsyDraftStatusRead(h.context,h.b,h.window,h.op)).status,replay);assert.deepEqual(h.effects,[]);assert.deepEqual(h.calls.map(c=>c.op),['begin']);});
for(const fail of ['mark_refresh','provider-refresh','rotate','mark_read','provider-get','complete'])test(`R11 ${fail} failure stays explicit with no retry or predecessor restore`,async()=>{const h=harness({fail});await assert.rejects(h.performEtsyDraftStatusRead(h.context,h.b,h.window,h.op),/^Error: own_shop_read_unverified$/);assert.equal(h.calls.at(-1).op,'fail');assert.ok(h.effects.filter(e=>e==='POST').length<=1);assert.ok(h.effects.filter(e=>e==='GET').length<=1);if(['mark_read','provider-get','complete'].includes(fail))assert.ok(h.saved());assert.equal(h.calls.some(c=>c.op==='restore'),false);});
for(const tamper of [{businessId:id(99)},{connectionId:id(99)},{revision:id(99)},{shopId:201},{userId:101},{expiresAt:'2027-12-31T00:00:00Z'},{scopes:['shops_r','listings_r','listings_w']}])test('R11 stored-credential identity/cutoff/scope tampering denies before provider call',async()=>{const h=harness({tamper});await assert.rejects(h.performEtsyDraftStatusRead(h.context,h.b,h.window,h.op));assert.deepEqual(h.effects,[]);});
test('R11 wrong Business, owner and Preview stop before token resolution',async()=>{for(const mode of ['business','owner','preview']){const h=harness();if(mode==='owner')h.context.userId=id(90);if(mode==='preview')h.env.VERCEL_ENV='preview';await assert.rejects(h.performEtsyDraftStatusRead(h.context,mode==='business'?id(99):h.b,h.window,h.op));assert.deepEqual(h.effects,[]);assert.deepEqual(h.calls,[]);}});
test('R11 owner can stop the exact read window without execution keys or provider calls',async()=>{const h=harness();delete h.env.ACCOUNTS_SERVER_KEY;delete h.env.ACCOUNTS_VAULT_KEY;assert.equal((await h.revokeEtsyReadWindow(h.context,h.b,h.window)).revoked,true);assert.deepEqual(h.effects,[]);assert.deepEqual(h.calls.map(c=>c.op),['revoke_window']);});
