import test from 'node:test';import assert from 'node:assert/strict';import {createRequire} from 'node:module';
const require=createRequire(import.meta.url),{verifyPrintfulEnvironmentBinding}=require('../.core-tests/connections/printful-read.js');
const input={storeId:18843726,storeKind:'ecommerce_linked',expectedProviderType:'etsy',credential:'inert-printful-token',scopeMode:'exact',approvedProviderScopes:['orders/write','stores_list/read']};
const permit=async(step,endpoint,method)=>({step,endpoint,method,expiresAt:new Date(Date.now()+15000).toISOString()});
const json=x=>new Response(JSON.stringify(x),{headers:{'content-type':'application/json'}});
function fixture(){const calls=[];return{calls,fetcher:async(url,init)=>{calls.push({url,init});return json(url.endsWith('/oauth/scopes')?{code:200,result:{scopes:[{scope:'stores_list/read'},{scope:'orders/write'}]}}:{code:200,result:{id:18843726,type:'etsy',name:'Inert own store',PRIVATE_EXTRA:'must not persist'}});}};}
test('R11 account-level Printful credential remains bounded to two metadata GETs and exact store',async()=>{const f=fixture(),proof=await verifyPrintfulEnvironmentBinding(input,permit,f.fetcher);assert.deepEqual(f.calls.map(c=>c.url),['https://api.printful.com/oauth/scopes','https://api.printful.com/stores/18843726']);assert.ok(f.calls.every(c=>c.init.method==='GET'&&c.init.redirect==='error'));assert.equal(f.calls[1].init.headers['X-PF-Store-Id'],'18843726');assert.deepEqual(proof.providerScopes,['orders/write','stores_list/read']);assert.equal(proof.providerType,'etsy');assert.ok(!JSON.stringify(proof).includes(input.credential));assert.ok(!JSON.stringify(proof).includes('PRIVATE_EXTRA'));});
test('R11 explicit inspect-and-record policy records real broader scopes without enumerating stores',async()=>{const f=fixture(),proof=await verifyPrintfulEnvironmentBinding({...input,scopeMode:'inspect_and_record',approvedProviderScopes:null},permit,f.fetcher);assert.ok(proof.providerScopes.includes('orders/write'));assert.equal(f.calls.some(c=>c.url==='https://api.printful.com/stores'),false);});
test('R11 changed scope stops before reading any store under exact-scope policy',async()=>{const f=fixture();await assert.rejects(verifyPrintfulEnvironmentBinding({...input,approvedProviderScopes:['stores_list/read']},permit,f.fetcher),/scopes_changed/);assert.equal(f.calls.length,1);});
for(const changes of [{id:18842941},{type:'native'},{name:''},{type:'shopify'}])test('R11 wrong selected store or integration cannot qualify',async()=>{const f=fixture();await assert.rejects(verifyPrintfulEnvironmentBinding(input,permit,async(url,init)=>url.endsWith('/oauth/scopes')?f.fetcher(url,init):json({code:200,result:{id:18843726,type:'etsy',name:'Inert',...changes}})));});
test('R11 malformed/oversized provider results and expired permit fail closed',async()=>{for(const fetcher of [async()=>new Response('secret',{status:403}),async()=>json({code:200,result:{scopes:[{scope:'bad scope'}]}}),async()=>new Response('a'.repeat(70000),{headers:{'content-type':'application/json'}})])await assert.rejects(verifyPrintfulEnvironmentBinding(input,permit,fetcher));let calls=0;await assert.rejects(verifyPrintfulEnvironmentBinding(input,async(step,endpoint,method)=>({step,endpoint,method,expiresAt:'2000-01-01T00:00:00Z'}),async()=>{calls++;return json({});}));assert.equal(calls,0);});
