import test from 'node:test';import assert from 'node:assert/strict';import {createRequire} from 'node:module';
const require=createRequire(import.meta.url),{readOAuthStart,exchangeReadOAuth,verifyEtsyReadConnection}=require('../.core-tests/connections/etsy-read.js');
const config={keystring:'inert-app-key',sharedSecret:'inert-shared-secret'},tokenResponse={access_token:'100.inert-access-token',refresh_token:'100.inert-refresh-token',token_type:'Bearer',expires_in:3600,scope:'shops_r listings_r'};
const json=x=>new Response(JSON.stringify(x),{headers:{'content-type':'application/json'}});
function fixture(){const calls=[],permits=[];const permit=async(step,endpoint,method,facts={})=>{permits.push({step,endpoint,method,facts});return{attemptId:'11000000-0000-4000-8000-000000000001',step,endpoint,method,expiresAt:new Date(Date.now()+15000).toISOString()};};
 const fetcher=async(url,init)=>{calls.push({url,method:init.method,body:init.body,headers:new Headers(init.headers)});if(url.endsWith('/token'))return json(tokenResponse);if(url.includes('/users/'))return json({user_id:100,shop_id:200,shop_name:'InertShop',currency_code:'NZD'});return json({count:1,results:[{listing_id:300,shop_id:200,user_id:100,state:'draft',description:'INERT PRIVATE TEXT MUST NOT BE RETAINED'}]});};return{calls,permits,permit,fetcher};}
test('R11 read consent has only exact read scopes, fixed callback and fresh PKCE',()=>{const a=readOAuthStart(config),b=readOAuthStart(config),url=new URL(a.url);assert.equal(url.searchParams.get('scope'),'shops_r listings_r');assert.equal(url.searchParams.get('redirect_uri'),'https://agent-labs-two.vercel.app/api/etsy/r11/callback');assert.notEqual(a.state,b.state);assert.notEqual(a.verifier,b.verifier);assert.ok(!a.url.includes(config.sharedSecret));});
test('R11 actual own-shop qualification runs exactly one token exchange and two finite GETs with minimized proof',async()=>{const f=fixture(),flow=readOAuthStart(config),tokens=await exchangeReadOAuth(config,{code:'inert-code-value',verifier:flow.verifier},f.permit,f.fetcher);const proof=await verifyEtsyReadConnection(config,tokens,'InertShop',f.permit,f.fetcher);assert.deepEqual(f.calls.map(c=>c.method),['POST','GET','GET']);assert.deepEqual(f.permits.map(p=>p.step),[0,1,2]);assert.equal(f.calls[2].url,'https://api.etsy.com/v3/application/shops/200/listings?state=draft&limit=1&offset=0');assert.equal(proof.listingCount,1);assert.equal(proof.shopId,200);assert.match(proof.factsHash,/^[a-f0-9]{64}$/);assert.ok(!JSON.stringify(proof).includes('PRIVATE'));assert.ok(!JSON.stringify(f.permits).includes('access-token'));assert.ok(!JSON.stringify(f.permits).includes('refresh-token'));});
for(const scope of [undefined,'shops_r','shops_r listings_r listings_w','shops_r shops_r'])test(`R11 missing/expanded/incomplete granted scopes ${scope} stop before GET`,async()=>{const f=fixture();await assert.rejects(exchangeReadOAuth(config,{code:'inert-code',verifier:readOAuthStart(config).verifier},f.permit,async()=>json({...tokenResponse,scope})),/granted_scopes_unverified/);assert.equal(f.permits.length,1);});
for(const changes of [{expires_in:0},{expires_in:7200},{refresh_token:'101.inert-refresh-token'},{access_token:'secret\nraw'},{token_type:'Other'}])test('R11 token identity/expiry/body anomalies never become a connection',async()=>{const f=fixture();await assert.rejects(exchangeReadOAuth(config,{code:'inert-code',verifier:readOAuthStart(config).verifier},f.permit,async()=>json({...tokenResponse,...changes})));});
test('R11 expired or denied permit prevents dispatch and no automatic retry occurs',async()=>{let calls=0;for(const permit of [async()=>{throw Error('inert denial');},async(step,endpoint,method)=>({step,endpoint,method,expiresAt:'2000-01-01T00:00:00Z'})])await assert.rejects(exchangeReadOAuth(config,{code:'inert-code',verifier:readOAuthStart(config).verifier},permit,async()=>{calls++;return json(tokenResponse);}));assert.equal(calls,0);});
test('R11 a foreign shop prevents listing reads',async()=>{const f=fixture(),tokens=await exchangeReadOAuth(config,{code:'inert-code',verifier:readOAuthStart(config).verifier},f.permit,f.fetcher);await assert.rejects(verifyEtsyReadConnection(config,tokens,'OtherShop',f.permit,f.fetcher),/shop_mismatch/);assert.equal(f.calls.length,2);});
for(const changed of [{shop_id:999},{user_id:999},{state:'active'},{listing_id:null}])test('R11 wrong listing identity/state fails without retaining response',async()=>{const f=fixture(),tokens=await exchangeReadOAuth(config,{code:'inert-code',verifier:readOAuthStart(config).verifier},f.permit,f.fetcher);await assert.rejects(verifyEtsyReadConnection(config,tokens,'InertShop',f.permit,async(url,init)=>url.includes('/listings?')?json({count:1,results:[{listing_id:300,shop_id:200,user_id:100,state:'draft',...changed}]}):f.fetcher(url,init)),/listing_identity_mismatch/);});
test('R11 empty draft page qualifies endpoint access without inventing a listing',async()=>{const f=fixture(),tokens=await exchangeReadOAuth(config,{code:'inert-code',verifier:readOAuthStart(config).verifier},f.permit,f.fetcher);const result=await verifyEtsyReadConnection(config,tokens,'InertShop',f.permit,async(url,init)=>url.includes('/listings?')?json({count:0,results:[]}):f.fetcher(url,init));assert.equal(result.listingCount,0);assert.equal(result.totalDrafts,0);assert.equal('listingId' in result,false);});
