import test from 'node:test';import assert from 'node:assert/strict';import {readFileSync} from 'node:fs';import {createRequire} from 'node:module';import {runInNewContext} from 'node:vm';
const require=createRequire(import.meta.url),ts=require('typescript'),C=require('../.core-tests/connections/contracts.js'),V=require('../.core-tests/accounts/vault.js'),E=require('../.core-tests/connections/etsy-read.js');
const id=n=>`11000000-0000-4000-8000-${String(n).padStart(12,'0')}`;
function harness({provider='etsy',enabled=true,failPhase=null}={}){
 const businessId=id(1),owner=id(2),sessionId=id(3),grantId=id(4),calls=[],providerCalls=[];let attempt=null,stored=null,status='available';
 const env={VERCEL_ENV:'production',ACCOUNTS_SERVER_KEY:'inert-server'.repeat(4),ACCOUNTS_VAULT_KEY:'1'.repeat(64),ETSY_KEYSTRING:'inert-etsy-key',ETSY_SHARED_SECRET:'inert-etsy-secret',PRINTFUL_INERT_TOKEN:'inert-printful-token'};
 const approvedCredentialFingerprint=C.fingerprint(provider==='etsy'?`${env.ETSY_KEYSTRING}\0${env.ETSY_SHARED_SECRET}`:env.PRINTFUL_INERT_TOKEN);
 const context={userId:owner,businesses:[{id:businessId}],supabase:{auth:{getClaims:async()=>({data:{claims:{sub:owner,session_id:sessionId}}})},rpc:async(name,args)=>{calls.push({name,args:structuredClone(args)});const p=args.p_payload;
  if(name==='r11_etsy_read_workspace')return{data:{businessId,grants:enabled?[{id:grantId,provider,expectedAccount:provider==='etsy'?'InertShop':'123',applicationId:'inert-app',purposeHash:'a'.repeat(64),approvedCredentialFingerprint,credentialAlias:provider==='printful'?'PRINTFUL_INERT_TOKEN':null,providerScopes:['stores_list/read'],providerScopeMode:'exact',expiresAt:new Date(Date.now()+600000).toISOString(),state:status}]:[],connections:[],attempts:[]}};
  if(args.p_operation===failPhase)return{error:{message:'PRIVATE SECRET ERROR BODY'}};
  if(args.p_operation==='begin'){attempt=structuredClone(p);stored=p.envelope;status='used';return{data:{attemptId:p.attemptId,revision:p.revision,connectionId:p.attemptId,applicationId:'inert-app',expectedAccount:provider==='etsy'?'InertShop':'123',storeKind:'manual_api',providerType:'native',connectionExpiresAt:new Date(Date.now()+86400000).toISOString()}};}
  if(args.p_operation==='consume'){if(stored===null)return{error:{message:'used'}};const envelope=stored;stored=null;return{data:{envelope,revision:attempt.revision,connectionId:attempt.attemptId,applicationId:'inert-app',expectedAccount:'InertShop',connectionExpiresAt:new Date(Date.now()+86400000).toISOString()}};}
  if(args.p_operation==='mark'){const endpoints=provider==='etsy'?['https://api.etsy.com/v3/public/oauth/token','https://api.etsy.com/v3/application/users/100/shops','https://api.etsy.com/v3/application/shops/200/listings?state=draft&limit=1&offset=0']:['https://api.printful.com/oauth/scopes','https://api.printful.com/stores/123'];return{data:{shouldDispatch:true,attemptId:p.attemptId,step:p.step,endpoint:endpoints[p.step],method:provider==='etsy'&&p.step===0?'POST':'GET',expiresAt:new Date(Date.now()+15000).toISOString()}};}
  return{data:{verified:true}};
 }}};
 const tokens={accessToken:'100.inert-access',refreshToken:'100.inert-refresh',userId:100,scopes:['shops_r','listings_r'],tokenExpiresAt:new Date(Date.now()+600000).toISOString()};
 const deps={'server-only':{},'node:crypto':require('node:crypto'),'../lib/core-ui/owner-business':{verifyOwnerBusiness:async(c,b)=>c.userId===owner&&b===businessId},'../accounts/vault':V,'./printful-read':{verifyPrintfulEnvironmentBinding:async(input,permit)=>{providerCalls.push('printful');for(const [step,endpoint]of ['https://api.printful.com/oauth/scopes','https://api.printful.com/stores/123'].entries())await permit(step,endpoint,'GET');return{storeId:input.storeId,storeKind:'manual_api',providerType:'native',providerScopes:['stores_list/read'],responseHash:'b'.repeat(64),verifiedAt:new Date().toISOString()};}},'./contracts':C,'./etsy-read':{...E,exchangeReadOAuth:async(config,input,permit)=>{providerCalls.push('token');await permit(0,'https://api.etsy.com/v3/public/oauth/token','POST');return structuredClone(tokens);},verifyEtsyReadConnection:async(config,t,shop,permit)=>{providerCalls.push('reads');await permit(1,'https://api.etsy.com/v3/application/users/100/shops','GET',{userId:100,scopes:t.scopes,tokenExpiresAt:t.tokenExpiresAt});await permit(2,'https://api.etsy.com/v3/application/shops/200/listings?state=draft&limit=1&offset=0','GET',{userId:100,shopId:200,shopName:shop,currency:'NZD'});return{userId:100,shopId:200,shopName:shop,currency:'NZD',listingCount:0,totalDrafts:0,factsHash:'c'.repeat(64),verifiedAt:new Date().toISOString()};}}};
 const source=ts.transpileModule(readFileSync('src/connections/server.ts','utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText,m={exports:{}};
 runInNewContext(`(function(require,module,exports){${source}\n})`,{process:{env},Buffer,Date,URLSearchParams})(n=>{assert.ok(n in deps,n);return deps[n];},m,m.exports);
 return{...m.exports,context,env,calls,providerCalls,businessId,grantId,sessionId,tokens,attempt:()=>attempt};
}
test('R11 absent grants/config and Preview cannot produce an OAuth grant URL',async()=>{
 for(const mode of ['no-grant','no-key','preview']){const h=harness({enabled:mode!=='no-grant'});if(mode==='no-key')delete h.env.ACCOUNTS_VAULT_KEY;if(mode==='preview')h.env.VERCEL_ENV='preview';await assert.rejects(h.beginEtsyReadConnection(h.context,h.businessId,h.grantId));assert.equal(h.providerCalls.length,0);assert.equal(h.calls.some(c=>c.args.p_operation==='begin'),false);}
});
test('R11 exact callback stores domain-separated encrypted renewable tokens, never plaintext or broad scopes',async()=>{
 const h=harness(),flow=await h.beginEtsyReadConnection(h.context,h.businessId,h.grantId),url=new URL(flow.url);
 const result=await h.completeEtsyReadConnection(h.context,flow.cookie,new URLSearchParams({state:url.searchParams.get('state'),code:'inert-auth-code'}));assert.equal(result,h.businessId);
 const call=h.calls.find(c=>c.args.p_operation==='complete').args.p_payload;assert.ok(!JSON.stringify(call).includes(h.tokens.accessToken));assert.ok(!JSON.stringify(call).includes(h.tokens.refreshToken));
 const a=h.attempt(),saved=V.unsealAccountSecret(call.envelope,{businessId:h.businessId,provider:'etsy_r11_access',connectionId:a.attemptId,revision:a.revision},h.env.ACCOUNTS_VAULT_KEY);
 assert.equal(saved.refreshToken,h.tokens.refreshToken);assert.deepEqual(saved.scopes,['shops_r','listings_r']);assert.equal(saved.shopId,200);
 assert.throws(()=>V.unsealAccountSecret(call.envelope,{businessId:h.businessId,provider:'etsy',connectionId:a.attemptId,revision:a.revision},h.env.ACCOUNTS_VAULT_KEY));
 assert.deepEqual(h.providerCalls,['token','reads']);await assert.rejects(h.completeEtsyReadConnection(h.context,flow.cookie,new URLSearchParams({state:url.searchParams.get('state'),code:'inert-auth-code'})));assert.deepEqual(h.providerCalls,['token','reads']);
});
test('R11 changed state, owner/session or app credential stops before token exchange',async()=>{
 for(const mode of ['state','owner','session','key']){const h=harness(),flow=await h.beginEtsyReadConnection(h.context,h.businessId,h.grantId),url=new URL(flow.url);if(mode==='owner')h.context.userId=id(99);if(mode==='session')h.context.supabase.auth.getClaims=async()=>({data:{claims:{sub:h.context.userId,session_id:id(99)}}});if(mode==='key')h.env.ETSY_SHARED_SECRET='changed-inert-secret';await assert.rejects(h.completeEtsyReadConnection(h.context,flow.cookie,new URLSearchParams({state:mode==='state'?'wrong':url.searchParams.get('state'),code:'inert-auth-code'})));assert.equal(h.providerCalls.length,0);}
});
test('R11 decline cancels only its exact saved request with no provider call',async()=>{const h=harness(),flow=await h.beginEtsyReadConnection(h.context,h.businessId,h.grantId);await h.completeEtsyReadConnection(h.context,flow.cookie,new URLSearchParams({state:new URL(flow.url).searchParams.get('state'),error:'access_denied'}));assert.equal(h.providerCalls.length,0);assert.equal(h.calls.at(-1).args.p_operation,'cancel');});
test('R11 Printful keeps token only in environment and binds two exact reads',async()=>{const h=harness({provider:'printful'});await h.qualifyPrintfulEnvironment(h.context,h.businessId,h.grantId);const complete=h.calls.find(c=>c.args.p_operation==='complete').args.p_payload;assert.equal(complete.envelope,null);assert.equal(complete.proof.storeId,123);assert.equal(h.calls.filter(c=>c.args.p_operation==='mark').length,2);assert.ok(!JSON.stringify(h.calls).includes(h.env.PRINTFUL_INERT_TOKEN));});
test('R11 failures retain an unverified attempt and sanitize private diagnostics',async()=>{const h=harness({failPhase:'complete'}),flow=await h.beginEtsyReadConnection(h.context,h.businessId,h.grantId);await assert.rejects(h.completeEtsyReadConnection(h.context,flow.cookie,new URLSearchParams({state:new URL(flow.url).searchParams.get('state'),code:'inert-auth-code'})),/^Error: connection_qualification_unverified$/);assert.equal(h.calls.at(-1).args.p_operation,'fail');});

test('R11 an app key replacement before begin cannot inherit the approved grant',async()=>{const h=harness();h.env.ETSY_KEYSTRING='inert-other-app';await assert.rejects(h.beginEtsyReadConnection(h.context,h.businessId,h.grantId),/unapproved_application_credential/);assert.equal(h.calls.some(c=>c.args.p_operation==='begin'),false);assert.equal(h.providerCalls.length,0);});

function readMetadataHarness(change){const h=harness(),original=h.context.supabase.rpc;h.context.supabase.rpc=async(name,args)=>{const out=await original(name,args);if(name==='r11_etsy_read_workspace'){const window={id:id(40),connectionId:id(41),bindingRevision:id(42),expiresAt:new Date(Date.now()+60000).toISOString(),mode:'qualification',credentialFingerprint:'4'.repeat(64),maxReads:1,maxRefreshes:1,readsDispatched:0,refreshesDispatched:0,minRefreshSeconds:3000,state:'available'};out.data.readWindows=[window];out.data.readAttempts=[];change(out.data);}return out;};return h;}
for(const change of [{maxReads:0},{maxReads:2},{maxReads:745},{minRefreshSeconds:100},{credentialFingerprint:'bad'},{readsDispatched:2},{refreshesDispatched:2}])test('R11 malformed read-window metadata fails closed without token resolution',async()=>{const h=readMetadataHarness(v=>Object.assign(v.readWindows[0],change));assert.equal((await h.readConnectionQualification(h.context,h.businessId)).unavailable,true);assert.deepEqual(h.providerCalls,[]);});
for(const listingCount of [null,false,'1',2])test('R11 malformed observed listing count cannot become a saved proof',async()=>{const h=readMetadataHarness(v=>{v.readAttempts=[{id:id(50),windowId:id(40),connectionId:id(41),bindingRevision:id(42),status:'succeeded',createdAt:new Date().toISOString(),completedAt:new Date().toISOString(),refreshed:true,proof:{totalDrafts:1,listingCount,verifiedAt:new Date().toISOString()}}];});assert.equal((await h.readConnectionQualification(h.context,h.businessId)).unavailable,true);assert.deepEqual(h.providerCalls,[]);});
test('R11 metadata read never resolves or refreshes tokens and strips window fingerprint',async()=>{const h=readMetadataHarness(()=>{}),view=await h.readConnectionQualification(h.context,h.businessId);assert.equal(view.unavailable,false);assert.equal(view.readWindows.length,1);assert.equal('credentialFingerprint' in view.readWindows[0],false);assert.deepEqual(h.providerCalls,[]);assert.equal(h.calls.every(c=>c.name==='r11_etsy_read_workspace'),true);});
