import test from 'node:test';import assert from 'node:assert/strict';
import{loadPublic,uid,h,hash,self,publicPolicy}from'./r12-public-fixtures.mjs';
import{r12CatalogFixture}from'./helpers/r12-provider-fixture.mjs';
import{qualifyEtsyOwnerResearchQuote}from'../.core-tests/products/discovery-r12-adaptive-quote.js';
const prep=await loadPublic('preparation'),e=await loadPublic('execution-quote'),T=Date.parse('2026-10-10T11:00:00.000Z');
function quote(at,factor=1,browserChanges={}){
 const catalogs=r12CatalogFixture(at);
 function discount(v){if(!v||typeof v!=='object')return;for(const[k,x]of Object.entries(v)){if(k==='pricing'){for(const key of ['prompt','completion','input_cache_read','input_cache_write'])if(typeof x[key]==='string')x[key]=(Number(x[key])*factor).toFixed(14).replace(/0+$/,'').replace(/\.$/,'');}else discount(x);}}
 if(factor!==1)discount(catalogs);
 const browser=self({version:'r12.public-browser-quote.1',provider:'steel',category:'browser',providerProjectId:uid(4),zeroCostQualificationHash:null,routeHash:h('route'),priceEvidenceHash:h('price'),settlementContractHash:h('settlement'),tariffHash:h('tariff'),qualificationHash:h('qualified'),maximumMicrounits:'2500',verifiedAt:new Date(at-1000).toISOString(),validUntil:new Date(at+299000).toISOString(),qualified:true,retentionDisclosure:'Same approved private aggregate capture and profile terms.',...browserChanges},'browserQuoteHash');
 return prep.qualifyPublicResearchQuote(qualifyEtsyOwnerResearchQuote(catalogs,at),browser,'10000000',at,10);
}
function fixture(){const approved=quote(T),{policy:base}=publicPolicy(10),{policyHash,...body}=base;void policyHash;const policy=self({...body,quoteHash:approved.quoteHash,phaseMaximumMicrounits:approved.phaseMaximumMicrounits},'policyHash'),binding={attemptOrdinal:1,windowAttemptOrdinal:1,phase:'plan',phaseAttemptId:uid(500)};
 const authority=self({version:'r12.public-execution-authority.1',businessId:policy.businessId,goalId:policy.goalId,authorityRootId:policy.authorityRootId,envelopeHash:policy.envelopeHash,policyHash:policy.policyHash,phaseAttemptId:binding.phaseAttemptId,knownActualMicrounits:'1000',heldMaximumMicrounits:'2000000',windowMaximumMicrounits:'10000000',rootHeadroomMicrounits:'10000000',businessHeadroomMicrounits:'10000000',allocationHeadroomMicrounits:'10000000',hasUnknownLiability:false,authorityActive:true,stopped:false,expiresAt:new Date(T+3600000).toISOString()},'snapshotHash');return{approved,policy,binding,authority};}
function qualify(f,current=quote(T+360000),authority=f.authority,at=T+360000){return e.qualifyPublicResearchExecutionQuote(f.approved,current,f.policy,f.binding,authority,h('private-current-route-evidence'),at);}
function authority(f,changes){const{snapshotHash,...body}=f.authority;void snapshotHash;return self({...body,...changes},'snapshotHash');}
test('fresh per-phase quote can renew expired observation without changing approved policy',()=>{const f=fixture(),before=hash(f.policy),current=quote(T+360000),proof=qualify(f,current);assert.notEqual(proof.executionQuoteHash,proof.approvedQuoteHash);assert.equal(proof.approvedQuoteHash,f.policy.quoteHash);assert.equal(hash(f.policy),before);assert.doesNotThrow(()=>e.validatePublicResearchExecutionQuoteProof(proof,f.approved,current,f.policy,f.binding,{routeEvidenceHash:proof.routeEvidenceHash,authoritySnapshotHash:f.authority.snapshotHash},T+360000));});
test('bounded pending maxima remain reserved under renewed quote and consume USD10 headroom',()=>{const f=fixture();assert.doesNotThrow(()=>qualify(f));assert.throws(()=>qualify(f,quote(T+360000),authority(f,{knownActualMicrounits:'9999999',heldMaximumMicrounits:'1'})),/budget_blocked/);assert.equal(f.authority.heldMaximumMicrounits,'2000000');});
test('unknown liability, Stop, or another envelope cannot be washed away by fresh quote',()=>{const f=fixture();for(const changes of [{hasUnknownLiability:true},{stopped:true},{envelopeHash:h('reset')},{policyHash:h('other-policy')}])assert.throws(()=>qualify(f,quote(T+360000),authority(f,changes)));});
test('price rebound after a lower quote stays bounded by original approved ceilings',()=>{const f=fixture(),lower=quote(T+360000,0.5),rebound=quote(T+370000);assert.doesNotThrow(()=>qualify(f,lower));assert.doesNotThrow(()=>qualify(f,rebound,f.authority,T+370000));assert.throws(()=>qualify(f,quote(T+380000,2),f.authority,T+380000),/expansion/);});
test('tariff, provider project and disclosure drift require new reviewed authority',()=>{const f=fixture();for(const changes of [{tariffHash:h('new-tariff')},{providerProjectId:uid(999)},{retentionDisclosure:'New recipient and expanded retention'}])assert.throws(()=>qualify(f,quote(T+360000,1,changes)),/terms_changed/);});
test('model route or data policy mismatch cannot hide under recomputed quote hash',()=>{const f=fixture(),current=quote(T+360000);current.inference.reviewer.modelId='openai/gpt-5.6-luna';assert.throws(()=>qualify(f,current));const privacy=structuredClone(quote(T+360000));privacy.inference.retention.inference='training_allowed';assert.throws(()=>qualify(f,privacy));});
test('per-phase proof cannot replay for another phase or actual attempt',()=>{const f=fixture(),current=quote(T+360000),proof=qualify(f,current),expected={routeEvidenceHash:proof.routeEvidenceHash,authoritySnapshotHash:f.authority.snapshotHash};assert.throws(()=>e.validatePublicResearchExecutionQuoteProof(proof,f.approved,current,f.policy,{...f.binding,phase:'strategy'},expected,T+360000));assert.throws(()=>e.validatePublicResearchExecutionQuoteProof(proof,f.approved,current,f.policy,{...f.binding,phaseAttemptId:uid(501)},expected,T+360000));});
test('quote expires immediately before dispatch and no TTL is silently extended',()=>{const f=fixture(),current=quote(T+360000),proof=qualify(f,current),expected={routeEvidenceHash:proof.routeEvidenceHash,authoritySnapshotHash:f.authority.snapshotHash};assert.throws(()=>e.validatePublicResearchExecutionQuoteProof(proof,f.approved,current,f.policy,f.binding,expected,Date.parse(proof.validUntil)));});
test('current private route and full ledger identities are independently pinned',()=>{const f=fixture(),current=quote(T+360000),proof=qualify(f,current);assert.throws(()=>e.validatePublicResearchExecutionQuoteProof(proof,f.approved,current,f.policy,f.binding,{routeEvidenceHash:h('forged-route'),authoritySnapshotHash:f.authority.snapshotHash},T+360000));assert.throws(()=>e.validatePublicResearchExecutionQuoteProof(proof,f.approved,current,f.policy,f.binding,{routeEvidenceHash:proof.routeEvidenceHash,authoritySnapshotHash:h('empty-ledger')},T+360000));});
