import test from 'node:test';
import assert from 'node:assert/strict';
import {focusedSuccessorFixture} from './helpers/r12-focused-successor-fixture.mjs';
import {withClock,now} from './r12-focused-pilot-runtime.test.mjs';
import {focusedStrategyOutput} from './helpers/r12-focused-profile-fixture.mjs';
import {buildDiscoveryR12PhaseRequest,readDiscoveryR12PhaseInputs,projectDiscoveryR12Phase} from '../.core-tests/products/discovery-r12-runtime.js';
import {routeDiscoveryR12Request,inspectDiscoveryR12Wire} from '../.core-tests/products/discovery-r12-wire.js';
import {createDiscoveryR12QuestAdapter} from '../.core-tests/products/discovery-r12-adapter.js';
import {validateR12ReviewOwnerEvidence} from '../.core-tests/products/discovery-r12-observation.js';

async function fixture({successor=true,broken='inconsistent'}={}){
 const f=withClock(now,focusedSuccessorFixture);if(!successor)delete f.value.focusedPilot.successor;
 const request=routeDiscoveryR12Request(withClock(now,()=>buildDiscoveryR12PhaseRequest(f.ctx,readDiscoveryR12PhaseInputs(f.ctx,f.value))),'strategy',{modelId:'openai/gpt-5.6-luna',endpoint:'azure/us',priceLimit:{prompt:1,completion:1,request:0}},true),wire=await inspectDiscoveryR12Wire(request,'strategy',false,true);
 const identity={qualificationHash:'b'.repeat(64),workflowDefinitionId:'dddddddd-dddd-4ddd-8ddd-000000000060',workerDefinitionId:'dddddddd-dddd-4ddd-8ddd-000000000061'},ctx=structuredClone(f.ctx);Object.assign(ctx.step,{...identity,adapter:`r12.discovery.${f.p.id}.strategy`,operationKey:`research.r12.${f.p.id}.strategy`,maximumMicrounits:'66671'});ctx.attempt.wireHash=wire.wireHash;ctx.plan.expiresAt=f.p.expiresAt;
 const binding={version:'r12.discovery-wire.1',scopeId:f.p.id,scopeHash:ctx.plan.discoveryScopeHash,attemptId:ctx.attempt.id,requestId:ctx.attempt.requestId,phase:'strategy',requestJson:JSON.stringify(request),requestHash:wire.requestHash,wireBody:wire.wire.body,wireHash:wire.wireHash,dependencyPins:[]};
 const saved={candidate:null,proof:null,diagnostic:null,observationSaved:false,receipt:{status:'awaiting_receipt'}},observations=[],settlements=[],events=[];let posts=0,gets=0;
 const store={operation:async(_id,operation,payload)=>{events.push(operation);if(operation==='load')return{binding,...saved};if(operation==='send')return{shouldDispatch:true};if(operation==='observe'){observations.push(payload.observation);saved.observationSaved=true;return{observed:true};}if(operation==='diagnose'){saved.diagnostic=payload.diagnostic;return{recorded:true};}if(operation==='stage'){saved.candidate=payload.candidate;return{staged:true};}if(operation==='claim')return{claimed:true,claimId:identity.workerDefinitionId};if(operation==='record'){saved.proof=payload.proof;return{recorded:true};}throw Error(operation);},settle:async(_id,s)=>settlements.push(s),dispatchedAt:async()=>new Date(now).toISOString()};
 const output=focusedStrategyOutput(f.prepared);if(broken==='inconsistent')output.candidates[0].dimensions[0].uncertainties.push({question:'Is this exact proposal blocked by the unresolved fixture constraint?',blockingForTest:true,reason:'The synthetic constraint prevents this exact pinned proposal from being recommended.'});
 const adapter=createDiscoveryR12QuestAdapter({scope:f.envelope,phase:'strategy',identity:{...identity,mode:'qualification'},dataClasses:['business_context','public_evidence'],store,request:async()=>request,quote:async()=>{throw Error('No quote call allowed');},project:async(qualified,c,r)=>withClock(now,()=>projectDiscoveryR12Phase(c,readDiscoveryR12PhaseInputs(c,{...f.value,inputMode:'receipt'}),qualified,r)),now:()=>now+1,config:{apiKey:'inert-config-no-secret',baseUrl:'https://openrouter.ai/api/v1'},fetcher:async(_url,init)=>{if(init.method==='GET'){gets++;return new Response(JSON.stringify({data:{id:'gen-successor-diagnostic-fixture',provider_name:'Azure',model:'openai/gpt-5.6-luna-20260709'}}));}posts++;return new Response(JSON.stringify({id:'gen-successor-diagnostic-fixture',model:'openai/gpt-5.6-luna-20260709',choices:[{finish_reason:'stop',message:{content:broken==='json'?'UNQUALIFIED_STRATEGY_SENTINEL':JSON.stringify(output)}}],usage:{prompt_tokens:100,completion_tokens:100,total_tokens:200,cost:.00001}}));}});
 return{adapter,ctx,wire,saved,observations,settlements,events,counts:()=>({posts,gets})};
}
for(const broken of ['inconsistent','json'])test(`successor ${broken} strategy is durably diagnosed once without losing charge`,async()=>{
 const f=await fixture({broken});await assert.rejects(f.adapter.dispatch({wire:f.wire.wire},f.ctx));assert.equal(f.counts().posts,1);assert.equal(f.saved.diagnostic.code,broken==='json'?'json_parse':'domain_validation');assert.equal(f.saved.diagnostic.observationSaved,true);assert.equal(f.observations.length,1);assert.equal(f.settlements[0].actualMicrounits,'10');assert.deepEqual(await f.adapter.reconcile(f.ctx),{status:'unknown'});assert.equal(f.counts().posts,1);assert.equal(f.counts().gets,broken==='json'?0:1);
 const {version,scopeId,attemptId,requestId,content,providerRequestId,providerModelId,...observation}=f.observations[0];void[version,scopeId,attemptId,requestId,content,providerRequestId,providerModelId];const {version:dv,scopeId:ds,attemptId:da,requestId:dr,...diagnostic}=f.saved.diagnostic;void[dv,ds,da,dr];
 assert.throws(()=>validateR12ReviewOwnerEvidence(observation,diagnostic,'strategy'));assert.doesNotThrow(()=>validateR12ReviewOwnerEvidence(observation,diagnostic,'strategy',true));assert.throws(()=>validateR12ReviewOwnerEvidence({...observation,content:'must never leak'},diagnostic,'strategy',true));
});
test('legacy focused strategy is not opted into successor diagnostic retention',async()=>{const f=await fixture({successor:false,broken:'json'});await assert.rejects(f.adapter.dispatch({wire:f.wire.wire},f.ctx));assert.equal(f.observations.length,0);assert.equal(f.saved.diagnostic,null);assert.equal(f.settlements[0].actualMicrounits,'10');});
