import {readFileSync} from 'node:fs';
import test from 'node:test';import assert from 'node:assert/strict';
import{loadPublic,uid,h,hash,self,stamp,lineage}from'./r12-public-fixtures.mjs';
const p=await loadPublic('preparation'),o=await loadPublic('origin');
export function ownerTestFixture(){
 const closure={version:'r12.direct-adaptive-origin-closure.1',businessId:uid(1),goalId:uid(2),predecessorPlanId:uid(10),predecessorPlanHash:h('plan'),predecessorPlanVersion:7,predecessorScopeId:uid(11),predecessorScopeHash:h('scope'),predecessorScopeVersion:'r12.discovery-owner-adaptive.2',predecessorSetupId:uid(12),predecessorSetupHash:h('setup'),predecessorActivationHash:h('activation'),predecessorPolicyId:uid(13),predecessorPolicyHash:h('policy'),authorityRootId:uid(3),fundingBindingId:uid(14),goalRevision:1,goalHash:h('goal'),businessRevision:1,businessHash:h('business'),headRevision:10,headState:'stopped',headReason:'Owner stopped after qualified source pause',baseChildren:19,baseDispatches:17,baseRepairs:0,basePivots:0,baseKnownMicrounits:'5000',closureProofHash:h('closure'),revocationHash:h('revoked'),settlementHash:h('settled'),historyHash:h('predecessor-history')};
 const originHistory=self({version:'r12.public-research-origin-history.1',businessId:uid(1),goalId:uid(2),predecessorScopeId:uid(11),predecessorClosureHash:hash(closure),receipts:[],financialProofs:[],provenance:[],materialHistory:[],continuity:{seenQuestionHashes:[],seenEvidenceIdentityHashes:[],seenFactIdentityHashes:[],usedDiagnosticHashes:[],negativeFindingHashes:[],consecutiveNonprogress:1}},'historyHash');
 const origin={predecessor:{kind:'adaptive_direct_origin',closure},originHistory};
 const capProposal={version:'r12.public-cap-proposal.1',business:{currentRevision:1,currentLimitMicrounits:'6000',proposedLimitMicrounits:'10005000'},root:{currentRevision:1,currentLimitMicrounits:'6000',proposedLimitMicrounits:'10005000'}};
 const quote=self({version:'r12.public-browser-quote.1',provider:'steel',category:'browser',providerProjectId:uid(4),zeroCostQualificationHash:null,routeHash:h('route'),priceEvidenceHash:h('price'),settlementContractHash:h('settlementcontract'),tariffHash:h('tariff'),qualificationHash:h('qualified'),maximumMicrounits:'2500',verifiedAt:stamp,validUntil:'2026-10-10T12:05:00.000Z',qualified:true,retentionDisclosure:'Private retained screenshots and approved opaque browser profile; no secrets enter the model.'},'browserQuoteHash');
 const input={version:'r12.owner-direct-test-input.1',businessId:uid(1),goalId:uid(2),grantId:uid(20),predecessorScopeId:uid(11),predecessorScopeHash:h('scope'),maximumAttemptsInWindow:10,maximumRunMicrounits:'10000000',capProposal,submissionId:uid(21)};
 const operation={operationKey:'etsy.owner_login',workflowDefinitionId:uid(25),workflowHash:h('workflow'),qualificationHash:h('qualified'),routeHash:h('route'),quoteHash:quote.browserQuoteHash,maximumMicrounits:'2500'};
 const ledger={revision:1,currentLimitMicrounits:'6000',conservativeExposureMicrounits:'5000',headroomMicrounits:'1000'};
 const funding={bindingId:uid(14),bindingKind:'legacy_research_root',authorityRootId:uid(3),business:ledger,root:{...ledger,bindingHash:h('binding')},funding:{binding:{kind:'legacy_research_root',bindingId:uid(14),authorityRootId:uid(3),priorRoundId:uid(30),originalSemanticGoalHash:h('semantic')},revision:1,hash:h('binding'),maximumMicrounits:'6000',committedMicrounits:'5000',pendingMicrounits:'0',hasUnknown:false,budget:{accounting:'qualified prior lifetime cost'}}};
 const preview={version:'r12.owner-direct-test-envelope.1',testEnvelopeId:uid(40),businessId:uid(1),goalId:uid(2),ownerId:uid(41),authorityRootId:uid(3),bindingId:uid(14),policyId:uid(42),grantId:uid(20),grantRootId:uid(43),grantReviewHash:h('grantreview'),originDirectRunId:uid(44),input,origin,originHash:hash(origin),funding,capProposal,maximumMicrounits:'10000000',maximumAttemptsInWindow:10,setupOperation:operation,verificationOperation:{...operation,operationKey:'etsy.verify_account'},setupQuote:quote,verificationQuote:quote,researchPins:{status:'not_executable'},profileTemplate:{status:'not_executable'},requiresPersistentAccessApproval:true,existingGoalBudget:{amount:'10',currency:'USD'},expiresAt:'2026-10-10T14:00:00.000Z'};
 return{version:'r12.owner-direct-test-receipt.1',businessId:uid(1),goalId:uid(2),testEnvelopeId:uid(40),testEnvelopeHash:hash(preview),confirmed:false,stopped:false,createdAt:stamp,expiresAt:preview.expiresAt,preview};
}
const expected={businessId:lineage.businessId,goalId:lineage.goalId};
function rehash(r){r.testEnvelopeHash=hash(r.preview);return r;}
test('owner bootstrap read binds original Goal/root, exact setup/verification and USD10 cap',()=>{const r=ownerTestFixture();assert.deepEqual(p.validatePublicResearchOwnerTestReceipt(r,expected),r);assert.equal(r.preview.requiresPersistentAccessApproval,true);});
test('receipt remains readable when stopped or expired without becoming authority',()=>{const r=ownerTestFixture();r.confirmed=true;r.stopped=true;assert.equal(p.validatePublicResearchOwnerTestReceipt(r,expected).stopped,true);});
test('saved origin/Goal/envelope hashes cannot be substituted',()=>{const r=ownerTestFixture();assert.throws(()=>p.validatePublicResearchOwnerTestReceipt(r,{...expected,testEnvelopeHash:h('other')}));r.preview.originHash=h('wrong');assert.throws(()=>p.validatePublicResearchOwnerTestReceipt(rehash(r),expected));});
test('new amount beyond USD10 cannot be hidden in a newly hashed preview',()=>{const r=ownerTestFixture();r.preview.maximumMicrounits='10000001';r.preview.input.maximumRunMicrounits='10000001';assert.throws(()=>p.validatePublicResearchOwnerTestReceipt(rehash(r),expected));});
test('setup and verification cannot consume all research headroom',()=>{const r=ownerTestFixture();r.preview.maximumMicrounits='5000';r.preview.input.maximumRunMicrounits='5000';assert.throws(()=>p.validatePublicResearchOwnerTestReceipt(rehash(r),expected));});
test('current cap revision and unclamped exposure stay pinned',()=>{const r=ownerTestFixture();r.preview.capProposal.business.currentRevision=2;assert.throws(()=>p.validatePublicResearchOwnerTestReceipt(rehash(r),expected));});
test('operation quote/project cannot cross into another private tariff',()=>{const r=ownerTestFixture();r.preview.setupOperation.routeHash=h('wrong');assert.throws(()=>p.validatePublicResearchOwnerTestReceipt(rehash(r),expected));});
test('browser release alone is not quote or settlement qualification',()=>{const r=ownerTestFixture();const{browserQuoteHash,...q}=r.preview.setupQuote;void browserQuoteHash;r.preview.setupQuote=self({...q,qualified:false},'browserQuoteHash');r.preview.setupOperation.quoteHash=r.preview.setupQuote.browserQuoteHash;assert.throws(()=>p.validatePublicResearchOwnerTestReceipt(rehash(r),expected));});
test('unknown bootstrap worker fields remain inert private projections, credentials reject',()=>{const r=ownerTestFixture();r.preview.researchPins={unexpectedCapability:'not activated'};assert.doesNotThrow(()=>p.validatePublicResearchOwnerTestReceipt(rehash(r),expected));r.preview.researchPins={apiKey:'sk-example-secret-material'};assert.throws(()=>p.validatePublicResearchOwnerTestReceipt(rehash(r),expected));});
test('public archive carries frozen nonprogress and prevents provenance omissions from seen sets',()=>{const r=ownerTestFixture(),history=r.preview.origin.originHistory;assert.equal(o.publicResearchInheritedHistory(history).consecutiveNonprogress,1);const provenance=self({kind:'owner_observation',scopeId:uid(11),containerId:uid(60),containerHash:h('bundle'),sourceId:'source1',sourceContentHash:h('text'),evidenceId:'metric1',evidenceIdentityHash:h('quote'),factIdentityHash:h('fact')},'provenanceHash');const{historyHash,...body}=history;void historyHash;assert.throws(()=>o.validatePublicResearchOriginHistory(self({...body,provenance:[provenance]},'historyHash')));});
test('reviewed-pins-only projection preserves complete large schema-shaped JSON beyond legacy 64KiB/1000-node bounds',()=>{const pins={version:'r12.direct-research-pins.1',snapshot:{releases:Array.from({length:700},(_,n)=>({id:uid(1000+n),name:`Reviewed schema item ${n}`,schema:{type:'object',additionalProperties:false,properties:{description:{type:'string',description:'Bounded immutable schema description for the reviewed worker.'}},required:['description']}}))}};const bytes=Buffer.byteLength(JSON.stringify(pins));assert.ok(bytes>73317&&bytes<262144);assert.deepEqual(p.validatePublicResearchReviewedPinsProjection(pins),pins);const r=ownerTestFixture();r.preview.researchPins=pins;assert.deepEqual(p.validatePublicResearchOwnerTestReceipt(rehash(r),expected).preview.researchPins,pins);r.preview.profileTemplate=pins;assert.throws(()=>p.validatePublicResearchOwnerTestReceipt(rehash(r),expected));});
test('reviewed pins scanner rejects nested credential strings and keys without truncating later nodes',()=>{for(const bad of [{value:'password: private'}, {'Authorization: Basic private':'ordinary'}]){const pins={values:Array.from({length:2000},(_,n)=>`ordinary ${n}`),last:bad};assert.throws(()=>p.validatePublicResearchReviewedPinsProjection(pins));}});
test('reviewed pins accessors and custom prototypes reject before invocation or hashing',()=>{let invoked=0;const nested={};Object.defineProperty(nested,'value',{enumerable:true,get(){invoked++;return 'ordinary';}});assert.throws(()=>p.validatePublicResearchReviewedPinsProjection({nested}));const receipt=ownerTestFixture();receipt.preview.researchPins={nested};assert.throws(()=>p.validatePublicResearchOwnerTestReceipt(receipt,expected));assert.equal(invoked,0);assert.throws(()=>p.validatePublicResearchReviewedPinsProjection({date:new Date()}));const array=[];Object.setPrototypeOf(array,{...Array.prototype});assert.throws(()=>p.validatePublicResearchReviewedPinsProjection({array}));});
test('reviewed pins cycles/depth/non-JSON values/oversize remain fail closed',()=>{const cyclic={};cyclic.self=cyclic;let deep={leaf:true};for(let n=0;n<25;n++)deep={next:deep};for(const value of [cyclic,deep,{many:Array(12001).fill(0)},{huge:'x'.repeat(262145)},{invalid:NaN},{invalid:Infinity},{invalid:undefined},{invalid:BigInt(1)},{invalid:()=>true}])assert.throws(()=>p.validatePublicResearchReviewedPinsProjection(value));const sparse=[];sparse.length=100000000;assert.throws(()=>p.validatePublicResearchReviewedPinsProjection({sparse}));const symbol={};symbol[Symbol('hidden')]='ordinary';assert.throws(()=>p.validatePublicResearchReviewedPinsProjection(symbol));});
test('ordinary projection limits and original envelope hashes are never widened by the reviewed-pins scanner',()=>{const r=ownerTestFixture();r.preview.researchPins={snapshot:{description:'x'.repeat(80000)}};assert.throws(()=>p.validatePublicResearchOwnerTestReceipt(r,expected));assert.doesNotThrow(()=>p.validatePublicResearchOwnerTestReceipt(rehash(r),expected));r.preview.profileTemplate={description:'x'.repeat(65537)};assert.throws(()=>p.validatePublicResearchOwnerTestReceipt(rehash(r),expected));});
test('complete real synthetic SQL reviewed pins73317B/2666nodes/depth22 pass without any omission',()=>{const pins=JSON.parse(readFileSync(new URL('./fixtures/r12-public-reviewed-pins.json',import.meta.url),'utf8'));let nodes=0,depth=0;function walk(v,d=0){nodes++;depth=Math.max(depth,d);if(v&&typeof v==='object')Object.values(v).forEach(x=>walk(x,d+1));}walk(pins);assert.equal(Buffer.byteLength(JSON.stringify(pins)),73317);assert.equal(nodes,2666);assert.equal(depth,22);assert.deepEqual(p.validatePublicResearchReviewedPinsProjection(pins),pins);const receipt=ownerTestFixture();receipt.preview.researchPins=pins;assert.deepEqual(p.validatePublicResearchOwnerTestReceipt(rehash(receipt),expected).preview.researchPins,pins);});
test('reviewed pins reflection failures return a fixed diagnostic without propagating thrown input details',()=>{const raw=new Proxy({},{getPrototypeOf(){throw Error('untrusted reflection detail');}});assert.throws(()=>p.validatePublicResearchReviewedPinsProjection(raw),e=>e.message==='r12_public_reviewed_pins_unverified');});
