import test from 'node:test';import assert from 'node:assert/strict';
import{loadPublic,uid,h,hash,self,accounting,binding,publicPolicy,command}from'./r12-public-fixtures.mjs';
import{fixture as browserFixture,NOW}from'./helpers/r12-public-insights-model-fixture.mjs';
import{r12CatalogFixture}from'./helpers/r12-provider-fixture.mjs';
import{r12PhaseOutputFixture}from'./helpers/r12-phase-output-fixture.mjs';
import{runEtsyInsightsResearch}from'../.core-tests/browser/etsy-insights-runtime.js';
import{ETSY_INSIGHTS_CAPTURE_POLICY_HASH,ETSY_INSIGHTS_SOURCE_POLICY_HASH}from'../.core-tests/browser/etsy-insights-policy.js';
import{qualifyEtsyOwnerResearchQuote}from'../.core-tests/products/discovery-r12-adaptive-quote.js';
import{qualifyGenerationRouteProof}from'../.core-tests/research/generation-route.js';
const m=await loadPublic('model'),prep=await loadPublic('preparation'),cycle=await loadPublic('cycle'),origin=await loadPublic('origin'),quality=await loadPublic('quality');
function repinState(s,changes={}){const{stateHash,...body}=s;void stateHash;return self({...body,...changes},'stateHash');}
function mkInput(f,phase){return self({version:'r12.public-research-phase-inputs.1',format:'r12.discovery-direct.1',phase,phaseAttemptId:f.state.attempts.at(-1).dispatches.at(-1).attemptId,validationAt:NOW,planHash:h('real-plan'),policy:f.policy,quote:f.quote,profile:f.profile,state:f.state,originHistory:f.history,sourcePackets:f.packets,dependencies:{plan:phase==='plan'?null:f.dependencies.plan,strategy:phase==='review'?f.dependencies.strategy:null},reviewQualification:f.qualification},'inputHash');}
function expect(i){return{businessId:i.policy.businessId,goalId:i.policy.goalId,scopeId:i.policy.scopeId,scopeHash:i.policy.scopeHash,planHash:i.planHash,phaseAttemptId:i.phaseAttemptId,phase:i.phase,inputHash:i.inputHash,profileHash:i.profile.profileHash,reviewQualificationHash:hash(i.reviewQualification),sourceReceiptHashes:i.sourcePackets.map(s=>s.receipt.receiptHash),dependencyResponseHashes:Object.values(i.dependencies).filter(Boolean).map(x=>x.responseHash)};}
function context(f,phase){const input=mkInput(f,phase);return m.readPublicResearchModelInputs(input,expect(input));}
function fixture(){
 const base=publicPolicy(10),history=self({version:'r12.public-research-origin-history.1',businessId:base.policy.businessId,goalId:base.policy.goalId,predecessorScopeId:uid(700),predecessorClosureHash:h('closed-history'),receipts:[],financialProofs:[],provenance:[],materialHistory:[],continuity:{seenQuestionHashes:[],seenEvidenceIdentityHashes:[],seenFactIdentityHashes:[],usedDiagnosticHashes:[],negativeFindingHashes:[],consecutiveNonprogress:2}},'historyHash');
 const inherited=origin.publicResearchInheritedHistory(history),continuation=base.policy.continuation;const{continuationHash,...cont}=continuation;void continuationHash;
 const account=binding({verifiedAt:new Date(NOW-1000).toISOString(),expiresAt:new Date(NOW+120000).toISOString()});
 const browser=self({version:'r12.public-browser-quote.1',provider:'steel',category:'browser',providerProjectId:account.providerProjectId,zeroCostQualificationHash:null,routeHash:h('route'),priceEvidenceHash:h('price'),settlementContractHash:h('settlement-contract'),tariffHash:h('tariff'),qualificationHash:h('qualified'),maximumMicrounits:'2500',verifiedAt:new Date(NOW-1000).toISOString(),validUntil:new Date(NOW+299000).toISOString(),qualified:true,retentionDisclosure:'Private aggregate viewport screenshots; approved opaque profile.'},'browserQuoteHash');
 const quote=prep.qualifyPublicResearchQuote(qualifyEtsyOwnerResearchQuote(r12CatalogFixture(NOW),NOW),browser,'10000000',NOW,10);
 const nextCont=self({...cont,historyHash:hash(inherited)},'continuationHash'),{policyHash,...body}=base.policy;void policyHash;
 const policy=self({...body,quoteHash:quote.quoteHash,inheritedStateHash:hash(inherited),continuation:nextCont,window:{...body.window,continuationHash:nextCont.continuationHash},phaseMaximumMicrounits:quote.phaseMaximumMicrounits,sourcePolicyHash:ETSY_INSIGHTS_SOURCE_POLICY_HASH,sourceAccess:{allowedSource:'etsy_authenticated_insights',sourcePurpose:'etsy_insights_aggregate_research',accountBinding:account,capturePolicyHash:ETSY_INSIGHTS_CAPTURE_POLICY_HASH}},'policyHash');
 const profile=self({version:'r12.owner-research-profile.4',id:uid(800),businessId:policy.businessId,goalId:policy.goalId,goalHash:h('goal'),marketSetKey:'gb',topicKey:'adult interests',publicGoal:'Compare bounded adult apparel hypotheses with literal marketplace observations.',productFormat:'Original adult printed T-shirt',category:'Adult apparel',markets:[{countryCode:'GB',currency:'GBP'}],audience:'Adults interested in original apparel',sourceAccess:policy.sourceAccess,maximumAttemptsInWindow:10,originalRunMaximumMicrounits:'10000000',validUntil:new Date(NOW+120000).toISOString()},'profileHash');
 // Inject a server-authenticated inert scheduled snapshot. This does not invoke
 // live admission; the public cycle still explicitly gates unqualified Insights.
 let state=cycle.createPublicResearchState(policy,inherited,base.initial);state=repinState(state,{attempts:[{ordinal:1,windowAttemptOrdinal:1,attemptId:uid(810),kind:'initial',epochOrdinal:0,command:base.initial,dispatches:[{phase:'plan',attemptId:uid(811),requestHash:h('preflight-placeholder'),receiptHash:null}],sourceProof:null,status:'running',review:null,failureHash:null}],windowAttemptsStarted:1,totalAttemptsStarted:1,modelDispatchesUsed:1,cumulativeDispatchesUsed:18,epochCriteriaHash:base.initial.criteriaHash,seenCriteriaHashes:[base.initial.criteriaHash],nextAttemptKind:null,pendingCommand:null,history:{...inherited,seenQuestionHashes:[base.initial.questionHash]}});
 cycle.validatePublicResearchState(state,policy);
 return{policy,profile,quote,history,state,packets:[],dependencies:{plan:null,strategy:null},qualification:{version:'r12.public-review-qualification.1',requirementHash:h('requirements'),comparativeConclusion:false,materialOpposingExplanation:true,sourceTemporalPrecisionSufficient:false,claimBoundariesRespected:true,missingCriticalRequirements:['No eligible exposure denominator'],supportingEvidenceVerified:false,refutingEvidenceVerified:false}};
}
async function complete(f,phase,output){
 let ctx=context(f,phase),pre=m.buildPublicResearchModelRequest(ctx),wire=await m.inspectPublicResearchModelWire(ctx);assert.equal(wire.requestHash,hash(pre));
 let state=structuredClone(f.state);state.attempts.at(-1).dispatches.at(-1).requestHash=wire.requestHash;f.state=repinState(state);ctx=context(f,phase);const request=m.buildPublicResearchModelRequest(ctx);assert.deepEqual(request,pre);assert.equal((await m.inspectPublicResearchModelWire(ctx)).wire.body,wire.wire.body);
 const reviewer=phase==='review',model=reviewer?f.quote.inference.reviewer:f.quote.inference.luna,attemptId=ctx.input.phaseAttemptId,requestId=uid(820+['plan','strategy','review'].indexOf(phase)),generationId=`gen-direct-inert-${phase}`;
 const binding={scopeId:f.policy.scopeId,attemptId,requestId,phase,request,maximumMicrousd:Number(f.policy.phaseMaximumMicrounits[phase]),dispatchedAt:new Date(NOW-1000).toISOString(),receiptExpiresAt:new Date(NOW+60000).toISOString()};
 const candidate={version:'r12.discovery-response.1',scopeId:f.policy.scopeId,attemptId,requestId,phase,requestHash:hash(request),providerRequestId:generationId,providerModelId:model.modelId,receivedAt:new Date(NOW).toISOString(),reportedMicrousd:1,output};
 const proof=qualifyGenerationRouteProof({data:{id:generationId,provider_name:model.providerName,model:model.modelId}},{generationId,providerName:model.providerName,acceptedResponseModelIds:model.acceptedResponseModelIds,requestedEndpoint:model.endpoint});
 const result=m.projectPublicResearchModelPhase(ctx,candidate,binding,proof),response={outcome:'accepted',result,checkedArtifacts:[],planHash:ctx.input.planHash,inputHash:h(`semantic-${phase}`)};
 const dep={stepKey:phase,attemptId,artifactId:uid(830+['plan','strategy','review'].indexOf(phase)),responseHash:hash(response),responseCanonicalHash:hash(response),response,binding,candidate,proof};
 f.state=cycle.recordPublicResearchReceipt(f.policy,f.state,phase,result.modelReceiptHash);if(phase!=='review')f.dependencies[phase]=dep;
 return{ctx,wire,request,dep,result};
}
async function acquire(f){
 const p=f.policy,a=f.state.attempts.at(-1),bf=browserFixture({operationId:uid(840),sourceAttemptId:uid(841),businessId:p.businessId,goalId:p.goalId,authorityRootId:p.authorityRootId,scopeId:p.scopeId,scopeHash:p.scopeHash,originDirectRunId:p.originDirectRunId,providerProjectId:p.browserAccountingPins.providerProjectId,window:p.window,attemptOrdinal:1,windowAttemptOrdinal:1,criteriaHash:a.command.criteriaHash,questionHash:a.command.questionHash,quoteHash:p.quoteHash,accountBinding:p.sourceAccess.accountBinding,query:a.command.query,maximumBrowserMicrounits:p.phaseMaximumMicrounits.source});
 const output=await runEtsyInsightsResearch(bf.s,bf.d);assert.equal(output.persistence,'verified');const r=output.receipt;assert.equal(r.status,'completed');
 const acct=accounting({providerProjectId:p.browserAccountingPins.providerProjectId,operationId:r.operationId,operationReceiptHash:r.receiptHash,requestHash:r.requestHash,reservationId:r.reservationId,reservationHash:r.reservationHash,quoteHash:p.quoteHash,maximumMicrounits:p.phaseMaximumMicrounits.source,recordedAt:new Date(NOW).toISOString()});
 const proof={version:'r12.public-research-source-proof.1',sourceReceiptVersion:r.version,...Object.fromEntries(['operationId','sourceAttemptId','requestHash','receiptHash','captureHash','businessId','goalId','authorityRootId','scopeId','scopeHash','originDirectRunId','windowId','windowOrdinal','windowAttemptOrdinal','attemptOrdinal','criteriaHash','questionHash','quoteHash','status','releaseState','liabilityState','accountBindingHash','accountVerificationHash','capturePolicyHash','witnesses'].map(k=>[k,r[k]])),accounting:acct};
 f.state=cycle.markPublicResearchDispatch(p,f.state,{phase:'source',attemptId:r.sourceAttemptId,requestHash:r.requestHash,receiptHash:null});f.state=cycle.recordPublicResearchReceipt(p,f.state,'source',r.receiptHash,proof);f.packets.push({scope:bf.s,receipt:r,accounting:acct});
}
async function readyStrategy(){const f=fixture(),outputs=r12PhaseOutputFixture(f.profile.audience);outputs.plan.queryFocus=[];await complete(f,'plan',outputs.plan);await acquire(f);f.state=cycle.markPublicResearchDispatch(f.policy,f.state,{phase:'strategy',attemptId:uid(850),requestHash:h('preflight-strategy'),receiptHash:null});const assessment=outputs.strategy;assessment.marketComparisons=assessment.marketComparisons.filter(m=>m.countryCode==='GB');return{f,strategy:{assessment,measurement:null}};}
test('actual plan source strategy independent review wires yield genuine model receipts without fake search/select',async()=>{
 const{f,strategy}=await readyStrategy(),s=await complete(f,'strategy',strategy);f.state=cycle.markPublicResearchDispatch(f.policy,f.state,{phase:'review',attemptId:uid(860),requestHash:h('preflight-review'),receiptHash:null});const ctx=context(f,'review'),ref=ctx.evidence.find(e=>e.kind==='searches').ref,ratings=Object.fromEntries(quality.PUBLIC_RESEARCH_DIMENSIONS.map(d=>[d,{score:3,anchorId:`${d}.3`,rationale:'Literal aggregate observations leave candidate demand and exposure unresolved.',evidenceRefs:[ref],contraryRefs:[ref],missingFacts:['Eligible exposure is unknown.']}]))
 const raw={version:'r12.direct-etsy-review.1',proposalHash:s.result.proposalHash,quality:ratings,hypothesisFinding:'undetermined',learningRecommendation:'NME',conclusion:'The descriptive result is concrete but the hypothesis remains unmeasured.',conclusionEvidenceRefs:[ref],contraryEvidenceRefs:[ref],proposedCommand:command('plants comparison',f.state.epochCriteriaHash)};
 const review=await complete(f,'review',raw);assert.equal(review.result.review.outcome,'NME');assert.equal(review.result.review.quality.passed,false);f.state=cycle.completePublicResearchAttempt(f.policy,f.state,review.result.review);assert.equal(f.state.modelDispatchesUsed,3);assert.equal(f.state.sourceOperationsStarted,1);assert.equal(f.state.nextAttemptKind,'targeted');assert.equal(f.state.history.consecutiveNonprogress,3);
 const wire=JSON.parse(review.wire.wire.body);assert.equal(wire.model,'anthropic/claude-haiku-4.5');assert.deepEqual(wire.provider.only,['amazon-bedrock/us']);assert.equal(wire.provider.allow_fallbacks,false);assert.equal('tools'in wire,false);assert.equal('plugins'in wire,false);const text=wire.messages.map(m=>m.content).join('\n');assert.ok(text.includes('2.4k'));assert.ok(text.includes('Last 30 days'));assert.ok(text.includes('untrusted'));for(const privateField of ['Example Store','profileBindingId','providerProjectId','testEnvelopeId','reservationId','screenshotHash','sessionId'])assert.equal(text.includes(privateField),false,privateField);
});
test('source evidence cannot be invented, relabeled private or swapped across scope',async()=>{const{f}=await readyStrategy(),input=mkInput(f,'strategy'),trusted=expect(input);let bad=structuredClone(input);bad.sourcePackets[0].receipt.scopeHash=h('swapped');const{inputHash,...body}=bad;void inputHash;bad=self(body,'inputHash');assert.throws(()=>m.readPublicResearchModelInputs(bad,{...trusted,inputHash:bad.inputHash}));});
test('schema-valid forged source citation is rejected by server normalization',async()=>{const{f,strategy}=await readyStrategy();strategy.assessment.marketComparisons[0].evidence=['invented'];assert.throws(()=>m.normalizePublicResearchStrategy(context(f,'strategy'),strategy),/citation_unverified/);});
test('model context is immutable after authenticated read and unknown phases reject',async()=>{const f=fixture(),ctx=context(f,'plan');ctx.input.profile.publicGoal='Changed after read';assert.throws(()=>m.buildPublicResearchModelRequest(ctx),/untrusted_model_context/);assert.throws(()=>m.publicResearchModelSchema('search'));assert.throws(()=>m.publicResearchModelSchema('select'));});
test('source and history omissions fail despite recomputed self hashes',async()=>{const{f}=await readyStrategy(),i=mkInput(f,'strategy'),e=expect(i);const{inputHash,...body}=i;void inputHash;const bad=self({...body,sourcePackets:[]},'inputHash');assert.throws(()=>m.readPublicResearchModelInputs(bad,{...e,inputHash:bad.inputHash,sourceReceiptHashes:[]}));const altered=structuredClone(i);altered.originHistory.continuity.consecutiveNonprogress=0;assert.throws(()=>m.readPublicResearchModelInputs(altered,e));});
