import test from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {createRequire} from 'node:module';
import {createHash} from 'node:crypto';
const require=createRequire(import.meta.url),ts=require('typescript'),crypto=require('node:crypto');
const id=n=>`dddddddd-dddd-4ddd-8ddd-${String(n).padStart(12,'0')}`,hash=x=>createHash('sha256').update(x).digest('hex');
function load(file,deps,env={}){const m={exports:{}};new Function('require','module','exports','process',ts.transpileModule(readFileSync(file,'utf8'),{compilerOptions:{target:ts.ScriptTarget.ES2022,module:ts.ModuleKind.CommonJS}}).outputText)(name=>{assert.ok(name in deps,`Unknown runtime dependency ${name}`);return deps[name];},m,m.exports,{env});return m.exports;}
function fixture(){
 const effects=[],state={owner:true,claims:true,enrolled:false,claimed:false,launchFailure:false,wrongReply:false},a={id:id(3),business_id:id(2),approval_hash:'a'.repeat(64),snapshot:{focusedPilotBinding:{}}};let capability,nonce;
 const rows={creative_approvals:a,creative_runs:{id:id(4),business_id:id(2),workflow_run_id:id(5)},workflow_runs:{id:id(5),business_id:id(2),goal_id:id(6)}};
 const context={userId:id(1),businesses:[{id:id(2)}],supabase:{auth:{getClaims:async()=>({data:{claims:{sub:state.claims?id(1):id(99)}},error:null})},from:table=>{const filters=[];const q={select:()=>q,eq:(k,v)=>{filters.push([k,v]);return q;},maybeSingle:async()=>({data:rows[table],error:null})};return q;},rpc:async(name,p)=>{effects.push({name,p});if(name==='begin_creative_run'){capability=p.p_runtime_capability;nonce=p.p_launch_nonce;Object.assign(rows.workflow_runs,{runtime_capability_hash:hash(capability),runtime_launch_nonce:nonce});return{data:{creativeRunId:id(4),workflowRunId:id(5),approvalHash:a.approval_hash},error:null};}if(name==='fail_creative_launch')return{data:{},error:null};throw Error(name);}}};
 const runtime={rpc:async(name,p)=>{assert.equal(name,'creative_runtime_transition');assert.equal(p.p_runtime_capability,capability);assert.equal(p.p_operation,'r12_launch_claim');assert.deepEqual(p.p_payload,{});effects.push({name,p});if(!state.enrolled)return{data:null,error:{message:'scope missing'}};const first=!state.claimed;state.claimed=true;return{data:{shouldStart:first,creativeRunId:id(4),workflowRunId:state.wrongReply?id(99):id(5),launchNonce:nonce},error:null};}};
 const api=load('src/creative/focused-owner-server.ts',{'server-only':{},'../lib/core-ui/owner-business':{verifyOwnerBusiness:async()=>state.owner},'../products/discovery-r12-owner':{},'./contracts':require('../.core-tests/creative/contracts.js'),'node:crypto':crypto,'../lib/supabase/runtime':{createRuntimeClient:()=>runtime},'workflow/api':{start:async(_fn,args)=>{effects.push({name:'start',args});if(state.launchFailure)throw Error('lost launch');return{};}},'../workflows/creative-runtime':{creativeRuntimeWorkflow:()=>{}}},{VERCEL_ENV:'production',R05_ADMISSION_SERVER_KEY:'inert-focused-owner-root-that-never-leaves-fixture'});
 return{api,context,state,effects};
}
test('owner preparation recovers stable private run keys without exposing credential values or launching',async()=>{const f=fixture(),first=await f.api.prepareFocusedCreativeRun(f.context,id(3)),second=await f.api.prepareFocusedCreativeRun(f.context,id(3));assert.deepEqual(first,second);assert.equal(first.dispatchAuthorized,false);assert.equal(f.effects.filter(e=>e.name==='start').length,0);const calls=f.effects.filter(e=>e.name==='begin_creative_run');assert.equal(calls[0].p.p_runtime_capability,calls[1].p.p_runtime_capability);assert.equal(JSON.stringify(first).includes(calls[0].p.p_runtime_capability),false);assert.equal(first.runtimeCapabilityHash,hash(calls[0].p.p_runtime_capability));});
test('missing enrollment, mismatched owner/session and wrong scoped claim never launch',async()=>{for(const mode of ['missing','owner','session','claim']){const f=fixture();await f.api.prepareFocusedCreativeRun(f.context,id(3));if(mode==='owner')f.state.owner=false;if(mode==='session')f.state.claims=false;if(mode==='claim'){f.state.enrolled=true;f.state.wrongReply=true;}await assert.rejects(f.api.startFocusedCreativeRun(f.context,id(3)));assert.equal(f.effects.filter(e=>e.name==='start').length,0);}});
test('duplicate Start claims use exactly one durable workflow and ambiguous launch failure never retries',async()=>{const f=fixture();await f.api.prepareFocusedCreativeRun(f.context,id(3));f.state.enrolled=true;assert.equal((await f.api.startFocusedCreativeRun(f.context,id(3))).started,true);assert.equal((await f.api.startFocusedCreativeRun(f.context,id(3))).started,false);assert.equal(f.effects.filter(e=>e.name==='start').length,1);const g=fixture();await g.api.prepareFocusedCreativeRun(g.context,id(3));g.state.enrolled=true;g.state.launchFailure=true;await assert.rejects(g.api.startFocusedCreativeRun(g.context,id(3)),/launch_unconfirmed/);assert.equal(g.effects.filter(e=>e.name==='fail_creative_launch').length,1);assert.equal((await g.api.startFocusedCreativeRun(g.context,id(3))).started,false);assert.equal(g.effects.filter(e=>e.name==='start').length,1);});
