import test from 'node:test';import assert from 'node:assert/strict';
import{loadPublic,uid,h,hash,publicPolicy}from'./r12-public-fixtures.mjs';
const c=await loadPublic('cycle'),{decidePublicResearchDriverAction:decide}=await loadPublic('driver');
function fixture(){const{policy:p,inherited,initial}=publicPolicy();let s=c.createPublicResearchState(p,inherited,initial);const start=()=>{s=c.startPublicResearchAttempt(p,s,{expectedStateHash:s.stateHash,attemptId:uid(900),planAttemptId:uid(901),planRequestHash:h('plan'),executionQuoteHash:h('quote'),executionQuoteProofHash:h('proof'),command:initial,capacity:{approvedWindowHash:hash(p.window),approvedMaximumAttemptsInWindow:p.window.maximumAttemptsInWindow,cumulativeDispatchesCeiling:p.cumulativeDispatchesCeiling,authorityActive:true,stopped:false,expired:false,hasUnknownLiability:false,liveGate:{quoteQualified:true,providerAccessQualified:true,sourcePurposeApproved:true,ownerApprovalBound:true,browserSettlementQualified:true},runCommittedMicrounits:'0',rootHeadroomMicrounits:'10000000',businessHeadroomMicrounits:'10000000',activationAllocationHeadroomMicrounits:'1000000'}});return s;};return{p,s,start};}
test('initial decision schedules only the planner with exact state CAS',()=>{const{p,s}=fixture();assert.deepEqual(decide(p,s),{kind:'schedule',phase:'plan',expectedStateHash:s.stateHash});});
test('pending phase recovers exact attempt rather than scheduling another',()=>{const f=fixture(),s=f.start();assert.deepEqual(decide(f.p,s),{kind:'continue_attempt',phase:'plan',attemptId:uid(901)});});
test('recorded planner advances to first source without a new logical cycle',()=>{const f=fixture(),s=c.recordPublicResearchReceipt(f.p,f.start(),'plan',h('receipt'));assert.deepEqual(decide(f.p,s),{kind:'schedule',phase:'source',expectedStateHash:s.stateHash});assert.equal(s.windowAttemptsStarted,1);});
test('settled technical failure is explicit pause until suffix repair is qualified',()=>{const f=fixture(),s=c.failPublicResearchAttempt(f.p,c.recordPublicResearchReceipt(f.p,f.start(),'plan',h('receipt')),h('failure'));assert.deepEqual(decide(f.p,s),{kind:'pause',reason:'technical_repair_requires_qualified_suffix'});});
test('forged state cannot direct a phase or claim broad Quest completion',()=>{const{p,s}=fixture();for(const patch of[{questComplete:true},{terminal:'RESEARCH_PASSED_SUPPORTS_TEST'},{researchWindowComplete:true},{stateHash:h('forged')}])assert.throws(()=>decide(p,{...s,...patch}));});
