import {repinFundingProof} from './helpers/r12-funding-proof-fixture.mjs';
import test from 'node:test';import assert from 'node:assert/strict';
import {fixture,phase,complete,archive} from './helpers/r12-adaptive-inputs-fixture.mjs';import {id,now} from './helpers/r12-adaptive-fixture.mjs';
import {createDiscoveryR12QuestAdapter,DiscoveryR12ReceiptPending} from '../.core-tests/products/discovery-r12-adapter.js';
import {buildAdaptivePhaseRequest,projectAdaptivePhaseOutput} from '../.core-tests/products/discovery-r12-adaptive-runtime.js';import {projectAdaptivePhaseResponse} from '../.core-tests/products/discovery-r12-adaptive-inputs.js';import {discoveryV2Hash as hash} from '../.core-tests/products/discovery-v2.js';
const original=Date.now;test.before(()=>{Date.now=()=>now;});test.after(()=>{Date.now=original;});
function harness(f,key,output,{deny=false,malformed=false,delay=false,cost=0.00001,responseAt=now,settlementFailure=false}={}){
 const inputs=phase(f,key),ctx=structuredClone(f.ctx),state={binding:null,receipt:{status:'ready'}},events=[],charges=[],posts=[],gets=[];let sent=false,delayed=delay;
 const store={operation:async(_id,op,p)=>{events.push(op);if(op==='load')return structuredClone(state);if(op==='bind'){state.binding=p.binding;return{};}if(op==='send'){if(deny||sent)return{shouldDispatch:false};sent=true;return{shouldDispatch:true};}if(op==='observe'){state.observation=p.observation;state.observationSaved=true;return{};}if(op==='diagnose'){state.diagnostic=p.diagnostic;return{};}if(op==='stage'){state.candidate=p.candidate;state.dispatchedAt=new Date(now-1000).toISOString();state.receipt={status:'awaiting_receipt',requestId:ctx.attempt.requestId,candidateHash:hash(p.candidate),attempts:0,nextCheckAt:null,receiptExpiresAt:new Date(Math.min(Date.parse(ctx.plan.expiresAt)+1800000,now-1000+3600000)).toISOString(),proofHash:null};return{};}if(op==='claim')return{claimed:true,claimId:id(800)};if(op==='record'){if(p.proof)state.proof=p.proof;return{};}throw Error(op);},settle:async(_id,s)=>{charges.push(s);if(settlementFailure){settlementFailure=false;throw Error("quest_controller_transition_unverified");}},dispatchedAt:async()=>new Date(now-1000).toISOString()};
 const reviewer=key==='review',model=reviewer?'anthropic/claude-4.5-haiku-20251001':'openai/gpt-5.6-luna-20260709',gen=`gen-adapter-${key}`;
 const fetcher=async(url,init)=>{if(init.method==='GET'){gets.push(url);assert.ok(state.candidate);if(delayed)return new Response(JSON.stringify({error:{message:'Index delay'}}),{status:404});return new Response(JSON.stringify({data:{id:gen,provider_name:reviewer?'Amazon Bedrock':'Azure',model}}),{status:200});}assert.equal(init.method,'POST');assert.equal(sent,true);const body=JSON.parse(init.body);posts.push(body);assert.deepEqual(body.provider.only,[reviewer?'amazon-bedrock/us':'azure/us']);const message=key==='search1'?{content:'Synthetic public context',annotations:output.annotations}:{content:malformed?'not valid JSON':JSON.stringify(output)};return new Response(JSON.stringify({id:gen,model,choices:[{finish_reason:'stop',message}],usage:{prompt_tokens:100,completion_tokens:50,total_tokens:150,cost,...(key==='search1'?{server_tool_use_details:{web_search_requests:1}}:{})}}),{status:200});};
 const adapter=createDiscoveryR12QuestAdapter({scope:f.raw.scope,adaptivePreview:f.raw.preview,adaptiveFundingProof:f.raw.fundingProof,phase:key,identity:{qualificationHash:ctx.step.qualificationHash,workflowDefinitionId:ctx.step.workflowDefinitionId,workerDefinitionId:ctx.step.workerDefinitionId,mode:'qualification'},dataClasses:['public_research'],store,request:async()=>buildAdaptivePhaseRequest(inputs,inputs.validationAt),quote:async()=>f.quote,project:async(q,c,r)=>projectAdaptivePhaseResponse(c,inputs,q,r),config:{apiKey:'inert-adaptive-tests-only',baseUrl:'https://openrouter.ai/api/v1',appUrl:'https://agent-labs-two.vercel.app',appName:'Agent Labs'},fetcher,now:()=>responseAt});
 return{adapter,ctx,state,events,charges,posts,gets,inputs,release:()=>{delayed=false;},prepare:async()=>{const first=await adapter.prepare(ctx);ctx.attempt.requestId=id(500+f.ctx.plan.steps.indexOf(f.ctx.step));ctx.attempt.wireHash=first.descriptor.wireRequestHash;ctx.attempt.status='reserved';return adapter.prepare(ctx);}};
}
function append(f,h,result){const {candidate,proof,binding:b}=h.state,response={...result,planHash:f.raw.planHash,inputHash:h.ctx.attempt.inputHash};delete response.settlement;const binding={scopeId:b.scopeId,attemptId:b.attemptId,requestId:b.requestId,phase:b.phase,request:JSON.parse(b.requestJson),maximumMicrousd:Number(h.charges[0]?.actualMicrounits??1000000)+1000000,dispatchedAt:new Date(now-1000).toISOString(),receiptExpiresAt:new Date(now+60000).toISOString()};binding.maximumMicrousd=f.quote.ceilings[h.inputs.phase];f.raw.dependencies.push({stepKey:b.phase,attemptId:b.attemptId,artifactId:id(300+f.ctx.plan.steps.indexOf(f.ctx.step)),responseHash:hash(response),responseCanonicalHash:hash(response),response,binding,candidate,proof,origin:{planHash:f.raw.planHash,scopeId:f.raw.scope.id,scopeHash:hash(f.raw.scope),intentId:f.raw.intent.id,actionHash:f.raw.actionHash,actionOrdinal:0},intentPins:structuredClone(f.raw.intentPins)});}
test('actual adapter completes five scoped phases with per-phase liabilities, four Luna calls and one Haiku call',async()=>{const f=fixture(),models=[],searches=[];for(const key of ['plan','search1','select1','strategy','review']){if(key==='strategy')archive(f);let output=key==='strategy'?{assessment:f.outputs.strategy,measurement:null}:f.outputs[key];if(key==='review'){const c=phase(f,key);output={version:'r12.adaptive-review.1',proposalHash:c.strategy.proposalHash,outcome:'NEEDS_MORE_EVIDENCE',ratings:Object.fromEntries(['evidence','learningValue','testDesign','feasibility'].map(k=>[k,{score:0,rationale:'The existing evidence does not support a bounded measurable proposal.',evidenceRefs:[]}])),proposalConcerns:[],executionPrerequisites:[],additionalQuestions:[],sufficiencyRationale:'No candidate-specific measurable experiment has been established.'};}const h=harness(f,key,output),call=await h.prepare();assert.equal(call.descriptor.liabilityMicrounits,String(f.quote.ceilings[h.inputs.phase]));assert.notEqual(call.descriptor.liabilityMicrounits,'10000000');assert.equal(h.state.binding.version,'r12.adaptive-wire.1');assert.equal(h.state.binding.actionHash,f.raw.actionHash);const wire=JSON.parse(call.wire.body);if(key==='strategy')assert.deepEqual(wire.response_format.json_schema.schema.required,['assessment','measurement']);if(key==='review')assert.ok(wire.response_format.json_schema.schema.required.includes('ratings'));const result=await h.adapter.dispatch(call,h.ctx);assert.equal(h.posts.length,1);assert.equal(h.charges[0].actualMicrounits,'10');assert.ok(h.state.observationSaved);models.push(h.posts[0].model);if(key==='search1')searches.push(h.posts[0]);if(key==='review'){assert.equal(result.result.outcome,'NEEDS_MORE_EVIDENCE');assert.equal(result.result.review.executionAuthorized,false);}append(f,h,result);}assert.deepEqual(models,['openai/gpt-5.6-luna','openai/gpt-5.6-luna','openai/gpt-5.6-luna','openai/gpt-5.6-luna','anthropic/claude-haiku-4.5']);assert.equal(searches.length,1);assert.deepEqual(searches[0].tools[0].parameters.allowed_domains,f.raw.scope.allowedDomains);});
test('known paid format failure retains private response and charge without staging a candidate or resending',async()=>{const f=fixture(),h=harness(f,'plan',f.outputs.plan,{malformed:true}),call=await h.prepare();await assert.rejects(h.adapter.dispatch(call,h.ctx));assert.equal(h.posts.length,1);assert.equal(h.charges[0].actualMicrounits,'10');assert.ok(h.state.observationSaved);assert.ok(h.state.diagnostic);assert.equal(h.state.candidate,undefined);assert.equal((await h.adapter.reconcile(h.ctx)).status,'unknown');assert.equal(h.posts.length,1);});
test('stopped or duplicate send denial prevents transport',async()=>{const f=fixture(),h=harness(f,'plan',f.outputs.plan,{deny:true}),call=await h.prepare();await assert.rejects(h.adapter.dispatch(call,h.ctx));assert.equal(h.posts.length,0);assert.equal(h.charges.length,0);const other=harness(f,'plan',f.outputs.plan),otherCall=await other.prepare();await other.adapter.dispatch(otherCall,other.ctx);await assert.rejects(other.adapter.dispatch(otherCall,other.ctx));assert.equal(other.posts.length,1);});
test('receipt indexing delay resumes readback only and never repeats a paid generation',async()=>{const f=fixture(),h=harness(f,'plan',f.outputs.plan,{delay:true}),call=await h.prepare();await assert.rejects(h.adapter.dispatch(call,h.ctx),DiscoveryR12ReceiptPending);assert.equal(h.posts.length,1);assert.equal(h.charges[0].actualMicrounits,'10');h.release();const r=await h.adapter.reconcile(h.ctx);assert.equal(r.status,'found');assert.equal(h.posts.length,1);assert.equal(h.gets.length,2);});
test('wire load rejects a substituted adaptive action, phase or dependencies before transport',async()=>{for(const change of[h=>h.state.binding.actionHash='0'.repeat(64),h=>h.state.binding.actionOrdinal=1,h=>h.state.binding.phase='review',h=>h.state.binding.dependencyPins=[{stepKey:'plan',attemptId:id(999),resultHash:'a'.repeat(64)}]]){const f=fixture(),h=harness(f,'plan',f.outputs.plan),call=await h.prepare();change(h);await assert.rejects(h.adapter.dispatch(call,h.ctx));assert.equal(h.posts.length,0);}});

test('database quote key reordering preserves exact admitted wire bytes and one transport',async()=>{
 const f=fixture(),h=harness(f,'plan',f.outputs.plan),call=await h.prepare(),savedWire=h.state.binding.wireBody;
 for(const route of [h.state.binding.quote.luna,h.state.binding.quote.reviewer]) {
  const p=route.priceLimit;route.priceLimit={request:p.request,prompt:p.prompt,completion:p.completion};
 }
 assert.equal(hash(h.state.binding.quote),hash(f.quote));
 const loaded=await h.adapter.prepare(h.ctx);
 assert.equal(loaded.wire.body,savedWire);assert.equal(loaded.descriptor.wireRequestHash,call.descriptor.wireRequestHash);
 assert.equal((await h.adapter.dispatch(loaded,h.ctx)).outcome,'accepted');
 assert.equal(h.posts.length,1);assert.equal(h.state.binding.wireBody,savedWire);
});

test('cost above the quoted phase ceiling is retained as actual charge but cannot become a qualified candidate',async()=>{const f=fixture(),h=harness(f,'plan',f.outputs.plan,{cost:0.5}),call=await h.prepare();await assert.rejects(h.adapter.dispatch(call,h.ctx));assert.equal(h.posts.length,1);assert.equal(h.charges[0].actualMicrounits,'500000');assert.ok(h.state.diagnostic);assert.equal(h.state.candidate,undefined);});

function expiresSoon(f){const expiry=new Date(now+1000).toISOString();f.raw.preview.expiresAt=expiry;f.raw.scope.expiresAt=expiry;f.raw.scope.intent.expiresAt=expiry;f.raw.intent.expiresAt=expiry;f.ctx.plan.expiresAt=expiry;f.ctx.plan.deadline=expiry;for(const step of f.ctx.plan.steps)step.expiresAt=expiry;f.ctx.plan.discoveryScopeHash=hash(f.raw.scope);f.raw.action.scopeHash=hash(f.raw.scope);f.raw.actionHash=hash(f.raw.action);f.raw.intentPins.scopeHash=hash(f.raw.scope);f.raw.intentPins.actionHash=f.raw.actionHash;f.ctx.attempt.adaptiveActionHash=f.raw.actionHash;f.raw.planHash=hash(f.ctx.plan);f.ctx.planHash=f.raw.planHash;f.raw.fundingProof=repinFundingProof(f.raw.fundingProof,f.raw.scope);}
test('paid response after authority expiry projects with frozen request clock inside existing receipt window',async()=>{const f=fixture();expiresSoon(f);const h=harness(f,'plan',f.outputs.plan,{responseAt:now+2000}),call=await h.prepare();const result=await h.adapter.dispatch(call,h.ctx);assert.equal(result.outcome,'accepted');assert.equal(h.state.candidate.receivedAt,new Date(now+2000).toISOString());assert.ok(Date.parse(h.state.candidate.receivedAt)>Date.parse(f.raw.scope.expiresAt));assert.equal(h.inputs.validationAt,now);assert.equal(h.posts.length,1);assert.equal(h.charges[0].actualMicrounits,'10');assert.equal((await h.adapter.reconcile(h.ctx)).status,'found');assert.equal(h.posts.length,1);});
test('late search observation retains actual response time rather than backdating to request validation',async()=>{const f=fixture();expiresSoon(f);complete(f,'plan',f.outputs.plan);const h=harness(f,'search1',f.outputs.search1,{responseAt:now+2000}),call=await h.prepare();const result=await h.adapter.dispatch(call,h.ctx);assert.equal(result.outcome,'accepted');assert.equal(h.state.candidate.receivedAt,new Date(now+2000).toISOString());const execution={modelId:'openai/gpt-5.6-luna',providerRequestId:h.state.candidate.providerRequestId,primaryOnly:true,qualifiedRoute:h.state.proof};assert.equal(result.result.collectionHash,hash(projectAdaptivePhaseOutput(h.inputs,f.outputs.search1,execution,now,now+2000)));assert.notEqual(result.result.collectionHash,hash(projectAdaptivePhaseOutput(h.inputs,f.outputs.search1,execution,now,now)));assert.equal(h.posts.length,1);assert.equal(h.charges[0].actualMicrounits,'10');});


test('frozen request clock does not extend the existing late-receipt window',async()=>{const f=fixture();expiresSoon(f);const h=harness(f,'plan',f.outputs.plan,{responseAt:now+1802000});// Reserve with the original fresh quote; only response arrival is late.
 const early=harness(f,'plan',f.outputs.plan),call=await early.prepare();h.state.binding=structuredClone(early.state.binding);h.ctx.attempt=structuredClone(early.ctx.attempt);await assert.rejects(h.adapter.dispatch(call,h.ctx));assert.equal(h.posts.length,1);assert.equal(h.charges[0].actualMicrounits,'10');assert.equal(h.state.candidate,undefined);});


import {validateAdaptiveReceiptResume} from '../.core-tests/products/discovery-r12-adaptive-receipt-recovery.js';
test('expired settlement lease after durable candidate recovers by receipt readback without a second POST',async()=>{const f=fixture(),h=harness(f,'plan',f.outputs.plan,{settlementFailure:true}),call=await h.prepare();await assert.rejects(h.adapter.dispatch(call,h.ctx),/quest_controller_transition_unverified/);assert.ok(h.state.candidate);assert.equal(h.state.proof,undefined);assert.equal(h.gets.length,0);h.ctx.attempt.status='dispatched';const recovery=await validateAdaptiveReceiptResume({context:h.ctx,expectedPlanId:h.ctx.planId,expectedPlanHash:h.ctx.planHash,scope:f.raw.scope,preview:f.raw.preview,fundingProof:f.raw.fundingProof,approvedQuote:f.quote,action:{actionHash:f.raw.actionHash,ordinal:0,phaseKeys:['plan','search1','select1','strategy','review'],attemptIds:[h.ctx.attempt.id],reused:[]},saved:h.state,now});assert.equal(recovery.mode,'receipt_lookup_only');assert.equal(recovery.authorityCreated,false);assert.equal((await h.adapter.reconcile(h.ctx)).status,'found');assert.equal(h.posts.length,1);assert.equal(h.gets.length,1);});
