import test from 'node:test';
import assert from 'node:assert/strict';
import {ADAPTIVE_REVIEW_VERSION as version, adaptiveReviewerResponseSchema, normalizeAdaptiveReviewerResponse as normalize, adaptiveEvidenceIdentity} from '../.core-tests/products/discovery-r12-adaptive-review-contract.js';
const plan=()=>({hypothesis:'A bounded private comparison can distinguish two original layout approaches.',deliverable:'A private comparison report with named observations',positiveCriterion:'At least one layout meets every predefined legibility check',negativeCriterion:'Neither layout meets the predefined legibility checks',inconclusiveCriterion:'The observations cannot distinguish the predefined outcomes',observationWindow:'One bounded observation session before the approved expiry',stopRule:'Stop after the approved observations; no automatic repairs',evidenceRefs:['E1']});
const context=()=>({proposalHash:'a'.repeat(64),proposedTest:plan(),allowedEvidenceRefs:['E1'],currentInputRefs:['input:1'],missingProposalRequirements:[],inheritedQuestions:['Would anyone buy the eventual product?'],producerModelId:'producer:canonical',reviewerModelId:'reviewer:canonical'});
const response=()=>({version,proposalHash:'a'.repeat(64),outcome:'TEST',ratings:Object.fromEntries(['evidence','learningValue','testDesign','feasibility'].map(k=>[k,{score:k==='evidence'||k==='feasibility'?1:2,rationale:'The cited observation supports this exact bounded learning question.',evidenceRefs:['E1']}])),proposalConcerns:[],executionPrerequisites:['Separate owner approval before any creative execution'],additionalQuestions:[],sufficiencyRationale:'This synthetic held-out proposal supports only the bounded observation and preserves commercial unknowns.'});
test('TEST attaches exact strategist plan, with no execution authority',()=>{const c=context();const r=normalize(response(),c);assert.deepEqual(r.testPlan,c.proposedTest);assert.equal(r.total,6);assert.equal(r.executionAuthorized,false);assert.equal(r.thresholdCalibrated,false);assert.deepEqual(r.inheritedQuestions,c.inheritedQuestions);});
test('high self-score cannot create absent experiment or ignore material omissions',()=>{const r=response();for(const x of Object.values(r.ratings))x.score=2;for(const c of [{...context(),proposedTest:null},{...context(),missingProposalRequirements:['source_permission']}]){const result=normalize(r,c);assert.equal(result.outcome,'NEEDS_MORE_EVIDENCE');assert.equal(result.modelOutcome,'TEST');assert.deepEqual(result.disagreements,['model_test_not_supported']);}r.outcome='NEEDS_MORE_EVIDENCE';assert.equal(normalize(r,{...context(),proposedTest:null}).outcome,'NEEDS_MORE_EVIDENCE');});
test('unknown evidence, proposal substitution and same-model review fail',()=>{for(const change of [c=>c.allowedEvidenceRefs=[],c=>c.proposalHash='b'.repeat(64),c=>c.reviewerModelId=c.producerModelId]){const c=context();change(c);assert.throws(()=>normalize(response(),c));}});
test('all bounded plan fields and distinct observable outcomes are required',()=>{for(const key of Object.keys(plan())){const c=context();delete c.proposedTest[key];assert.throws(()=>normalize(response(),c));}const c=context();c.proposedTest.negativeCriterion=c.proposedTest.positiveCriterion;assert.throws(()=>normalize(response(),c));});
test('schema rejects extra keys, excess arrays, long reasons and invalid scores',()=>{for(const change of [r=>r.authorizeSpend=true,r=>r.additionalQuestions=Array.from({length:13},(_,i)=>`A genuinely distinct research question number ${i}?`),r=>r.ratings.evidence.rationale='x'.repeat(301),r=>r.ratings.evidence.score=3]){const r=response();change(r);assert.throws(()=>normalize(r,context()));}});
test('nonexistent future artwork cannot be named as a present input blocker',()=>{const r=response();r.outcome='NEEDS_MORE_EVIDENCE';r.proposalConcerns=[{severity:'uncertainty',affectedInputRef:'future:artwork',missingRequirement:null,rationale:'No future artwork exists, so its rights cannot yet be inspected.',evidenceRefs:[]}];assert.throws(()=>normalize(r,context()));r.proposalConcerns[0].affectedInputRef=null;r.proposalConcerns[0].missingRequirement='commercial_clearance';assert.throws(()=>normalize(r,context()));});
test('actual identified forbidden input can yield REJECT with evidence',()=>{const r=response();r.outcome='REJECT';r.proposalConcerns=[{severity:'known_failure',affectedInputRef:'input:1',missingRequirement:null,rationale:'The identified supplied input violates the exact prohibited-input rule.',evidenceRefs:['E1']}];assert.equal(normalize(r,context()).outcome,'REJECT');r.proposalConcerns[0].evidenceRefs=[];assert.throws(()=>normalize(r,context()));});
test('redundant questions are preserved raw but deduplicated in derived additions',()=>{const r=response();r.additionalQuestions=['  Would anyone buy the eventual product?  ','Which distinct observed input needs checking?','Which distinct observed input needs checking?'];const result=normalize(r,context());assert.equal(result.redundantQuestionCount,2);assert.deepEqual(result.additionalQuestions,['Which distinct observed input needs checking?']);assert.deepEqual(result.rawResponse,r);assert.deepEqual(result.inheritedQuestions,context().inheritedQuestions);});
test('unsupported rejection is retained as disagreement and conservatively yields NME',()=>{const r=response();r.outcome='REJECT';const result=normalize(r,context());assert.equal(result.outcome,'NEEDS_MORE_EVIDENCE');assert.equal(result.modelOutcome,'REJECT');assert.deepEqual(result.disagreements,['model_reject_not_supported']);assert.deepEqual(result.rawResponse,r);});
test('independent reviewer may decline otherwise eligible proposal',()=>{const r=response();r.outcome='NEEDS_MORE_EVIDENCE';assert.equal(normalize(r,context()).testPlan,null);});
test('provider grammar contains no actual private proposal or evidence IDs',()=>{const schema=JSON.stringify(adaptiveReviewerResponseSchema());assert.equal(schema.includes('a'.repeat(64)),false);assert.equal(schema.includes('E1'),false);assert.equal(schema.includes('input:1'),false);});
const nextAction=kind=>({kind,publicQuestion:'Which dated observation could distinguish the remaining candidate hypothesis?',hypothesis:'A bounded observation can resolve the named remaining uncertainty.',expectedInformationGain:'The result would eliminate or narrow one specific candidate assumption.',counterevidenceQuestion:'Which observation would refute the current preferred explanation?',gap:kind==='pivot'?'hypothesis':'evidence',reason:'The named evidence gap remains material and the bounded action could change the decision.'});
test('negative supported rejection can propose a pivot without completing the goal',()=>{const r=response();r.outcome='REJECT';r.proposalConcerns=[{severity:'known_failure',affectedInputRef:'input:1',missingRequirement:null,rationale:'The supplied input conflicts with the exact forbidden input requirement.',evidenceRefs:['E1']}];r.recommendedNextAction=nextAction('pivot');const v=normalize(r,context());assert.equal(v.outcome,'REJECT');assert.equal(v.recommendedNextAction.kind,'pivot');assert.equal(v.nextActionStatus,'requires_scope_and_atomic_admission');});
test('NME proposes a targeted follow-up; absent next action pauses honestly',()=>{const r=response();r.outcome='NEEDS_MORE_EVIDENCE';r.recommendedNextAction=nextAction('followup');assert.equal(normalize(r,context()).recommendedNextAction.kind,'followup');delete r.recommendedNextAction;assert.equal(normalize(r,context()).nextActionStatus,'pause_no_reviewed_action');});
test('model may not label NME a repair to poll for a favorable outcome',()=>{const r=response();r.outcome='NEEDS_MORE_EVIDENCE';r.recommendedNextAction=nextAction('repair');assert.throws(()=>normalize(r,context()));});
test('progress requires exact prior finding and stable evidence identity, not changing E labels',()=>{const c=context();c.priorFindings=[{questionId:'q1',findingHash:'b'.repeat(64),statement:'The existing observation leaves this hypothesis unresolved.',evidenceIdentityHashes:['c'.repeat(64)]}];c.evidenceIdentityHashes={E1:'c'.repeat(64)};const r=response();r.progress={questionId:'q1',priorFindingHash:'b'.repeat(64),kind:'refuted',finding:'New phrasing claims that the existing observation refutes this hypothesis.',evidenceRefs:['E1'],opposingInterpretation:'The observation could instead be incomplete and may not refute the claim.'};assert.equal(normalize(r,c).progress.kind,'unchanged');c.evidenceIdentityHashes.E1='d'.repeat(64);assert.equal(normalize(r,c).progress.kind,'refuted');r.progress.priorFindingHash='e'.repeat(64);assert.throws(()=>normalize(r,c));});
test('unchanged finding never resets stagnation despite new evidence or claimed progress',()=>{const c=context();c.priorFindings=[{questionId:'q1',findingHash:'b'.repeat(64),statement:'The existing observation leaves this hypothesis unresolved.',evidenceIdentityHashes:[]}];c.evidenceIdentityHashes={E1:'d'.repeat(64)};const r=response();r.progress={questionId:'q1',priorFindingHash:'b'.repeat(64),kind:'resolved',finding:c.priorFindings[0].statement,evidenceRefs:['E1'],opposingInterpretation:'The observation remains incomplete and cannot distinguish the alternatives.'};const v=normalize(r,c);assert.equal(v.progress.kind,'unchanged');assert.equal(v.progress.afterFindingHash,'b'.repeat(64));});

test('recollected source/span cannot reset stagnation by changing artifact or evidence identity',()=>{
 const old={quote:'The public survey describes nature interest, without candidate-specific purchase evidence.',artifactId:'old-artifact',evidenceId:'old-evidence',sourceId:'src-original',sourceContentHash:'c'.repeat(64),start:10,end:80};
 const recollected={...old,artifactId:'new-artifact',evidenceId:'new-local-label',sourceId:'src-mirror',sourceContentHash:'d'.repeat(64),start:100,end:170};
 const previous=adaptiveEvidenceIdentity(old),current=adaptiveEvidenceIdentity(recollected);
 assert.equal(current,previous);
 const c=context();c.priorFindings=[{questionId:'q1',findingHash:'b'.repeat(64),statement:'The existing excerpt leaves buyer demand unknown.',evidenceIdentityHashes:[previous]}];c.evidenceIdentityHashes={E1:current};
 const r=response();r.progress={questionId:'q1',priorFindingHash:'b'.repeat(64),kind:'narrowed',finding:'Rephrasing this repeated excerpt now claims buyer demand is narrower.',evidenceRefs:['E1'],opposingInterpretation:'The same contextual excerpt still supplies no candidate-specific purchase evidence.'};
 assert.equal(normalize(r,c).progress.kind,'unchanged');assert.equal(normalize(r,c).progress.newEvidence,false);
 assert.equal(adaptiveEvidenceIdentity({quote:'  The public survey\tdescribes nature interest,\nwithout candidate-specific purchase evidence.  '}),previous);
 assert.equal(adaptiveEvidenceIdentity({quote:'Caf\u00e9 visits are reported.'}),adaptiveEvidenceIdentity({quote:'Cafe\u0301 visits are reported.'}));
 assert.notEqual(adaptiveEvidenceIdentity({quote:'Observed purchases declined in the measured candidate-specific trial.'}),previous);
});

import {proposeMissingRecommendationDiagnostic as diagnostic} from '../.core-tests/products/discovery-r12-adaptive-policy.js';
function diagnosticInput(review){return{scopeId:'12080000-0000-4000-8000-000000000040',originReviewHash:'f'.repeat(64),review,usedGapHashes:[],capacity:{extraActionsUsed:0,childrenUsed:24,dispatchesUsed:22,createdPhaseSlots:['plan','search','select','strategy','review'],runCommittedMicrousd:1000,rootHeadroomMicrousd:9999000,businessHeadroomMicrousd:9999000,hasUnknownLiability:false,authorityActive:true,expired:false},phaseCeilings:{strategy:82891,review:265303}};}
test('raw omitted NME recommendation permits one diagnostic and remains immutable',()=>{const raw=response();raw.outcome='NEEDS_MORE_EVIDENCE';raw.additionalQuestions=['Which dated observation distinguishes buying behavior from motif preference?'];const saved=structuredClone(raw),review=normalize(raw,context()),input=diagnosticInput(review),first=diagnostic(input);assert.equal(first.decision,'requires_atomic_admission');assert.deepEqual(first.phases,['strategy','review']);assert.equal(first.admission.paidCalls+first.admission.reservedDownstreamCalls,2);assert.equal(first.extraActionIncrement,1);assert.equal(first.progressCounts,false);assert.equal(first.authorityCreated,false);assert.equal(review.recommendedNextAction,null);assert.equal(review.outcome,'NEEDS_MORE_EVIDENCE');assert.deepEqual(review.rawResponse,saved);assert.equal(Object.hasOwn(review.rawResponse,'recommendedNextAction'),false);input.usedGapHashes=[first.gapHash];input.originReviewHash='e'.repeat(64);assert.equal(diagnostic(input).reason,'diagnostic_already_used');});
test('gap hash ignores question order, ASCII case and whitespace',()=>{const review={outcome:'NEEDS_MORE_EVIDENCE',rawResponse:{},inheritedQuestions:['Which observation would refute demand?'],additionalQuestions:['Which source gives a denominator?']};const first=diagnostic(diagnosticInput(review));const input=diagnosticInput({...review,inheritedQuestions:['  WHICH source gives a denominator? '],additionalQuestions:['Which\tobservation would refute demand?']});input.usedGapHashes=[first.gapHash];assert.equal(diagnostic(input).reason,'diagnostic_already_used');});
test('diagnostic preserves explicit null and financial, call and action limits',()=>{const base={outcome:'NEEDS_MORE_EVIDENCE',rawResponse:{},inheritedQuestions:['Which observation would refute demand?'],additionalQuestions:[]};for(const review of[{...base,rawResponse:{recommendedNextAction:null}},{...base,inheritedQuestions:[]},{...base,outcome:'REJECT'}])assert.equal(diagnostic(diagnosticInput(review)).decision,'no_diagnostic');for(const change of[c=>c.extraActionsUsed=10,c=>c.dispatchesUsed=63,c=>c.hasUnknownLiability=true,c=>c.runCommittedMicrousd=9999999]){const input=diagnosticInput(base);change(input.capacity);assert.equal(diagnostic(input).decision,'pause');}});
