import test from 'node:test';import assert from 'node:assert/strict';import {createRequire}from'node:module';import{resolve}from'node:path';
import{directSonnetCatalogFixture}from'./helpers/r12-direct-sonnet-catalog-fixture.mjs';
const require=createRequire(import.meta.url),core=resolve(process.env.R12_PUBLIC_CORE_DIR||'.core-tests');
const q=require(resolve(core,'products/discovery-r12-public-reviewer-quote.js')),p=require(resolve(core,'products/discovery-r12-public-preparation.js')),a=require(resolve(core,'products/discovery-r12-adaptive-quote.js')),legacy=require(resolve(core,'products/discovery-r12-quote.js')),{publicResearchHash:hash}=require(resolve(core,'products/discovery-r12-public-utils.js'));
const T=Date.parse('2026-10-10T12:00:00.000Z'),H=x=>hash(x),self=(v,k)=>({...v,[k]:hash(v)});
function browser(){return self({version:'r12.public-browser-quote.1',provider:'steel',category:'browser',providerProjectId:'00000000-0000-4000-8000-000000000001',zeroCostQualificationHash:null,routeHash:H('route'),priceEvidenceHash:H('price'),settlementContractHash:H('settlement'),tariffHash:H('tariff'),qualificationHash:H('qualified'),maximumMicrounits:'25000',verifiedAt:new Date(T-1000).toISOString(),validUntil:new Date(T+299000).toISOString(),qualified:true,retentionDisclosure:'Synthetic independently reviewed retained private aggregate browser capture.'},'browserQuoteHash');}
function fresh(){return q.qualifyDirectSonnetInferenceQuote(directSonnetCatalogFixture(T),T);}
test('direct quote.3 binds exact Sonnet alias/canonical Bedrock US and leaves legacy reviewer untouched',()=>{const x=fresh(),z=p.qualifyPublicResearchSonnetQuote(x,browser(),'10000000',T,10);assert.equal(x.version,'r12.direct-inference-quote.1');assert.equal(z.version,'r12.public-research-quote.3');assert.equal(x.reviewer.modelId,'anthropic/claude-sonnet-4.6');assert.equal(x.reviewer.canonicalModelId,'anthropic/claude-4.6-sonnet-20260217');assert.equal(x.reviewer.endpoint,'amazon-bedrock/us');assert.equal(legacy.DISCOVERY_R12_REVIEWER.modelId,'anthropic/claude-haiku-4.5');assert.throws(()=>a.validateAdaptiveResearchQuote(x,T));assert.deepEqual(p.validatePublicResearchQuote(z,T),z);assert.equal(x.maximumExtraActions,undefined);assert.equal(x.retention.sourceAcquisition,'separately_quoted_browser');assert.equal(z.dispatchAuthorized,false);});
test('exact conservative worst cache-write addition reproduces reviewed ten-cycle upper bound',()=>{const x=fresh(),z=p.qualifyPublicResearchSonnetQuote(x,browser(),'10000000',T,10);assert.equal(x.reviewer.tokenPricesUsd.cacheWrite,'0.0000066');assert.deepEqual(x.ceilings,{plan:43521,strategy:82891,review:795908});assert.equal(BigInt(z.maximumWindowMicrounits)+BigInt(50000),BigInt(9523200));assert.equal(z.originalRunMaximumMicrounits,'10000000');assert.ok(Number(z.maximumWindowMicrounits)<10000000);});
test('quote.3 exact two-dollar model ceiling is valid at N1 and N10 without granting window spend',()=>{
 const c=directSonnetCatalogFixture(T);for(const row of [c.reviewerAlias.payload.data.endpoints[0],c.reviewerCanonical.payload.data.endpoints[0],c.zdr.payload.data[1]])row.pricing={prompt:'0.00001',completion:'0.00031568',input_cache_read:'0',input_cache_write:'0'};
 const x=q.qualifyDirectSonnetInferenceQuote(c,T);assert.equal(x.ceilings.review,2000000);assert.deepEqual(q.validateDirectSonnetInferenceQuote(x,T),x);
 const one=p.qualifyPublicResearchSonnetQuote(x,browser(),'10000000',T,1);assert.equal(one.phaseMaximumMicrounits.review,'2000000');assert.deepEqual(p.validatePublicResearchQuote(one,T),one);
 const ten=p.qualifyPublicResearchSonnetQuote(x,browser(),'10000000',T,10);assert.deepEqual(p.validatePublicResearchQuote(ten,T),ten);assert.equal(ten.phaseMaximumMicrounits.review,'2000000');assert.equal(ten.originalRunMaximumMicrounits,'10000000');assert.ok(BigInt(ten.maximumWindowMicrounits)>BigInt(ten.originalRunMaximumMicrounits));assert.equal(ten.proposalOnly,true);assert.equal(ten.dispatchAuthorized,false);
 assert.doesNotThrow(()=>p.qualifyPublicResearchSonnetQuote(fresh(),browser(),'10000000',T,10));
});
test('one microunit above the model receipt ceiling fails before an N1 or N10 quote can be prepared',()=>{
 const c=directSonnetCatalogFixture(T);for(const row of [c.reviewerAlias.payload.data.endpoints[0],c.reviewerCanonical.payload.data.endpoints[0],c.zdr.payload.data[1]])row.pricing={prompt:'0.00001',completion:'0.00031568025',input_cache_read:'0',input_cache_write:'0'};
 const{quoteTextTokenCost}=require(resolve(core,'research/qualification-quote.js'));
 assert.equal(quoteTextTokenCost({prompt:'0.00001',completion:'0.00031568025',cacheRead:'0',cacheWrite:'0',reasoning:'0'},73728,4000),2000001);
 for(const count of [1,10])assert.throws(()=>p.qualifyPublicResearchSonnetQuote(q.qualifyDirectSonnetInferenceQuote(c,T),browser(),'10000000',T,count));
});
for(const[name,mutate]of[
 ['wrong canonical identity',c=>c.models.payload.data[1].canonical_slug='anthropic/other'],['wrong model detail URL',c=>c.models.payload.data[1].links.details='/api/v1/other'],['duplicate identity',c=>c.models.payload.data.push(c.models.payload.data[1])],['wrong endpoint URL',c=>c.reviewerCanonical.url+='?alternate=1'],['unhealthy alias',c=>c.reviewerAlias.payload.data.endpoints[0].status=-2],['nonmatching canonical price',c=>c.reviewerCanonical.payload.data.endpoints[0].pricing.prompt='0.0000034'],['missing exact ZDR endpoint',c=>c.zdr.payload.data.pop()],['duplicate ZDR endpoint',c=>c.zdr.payload.data.push(c.zdr.payload.data[1])],['global Bedrock fallback',c=>c.reviewerAlias.payload.data.endpoints[0].tag='amazon-bedrock'],['wrong provider',c=>c.reviewerAlias.payload.data.endpoints[0].provider_name='Anthropic'],['structured output missing',c=>c.reviewerAlias.payload.data.endpoints[0].supported_parameters=['max_tokens']],['insufficient context',c=>c.reviewerAlias.payload.data.endpoints[0].context_length=65536],['insufficient output',c=>c.reviewerAlias.payload.data.endpoints[0].max_completion_tokens=1],['prompt capacity missing',c=>c.reviewerAlias.payload.data.endpoints[0].max_prompt_tokens=1],['duplicate parameters',c=>c.reviewerAlias.payload.data.endpoints[0].supported_parameters.push('max_tokens')],['stale observation',c=>c.zdr.fetchedAt=new Date(T-300000).toISOString()],['future observation',c=>c.models.fetchedAt=new Date(T+1).toISOString()],['unexplained charge',c=>c.reviewerAlias.payload.data.endpoints[0].pricing.image='0.001'],['discount invention',c=>c.reviewerAlias.payload.data.endpoints[0].pricing.discount=0.5],['nonzero request fee',c=>c.reviewerAlias.payload.data.endpoints[0].pricing.request='0.000001']
])test(`direct catalog rejects ${name}`,()=>{const c=directSonnetCatalogFixture(T);mutate(c);assert.throws(()=>q.qualifyDirectSonnetInferenceQuote(c,T));});
for(const[name,mutate]of[
 ['unknown version',x=>x.version='r12.direct-inference-quote.2'],['legacy extra-action reset',x=>x.maximumExtraActions=10],['privacy expansion',x=>x.retention.inference='training_allowed'],['reduced additive reserve',x=>x.ceilings.review=1],['extended freshness',x=>x.validUntil=new Date(T+300000).toISOString()],['wrong accepted model',x=>x.reviewer.acceptedResponseModelIds=['anthropic/claude-haiku-4.5']],['unmatched endpoint hash',x=>x.reviewer.sourceHashes.zdr=H('other')]
])test(`rehashing cannot hide ${name}`,()=>{const x=fresh();mutate(x);const{quoteHash,verifiedAt,validUntil,...b}=x;void quoteHash;const rebuilt={...b,quoteHash:hash(b),verifiedAt,validUntil};assert.throws(()=>q.validateDirectSonnetInferenceQuote(rebuilt,T));});
test('fresh fetch uses six exact public GETs with bounded noncredentialed requests',async()=>{const c=directSonnetCatalogFixture(T),calls=[];const got=await q.fetchDirectSonnetInferenceQuote({now:()=>T,fetch:async(url,init)=>{calls.push(url);assert.equal(init.method,'GET');assert.equal(init.credentials,'omit');assert.equal(init.redirect,'error');assert.equal(init.cache,'no-store');assert.equal(init.headers.Authorization,undefined);const s=Object.values(c).find(s=>s.url===url);assert.ok(s);return new Response(JSON.stringify(s.payload),{headers:{'content-type':'application/json'}});}});assert.equal(calls.length,6);assert.equal(new Set(calls).size,6);assert.equal(got.reviewer.modelId,'anthropic/claude-sonnet-4.6');});
test('fetch cannot refresh an old cached response or swallow provider redirects',async()=>{for(const age of ['300','bad'])await assert.rejects(q.fetchDirectSonnetInferenceQuote({now:()=>T,fetch:async()=>new Response('{}',{headers:{age}})}));await assert.rejects(q.fetchDirectSonnetInferenceQuote({now:()=>T,fetch:async()=>Response.redirect('https://example.invalid',302)}));});
const routes=require(resolve(core,'research/generation-route.js'));
const proofRaw=()=>({data:{id:'gen-direct-sonnet-proof',provider_name:'Amazon Bedrock',model:'anthropic/claude-sonnet-4.6',provider_responses:[{provider_name:'Amazon Bedrock',model_permaslug:'anthropic/claude-4.6-sonnet-20260217',status:200}]}});
test('Sonnet route proof retains both actual aliases and never qualifies through the old route validator',()=>{const raw=proofRaw(),v=q.qualifyDirectSonnetRouteProof(raw,raw.data.id);assert.equal(v.modelId,raw.data.model);assert.equal(v.providerResponses[0].modelId,raw.data.provider_responses[0].model_permaslug);assert.deepEqual(q.validateDirectSonnetRouteProof(v,raw.data.id),v);assert.throws(()=>routes.validateGenerationRouteProof(v,{generationId:raw.data.id,providerName:'Amazon Bedrock',requestedEndpoint:'amazon-bedrock/us',acceptedResponseModelIds:['anthropic/claude-haiku-4.5','anthropic/claude-4.5-haiku-20251001']}));});
for(const[name,change]of [['Haiku response',r=>r.data.model='anthropic/claude-haiku-4.5'],['unknown canonical',r=>r.data.model='anthropic/claude-4.6-sonnet-other'],['another provider',r=>r.data.provider_name='Anthropic'],['wrong generation',r=>r.data.id='gen-other'],['failed inner attempt',r=>r.data.provider_responses[0].status=500],['wrong inner provider',r=>r.data.provider_responses[0].provider_name='Anthropic'],['missing inner identity',r=>delete r.data.provider_responses[0].model_permaslug],['upstream error',r=>r.error={}]] )test(`direct route proof rejects ${name}`,()=>{const raw=proofRaw();change(raw);assert.throws(()=>q.qualifyDirectSonnetRouteProof(raw,'gen-direct-sonnet-proof'));});
test('saved route proof rejects missing extra or forged integrity fields',()=>{const raw=proofRaw(),v=q.qualifyDirectSonnetRouteProof(raw,raw.data.id);for(const changed of [{...v,extra:true},{...v,proofHash:H('wrong')},{...v,requestedEndpoint:'amazon-bedrock'},{...v,providerResponses:[{...v.providerResponses[0],secret:'bad'}]}])assert.throws(()=>q.validateDirectSonnetRouteProof(changed,raw.data.id));});
test('metadata fetch is one fixed-origin non-generating GET with the exact candidate ID',async()=>{let calls=0;const raw=proofRaw(),v=await q.fetchDirectSonnetRouteProofOnce({generationId:raw.data.id,apiKey:'inert-metadata-key',fetcher:async(url,init)=>{calls++;assert.equal(url,'https://openrouter.ai/api/v1/generation?id=gen-direct-sonnet-proof');assert.equal(init.method,'GET');assert.equal(init.redirect,'error');assert.equal(init.credentials,'omit');return Response.json(raw);}});assert.equal(calls,1);assert.equal(v.generationId,raw.data.id);});
test('metadata oversize rejection never waits for hostile stream cancellation',async()=>{let cancelStarted=false;const v=q.fetchDirectSonnetRouteProofOnce({generationId:'gen-direct-sonnet-proof',apiKey:'inert-metadata-key',fetcher:async()=>new Response(new ReadableStream({cancel(){cancelStarted=true;return new Promise(()=>{});}}),{headers:{'content-length':'65537'}})});await assert.rejects(v);assert.equal(cancelStarted,true);});
test('metadata read obeys caller cancellation even after headers',async()=>{const controller=new AbortController();let readStarted;const started=new Promise(r=>readStarted=r),pending=q.fetchDirectSonnetRouteProofOnce({generationId:'gen-direct-sonnet-proof',apiKey:'inert-metadata-key',signal:controller.signal,fetcher:async()=>new Response(new ReadableStream({pull(){readStarted();return new Promise(()=>{});},cancel(){return new Promise(()=>{});}}))});await started;controller.abort();await assert.rejects(pending);});
test('quote.3 renewal permits offset cache-rate drift only within every original cap and refuses version/model substitution',()=>{
 const ex=require(resolve(core,'products/discovery-r12-public-execution-quote.js')),contracts=require(resolve(core,'products/discovery-r12-public-contracts.js')),window=require(resolve(core,'products/discovery-r12-public-window.js'));
 const id=n=>`00000000-0000-4000-8000-${String(n).padStart(12,'0')}`,approved=p.qualifyPublicResearchSonnetQuote(fresh(),browser(),'10000000',T,10),continuation=window.createInitialPublicResearchContinuation(id(10),H('history'));
 const base={version:'r12.direct-etsy-attempt-policy.1',scopeVersion:'r12.discovery-owner-adaptive.4',businessId:id(1),goalId:id(2),authorityRootId:id(3),envelopeHash:H('envelope'),scopeId:id(12),scopeHash:H('scope'),originDirectRunId:id(10),originalSemanticGoalHash:null,browserAccountingPins:{providerProjectId:id(1),routeHash:H('route'),tariffHash:H('tariff'),qualificationHash:H('qualified')},inheritedStateHash:H('history'),initialCommandHash:H('initial'),quoteHash:approved.quoteHash,sourcePolicyHash:H('source'),approvalHash:H('approval'),rubricVersion:'r12.research-quality-rubric.1',window:{version:'r12.research-attempt-window.1',windowId:id(11),windowOrdinal:1,maximumAttemptsInWindow:10,baseAttemptsStarted:0,continuationHash:continuation.continuationHash},continuation,sourceAccess:{allowedSource:'etsy_public_browser',sourcePurpose:'public_marketplace_research'},maximumModelDispatches:30,maximumSourceOperations:10,maximumNmePerEpoch:4,maximumDispatchesPerAttempt:4,baseChildren:19,baseDispatches:17,baseRepairs:0,basePivots:0,cumulativeChildrenCeiling:23,cumulativeDispatchesCeiling:57,baseKnownMicrounits:'5000',originalRunMaximumMicrounits:'10000000',maximumNewAllocationMicrounits:approved.maximumWindowMicrounits,businessLifetimeLimitMicrounits:'15000000',rootLifetimeLimitMicrounits:'15000000',phaseMaximumMicrounits:approved.phaseMaximumMicrounits},policy=self(base,'policyHash');contracts.validatePublicResearchPolicy(policy);
 const later=T+360000,b=browser();b.verifiedAt=new Date(later-1000).toISOString();b.validUntil=new Date(later+299000).toISOString();const{browserQuoteHash,...body}=b;void browserQuoteHash;const current=p.qualifyPublicResearchSonnetQuote(q.qualifyDirectSonnetInferenceQuote(directSonnetCatalogFixture(later),later),self(body,'browserQuoteHash'),'10000000',later,10);assert.doesNotThrow(()=>ex.validatePublicResearchExecutionQuoteCompatibility(approved,current,policy,later));assert.throws(()=>ex.validatePublicResearchExecutionQuoteCompatibility(approved,approved,policy,later));assert.throws(()=>ex.validatePublicResearchExecutionQuoteCompatibility(approved,{...current,version:'r12.public-research-quote.2'},policy,later));const rebound=structuredClone(current);rebound.inference.reviewer.modelId='anthropic/claude-haiku-4.5';assert.throws(()=>ex.validatePublicResearchExecutionQuoteCompatibility(approved,rebound,policy,later));
 const offsetCatalogs=directSonnetCatalogFixture(later);for(const row of [offsetCatalogs.reviewerAlias.payload.data.endpoints[0],offsetCatalogs.reviewerCanonical.payload.data.endpoints[0],offsetCatalogs.zdr.payload.data[1]]){row.pricing.prompt='0.0000022';row.pricing.input_cache_write_1h='0.0000077';}
 const offset=p.qualifyPublicResearchSonnetQuote(q.qualifyDirectSonnetInferenceQuote(offsetCatalogs,later),self(body,'browserQuoteHash'),'10000000',later,10);assert.notEqual(offset.quoteHash,current.quoteHash);assert.equal(offset.inference.reviewer.tokenPricesUsd.cacheWrite,'0.0000077');assert.deepEqual(offset.phaseMaximumMicrounits,approved.phaseMaximumMicrounits);assert.doesNotThrow(()=>ex.validatePublicResearchExecutionQuoteCompatibility(approved,offset,policy,later));
 for(const row of [offsetCatalogs.reviewerAlias.payload.data.endpoints[0],offsetCatalogs.reviewerCanonical.payload.data.endpoints[0],offsetCatalogs.zdr.payload.data[1]])row.pricing.input_cache_write_1h='0.00000770002';
 const expanded=p.qualifyPublicResearchSonnetQuote(q.qualifyDirectSonnetInferenceQuote(offsetCatalogs,later),self(body,'browserQuoteHash'),'10000000',later,10);assert.ok(BigInt(expanded.phaseMaximumMicrounits.review)>BigInt(approved.phaseMaximumMicrounits.review));assert.throws(()=>ex.validatePublicResearchExecutionQuoteCompatibility(approved,expanded,policy,later),/expansion/);

});
