import test from 'node:test';
import assert from 'node:assert/strict';
import {resolveModelRoute} from '../.core-tests/models/registry.js';
import {createDiscoveryR12Candidate,validateDiscoveryR12Candidate,qualifyDiscoveryR12Candidate,discoveryR12ReceiptExpectation} from '../.core-tests/products/discovery-r12-receipt.js';
import {qualifyGenerationRouteProof} from '../.core-tests/research/generation-route.js';
const id=n=>`12000000-0000-4000-8000-${String(n).padStart(12,'0')}`;
const stamp='2026-10-06T00:20:00.000Z';
function fixture(phase='plan'){
 const model=resolveModelRoute(phase==='review'?'reviewer.independent':'standard.default').primary;
 const request=phase==='search1'?{model,query:'Compare dated adult outdoor participation observations and explicit population limitations.',allowedDomains:['adult-outdoors.example'],excludedDomains:['etsy.com','etsy.me','etsystatic.com']}:{model,messages:[{role:'user',content:'Bounded inert response'}],schemaName:'r12_inert_candidate',maxOutputTokens:phase==='review'?4000:1500,outputSchema:{type:'object',additionalProperties:false,required:['result'],properties:{result:{type:'string',minLength:20,maxLength:160}}}};
 const binding={scopeId:id(1),attemptId:id(2),requestId:id(3),phase,request,maximumMicrousd:10000,dispatchedAt:'2026-10-06T00:19:00.000Z',receiptExpiresAt:'2026-10-06T00:49:00.000Z'};
 const response={provider:'UNDOCUMENTED_PROVIDER_LABEL_DO_NOT_RETAIN',providerModelId:phase==='review'?'anthropic/claude-4.5-haiku-20251001':'openai/gpt-5.6-luna-20260709',providerRequestId:'gen-r12-response-candidate',latencyMs:5,usage:{reportedCostUsd:.001},metadata:{finishReason:'stop',...(phase==='search1'?{searchRequests:1}:{})},output:phase==='search1'?{annotations:[{type:'url_citation',url_citation:{url:'https://adult-outdoors.example/report',title:'Adult survey report',content:'A dated adult recreation survey reports its sampled population and geographic limitations.'}}]}:{result:'A bounded saved output awaiting independent route verification.'}};
 return{binding,response};
}
test('R12 saves bounded output and original time before route verification without retaining provider labels',()=>{const f=fixture(),before=structuredClone(f);const candidate=createDiscoveryR12Candidate(f.binding,f.response,stamp);assert.equal(candidate.providerModelId,f.response.providerModelId);assert.equal(candidate.receivedAt,stamp);assert.equal(candidate.reportedMicrousd,1000);assert.equal(JSON.stringify(candidate).includes('UNDOCUMENTED'),false);assert.deepEqual(validateDiscoveryR12Candidate(candidate,f.binding),candidate);assert.deepEqual(f,before);});
test('R12 retains unknown cost explicitly and refuses to qualify it as financially known',()=>{const f=fixture();f.response.usage.reportedCostUsd=null;const candidate=createDiscoveryR12Candidate(f.binding,f.response,stamp);assert.equal(candidate.reportedMicrousd,null);const expectation=discoveryR12ReceiptExpectation(candidate),proof=qualifyGenerationRouteProof({data:{id:candidate.providerRequestId,provider_name:'Azure',model:candidate.providerModelId}},expectation);assert.throws(()=>qualifyDiscoveryR12Candidate(candidate,f.binding,proof),/unverified/);});
test('R12 review candidate requires its independently bound Bedrock route and preserves both actual aliases',()=>{const f=fixture('review'),candidate=createDiscoveryR12Candidate(f.binding,f.response,stamp),expectation=discoveryR12ReceiptExpectation(candidate);assert.equal(expectation.providerName,'Amazon Bedrock');const proof=qualifyGenerationRouteProof({data:{id:candidate.providerRequestId,provider_name:'Amazon Bedrock',model:'anthropic/claude-haiku-4.5'}},expectation);const qualified=qualifyDiscoveryR12Candidate(candidate,f.binding,proof);assert.equal(qualified.candidate.providerModelId,'anthropic/claude-4.5-haiku-20251001');assert.equal(qualified.route.modelId,'anthropic/claude-haiku-4.5');assert.equal(qualified.financiallyKnown,true);});
for(const [name,change] of [['truncated result',f=>f.response.metadata.finishReason='length'],['wrong model',f=>f.response.providerModelId='anthropic/claude-haiku-4.5'],['over ceiling',f=>f.response.usage.reportedCostUsd=1],['negative cost',f=>f.response.usage.reportedCostUsd=-1],['NaN cost',f=>f.response.usage.reportedCostUsd=NaN],['missing generation',f=>f.response.providerRequestId=null],['invalid schema',f=>f.response.output.extra='unrecognized'],['overlong prose',f=>f.response.output.result='a'.repeat(161)]])test(`R12 private candidate rejects ${name}`,()=>{const f=fixture();change(f);assert.throws(()=>createDiscoveryR12Candidate(f.binding,f.response,stamp));});
test('R12 stored candidate cannot change scope, request, original time, cost or output shape',()=>{const f=fixture(),candidate=createDiscoveryR12Candidate(f.binding,f.response,stamp);for(const change of [{scopeId:id(99)},{attemptId:id(99)},{requestId:id(99)},{requestHash:'0'.repeat(64)},{phase:'review'},{receivedAt:'2026-10-06T01:00:00.000Z'},{reportedMicrousd:10001},{secret:'extra'}])assert.throws(()=>validateDiscoveryR12Candidate({...candidate,...change},f.binding));});
test('R12 search candidate rejects restricted origins before private persistence',()=>{const f=fixture('search1'),candidate=createDiscoveryR12Candidate(f.binding,f.response,stamp);assert.equal(candidate.output.annotations.length,1);for(const url of ['https://etsy.com/listing/1','https://evil.example/report','https://adult-outdoors.example/report?token=must-not-retain']){f.response.output.annotations[0].url_citation.url=url;assert.throws(()=>createDiscoveryR12Candidate(f.binding,f.response,stamp));}});
