import test from 'node:test';import assert from 'node:assert/strict';
import {loadPublic,uid,h,hash,self,publicPolicy,command,sourceProof} from './r12-public-fixtures.mjs';
const c=await loadPublic('cycle'),r=await loadPublic('review'),q=await loadPublic('quality');
function capacity(p,overrides={}){return{approvedWindowHash:hash(p.window),approvedMaximumAttemptsInWindow:p.window.maximumAttemptsInWindow,cumulativeDispatchesCeiling:p.cumulativeDispatchesCeiling,authorityActive:true,stopped:false,expired:false,hasUnknownLiability:false,liveGate:{quoteQualified:true,providerAccessQualified:true,sourcePurposeApproved:true,ownerApprovalBound:true,browserSettlementQualified:true},runCommittedMicrounits:'0',rootHeadroomMicrounits:'10000000',businessHeadroomMicrounits:'10000000',activationAllocationHeadroomMicrounits:'1000000',...overrides};}
function start(p,s,overrides={}){const n=s.windowAttemptsStarted+1;return c.startPublicResearchAttempt(p,s,{expectedStateHash:s.stateHash,attemptId:uid(1000+n),planAttemptId:uid(1100+n),planRequestHash:h(`plan-${n}`),executionQuoteHash:h('execution'),executionQuoteProofHash:h(`quote-proof-${uid(1100+n)}`),command:s.pendingCommand,capacity:capacity(p),...overrides});}
function actualCycle(p,old,{outcome='NME',nextCommand=null}={}){
 let s=start(p,old),n=s.windowAttemptsStarted,cmd=s.attempts.at(-1).command;
 s=c.recordPublicResearchReceipt(p,s,'plan',h(`plan-receipt-${n}`));const source=sourceProof(p,n,cmd);
 s=c.markPublicResearchDispatch(p,s,{phase:'source',attemptId:source.sourceAttemptId,requestHash:source.requestHash,executionQuoteHash:source.executionQuoteHash,executionQuoteProofHash:source.executionQuoteProofHash,receiptHash:null});s=c.recordPublicResearchReceipt(p,s,'source',source.receiptHash,source);
 s=c.markPublicResearchDispatch(p,s,{phase:'strategy',attemptId:uid(1200+n),requestHash:h(`strategy-${n}`),executionQuoteHash:h('execution'),executionQuoteProofHash:h(`quote-proof-${uid(1200+n)}`),receiptHash:null});s=c.recordPublicResearchReceipt(p,s,'strategy',h(`strategy-receipt-${n}`));
 s=c.markPublicResearchDispatch(p,s,{phase:'review',attemptId:uid(1300+n),requestHash:h(`review-${n}`),executionQuoteHash:h('execution'),executionQuoteProofHash:h(`quote-proof-${uid(1300+n)}`),receiptHash:null});s=c.recordPublicResearchReceipt(p,s,'review',h(`review-receipt-${n}`));
 const refs=s.attempts.flatMap(a=>a.sourceProof?.witnesses.map(w=>w.ref)??[]),current=source.witnesses[0].ref,score=outcome==='NME'?3:4;
 const ratings=Object.fromEntries(q.PUBLIC_RESEARCH_DIMENSIONS.map(d=>[d,{score,anchorId:`${d}.${score}`,rationale:'Bounded scoped conclusion with explicit gaps',evidenceRefs:[current],contraryRefs:[current],missingFacts:[]}]))
 const nme=s.nmeCountInEpoch+1,proposedCommand=outcome==='NME'?(nextCommand??(nme===4?command(`pivot-${s.epochOrdinal+1}`,undefined,'pivot',cmd.query):command(`${cmd.query} targeted-${n}`,cmd.criteriaHash))):{kind:'finish',rationale:'The scoped hypothesis has been independently reviewed.'};
 const raw={version:'r12.direct-etsy-review.1',proposalHash:h(`proposal-${n}`),quality:ratings,hypothesisFinding:outcome==='TEST'?'supported':outcome==='REJECT'?'refuted':'undetermined',learningRecommendation:outcome,conclusion:'Only the bounded question is answered.',conclusionEvidenceRefs:[current],contraryEvidenceRefs:[current],proposedCommand};
 const review=r.normalizePublicResearchReviewerResponse(raw,{policy:p,attemptOrdinal:n,criteriaHash:cmd.criteriaHash,questionHash:cmd.questionHash,proposalHash:raw.proposalHash,producerModelId:'openai/gpt-5.6-luna',reviewerModelId:'anthropic/claude-haiku-4.5',strategyReceiptHash:h(`strategy-receipt-${n}`),reviewReceiptHash:h(`review-receipt-${n}`),reviewResponseHash:hash(raw),currentSourceProof:source,earlierSourceProofs:s.attempts.slice(0,-1).flatMap(a=>a.sourceProof?[a.sourceProof]:[]),persistedProofsAuthenticated:true,qualityContext:{allowedEvidenceRefs:refs,missingCriticalRequirements:[],comparativeConclusion:false,materialOpposingExplanation:true,sourceAcquisitionVerified:true,citationGroundingVerified:true,independentReviewerVerified:true,sourceTemporalPrecisionSufficient:false,claimBoundariesRespected:true},testReadinessPassed:outcome==='TEST',supportingEvidenceVerified:outcome==='TEST',refutingEvidenceVerified:outcome==='REJECT'});
 return c.completePublicResearchAttempt(p,s,review);
}
for(const n of [1,3,10])test(`N${n} total attempts includes initial and pauses Quest at reviewed window limit`,()=>{const{policy:p,inherited,initial}=publicPolicy(n);let s=c.createPublicResearchState(p,inherited,initial);for(let i=0;i<n;i++)s=actualCycle(p,s);assert.equal(s.totalAttemptsStarted,n);assert.equal(s.modelDispatchesUsed,3*n);assert.equal(s.sourceOperationsStarted,n);assert.equal(s.cumulativeChildrenUsed,23);assert.equal(s.cumulativeDispatchesUsed,17+4*n);assert.equal(s.questComplete,false);assert.equal(s.requiresReviewedRenewal,true);assert.equal(s.terminal,'RESEARCH_INSUFFICIENT_AT_WINDOW_LIMIT');assert.equal(s.windowOutcome,'RESEARCH_FAILED_QUALITY');assert.throws(()=>start(p,s));});
test('NME1–3 targeted, fourth pivots; epochs and seen history survive',()=>{const{policy:p,inherited,initial}=publicPolicy();let s=c.createPublicResearchState(p,inherited,initial);for(let i=0;i<4;i++){s=actualCycle(p,s);assert.equal(s.nextAttemptKind,i===3?'pivot':'targeted');}const old=[...s.history.seenEvidenceIdentityHashes];s=actualCycle(p,s);assert.equal(s.epochOrdinal,1);assert.equal(s.nmeCountInEpoch,1);assert.equal(s.pivots,1);assert.ok(old.every(x=>s.history.seenEvidenceIdentityHashes.includes(x)));assert.equal(s.history.consecutiveNonprogress,5);});
test('fourth NME at cap still requires and retains the pivot command',()=>{const{policy:p,inherited,initial}=publicPolicy(4);let s=c.createPublicResearchState(p,inherited,initial);for(let i=0;i<3;i++)s=actualCycle(p,s);assert.throws(()=>actualCycle(p,s,{nextCommand:command('same criteria',s.epochCriteriaHash)}),/fourth_nme_requires_pivot/);s=actualCycle(p,s);assert.equal(s.pendingCommand.kind,'pivot');assert.equal(c.publicResearchContinuationFromState(p,s).nmeCountInEpoch,4);});
test('supported and refuted high-quality conclusions are distinct on final allowed slot',()=>{for(const outcome of ['TEST','REJECT']){const{policy:p,inherited,initial}=publicPolicy(1);const s=actualCycle(p,c.createPublicResearchState(p,inherited,initial),{outcome});assert.equal(s.questComplete,false);assert.equal(s.researchWindowComplete,true);assert.equal(s.researchStageOutcome,s.terminal);assert.equal(s.requiresReviewedRenewal,false);assert.equal(s.terminal,outcome==='TEST'?'RESEARCH_PASSED_SUPPORTS_TEST':'RESEARCH_PASSED_REJECTS_HYPOTHESIS');}});
test('technical repair consumes a total attempt and never creates a hidden paid call',()=>{const{policy:p,inherited,initial}=publicPolicy(1);let s=start(p,c.createPublicResearchState(p,inherited,initial));assert.throws(()=>c.failPublicResearchAttempt(p,s,h('failure')));s=c.recordPublicResearchReceipt(p,s,'plan',h('failed-receipt'));s=c.failPublicResearchAttempt(p,s,h('failure'));assert.equal(s.totalAttemptsStarted,1);assert.equal(s.modelDispatchesUsed,1);assert.equal(s.windowOutcome,'INVALID_RESEARCH');assert.equal(s.requiresReviewedRenewal,true);assert.throws(()=>start(p,s));});
test('reviewed attempt authority and cash ceilings cannot be raised by a larger requested window',()=>{const{policy:p,inherited,initial}=publicPolicy(10),s=c.createPublicResearchState(p,inherited,initial);assert.throws(()=>start(p,s,{capacity:capacity(p,{approvedMaximumAttemptsInWindow:9})}));assert.throws(()=>start(p,s,{capacity:capacity(p,{runCommittedMicrounits:'9999000'})}));assert.throws(()=>start(p,s,{capacity:capacity(p,{cumulativeDispatchesCeiling:20})}));assert.throws(()=>start(p,s,{capacity:capacity(p,{hasUnknownLiability:true})}));});
test('same source quote or typed fact rewrapped under a new capture cannot qualify novelty',()=>{const{policy:p,inherited,initial}=publicPolicy(3);let s=actualCycle(p,c.createPublicResearchState(p,inherited,initial));const witness=s.attempts[0].sourceProof.witnesses[0];s=start(p,s);s=c.recordPublicResearchReceipt(p,s,'plan',h('second-plan'));const proof=sourceProof(p,2,s.attempts.at(-1).command);proof.witnesses[0].factIdentityHash=witness.factIdentityHash;s=c.markPublicResearchDispatch(p,s,{phase:'source',attemptId:proof.sourceAttemptId,requestHash:proof.requestHash,executionQuoteHash:proof.executionQuoteHash,executionQuoteProofHash:proof.executionQuoteProofHash,receiptHash:null});assert.throws(()=>c.recordPublicResearchReceipt(p,s,'source',proof.receiptHash,proof),/source_repetition/);});
test('forged cumulative counters cannot reset immutable state',()=>{const{policy:p,inherited,initial}=publicPolicy(),s=actualCycle(p,c.createPublicResearchState(p,inherited,initial));const{stateHash,...body}=s;void stateHash;assert.throws(()=>c.validatePublicResearchState(self({...body,totalAttemptsStarted:0},'stateHash'),p));});
test('renewal projection retains origin/counters/history and remains activation gated',()=>{const{policy:p,inherited,initial}=publicPolicy(1);const s=actualCycle(p,c.createPublicResearchState(p,inherited,initial)),continuation=c.publicResearchContinuationFromState(p,s);const{policyHash,...body}=p;void policyHash;const next=self({...body,scopeId:uid(900),scopeHash:h('nextscope'),inheritedStateHash:hash(s.history),initialCommandHash:hash(s.pendingCommand),continuation,window:{...p.window,windowId:uid(901),windowOrdinal:2,baseAttemptsStarted:s.totalAttemptsStarted,continuationHash:continuation.continuationHash},baseChildren:s.cumulativeChildrenUsed,baseDispatches:s.cumulativeDispatchesUsed,baseRepairs:s.repairs,basePivots:s.pivots,cumulativeDispatchesCeiling:s.cumulativeDispatchesUsed+4},'policyHash');assert.doesNotThrow(()=>c.validatePublicResearchRenewalProjection(p,s,next));const nextState=c.createPublicResearchState(next,s.history,s.pendingCommand);assert.throws(()=>start(next,nextState),/renewal_activation_unqualified/);const{policyHash:unused,...bad}=next;void unused;assert.throws(()=>c.validatePublicResearchRenewalProjection(p,s,self({...bad,baseDispatches:17},'policyHash')));});
test('rehashed passed true cannot bypass numeric quality replay or universal floors',()=>{const{policy:p,inherited,initial}=publicPolicy(1);const s=actualCycle(p,c.createPublicResearchState(p,inherited,initial),{outcome:'TEST'});let review=structuredClone(s.attempts[0].review);const{qualityHash,...qbody}=review.quality;void qualityHash;qbody.quality.uncertaintyDiscipline.score=2;qbody.quality.uncertaintyDiscipline.anchorId='uncertaintyDiscipline.2';qbody.qualityBasisPoints=9250;review.quality=self(qbody,'qualityHash');const{reviewHash,...body}=review;void reviewHash;review=self(body,'reviewHash');assert.throws(()=>r.validatePublicResearchReviewedResult(review,p),/quality_replay_mismatch/);});
test('nontechnical NME rejects repeated normalized query or seen question; technical retry remains counted',()=>{const{policy:p,inherited,initial}=publicPolicy(2),s=c.createPublicResearchState(p,inherited,initial);assert.throws(()=>actualCycle(p,s,{nextCommand:command('  PLANTS  ',initial.criteriaHash)}),/repeated_followup_command/);const other=command('different query',initial.criteriaHash);other.namedGap=initial.namedGap;other.questionHash=initial.questionHash;assert.throws(()=>actualCycle(p,s,{nextCommand:other}),/repeated_followup_command/);let failed=start(p,s);failed=c.recordPublicResearchReceipt(p,failed,'plan',h('failed-plan'));failed=c.failPublicResearchAttempt(p,failed,h('technical-failure'));const retry=start(p,failed);assert.equal(retry.attempts[1].kind,'technical_retry');assert.deepEqual(retry.attempts[1].command,initial);assert.equal(retry.totalAttemptsStarted,2);assert.equal(retry.repairs,1);});
