import test from 'node:test';
import assert from 'node:assert/strict';
import {prepareAmendedDiscoveryScope} from '../.core-tests/products/discovery-r12-scope.js';
import {buildDiscoveryIntentFromGoal,DISCOVERY_GOAL_DEFAULT} from '../.core-tests/products/discovery-v2-goal.js';
import {discoveryV2Hash} from '../.core-tests/products/discovery-v2.js';
const id=n=>`12000000-0000-4000-8000-${String(n).padStart(12,'0')}`;
const now=Date.parse('2026-10-05T23:00:00Z');
export function scopeFixture(){
 const priorIntent=buildDiscoveryIntentFromGoal({id:id(2),businessId:id(1),goal:DISCOVERY_GOAL_DEFAULT,maximumMicrousd:2000000,maximumCollections:1,now:now-4*86400000});
 const original={businessId:id(1),budgetAuthorityRootId:id(3),priorRoundId:priorIntent.id,semanticGoalHash:'a'.repeat(64),priorIntent,maximumMicrousd:2000000,committedMicrousd:109480,hasUncertainCosts:false};
 const amendment={version:'r12.discovery-source-scope.1',id:id(4),businessId:id(1),goalId:id(5),budgetAuthorityRootId:id(3),priorRoundId:id(2),originalIntentHash:discoveryV2Hash(priorIntent),originalSemanticGoalHash:original.semanticGoalHash,allowedDomains:['adult-outdoors.example'],excludedDomains:['etsy.com','etsy.me','etsystatic.com'],sourceReviews:[{domain:'adult-outdoors.example',basis:'documented_api_factual_snippets',reviewHash:'b'.repeat(64)}],approvalHash:'c'.repeat(64),independentReviewHash:'d'.repeat(64),approvedQuery:'Compare dated adult outdoor-apparel purchase criteria across US, GB, AU and NZ. Preserve exact population, geography, survey date and denominator limits; original nature-shirt demand, willingness to pay and operating costs remain unproven unless directly measured.',purposeReviewHash:'e'.repeat(64),createdAt:new Date(now-1000).toISOString(),expiresAt:new Date(now+3600000).toISOString()};
 amendment.purposeReviewHash=discoveryV2Hash({query:amendment.approvedQuery,classification:'generic_nonpersonal_public_research'});
 return {original,amendment,now};
}
test('R12 source-only amendment carries original funding and intent without renewing historical evidence',()=>{
 const f=scopeFixture(),before=structuredClone(f),result=prepareAmendedDiscoveryScope(f.original,f.amendment,f.now);
 assert.equal(result.executionAuthorized,false);assert.equal(result.budgetAuthorityRootId,f.original.budgetAuthorityRootId);assert.equal(result.originalSemanticGoalHash,f.original.semanticGoalHash);assert.equal(result.remainingMicrousd,1890520);
 const expected=structuredClone(f.original.priorIntent);expected.id=f.amendment.id;expected.expiresAt=f.amendment.expiresAt;expected.comparisonUniverse.sourceDomains=f.amendment.allowedDomains;expected.limits.maximumNewCollections=1;
 assert.deepEqual(result.intent,expected);assert.deepEqual(f,before);assert.equal(result.intent.limits.maximumMicrousd,2000000);assert.notEqual(result.intentHash,f.amendment.originalIntentHash);
});
for(const [name,change] of [
 ['changed public query',f=>f.amendment.approvedQuery+=' Private new scope'],['missing public query',f=>delete f.amendment.approvedQuery],['wrong public query review',f=>f.amendment.purposeReviewHash='f'.repeat(64)],['different Business',f=>f.amendment.businessId=id(99)],['different root',f=>f.amendment.budgetAuthorityRootId=id(99)],['different latest round',f=>f.amendment.priorRoundId=id(99)],['relabelled semantic goal',f=>f.amendment.originalSemanticGoalHash='f'.repeat(64)],['changed audience',f=>f.original.priorIntent.comparisonUniverse.audiences=['Other audience']],['changed geography',f=>f.original.priorIntent.comparisonUniverse.markets.pop()],['unknown liability',f=>f.original.hasUncertainCosts=true],['exhausted allowance',f=>f.original.committedMicrousd=2000000],['reduced allowance',f=>f.original.maximumMicrousd=1000000],['expired amendment',f=>f.amendment.expiresAt=new Date(f.now).toISOString()],['unbounded freshness',f=>f.amendment.expiresAt=new Date(f.now+2*86400000).toISOString()],['future amendment',f=>f.amendment.createdAt=new Date(f.now+1).toISOString()],['missing reviewer',f=>delete f.amendment.independentReviewHash],['injected authority',f=>f.amendment.authorized=true],['restricted source',f=>f.amendment.allowedDomains=['etsy.com']],['restricted subdomain',f=>f.amendment.allowedDomains=['www.etsy.com']],['missing exclusion',f=>f.amendment.excludedDomains=['etsy.com']],['missing source review',f=>f.amendment.sourceReviews=[]],['fabricated licence',f=>f.amendment.sourceReviews[0].basis='public_means_free'],['missing evidence hash',f=>f.amendment.sourceReviews[0].reviewHash=null],['reused identity',f=>f.amendment.id=f.original.priorRoundId],
])test(`R12 source amendment rejects ${name}`,()=>{const f=scopeFixture();change(f);assert.throws(()=>prepareAmendedDiscoveryScope(f.original,f.amendment,f.now));});
