/** Genuine closed history; owner captures and three paid phases, no transport. */
import test from 'node:test';
import assert from 'node:assert/strict';
import {createRequire} from 'node:module';
import {readFileSync,readdirSync} from 'node:fs';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
import {randomUUID} from 'node:crypto';
import {r04SqlBootstrap} from './helpers/r04-sql-bootstrap.mjs';
import {sessionBootstrap} from './helpers/r10-sql-fixture.mjs';
import {prepareFourPlanEtsyFixture,etsyObservationFixture,bindEtsyPlanner} from './helpers/r12-etsy-activation-fixture.mjs';
import {startAdaptivePlanner} from './helpers/r12-adaptive-postgres-races.mjs';
import {runEtsyAction,etsyActionController} from './helpers/r12-etsy-runtime-fixture.mjs';
import {one,ownerInitialRuntimeRpc} from './helpers/r12-owner-initial-sql-fixture.mjs';
import {readClosedResearchHistory} from './helpers/r12-adaptive-history-fixture.mjs';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..');
const host=process.env.R12_SQL_TEST_HOST;
test('Etsy-only mode keeps five-phase history but creates exactly three real child and policy slots',{skip:!host,timeout:120000},async()=>{
 const req=createRequire(path.resolve(host,'package.json'));
 const {PGlite}=req('@electric-sql/pglite'),{pgcrypto}=req('@electric-sql/pglite/contrib/pgcrypto');
 const db=new PGlite({extensions:{pgcrypto}});
 try{
  await db.exec(r04SqlBootstrap+sessionBootstrap);
  for(const file of readdirSync(path.join(root,'supabase/migrations')).filter(x=>x.endsWith('.sql')).sort())await db.exec(readFileSync(path.join(root,'supabase/migrations',file),'utf8'));
  const x=await prepareFourPlanEtsyFixture(db);
  assert.equal(x.prepared.preview.version,'r12.adaptive-research-preview.2');
  assert.equal(x.prepared.preview.maximumNewChildren,3);
  assert.equal(x.packet.version,'r12.owner-adaptive-planner-preflight-input.2');
  assert.equal(x.preflight.version,'r12.owner-adaptive-planner-preflight.2');
  assert.deepEqual(x.packet.intentPins.evidenceManifest,[]);
  assert.deepEqual(x.packet.intentPins.activeEvidenceArtifactIds,[]);
  assert.equal(x.packet.intent.limits.maximumNewCollections,0);
  assert.equal(x.prepared.preview.imports.length,5);
  assert.equal((await one(db,'select count(*)::int n from private.r12_adaptive_activations')).n,0);
  assert.equal((await one(db,'select count(*)::int n from private.r05_requests where business_id=$1',[x.f.businessId])).n,20);
  await assert.rejects(x.prepare({ownerObservationRef:null}),/r12_owner_observation_ref_required/);
  const foreign=etsyObservationFixture(x.f.businessId,x.f.ownerId,{sourceUrl:'https://market.example/insights'});
  await x.f.rpc('r12_owner_observation_server',[x.f.businessId,'save',{bundle:foreign.bundle},'']);
  await assert.rejects(x.prepare({ownerObservationRef:foreign.ownerObservationRef}),/r12_adaptive_etsy_observation_source_required/);
  await assert.rejects(x.confirm({...x,confirmPayload:{...x.confirmPayload,quote:{...x.quote,version:'r12.adaptive-quote.1'}}}),/r12_adaptive_cross_mode_replay/);
  const started=await startAdaptivePlanner(db,x),confirmed=started.activated;
  const plan=started.context.plan;
  assert.equal(plan.format,'r12.discovery-adaptive.2');
  assert.deepEqual(plan.steps.map(s=>s.key),['plan','strategy','review']);
  assert.deepEqual(plan.steps.map(s=>s.dependsOn),[[],['plan'],['plan','strategy']]);
  assert.equal((await one(db,'select count(*)::int n from private.r07_children where plan_id=$1',[confirmed.planId])).n,3);
  const policy=await one(db,'select payload from private.r05_policies where id=$1',[x.prepared.policyId]);
  assert.equal(policy.payload.operations.length,3);
  assert.ok(policy.payload.operations.every(o=>!/(search1|select1)$/.test(o.operationKey)));
  assert.equal(started.raw.version,'r12.discovery-adaptive-inputs.2');
  assert.deepEqual(started.raw.archive,[]);
  assert.deepEqual(started.raw.dependencies,[]);
  assert.deepEqual(started.raw.ownerObservationContext.bundles,[x.bundle]);
  assert.deepEqual(started.raw.action.phases,['plan','strategy','review']);
  const command=(op,payload,epoch=null)=>ownerInitialRuntimeRpc(db,'r07_controller',[x.f.businessId,x.f.goalId,op,payload,randomUUID(),started.controller,started.lease,epoch,started.admission]);
  for(const stepKey of ['search1','select1'])await assert.rejects(command('schedule',{stepKey,attemptId:randomUUID(),reason:'Inert forbidden phase',evidenceHash:started.context.planHash,actionHash:started.raw.actionHash,actionOrdinal:0,runtimeCapability:'inert-forbidden-'+stepKey},started.epoch));
  const action=(await one(db,'select content from private.r12_adaptive_actions where scope_id=$1',[x.prepared.scopeId])).content;
  await assert.rejects(db.query('select private.r12_adaptive_admit_action($1,$2)',[x.prepared.scopeId,{...action,version:'r12.adaptive-action.1'}]),/idempotency_conflict/);
  assert.equal((await one(db,'select count(*)::int n from private.r05_requests where business_id=$1',[x.f.businessId])).n,20);
  await db.exec('begin');
  const bound=await bindEtsyPlanner(db,x,started,{reserve:true,marker:true});
  assert.ok(bound.requestId);
  assert.equal((await one(db,'select count(*)::int n from private.r12_adaptive_call_admissions where scope_id=$1',[x.prepared.scopeId])).n,1);
  const wire=await one(db,'select binding from private.r12_discovery_wires where request_id=$1',[bound.requestId]);
  assert.equal(wire.binding.version,'r12.adaptive-wire.2');
  assert.equal(wire.binding.quote.version,'r12.adaptive-quote.2');
  const unknown=await one(db,'select e.unknown,e.held from private.r05_requests r join lateral private.r05_exposure(r.business_id) e on e.source_key=r.source_key where r.id=$1',[bound.requestId]);
  assert.equal(unknown.unknown,true);assert.equal(Number(unknown.held),x.quote.ceilings.plan);
  assert.equal((await one(db,'select count(*)::int n from private.r05_settlements where request_id=$1',[bound.requestId])).n,0);
  await db.exec('rollback');
  await assert.rejects(db.query('select private.r12_adaptive_quote_check($1,$2)',[{...x.quote,version:'r12.adaptive-quote.1'},x.quote]),/cross_mode_replay/);
  for(const [kind,repair,phases] of [['initial',null,['plan','strategy','review']],['pivot',null,['plan','strategy','review']],['reasoning_review',null,['strategy','review']],['repair','plan',['plan','strategy','review']],['repair','strategy',['strategy','review']],['repair','review',['strategy','review']]])assert.deepEqual((await one(db,'select private.r12_adaptive_etsy_action_phases($1,$2) phases',[kind,repair])).phases,phases);
  await assert.rejects(db.query("select private.r12_adaptive_etsy_action_phases('followup')"),/owner_source_operation_required/);
  await assert.rejects(db.query("select private.r12_adaptive_etsy_action_phases('repair','search')"),/topology_invalid/);
  const initial=await runEtsyAction(db,x,started,{nextKind:'reasoning_review'});
  assert.deepEqual(initial.phases,['plan','strategy','review']);assert.equal(initial.posts,3);assert.equal(initial.gets,3);
  const closure=await one(db,'select * from private.r12_adaptive_action_closures where scope_id=$1 and action_ordinal=0',[x.prepared.scopeId]);
  assert.equal(closure.state,'completed');assert.equal(closure.outcome,'NEEDS_MORE_EVIDENCE');assert.equal(Number(closure.committed_microusd),30);
  const inputs=(await db.query('select s.content from private.r12_adaptive_input_snapshots s join private.r07_attempts a on a.id=s.attempt_id where s.scope_id=$1 order by a.created_at,a.id',[x.prepared.scopeId])).rows.map(r=>r.content);
  assert.deepEqual(inputs.map(i=>i.dependencies.map(d=>d.stepKey)),[[],['plan'],['plan','strategy']]);
  // Adapter and controller preserve independent qualified receipt hashes for one
  // request. Accounting must use the maximum per request, never sum duplicates.
  const costs=(await db.query('select c.request_id,count(s.id)::int receipts,max(s.actual_microunits) actual from private.r12_adaptive_call_admissions c join private.r05_settlements s on s.request_id=c.request_id where c.scope_id=$1 group by c.request_id',[x.prepared.scopeId])).rows;
  assert.equal(costs.length,3);assert.ok(costs.every(c=>c.receipts>=2&&Number(c.actual)===10));
  assert.equal(costs.reduce((sum,c)=>sum+Number(c.actual),0),30);
  assert.deepEqual(inputs.map(i=>i.intentPins.finance.actionCommittedMicrousd),[0,10,20]);
  assert.deepEqual(inputs.map(i=>i.intentPins.finance.runCommittedMicrousd),[0,10,20]);
  const setupReceipt=await one(db,'select private.r12_adaptive_setup_receipt(s) receipt from private.r12_adaptive_setups s where id=$1',[x.prepared.setupId]);
  assert.equal(Number(setupReceipt.receipt.actions[0].committedMicrounits),30);
  assert.ok(inputs.every(i=>i.version==='r12.discovery-adaptive-inputs.2'&&i.archive.length===0&&i.ownerObservationContext.manifestHash===x.ownerObservationRef.manifestHash));
  assert.equal((await one(db,'select children_created from private.r07_heads where goal_id=$1',[x.f.goalId])).children_created,23);
  const controller=etsyActionController(db,x,started),admitted=await controller.adaptive('admit_next');
  assert.equal(admitted.admitted,true);assert.equal(admitted.ordinal,1);
  const current=await controller.readAdaptiveAction();assert.deepEqual(current.phaseKeys,['strategy','review']);
  assert.deepEqual(current.reused.map(p=>p.stepKey),['plan']);
  // Rollback only the synthetic branch. Every phase still uses the real APIs.
  await db.exec('begin');
  const reasoning=await runEtsyAction(db,x,started,{nextKind:'followup'});
  assert.deepEqual(reasoning.phases,['strategy','review']);assert.equal(reasoning.posts,2);assert.equal(reasoning.gets,2);
  assert.deepEqual(await controller.adaptive('admit_next'),{admitted:false,reason:'owner_source_operation_required'});
  assert.equal((await one(db,'select count(*)::int n from private.r12_adaptive_actions where scope_id=$1',[x.prepared.scopeId])).n,2);
  assert.equal((await one(db,'select count(*)::int n from private.r12_adaptive_call_admissions where scope_id=$1',[x.prepared.scopeId])).n,5);
  assert.equal((await one(db,'select children_created from private.r07_heads where goal_id=$1',[x.f.goalId])).children_created,23);
  await db.exec('rollback');
  const stop=()=>x.f.rpc('r12_owner_adaptive_server',[x.f.businessId,'stop',{businessId:x.f.businessId,setupId:x.prepared.setupId,setupHash:x.prepared.setupHash,submissionId:randomUUID()},'']);
  await db.exec('begin');
  await stop();
  assert.equal((await controller.adaptive('admit_next')).reason,'owner_stopped');
  assert.equal((await one(db,'select count(*)::int n from private.r12_adaptive_call_admissions where scope_id=$1',[x.prepared.scopeId])).n,3);
  assert.equal(Number((await one(db,'select private.r12_adaptive_outstanding_hold($1) hold',[x.f.businessId])).hold),0);
  await db.exec('rollback');
  const late=await runEtsyAction(db,x,started,{onFirstPost:stop,stopAfterResponse:true});
  assert.deepEqual(late.phases,['strategy']);assert.equal(late.posts,1);assert.equal(late.gets,1);
  assert.equal((await controller.adaptive('admit_next')).reason,'owner_stopped');
  assert.equal((await one(db,'select count(*)::int n from private.r05_exposure($1) where unknown',[x.f.businessId])).n,0);
  const paid=await one(db,"select t.id,r.request_id from private.r07_attempts t join private.r12_adaptive_call_admissions r on r.attempt_id=t.id where r.scope_id=$1 and r.action_ordinal=1",[x.prepared.scopeId]);
  const receipt=await ownerInitialRuntimeRpc(db,'r12_discovery_server',[x.f.businessId,paid.id,'inputs',{},started.controller]);
  assert.equal(receipt.inputMode,'receipt');assert.equal(receipt.version,'r12.discovery-adaptive-inputs.2');
  assert.equal(Number((await one(db,'select max(actual_microunits) actual from private.r05_settlements where request_id=$1',[paid.request_id])).actual),10);
  assert.equal((await one(db,'select count(*)::int n from private.r12_adaptive_call_admissions where scope_id=$1',[x.prepared.scopeId])).n,4);
  assert.deepEqual(await readClosedResearchHistory(db,x.f.goalId),x.history);
  const acl=await one(db,"select has_function_privilege('anon','private.r12_adaptive_quote_check_etsy(jsonb,jsonb)','EXECUTE') anon,has_function_privilege('authenticated','private.r12_owner_adaptive_confirm_etsy(uuid,jsonb,text)','EXECUTE') owner");
  assert.deepEqual(acl,{anon:false,owner:false});
 }catch(error){if(error.where)error.message+='\n'+error.where;throw error;}finally{await db.close();}
});
