import test from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {createRequire} from 'node:module';
const require=createRequire(import.meta.url),ts=require('typescript');
function route(owner,prepare){const fixtureModule={exports:{}},source=ts.transpileModule(readFileSync('src/app/api/research/r12/prepare/route.ts','utf8'),{compilerOptions:{target:ts.ScriptTarget.ES2022,module:ts.ModuleKind.CommonJS}}).outputText;new Function('require','module','exports',source)(name=>{if(name==='@/lib/core-ui/data')return{requireOwnerUiContext:owner};if(name==='@/products/discovery-r12-server')return{prepareDiscoveryR12Authority:prepare};throw Error(`Unexpected route dependency ${name}`);},fixtureModule,fixtureModule.exports);return fixtureModule.exports;}
const origin='https://agent-labs-two.vercel.app',businessId='11111111-1111-4111-8111-111111111111',scopeId='22222222-2222-4222-8222-222222222222';
function request(body={businessId,scopeId},headers={}){return new Request(`${origin}/api/research/r12/prepare`,{method:'POST',headers:{origin,'content-type':'application/json',...headers},body:typeof body==='string'?body:JSON.stringify(body)});}
test('R12 preparation returns only nonsecret bound verifier hashes and no authority',async()=>{let calls=0;const context={userId:'owner'},api=route(async()=>context,async(c,b,s)=>{calls++;assert.equal(c,context);assert.equal(b,businessId);assert.equal(s,scopeId);return{controllerKeyHash:'a'.repeat(64),admissionKeyHash:'b'.repeat(64),authorityCreated:false};});const response=await api.POST(request());assert.equal(response.status,200);assert.equal(response.headers.get('cache-control'),'no-store');const body=await response.json();assert.equal(body.authorityCreated,false);assert.deepEqual(Object.keys(body).sort(),['admissionKeyHash','authorityCreated','businessId','controllerKeyHash','scopeId']);assert.equal(calls,1);});
test('R12 preparation rejects cross-origin, oversized, malformed and unauthenticated inputs before preparation',async()=>{let calls=0;const api=route(async()=>({userId:'owner'}),async()=>{calls++;throw Error('must not prepare');});for(const req of [request({}, {origin:'https://foreign.invalid'}),request('x'.repeat(513)),request({businessId,scopeId,authority:true}),request('{'),request({}, {'content-type':'text/plain'})])assert.ok((await api.POST(req)).status>=400);assert.equal(calls,0);const denied=route(async()=>{throw Error('private auth failure');},async()=>{throw Error('must not prepare');});const response=await denied.POST(request());assert.equal(response.status,403);assert.deepEqual(await response.json(),{error:'preparation_unavailable'});});
