import test from 'node:test';import assert from 'node:assert/strict';
import {r12CatalogFixture} from './helpers/r12-provider-fixture.mjs';
import {qualifyAdaptiveResearchQuote as qualify,validateAdaptiveExecutionQuote as compatible} from '../.core-tests/products/discovery-r12-adaptive-quote.js';
import {discoveryV2Hash as hash} from '../.core-tests/products/discovery-v2.js';
const now=Date.parse('2026-10-10T03:00:00Z');
function change(catalogs,fn){for(const key of ['lunaAlias','lunaCanonical','reviewerAlias','reviewerCanonical'])for(const r of catalogs[key].payload.data.endpoints)fn(r);for(const r of catalogs.zdr.payload.data)fn(r);return catalogs;}
function scale(r,factor){for(const tier of [r.pricing,...(r.pricing.overrides??[])])for(const key of ['prompt','completion','input_cache_read','input_cache_write','input_cache_write_1h','internal_reasoning'])if(tier[key]!==undefined)tier[key]=(Number(tier[key])*factor).toFixed(12);}
function rehash(q){const{quoteHash,verifiedAt,validUntil,...body}=q;void quoteHash;void verifiedAt;void validUntil;q.quoteHash=hash(body);return q;}
test('fresh observation refresh after old expiry retains approved envelope without mutating old quote',()=>{const old=qualify(r12CatalogFixture(now),now),saved=structuredClone(old),later=now+360000,current=qualify(change(r12CatalogFixture(later),r=>{r.name+=' refreshed display label';}),later);assert.notEqual(current.quoteHash,old.quoteHash);assert.deepEqual(current.ceilings,old.ceilings);assert.deepEqual(compatible(current,old,old.quoteHash,later),current);assert.deepEqual(old,saved);});
test('fresh qualified lower prices are accepted while any increased phase ceiling fails',()=>{const old=qualify(r12CatalogFixture(now),now);const low=qualify(change(r12CatalogFixture(now),r=>scale(r,0.5)),now);assert.ok(low.ceilings.plan<old.ceilings.plan);assert.doesNotThrow(()=>compatible(low,old,old.quoteHash,now));assert.throws(()=>compatible(old,low,low.quoteHash,now),/incompatible/);});
test('freshness, approved identity, privacy, routing, call bounds and total run limits remain mandatory',()=>{const old=qualify(r12CatalogFixture(now),now);assert.throws(()=>compatible(old,old,'0'.repeat(64),now));assert.throws(()=>compatible(old,old,old.quoteHash,now+300000));for(const mutate of[q=>q.retention.inference='training_allowed',q=>q.luna.endpoint='other/us',q=>q.luna.acceptedResponseModelIds.push('other'),q=>q.requestBytes.plan++,q=>q.outputTokens.review++,q=>q.maximumRunMicrousd++,q=>q.maximumExtraActions++]){const current=structuredClone(old);mutate(current);rehash(current);assert.throws(()=>compatible(current,old,old.quoteHash,now));}});
