import test from 'node:test';
import assert from 'node:assert/strict';
import {buildOwnerObservationIntake} from '../.core-tests/products/discovery-r12-owner-observation-intake.js';
import {selectedOwnerObservationBaselines} from '../.core-tests/products/discovery-r12-owner-observation.js';
const id=n=>`20000000-0000-4000-8000-${String(n).padStart(12,'0')}`;
function draft(){return {id:id(1),createdAt:'2026-10-10T00:00:00Z',productFormat:'Adult printed T-shirt',category:'Adult apparel',windowStart:'2026-09-01T00:00:00Z',windowEnd:'2026-10-01T00:00:00Z',locale:'en-NZ',privacyReviewed:true,baseline:null,observations:[{id:id(4),query:'astronomy shirt',url:'https://www.etsy.com/your/shops/me/marketplace-insights',interface:'Etsy Marketplace Insights',capturedAt:'2026-10-09T00:00:00Z',content:'🌿 Searches 1.1k. Conversion Very low.',excerpt:'Searches 1.1k',limitations:'Rounded searches; relative conversion label. No buyer geography or item sales established.'}]};}
test('normal owner intake derives immutable identities from witnessed Etsy text without numeric claims',()=>{const b=buildOwnerObservationIntake(draft(),id(2),id(3)),o=b.observations[0];assert.equal(o.metrics[0].kind,'statement');assert.equal(o.metrics[0].start,2);assert.equal(o.context.geography.kind,'unknown');assert.match(b.bundleHash,/^[a-f0-9]{64}$/);assert.deepEqual(buildOwnerObservationIntake(draft(),id(2),id(3)),b);});
test('intake rejects missing privacy review, fabricated excerpt, third party source and invalid dates',()=>{for(const mutate of [x=>x.privacyReviewed=false,x=>x.observations[0].excerpt='Made-up sales',x=>x.observations[0].url='https://research.example/insights',x=>x.windowEnd='2027-01-01T00:00:00Z',x=>x.observations[0].content+=' customer email: person@example.com']){const d=draft();mutate(d);assert.throws(()=>buildOwnerObservationIntake(d,id(2),id(3)));}});
test('baseline binds two candidates and a distinct retained negative reference',()=>{const d=draft();d.observations=[0,1,2].map((i)=>({...d.observations[0],id:id(i+4),query:`hypothesis ${i}`}));d.baseline={hypothesis:'A narrower theme may justify a bounded learning test.',positiveCriterion:'Comparable channel evidence supports a useful private experiment.',negativeCriterion:'Contrary observations defeat the hypothesis.',inconclusiveCriterion:'Missing or incomparable data is inconclusive.'};const b=buildOwnerObservationIntake(d,id(2),id(3));assert.deepEqual(b.baseline.candidateObservationIds,[id(4),id(5)]);assert.equal(b.baseline.referenceObservationId,id(6));assert.equal(b.baseline.timing,'retrospective');const context={manifest:[{bundleId:b.id,bundleHash:b.bundleHash,selectedObservationIds:[id(4)]}],bundles:new Map([[b.id,b]])};const wire=selectedOwnerObservationBaselines(context);assert.equal(wire[0].baseline,null);assert.match(wire[0].baselineStatus,/incomplete/);assert.doesNotMatch(JSON.stringify(wire),/hypothesis 1|hypothesis 2|Contrary observations/);});
