import test from 'node:test';import assert from 'node:assert/strict';
import {fixture,complete} from './helpers/r12-adaptive-inputs-fixture.mjs';import {now} from './helpers/r12-adaptive-fixture.mjs';
import {inspectAdaptiveResearchWire} from '../.core-tests/products/discovery-r12-adaptive-wire.js';import {discoveryV2Hash as hash} from '../.core-tests/products/discovery-v2.js';import {validateAdaptiveReceiptResume as check} from '../.core-tests/products/discovery-r12-adaptive-receipt-recovery.js';
const original=Date.now;test.before(()=>{Date.now=()=>now;});test.after(()=>{Date.now=original;});
async function input(){const f=fixture(),{d}=complete(f,'plan',f.outputs.plan),wire=await inspectAdaptiveResearchWire(d.binding.request,'plan',f.quote,now);const context=structuredClone(f.ctx);Object.assign(context.attempt,{status:'dispatched',requestId:d.binding.requestId,wireHash:wire.wireHash});const saved={binding:{version:'r12.adaptive-wire.1',scopeId:f.raw.scope.id,scopeHash:hash(f.raw.scope),attemptId:d.attemptId,requestId:d.binding.requestId,phase:'plan',actionHash:f.raw.actionHash,actionOrdinal:0,requestJson:JSON.stringify(d.binding.request),requestHash:wire.requestHash,wireBody:wire.wire.body,wireHash:wire.wireHash,quote:f.quote,dependencyPins:[]},candidate:d.candidate,dispatchedAt:d.binding.dispatchedAt,receipt:{status:'awaiting_receipt',requestId:d.binding.requestId,candidateHash:hash(d.candidate),attempts:0,nextCheckAt:null,receiptExpiresAt:new Date(now-1000+3600000).toISOString(),proofHash:null}};return{context,expectedPlanId:context.planId,expectedPlanHash:context.planHash,scope:f.raw.scope,preview:f.raw.preview,approvedQuote:f.quote,action:{actionHash:f.raw.actionHash,ordinal:0,phaseKeys:['plan','search1','select1','strategy','review'],attemptIds:[d.attemptId],reused:[]},saved,now,proof:d.proof};}
test('saved known-cost candidate without proof allows only receipt lookup after lease failure',async()=>{const x=await input(),r=await check(x);assert.equal(r.eligible,true);assert.equal(r.authorityCreated,false);assert.equal(r.mode,'receipt_lookup_only');assert.match(r.receiptProgressHash,/^[a-f0-9]{64}$/);});
test('verified proof permits saved projection and receipt progress changes independently of lease',async()=>{const x=await input(),a=await check(x);x.saved.proof=x.proof;x.saved.receipt.status='verified';x.saved.receipt.attempts=1;x.saved.receipt.proofHash=x.proof.proofHash;const b=await check(x);assert.equal(b.mode,'project_saved_receipt');assert.notEqual(a.receiptProgressHash,b.receiptProgressHash);x.context.attempt.reason='same data after lease renewal';assert.equal((await check(x)).receiptProgressHash,b.receiptProgressHash);});
test('foreign actions, changed wire, unknown costs, diagnostic, unsent and expired receipt states fail closed',async()=>{for(const mutate of[x=>x.action.actionHash='0'.repeat(64),x=>x.action.attemptIds=[],x=>x.context.attempt.status='reserved',x=>x.saved.binding.wireBody+=' ',x=>x.saved.candidate.reportedMicrousd=null,x=>x.saved.diagnostic={code:'json_parse'},x=>x.saved.receipt.status='stopped',x=>x.saved.receipt.status='terminal',x=>x.saved.receipt.candidateHash='0'.repeat(64),x=>x.now+=3600000,x=>x.saved.receipt.receiptExpiresAt=new Date(now+7200000).toISOString(),x=>x.saved.receipt.status='verified']){const x=await input();mutate(x);await assert.rejects(check(x));}});

test('authenticated SQL plan identity can differ from JS canonical body hash without permitting substitution',async()=>{
 const x=await input(),sqlPlanHash='b'.repeat(64);assert.notEqual(sqlPlanHash,hash(x.context.plan));
 x.expectedPlanHash=sqlPlanHash;x.context.planHash=sqlPlanHash;assert.equal((await check(x)).mode,'receipt_lookup_only');
 for(const mutate of [v=>v.context.planId='ffffffff-ffff-4fff-8fff-ffffffffffff',v=>v.expectedPlanId='ffffffff-ffff-4fff-8fff-ffffffffffff',v=>v.context.planHash='c'.repeat(64),v=>v.expectedPlanHash='c'.repeat(64),v=>v.expectedPlanHash='not-a-hash',v=>v.context.plan.businessId='ffffffff-ffff-4fff-8fff-ffffffffffff']){const changed=structuredClone(x);mutate(changed);await assert.rejects(check(changed));}
});

test('authenticated lease expiry only delays receipt wake and malformed dates fail closed',async()=>{
 const x=await input();x.leaseExpiresAt=new Date(now+60000).toISOString();x.saved.receipt.nextCheckAt=new Date(now+2000).toISOString();
 const future=await check(x);assert.equal(future.wakeAt,x.leaseExpiresAt);
 x.leaseExpiresAt=x.leaseExpiresAt.replace('.000Z','.000123+00:00');assert.equal((await check(x)).wakeAt,future.wakeAt);assert.equal(future.authorityCreated,false);assert.equal(future.mode,'receipt_lookup_only');
 x.leaseExpiresAt=new Date(now-1000).toISOString();assert.equal((await check(x)).wakeAt,x.saved.receipt.nextCheckAt);
 x.saved.receipt.nextCheckAt=new Date(now-2000).toISOString();assert.equal((await check(x)).wakeAt,new Date(now).toISOString());
 for(const value of ['invalid','2030-02-31T00:00:00.000Z','2026-10-10 00:00:00']){x.leaseExpiresAt=value;await assert.rejects(check(x));}
});
