import test from 'node:test';import assert from 'node:assert/strict';
import {fixture,phase,complete,archive} from './helpers/r12-adaptive-inputs-fixture.mjs';
import {id,now} from './helpers/r12-adaptive-fixture.mjs';
import {readAdaptivePhaseInputs,projectAdaptivePhaseResponse} from '../.core-tests/products/discovery-r12-adaptive-inputs.js';
import {buildAdaptivePhaseRequest} from '../.core-tests/products/discovery-r12-adaptive-runtime.js';
import {discoveryV2Hash as hash} from '../.core-tests/products/discovery-v2.js';
import {qualifyDiscoveryR12Candidate} from '../.core-tests/products/discovery-r12-receipt.js';
const originalNow=Date.now;test.before(()=>{Date.now=()=>now;});test.after(()=>{Date.now=originalNow;});
test('actual five phases reconstruct only qualified saved receipts and exact archived evidence',()=>{const f=fixture();complete(f,'plan',f.outputs.plan);complete(f,'search1',f.outputs.search1);complete(f,'select1',f.outputs.select1);archive(f);complete(f,'strategy',{assessment:f.outputs.strategy,measurement:null});const c=phase(f,'review');const review={version:'r12.adaptive-review.1',proposalHash:c.strategy.proposalHash,outcome:'NEEDS_MORE_EVIDENCE',ratings:Object.fromEntries(['evidence','learningValue','testDesign','feasibility'].map(k=>[k,{score:0,rationale:'This bounded source context does not resolve the current hypothesis.',evidenceRefs:[]}])),proposalConcerns:[],executionPrerequisites:[],additionalQuestions:[],sufficiencyRationale:'The current proposal lacks measurable bounded experiment outcomes.'};const r=complete(f,'review',review);assert.equal(r.projected.result.outcome,'NEEDS_MORE_EVIDENCE');assert.equal(r.projected.result.review.executionAuthorized,false);assert.deepEqual(r.projected.checkedArtifacts,f.ctx.attempt.dependencyPins);});
test('current action, dependency result, scope and archived source substitutions fail before building',()=>{const f=fixture();complete(f,'plan',f.outputs.plan);complete(f,'search1',f.outputs.search1);complete(f,'select1',f.outputs.select1);archive(f);phase(f,'strategy');for(const change of[r=>r.actionHash='0'.repeat(64),r=>r.intentPins.finance.runMaximumMicrousd=1,r=>r.dependencies[0].responseHash='0'.repeat(64),r=>r.archive[0].persisted.evidencePack.limitations.push('fabricated'),r=>r.archive=[],r=>r.intentPins.activeEvidenceArtifactIds=[],r=>r.dependencies[1].origin.actionHash='0'.repeat(64)]){const r=structuredClone(f.raw);change(r);assert.throws(()=>readAdaptivePhaseInputs(f.ctx,r));}});

test('review reconstructs original strategy snapshot while current run costs advance',()=>{const f=fixture();complete(f,'plan',f.outputs.plan);complete(f,'search1',f.outputs.search1);complete(f,'select1',f.outputs.select1);archive(f);const strategy=complete(f,'strategy',{assessment:f.outputs.strategy,measurement:null});f.raw.intentPins.finance.runCommittedMicrousd=4000;f.raw.intentPins.finance.actionCommittedMicrousd=4000;f.raw.intentPins.finance.rootCommittedMicrousd+=4000;f.raw.intentPins.finance.ledgerSnapshotHash='e'.repeat(64);const r=phase(f,'review');assert.equal(r.strategy.proposalHash,strategy.projected.result.proposalHash);assert.equal(r.binding.finance.runCommittedMicrousd,4000);assert.notEqual(r.strategy.adaptiveBindingHash,r.binding.bindingHash);const corrupt=structuredClone(f.raw);corrupt.dependencies.at(-1).intentPins.materialHistory=[{kind:'negative_finding',recordHash:'e'.repeat(64),statement:'A fabricated contrary finding substituted after strategy.',evidenceArtifactIds:[]}];assert.throws(()=>readAdaptivePhaseInputs(f.ctx,corrupt));});
test('followup builds a changed reviewed question with original public scope and identical source filter',()=>{const f=fixture();complete(f,'plan',f.outputs.plan);const oldHash=f.raw.actionHash;Object.assign(f.raw.action,{ordinal:1,kind:'followup',previousActionHash:oldHash,question:'Which dated observations distinguish gardening apparel comfort from motif preference?',phases:['search','select','strategy','review']});f.raw.actionHash=hash(f.raw.action);f.raw.intent=structuredClone(f.raw.intent);f.raw.intent.id=id(151);const query=`${f.raw.scope.approvedQuery}\nInvestigate: ${f.raw.action.question}`;f.raw.intent.comparisonUniverse.selectionQuestion=query;Object.assign(f.raw.intentPins,{actionHash:f.raw.actionHash,actionOrdinal:1,approvedQuery:query});Object.assign(f.ctx.attempt,{adaptiveActionHash:f.raw.actionHash,adaptiveActionOrdinal:1});const r=phase(f,'search1'),request=buildAdaptivePhaseRequest(r,r.validationAt);assert.equal(request.query,query);assert.notEqual(request.query,f.raw.scope.approvedQuery);assert.deepEqual(request.allowedDomains,f.raw.scope.allowedDomains);const changed=structuredClone(f.raw);changed.intentPins.approvedQuery=changed.scope.approvedQuery;changed.intent.comparisonUniverse.selectionQuestion=changed.scope.approvedQuery;assert.throws(()=>readAdaptivePhaseInputs(f.ctx,changed));});
test('response projection rejects another attempt or changed exact request before accepting a phase',()=>{const f=fixture(),done=complete(f,'plan',f.outputs.plan),qualified=qualifyDiscoveryR12Candidate(done.d.candidate,done.d.binding,done.d.proof);const wrong={...f.ctx,attempt:{...f.ctx.attempt,id:id(999)}};assert.throws(()=>projectAdaptivePhaseResponse(wrong,done.inputs,qualified,done.d.binding.request));const request=structuredClone(done.d.binding.request);request.messages[0].content+='changed';assert.throws(()=>projectAdaptivePhaseResponse(f.ctx,done.inputs,qualified,request));});
