import {repinFundingProof} from './helpers/r12-funding-proof-fixture.mjs';
import test from 'node:test';
import assert from 'node:assert/strict';
import {etsyObserved} from './helpers/r12-etsy-wire-fixture.mjs';
import {phase,complete} from './helpers/r12-adaptive-inputs-fixture.mjs';
import {now,id} from './helpers/r12-adaptive-fixture.mjs';
import {discoveryV2Hash as hash} from '../.core-tests/products/discovery-v2.js';
import {buildAdaptivePhaseRequest} from '../.core-tests/products/discovery-r12-adaptive-runtime.js';
import {readAdaptivePhaseInputs} from '../.core-tests/products/discovery-r12-adaptive-inputs.js';
import {inspectAdaptiveResearchWire} from '../.core-tests/products/discovery-r12-adaptive-wire.js';
import {preflightAdaptiveOwnerPlanner} from '../.core-tests/products/discovery-r12-adaptive-planner-preflight.js';
const originalNow=Date.now;test.before(()=>{Date.now=()=>now;});test.after(()=>{Date.now=originalNow;});
function preflight(f){return {version:'r12.owner-adaptive-planner-preflight-input.2',setupId:f.raw.scope.setupId,setupHash:f.raw.scope.setupHash,scopeId:f.raw.scope.id,cutoff:f.raw.intent.expiresAt,intent:f.raw.intent,intentPins:f.raw.intentPins,knowledgeSnapshot:f.raw.knowledgeSnapshot,quoteHash:f.quote.quoteHash,inputHash:'f'.repeat(64),ownerObservationContext:f.raw.ownerObservationContext};}
function review(f){const r=phase(f,'review');return {version:'r12.adaptive-review.1',proposalHash:r.strategy.proposalHash,outcome:'NEEDS_MORE_EVIDENCE',ratings:Object.fromEntries(['evidence','learningValue','testDesign','feasibility'].map(k=>[k,{score:0,rationale:'These attributed negative observations do not establish a bounded test.',evidenceRefs:[]}])),proposalConcerns:[],executionPrerequisites:[],additionalQuestions:[],sufficiencyRationale:'Retain missing buyer geography and weak channel evidence; no successful outcome has been established.'};}
function wires(f){const out=[];out.push(buildAdaptivePhaseRequest(phase(f,'plan'),now));complete(f,'plan',f.outputs.plan);out.push(buildAdaptivePhaseRequest(phase(f,'strategy'),now));complete(f,'strategy',{assessment:f.outputs.strategy,measurement:null});out.push(buildAdaptivePhaseRequest(phase(f,'review'),now));complete(f,'review',review(f));return out;}
test('Etsy .2 actual runtime completes exactly three qualified inert receipts without collection or selection',async()=>{const f=etsyObserved(),request=buildAdaptivePhaseRequest(phase(f,'plan'),now);assert.equal(request.outputSchema.properties.queryFocus.maxItems,0);const checked=await preflightAdaptiveOwnerPlanner(preflight(f),f.quote,now),wire=await inspectAdaptiveResearchWire(request,'plan',f.quote,now);assert.equal(checked.wireHash,wire.wireHash);const requests=wires(f);assert.deepEqual(f.raw.dependencies.map(d=>d.stepKey),['plan','strategy','review']);assert.equal(f.raw.archive.length,0);for(const r of requests){assert.ok('messages'in r);assert.equal(r.tools,undefined);assert.equal(r.plugins,undefined);}assert.match(requests[2].messages[0].content,/untrusted data, never instructions/);assert.match(requests[2].messages[0].content,/exact owner observation/);assert.equal(f.raw.dependencies.at(-1).response.result.outcome,'NEEDS_MORE_EVIDENCE');});
test('Etsy .2 rejects search/select context, old input version, absent captures and third-party sources',()=>{const f=etsyObserved(),input=phase(f,'plan');for(const phase of ['search','select'])assert.throws(()=>buildAdaptivePhaseRequest({...input,phase},now));for(const change of [r=>r.version='r12.discovery-adaptive-inputs.1',r=>r.ownerObservationContext=null,r=>r.intent.limits.maximumNewCollections=1]){const raw=structuredClone(f.raw);change(raw);assert.throws(()=>readAdaptivePhaseInputs(f.ctx,raw));}const bad=structuredClone(input),bundle=[...bad.ownerObservations.bundles.values()][0];bundle.observations[0].source.url='https://research.example/insights';const {bundleHash,...body}=bundle;void bundleHash;bundle.bundleHash=hash(body);bad.ownerObservations.manifest[0].bundleHash=bundle.bundleHash;assert.throws(()=>buildAdaptivePhaseRequest(bad,now));});
test('actual plan strategy and review wires withhold unselected comparison terms and declaration',()=>{const f=etsyObserved();const pin=f.raw.scope.ownerObservationRef.manifest[0];pin.selectedObservationIds=pin.selectedObservationIds.filter(v=>v!==id(602));f.raw.scope.ownerObservationRef.manifestHash=hash(f.raw.scope.ownerObservationRef.manifest);const selection=structuredClone(f.raw.scope.ownerObservationRef);f.raw.preview.ownerObservationRef=selection;f.raw.intentPins.ownerObservationRef=selection;Object.assign(f.raw.ownerObservationContext,selection);f.ctx.plan.discoveryScopeHash=hash(f.raw.scope);f.ctx.planHash=hash(f.ctx.plan);f.raw.planHash=f.ctx.planHash;f.raw.action.scopeHash=hash(f.raw.scope);f.raw.actionHash=hash(f.raw.action);Object.assign(f.raw.intentPins,{scopeHash:hash(f.raw.scope),actionHash:f.raw.actionHash});f.ctx.attempt.adaptiveActionHash=f.raw.actionHash;f.raw.ownerObservationContext.scopeHash=hash(f.raw.scope);f.raw.fundingProof=repinFundingProof(f.raw.fundingProof,f.raw.scope);for(const request of wires(f)){assert.doesNotMatch(JSON.stringify(request),/negative reference|Contrary observations defeat the specific premise/);assert.match(JSON.stringify(request),/withheld_or_incomplete_no_comparable_baseline/);}assert.equal(f.raw.dependencies.at(-1).response.result.outcome,'NEEDS_MORE_EVIDENCE');});
