/** Pure DTO/read-only builder parity. Real publication/ACL/state behavior is
 * qualified separately by the migrated-SQL enrollment suite. */
import test from 'node:test';
import assert from 'node:assert/strict';
import {createRequire} from 'node:module';
import {resolve} from 'node:path';
import {readFileSync,existsSync} from 'node:fs';
import {buildDirectEnrollmentReviewPackage,projectDirectEnrollmentReceipt,DIRECT_ENROLLMENT_PACKAGE_KEYS,DIRECT_ENROLLMENT_REGISTRY_KEYS} from './helpers/r12-direct-enrollment-review-package.mjs';
const require=createRequire(import.meta.url),core=resolve(process.env.R12_ENROLLMENT_CORE_DIR??'.core-tests');
const {discoveryV2Hash:hash}=require(resolve(core,'products/discovery-v2-hash.js'));
const {validateDirectEnrollmentReceipt,validateDirectEnrollmentInput}=require(resolve(core,'products/discovery-r12-direct-enrollment-contracts.js'));
const id=n=>`ce100000-0000-4000-8000-${String(n).padStart(12,'0')}`;
const validFrom='2026-10-10T00:00:00.000Z',reviewedAt='2026-10-10T00:01:00.000Z',expiresAt='2026-10-11T00:00:00.000Z';
function fixture(){
 const snapshot={rootPackId:id(8),releases:[{packId:id(8),version:'inert-registered-release'}]},calls=[];
 const state={businessRevision:17,businessHash:hash('inert-business'),goalRevision:14,goalHash:hash('inert-goal'),bindingId:id(7),authorityRootId:id(6),originHash:hash('inert-history'),fundingSnapshotHash:hash('inert-canonical-funding'),currentGrantRoot:{rootId:id(3),revision:2,revisionHash:hash('inert-root-revision2'),maximumScopes:3,maximumAllocationMicrounits:'1220208',scopesUsed:3,allocationUsedMicrounits:'1220208'}};
 const read={state,definition_hash:hash('inert-database-definitions'),pack:{id:id(8),status:'qualified',manifestHash:hash('inert-registered-manifest'),qualificationHash:hash('inert-registered-qualification')},installation:{id:id(9),businessId:id(1),rootPackId:id(8),status:'active',snapshotHash:hash('inert-r04-jsonb-snapshot'),canonicalSnapshotHash:hash(snapshot)},origin_profile_hash:hash('inert-old-expired-profile'),owner_matches:true,grant_exists:false,profile_exists:false};
 const registry=Object.fromEntries(Object.entries(DIRECT_ENROLLMENT_REGISTRY_KEYS).map(([name,keys])=>[name,Object.fromEntries(keys.split(',').map(k=>[k,hash({inert:name,key:k})]))]));
 const route=registry.browserRoute;Object.assign(route,{provider_project_id:id(10),maximum_session_ms:60000,maximum_session_microunits:1000,content:{version:'r12.steel-browser-route.1',usageBound:{version:'r12.steel-usage-bound.1',maximumProxyBytes:0,tariffCoversSessionAndProfileLifecycle:true,captchaDisabled:true,extraServicesDisabled:true},priceEvidenceHash:hash('inert-public-price-evidence'),retentionDisclosure:'Synthetic provider review only. No live provider qualification.'},valid_from:validFrom,valid_until:expiresAt});route.content_hash=hash(route.content);
 for(const name of ['ownerRenderer','sourceQualification','verificationCandidate','researchRenderer'])Object.assign(registry[name],{route_hash:route.route_hash,provider_project_id:id(10),valid_from:validFrom,valid_until:expiresAt});
 registry.ownerRenderer.policy={version:'etsy.owner-bootstrap-policy.1'};registry.ownerRenderer.policy_hash=hash(registry.ownerRenderer.policy);delete registry.ownerRenderer.review_hash;registry.ownerRenderer.review_hash=hash(registry.ownerRenderer);
 const source=registry.sourceQualification;Object.assign(source,{worker_definition_id:id(11),workflow_definition_id:id(12),purpose:'etsy_insights_read_only',content:{version:'r12.direct-source-qualification.1',rendererPolicy:{version:'etsy.insights-renderer-research-policy.4'}}});source.qualification_hash=hash(source.content);
 registry.verificationCandidate.content={version:'r12.insights-verification-candidate-review.3',landingControlsHash:hash('inert-landing-controls')};registry.verificationCandidate.review_hash=hash(registry.verificationCandidate.content);
 Object.assign(registry.researchRenderer,{qualification_hash:source.qualification_hash,candidate_review_hash:registry.verificationCandidate.review_hash,content:{version:'r12.insights-proof-bound-source-review.4'}});registry.researchRenderer.review_hash=hash(registry.researchRenderer.content);
 const grantReview={version:'r12.direct-grant-review.1',grantId:id(90),goalId:id(2),goalRevision:1,goalHash:hash('old'),providerProjectId:id(10),routeHash:route.route_hash,maximumTestMicrounits:'10000000',maximumAttemptsInWindow:10,cumulativeDispatchesCeiling:64,setupOperation:{operationKey:'browser.etsy.owner_handoff.create'},verificationOperation:{operationKey:'browser.etsy.account_verification.create'},researchPins:{packId:id(8),installationId:id(9),snapshot,snapshotHash:hash('inert-r04-jsonb-snapshot'),workflowDefinitionId:id(12),executionReviewHash:source.qualification_hash,inferenceCatalogHash:hash('inert-model-catalog')},profileTemplate:{id:id(91),marketSetKey:'synthetic-market',topicKey:'synthetic-topic',markets:[{countryCode:'GB',currency:'GBP'}],audience:'Adult synthetic fixture buyers',publicGoal:'Inert original product research',productFormat:'original_pod_tshirt',category:'original apparel'},approvalHash:hash('inert-operator-review'),expiresAt};
 const commit='1'.repeat(40),externalEvidence={release:{commitSha:commit,treeSha:'2'.repeat(40),qualificationRuns:['ci.yml','direct-etsy-qualification.yml','etsy-browser-boundary.yml'].map((workflow,n)=>({workflow,runId:String(100+n),headSha:commit,conclusion:'success',artifactHash:hash({inert:true,workflow})})),deploymentReceiptHash:hash('inert-deployment')},provider:{projectReadbackHash:hash('inert-project-readback'),retentionReviewHash:hash('inert-retention-review')},security:{scope:'r12.direct-steel-insights.1',approvalHash:hash('inert-security-approval'),recordHash:hash('inert-security-record')},model:{routeReviewHash:hash('inert-route-review'),schemaReviewHash:hash('inert-schema-review'),dataUseReviewHash:hash('inert-data-use'),inferenceContract:{version:'r12.direct-inference-contract.1',publicQuoteVersion:'r12.public-research-quote.3',inferenceQuoteVersion:'r12.direct-inference-quote.1',catalogVersion:'r12.direct-inference-catalog.1',luna:{modelId:'openai/gpt-5.6-luna',canonicalModelId:'openai/gpt-5.6-luna-20260709',endpoint:'azure/us',providerName:'Azure'},reviewer:{modelId:'anthropic/claude-sonnet-4.6',canonicalModelId:'anthropic/claude-4.6-sonnet-20260217',endpoint:'amazon-bedrock/us',providerName:'Amazon Bedrock'}}}};
 const input={businessId:id(1),goalId:id(2),rootId:id(3),ownerId:id(4),originProfileId:id(5),grantId:id(13),profileId:id(14),serverKeyHash:hash('inert-app-derived-verifier'),grantReview,registry,reviewedAt,validFrom,expiresAt,externalEvidence};
 const db={query:async(sql,params)=>{calls.push({sql,params});return{rows:[structuredClone(read)]};}};
 return{input,read,db,calls};
}
test('package builder reads registered fixture state only, preserving exact history and independently supplied evidence',async()=>{
 const f=fixture(),before=structuredClone(f.input),result=await buildDirectEnrollmentReviewPackage(f.db,f.input),p=result.package;
 assert.deepEqual(f.input,before);assert.equal(f.calls.length,1);assert.match(f.calls[0].sql,/^select/);assert.doesNotMatch(f.calls[0].sql,/\b(insert|update|delete|publish|activate|register|qualify)\b/i);
 assert.notEqual(f.read.installation.snapshotHash,f.read.installation.canonicalSnapshotHash);assert.equal(p.grantReview.researchPins.snapshotHash,f.read.installation.snapshotHash);assert.match(f.calls[0].sql,/private\.r04_hash\(i\.snapshot\)/);assert.match(f.calls[0].sql,/private\.stage14_hash\(i\.snapshot\)/);
 assert.deepEqual(p.expectedState,f.read.state);assert.equal(p.originProfileId,f.input.originProfileId);assert.equal(p.originProfileHash,f.read.origin_profile_hash);assert.equal(p.grantReview.profileTemplate.id,f.input.profileId);assert.equal(p.grantReview.goalHash,f.read.state.goalHash);
 assert.deepEqual(result.reviewEvidence.model.inferenceContract,f.input.externalEvidence.model.inferenceContract);
 assert.deepEqual(result.reviewEvidence.release.qualificationRuns,f.input.externalEvidence.release.qualificationRuns);assert.equal(result.reviewEvidence.release.databaseDefinitionHash,f.read.definition_hash);assert.equal(result.reviewEvidence.pack.manifestHash,f.read.pack.manifestHash);assert.equal(p.reviewEvidenceHash,hash(result.reviewEvidence));
 assert.equal(p.registry.sourceQualification.qualification_hash,f.input.registry.sourceQualification.qualification_hash);assert.deepEqual(Object.keys(p).sort(),DIRECT_ENROLLMENT_PACKAGE_KEYS.split(',').sort());
});
test('publication arguments project to exact owner DTO with stored-plus-one arithmetic and no private verifier/provider data',async()=>{
 const f=fixture(),packet=await buildDirectEnrollmentReviewPackage(f.db,f.input),r=projectDirectEnrollmentReceipt(packet,{proposalId:id(15),createdAt:reviewedAt});
 assert.deepEqual(validateDirectEnrollmentReceipt(r,{businessId:id(1),goalId:id(2),ownerId:id(4)}),r);assert.equal(r.preview.currentGrantRoot.scopesUsed,3);assert.equal(r.preview.proposedGrantRoot.maximumScopes,4);assert.equal(r.preview.proposedGrantRoot.maximumAllocationMicrounits,'11220208');
 assert.equal(r.preview.authorityCreated,false);assert.equal(r.confirmed,false);assert.equal(JSON.stringify(r).includes(f.input.serverKeyHash),false);assert.equal(JSON.stringify(r).includes(id(10)),false);
 assert.equal(validateDirectEnrollmentReceipt(projectDirectEnrollmentReceipt(packet,{proposalId:id(15),createdAt:reviewedAt,confirmed:true})).confirmed,true);
 assert.throws(()=>validateDirectEnrollmentInput(packet.package),'A reviewed operator package cannot enter the reference-only owner RPC');
});
for(const [name,mutate]of [
 ['foreign owner',f=>{f.read.owner_matches=false;}],['already materialized grant',f=>{f.read.grant_exists=true;}],['old profile reused',f=>{f.read.profile_exists=true;}],['unqualified root pack',f=>{f.read.pack.status='experimental';}],['inactive installation',f=>{f.read.installation.status='superseded';}],['foreign installation',f=>{f.read.installation.businessId=id(99);}],['changed installed snapshot',f=>{f.read.installation.snapshotHash=hash('changed');}],['changed payload with unchanged R04 pin',f=>{f.input.grantReview.researchPins.snapshot.releases[0].version='changed';}],['wrong reviewed reviewer identity',f=>{f.input.externalEvidence.model.inferenceContract.reviewer.modelId='anthropic/claude-haiku-4.5';}],['unversioned model selection',f=>{delete f.input.externalEvidence.model.inferenceContract;}],['missing independent external evidence',f=>{delete f.input.externalEvidence.provider.projectReadbackHash;}],['arbitrary registry column',f=>{f.input.registry.browserRoute.secret='forbidden';}],['missing original profile proof',f=>{f.read.origin_profile_hash=null;}],
 ])test(`builder rejects ${name} and performs no write`,async()=>{const f=fixture();mutate(f);await assert.rejects(buildDirectEnrollmentReviewPackage(f.db,f.input),/inert_enrollment_package_/);assert.ok(f.calls.every(c=>/^select/.test(c.sql)));});
test('repair-aware unit window remains independent of actual dispatch ceiling',async()=>{
 const f=fixture();f.input.grantReview.maximumAttemptsInWindow=32;const packet=await buildDirectEnrollmentReviewPackage(f.db,f.input),r=projectDirectEnrollmentReceipt(packet,{proposalId:id(15),createdAt:reviewedAt});assert.equal(validateDirectEnrollmentReceipt(r).preview.testBounds.maximumUnitsInWindow,32);assert.equal(r.preview.testBounds.cumulativeDispatchesCeiling,64);
});
test('valid above-base usage stays in state and cannot become automatic catch-up authority',async()=>{
 const f=fixture();f.read.state.currentGrantRoot.maximumScopes=1;f.read.state.currentGrantRoot.maximumAllocationMicrounits='406736';const before=structuredClone(f.read.state),packet=await buildDirectEnrollmentReviewPackage(f.db,f.input);assert.deepEqual(packet.package.expectedState,before);assert.throws(()=>projectDirectEnrollmentReceipt(packet,{proposalId:id(15),createdAt:reviewedAt}),/separate_cumulative_review_required/);assert.deepEqual(f.read.state,before);
});
test('builder package and registry keysets track the exact additive SQL publisher schema',()=>{
 const base='supabase/migrations/20261010121000_r12_direct_reviewed_enrollment.sql',sql=readFileSync(existsSync(base)?base:base+'.wip','utf8');
 const keys=sql.match(/r04_keys\(p_package,array\[([^\]]+)\]/)?.[1].match(/'([^']+)'/g)?.map(x=>x.slice(1,-1));assert.deepEqual(keys?.sort(),DIRECT_ENROLLMENT_PACKAGE_KEYS.split(',').sort());
 for(const[name,alias]of Object.entries({browserRoute:'r',ownerRenderer:'o',sourceQualification:'s',verificationCandidate:'v',researchRenderer:'w'})){
  const found=sql.match(new RegExp(`r04_keys\\(${alias},array\\[([^\\]]+)\\]`))?.[1].match(/'([^']+)'/g)?.map(x=>x.slice(1,-1));assert.deepEqual(found?.sort(),DIRECT_ENROLLMENT_REGISTRY_KEYS[name].split(',').sort(),name);
 }
});
