import test from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {discoveryKnowledgeFixture} from './discovery-v2-fixtures.mjs';
import {r12PhaseOutputFixture} from './helpers/r12-phase-output-fixture.mjs';
import {bindValidatedAdaptiveResearchIntent as bind} from '../.core-tests/products/discovery-r12-adaptive-intent.js';
import {qualifyAdaptiveResearchQuote} from '../.core-tests/products/discovery-r12-adaptive-quote.js';
import {buildAdaptivePhaseRequest} from '../.core-tests/products/discovery-r12-adaptive-runtime.js';
import {inspectAdaptiveResearchWire} from '../.core-tests/products/discovery-r12-adaptive-wire.js';
import {preflightAdaptiveOwnerPlanner} from '../.core-tests/products/discovery-r12-adaptive-planner-preflight.js';
const now=Date.parse('2026-10-05T23:53:20Z'),id=n=>`00000000-0000-4000-8000-${String(n).padStart(12,'0')}`;
function catalogs(){const saved=JSON.parse(readFileSync('tests/fixtures/r12-provider-catalogs.json','utf8'));const [luna,haiku]=structuredClone(saved.endpoints);delete luna.canonicalModelId;delete haiku.canonicalModelId;const base='https://openrouter.ai/api/v1',s=(url,payload)=>({url,fetchedAt:new Date(now).toISOString(),payload});return{models:s(`${base}/models`,{data:saved.endpoints.map(e=>({id:e.model_id,canonical_slug:e.canonicalModelId,links:{details:`/api/v1/models/${e.canonicalModelId}/endpoints`}}))}),lunaAlias:s(`${base}/models/${luna.model_id}/endpoints`,{data:{id:luna.model_id,endpoints:[luna]}}),lunaCanonical:s(`${base}/models/${saved.endpoints[0].canonicalModelId}/endpoints`,{data:{id:luna.model_id,endpoints:[structuredClone(luna)]}}),reviewerAlias:s(`${base}/models/${haiku.model_id}/endpoints`,{data:{id:haiku.model_id,endpoints:[haiku]}}),reviewerCanonical:s(`${base}/models/${saved.endpoints[1].canonicalModelId}/endpoints`,{data:{id:haiku.model_id,endpoints:[structuredClone(haiku)]}}),zdr:s(`${base}/endpoints/zdr`,{data:[structuredClone(luna),structuredClone(haiku)]})};}
function fixture(){const intent={version:'pod-discovery-2.0',id:id(1),businessId:id(2),objective:'Compare original nature shirt hypotheses through bounded public research without commercial execution.',comparisonUniverse:{productType:'original_pod_tshirt',markets:[{countryCode:'US',currency:'USD'},{countryCode:'GB',currency:'GBP'},{countryCode:'AU',currency:'AUD'},{countryCode:'NZ',currency:'NZD'}],audiences:['adult T-shirt buyers'],sourceDomains:['adult-outdoors.example'],selectionQuestion:'Compare adult nature shirt research using dated public apparel observations and preserve every material limitation.'},limits:{maximumAlternatives:3,maximumNewCollections:1,maximumMicrousd:10000000,maximumGenerations:1},expiresAt:new Date(now+3600000).toISOString()};const pins={scopeVersion:'r12.discovery-owner-adaptive.1',scopeId:id(3),scopeHash:'a'.repeat(64),actionHash:'b'.repeat(64),actionOrdinal:0,approvedQuery:intent.comparisonUniverse.selectionQuestion,finance:{authorityRootId:id(4),ledgerSnapshotHash:'c'.repeat(64),runMaximumMicrousd:10000000,runCommittedMicrousd:0,rootMaximumMicrousd:10265736,rootCommittedMicrousd:265736,actionMaximumMicrousd:1000000,actionCommittedMicrousd:0},evidenceManifest:[],activeEvidenceArtifactIds:[],ownerObservationRef:null,materialHistory:[{kind:'prior_decision',recordHash:'d'.repeat(64),statement:'Prior broad research did not establish a geographic winner.',evidenceArtifactIds:[]}]};return{intent,pins,binding:bind(intent,pins,now),knowledge:discoveryKnowledgeFixture(now),outputs:r12PhaseOutputFixture(intent.comparisonUniverse.audiences[0])};}
const originalNow=Date.now; test.before(()=>{Date.now=()=>now;}); test.after(()=>{Date.now=originalNow;});
function packet(f,q){return{version:'r12.owner-adaptive-planner-preflight-input.1',setupId:id(8),setupHash:'e'.repeat(64),scopeId:f.pins.scopeId,cutoff:f.intent.expiresAt,intent:f.intent,intentPins:f.pins,knowledgeSnapshot:f.knowledge.snapshot,quoteHash:q.quoteHash,inputHash:'f'.repeat(64),ownerObservationContext:null};}
test('preflight serializes the actual complete adaptive planner with exact hashes and no transport',async()=>{const f=fixture(),q=qualifyAdaptiveResearchQuote(catalogs(),now),p=packet(f,q);const original=globalThis.fetch;let calls=0;globalThis.fetch=async()=>{calls++;throw Error('unexpected transport');};try{const result=await preflightAdaptiveOwnerPlanner(p,q,now),wire=await inspectAdaptiveResearchWire(buildAdaptivePhaseRequest({phase:'plan',binding:f.binding,knowledge:f.knowledge},now),'plan',q,now);assert.equal(result.wireHash,wire.wireHash);assert.equal(result.requestHash,wire.requestHash);assert.equal(result.bindingHash,f.binding.bindingHash);assert.equal(result.wireBytes,wire.wireBytes);assert.equal(result.inputHash,p.inputHash);assert.ok(result.requestBytes<=q.requestBytes.plan);assert.equal(calls,0);}finally{globalThis.fetch=original;}});
test('preflight rejects substituted scope, quote, noninitial costs/action and expired input',async()=>{const f=fixture(),q=qualifyAdaptiveResearchQuote(catalogs(),now);for(const change of[p=>p.scopeId=id(9),p=>p.quoteHash='0'.repeat(64),p=>p.intentPins.actionOrdinal=1,p=>p.intentPins.finance.runCommittedMicrousd=1,p=>p.intentPins.finance.actionCommittedMicrousd=1,p=>p.cutoff=new Date(now-1).toISOString(),p=>p.intent.limits.maximumNewCollections=0,p=>p.extra='unexpected',p=>p.knowledgeSnapshot.releases=[]]){const p=structuredClone(packet(f,q));change(p);await assert.rejects(preflightAdaptiveOwnerPlanner(p,q,now),/preflight_failed/);}await assert.rejects(preflightAdaptiveOwnerPlanner(packet(f,q),q,now+300000),/preflight_failed/);});
test('root ledger and inherited negative history change actual request pins; oversized complete history fails without truncation',async()=>{const f=fixture(),q=qualifyAdaptiveResearchQuote(catalogs(),now),p=packet(f,q),a=await preflightAdaptiveOwnerPlanner(p,q,now);for(const change of[p=>p.intentPins.finance.rootCommittedMicrousd++,p=>p.intentPins.materialHistory[0].statement='Prior evidence refuted this hypothesis; preserve this contrary finding.']){const changed=structuredClone(p);change(changed);const b=await preflightAdaptiveOwnerPlanner(changed,q,now);assert.notEqual(b.bindingHash,a.bindingHash);assert.notEqual(b.requestHash,a.requestHash);assert.notEqual(b.wireHash,a.wireHash);}const large=structuredClone(p);large.intentPins.materialHistory=Array.from({length:100},(_,i)=>({kind:'negative_finding',recordHash:String(i).padStart(64,'0'),statement:'A'.repeat(600),evidenceArtifactIds:[]}));await assert.rejects(preflightAdaptiveOwnerPlanner(large,q,now),/preflight_failed/);});
