import test from 'node:test';
import assert from 'node:assert/strict';
import {r12CatalogFixture} from './helpers/r12-provider-fixture.mjs';
import {qualifyFocusedCreativeQuote,fetchFocusedCreativeQuote} from '../.core-tests/creative/focused-quote.js';
const now=Date.parse('2026-10-07T01:00:00.000Z');
function fixture(){const catalogs=r12CatalogFixture(now);catalogs.models.payload.data[1].architecture={input_modalities:['text','image'],output_modalities:['text']};return{catalogs,image:{url:'https://openrouter.ai/api/v1/images/models/black-forest-labs/flux.2-klein-4b/endpoints',fetchedAt:new Date(now-1000).toISOString(),payload:{id:'black-forest-labs/flux.2-klein-4b',endpoints:[{provider_tag:'black-forest-labs',provider_slug:'black-forest-labs',provider_name:'Black Forest Labs',supported_parameters:{aspect_ratio:{type:'enum',values:['1:1']},n:{type:'range',min:1,max:1},output_format:{type:'enum',values:['png']}},pricing:[{billable:'output_image',unit:'megapixel',cost_usd:.014}]}]}}};}
test('focused creative prices exact Azure/Bedrock text tiers and one native BFL image without inheriting image ZDR',()=>{const f=fixture(),q=qualifyFocusedCreativeQuote(f.catalogs,f.image,true,now);assert.deepEqual(q.approvalQuote.maximaMicrousd,{brief:37391,screen:118035,generation:70000,review:145068});assert.equal(q.approvalQuote.maximumEstimateMicrousd,370494);assert.equal(q.approvalQuote.maximumCalls,4);assert.equal(q.dispatchAuthorized,false);assert.equal(q.luna.endpoint,'azure/us');assert.equal(q.reviewer.endpoint,'amazon-bedrock/us');assert.equal(q.approvalQuote.providerBinding.disclosureVersion,'bfl-openrouter-data-use-1.0');assert.equal(q.validUntil,'2026-10-07T01:04:59.000Z');});
test('focused creative rejects missing image capability, acknowledgement, stale image catalog and extra image billing',()=>{for(const change of [f=>f.catalogs.models.payload.data[1].architecture.input_modalities=['text'],f=>f.image.fetchedAt=new Date(now-300000).toISOString(),f=>f.image.payload.endpoints[0].pricing.push({billable:'request',unit:'request',cost_usd:.01}),f=>f.image.payload.endpoints[0].provider_tag='other']){const f=fixture();change(f);assert.throws(()=>qualifyFocusedCreativeQuote(f.catalogs,f.image,true,now));}const f=fixture();assert.throws(()=>qualifyFocusedCreativeQuote(f.catalogs,f.image,false,now));});
test('focused creative quote performs exactly seven public credential-free catalog reads and respects cached age',async()=>{const f=fixture(),map=new Map([...Object.values(f.catalogs),f.image].map(s=>[s.url,s])),calls=[];const q=await fetchFocusedCreativeQuote(true,{now:()=>now,fetch:async(url,init)=>{assert.equal(init.method,'GET');assert.equal(init.credentials,'omit');assert.equal(init.body,undefined);assert.equal(init.headers.Authorization,undefined);assert.ok(map.has(url));calls.push(url);return new Response(JSON.stringify(map.get(url).payload),{headers:{Age:'1'}});}});assert.equal(calls.length,7);assert.equal(new Set(calls).size,7);assert.equal(q.verifiedAt,'2026-10-07T00:59:59.000Z');await assert.rejects(fetchFocusedCreativeQuote(true,{now:()=>now,fetch:async()=>new Response('{}',{headers:{Age:'300'}})}));});
test('each text dispatch binds fresh qualified route prices within the fixed approval ceiling',async()=>{
 const{focusedCreativeDispatchQuote}=await import('../.core-tests/creative/focused-quote.js');const{validateFocusedCreativeDispatchQuote}=await import('../.core-tests/creative/focused-runtime-contract.js');const f=fixture(),q=qualifyFocusedCreativeQuote(f.catalogs,f.image,true,now),scope={phaseCeilings:{'brief:1':37391,'screen:1':118035,'review:1':145068},priceLimitsByPhase:{'brief:1':q.luna.priceLimit,'screen:1':q.reviewer.priceLimit,'review:1':q.reviewer.priceLimit}};
 for(const phase of ['brief:1','screen:1','review:1']){const d=focusedCreativeDispatchQuote(q,scope,phase,now);assert.equal(d.callKey,phase);assert.equal(d.sourceQuoteHash,q.quoteHash);assert.doesNotThrow(()=>validateFocusedCreativeDispatchQuote(d,scope,phase,now));assert.throws(()=>validateFocusedCreativeDispatchQuote(d,scope,phase,Date.parse(d.validUntil)));assert.throws(()=>validateFocusedCreativeDispatchQuote({...d,endpoint:'other'},scope,phase,now));assert.throws(()=>focusedCreativeDispatchQuote(q,{...scope,phaseCeilings:{...scope.phaseCeilings,[phase]:scope.phaseCeilings[phase]-1}},phase,now));}
 assert.throws(()=>focusedCreativeDispatchQuote(q,{...scope,priceLimitsByPhase:{...scope.priceLimitsByPhase,'brief:1':{prompt:0,completion:0,request:0}}},'brief:1',now));
});
