import test from 'node:test';
import assert from 'node:assert/strict';
import {loadPublic,hash} from './r12-public-fixtures.mjs';
import {fixture,runEtsyInsightsResearch,id} from './helpers/r12-public-insights-model-fixture.mjs';
const p=await loadPublic('model-projection');
async function sources(n=10){const receipts=[];for(let ordinal=1;ordinal<=n;ordinal++){const f=fixture({operationId:id(1000+ordinal),sourceAttemptId:id(2000+ordinal),attemptOrdinal:ordinal,windowAttemptOrdinal:ordinal,window:{maximumAttemptsInWindow:10},query:`pottery comparison ${ordinal}`});const result=await runEtsyInsightsResearch(f.s,f.d);assert.equal(result.persistence,'verified');assert.equal(result.receipt.status,'completed');receipts.push(result.receipt);}return receipts;}
test('ten actual inert captures project forty substantive references with all context and immutable full receipts retained',async()=>{
 const receipts=await sources(),original=hash(receipts),r=p.projectPublicResearchModelSources(receipts,'review');
 assert.equal(receipts.flatMap(r=>r.witnesses).length,90);assert.equal(r.evidence.length,40);assert.equal(r.sourceContexts.length,10);assert.equal(r.selection.contextRefs.length,40);assert.equal(r.selection.privateIdentityFactCount,10);
 assert.deepEqual([...new Set(r.evidence.map(x=>x.kind))].sort(),['conversion_statement','price','results','searches']);assert.ok(r.sourceContexts.every(c=>c.facts.some(f=>f.kind==='reporting_window'&&f.quote==='Last 30 days')));assert.ok(r.sourceContexts.every(c=>c.facts.some(f=>f.kind==='aggregate_region'&&f.quote==='Region: Worldwide')));assert.ok(r.evidence.some(x=>x.quote==='Searches: 2.4k'));assert.equal(hash(receipts),original);
 const{selectionHash,...body}=r.selection;assert.equal(selectionHash,hash(body));assert.equal(p.publicResearchModelSelectionDisclosure(r.selection).selectedMetricCount,40);
 assert.deepEqual(p.projectPublicResearchModelSources([...receipts].reverse(),'review'),r,'Receipt arrival order does not alter projection');
});
test('projection partitions every witnessed fact and fails oversized metrics instead of truncating',async()=>{
 const receipts=await sources(1),r=p.projectPublicResearchModelSources(receipts,'strategy');assert.equal(r.evidence.length+r.selection.contextRefs.length+r.selection.privateIdentityFactCount,receipts[0].witnesses.length);
 const many=Array.from({length:13},(_,n)=>{const x=structuredClone(receipts[0]);x.attemptOrdinal=n+1;x.receiptHash=hash(n);for(const c of x.captures){const old=c.captureHash;c.captureHash=hash(`capture-${n}`);for(const w of x.witnesses)w.ref=w.ref.replace(old,c.captureHash);}return x;});assert.throws(()=>p.projectPublicResearchModelSources(many,'review'),/substantive_evidence_bound/);
 const missing=structuredClone(receipts);missing[0].witnesses=[];assert.throws(()=>p.projectPublicResearchModelSources(missing,'review'),/witness_required/);assert.throws(()=>p.projectPublicResearchModelSources(receipts,'search'));
});
test('local history retains conclusions, all contrary/gap/rationale text, failed attempts and original commands',()=>{
 const rating=d=>({rationale:`Rationale ${d}`,evidenceRefs:['support'],contraryRefs:[`opposition-${d}`],missingFacts:[`Missing ${d}`]});const quality=Object.fromEntries(['sourceFidelity','decisionRelevance','measurementComparability','counterevidence','uncertaintyDiscipline'].map(d=>[d,rating(d)]));
 const review={reviewHash:hash('review'),outcome:'NME',hypothesisFinding:'undetermined',conclusion:'An inconclusive hypothesis remains in history.',conclusionEvidenceRefs:['conclusion'],contraryEvidenceRefs:['contradiction'],missingCriticalRequirements:['Exact exposure remains unknown.'],quality:{qualityBasisPoints:6000,quality}};
 const state={attempts:[{ordinal:1,kind:'initial',status:'completed',command:{query:'old hypothesis'},failureHash:null,review},{ordinal:2,kind:'technical_retry',status:'technical_failed',command:{query:'failed retry'},failureHash:hash('failure'),review:null},{ordinal:3,status:'running'}]};const out=p.publicResearchModelLocalHistory(state);
 assert.equal(out.length,2);assert.deepEqual(out[0].command,state.attempts[0].command);assert.equal(out[0].review.findingRationales.length,5);assert.equal(out[0].review.contraryEvidenceRefs.length,6);assert.equal(out[0].review.missingFacts.length,6);assert.equal(out[1].failureHash,hash('failure'));assert.equal(out[1].review,null);assert.equal(hash(state.attempts[0].review),hash(review));
});
test('wire citation indexes reconstruct every historical reference without changing full return IDs',()=>{const quality=Object.fromEntries(['sourceFidelity','decisionRelevance','measurementComparability','counterevidence','uncertaintyDiscipline'].map(d=>[d,{rationale:d,evidenceRefs:['ref-a'],contraryRefs:['archived-ref'],missingFacts:['Still unknown']}]));const state={attempts:[{ordinal:1,kind:'initial',status:'completed',command:{kind:'targeted',query:'literal query',criteriaHash:'criteria',questionHash:'question',namedGap:'Literal question?',expectedInformationGain:'Meaning',opposingCheck:'Countercheck',changedCriterion:null},failureHash:null,review:{reviewHash:hash('review'),outcome:'NME',hypothesisFinding:'undetermined',conclusion:'Preserved.',conclusionEvidenceRefs:['ref-b'],contraryEvidenceRefs:['ref-a'],missingCriticalRequirements:[],quality:{qualityBasisPoints:6000,quality}}},{ordinal:2,status:'running'}]};const evidence=[{ref:'ref-b'},{ref:'ref-a'}],full=p.publicResearchModelLocalHistory(state)[0],wire=p.publicResearchModelLocalHistoryWire(state,evidence)[0],decode=x=>[...x.sourceEvidenceZeroBasedIndexes.map(n=>evidence[n].ref),...x.archivedRefs].sort();assert.deepEqual(decode(wire.review.supportingEvidenceRefs),full.review.supportingEvidenceRefs);assert.deepEqual(decode(wire.review.contraryEvidenceRefs),full.review.contraryEvidenceRefs);assert.equal(wire.command.query,full.command.query);assert.equal(wire.command.namedGap,full.command.namedGap);assert.equal('criteriaHash'in wire.command,false);assert.equal(state.attempts[0].command.criteriaHash,'criteria');});
