import test from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {discoveryKnowledgeFixture} from './discovery-v2-fixtures.mjs';
import {r12PhaseOutputFixture} from './helpers/r12-phase-output-fixture.mjs';
import {bindValidatedAdaptiveResearchIntent as bind,assertValidatedAdaptiveResearchIntent} from '../.core-tests/products/discovery-r12-adaptive-intent.js';
import {discoveryV2Hash as hash,validateDiscoveryIntentV2} from '../.core-tests/products/discovery-v2.js';
import {prepareDiscoveryWorkerContextV2} from '../.core-tests/products/discovery-v2-worker-contract.js';
import {qualifyGenerationRouteProof} from '../.core-tests/research/generation-route.js';
import {qualifyAdaptiveResearchQuote,validateAdaptiveResearchQuote} from '../.core-tests/products/discovery-r12-adaptive-quote.js';
import {routeAdaptiveResearchRequest,inspectAdaptiveResearchWire} from '../.core-tests/products/discovery-r12-adaptive-wire.js';
import {buildAdaptivePhaseRequest,projectAdaptivePhaseOutput} from '../.core-tests/products/discovery-r12-adaptive-runtime.js';
import {adaptiveReviewerResponseSchema} from '../.core-tests/products/discovery-r12-adaptive-review-contract.js';
const now=Date.parse('2026-10-05T23:53:20Z'),id=n=>`00000000-0000-4000-8000-${String(n).padStart(12,'0')}`;
const clock=async fn=>{const original=Date.now;Date.now=()=>now;try{return await fn();}finally{Date.now=original;}};
function catalogs(){const saved=JSON.parse(readFileSync('tests/fixtures/r12-provider-catalogs.json','utf8'));const [luna,haiku]=structuredClone(saved.endpoints);delete luna.canonicalModelId;delete haiku.canonicalModelId;const base='https://openrouter.ai/api/v1',s=(url,payload)=>({url,fetchedAt:new Date(now).toISOString(),payload});return{models:s(`${base}/models`,{data:saved.endpoints.map(e=>({id:e.model_id,canonical_slug:e.canonicalModelId,links:{details:`/api/v1/models/${e.canonicalModelId}/endpoints`}}))}),lunaAlias:s(`${base}/models/${luna.model_id}/endpoints`,{data:{id:luna.model_id,endpoints:[luna]}}),lunaCanonical:s(`${base}/models/${saved.endpoints[0].canonicalModelId}/endpoints`,{data:{id:luna.model_id,endpoints:[structuredClone(luna)]}}),reviewerAlias:s(`${base}/models/${haiku.model_id}/endpoints`,{data:{id:haiku.model_id,endpoints:[haiku]}}),reviewerCanonical:s(`${base}/models/${saved.endpoints[1].canonicalModelId}/endpoints`,{data:{id:haiku.model_id,endpoints:[structuredClone(haiku)]}}),zdr:s(`${base}/endpoints/zdr`,{data:[structuredClone(luna),structuredClone(haiku)]})};}
function fixture(){const intent={version:'pod-discovery-2.0',id:id(1),businessId:id(2),objective:'Compare original nature shirt hypotheses through bounded public research without commercial execution.',comparisonUniverse:{productType:'original_pod_tshirt',markets:[{countryCode:'US',currency:'USD'},{countryCode:'GB',currency:'GBP'},{countryCode:'AU',currency:'AUD'},{countryCode:'NZ',currency:'NZD'}],audiences:['adult T-shirt buyers'],sourceDomains:['adult-outdoors.example'],selectionQuestion:'Compare adult nature shirt research using dated public apparel observations and preserve every material limitation.'},limits:{maximumAlternatives:3,maximumNewCollections:1,maximumMicrousd:10000000,maximumGenerations:1},expiresAt:new Date(now+3600000).toISOString()};const pins={scopeVersion:'r12.discovery-owner-adaptive.1',scopeId:id(3),scopeHash:'a'.repeat(64),actionHash:'b'.repeat(64),actionOrdinal:0,approvedQuery:intent.comparisonUniverse.selectionQuestion,finance:{authorityRootId:id(4),ledgerSnapshotHash:'c'.repeat(64),runMaximumMicrousd:10000000,runCommittedMicrousd:0,rootMaximumMicrousd:10265736,rootCommittedMicrousd:265736,actionMaximumMicrousd:1000000,actionCommittedMicrousd:0},evidenceManifest:[],activeEvidenceArtifactIds:[],ownerObservationRef:null,materialHistory:[{kind:'prior_decision',recordHash:'d'.repeat(64),statement:'Prior broad research did not establish a geographic winner.',evidenceArtifactIds:[]}]};return{intent,pins,binding:bind(intent,pins,now),knowledge:discoveryKnowledgeFixture(now),outputs:r12PhaseOutputFixture(intent.comparisonUniverse.audiences[0])};}
function execution(phase){const reviewer=phase==='review',modelId=reviewer?'anthropic/claude-haiku-4.5':'openai/gpt-5.6-luna',providerRequestId=`gen-adaptive-${phase}`;return{modelId,providerRequestId,primaryOnly:true,qualifiedRoute:qualifyGenerationRouteProof({data:{id:providerRequestId,provider_name:reviewer?'Amazon Bedrock':'Azure',model:modelId}},{generationId:providerRequestId,providerName:reviewer?'Amazon Bedrock':'Azure',requestedEndpoint:reviewer?'amazon-bedrock/us':'azure/us',acceptedResponseModelIds:reviewer?[modelId,'anthropic/claude-4.5-haiku-20251001']:[modelId,'openai/gpt-5.6-luna-20260709']})};}
function analysis(f){const base={binding:f.binding,knowledge:f.knowledge};const collection=projectAdaptivePhaseOutput({...base,phase:'search'},f.outputs.search1,execution('search'),now);const pack=projectAdaptivePhaseOutput({...base,phase:'select',collection},f.outputs.select1,execution('select'),now);const planned=projectAdaptivePhaseOutput({...base,phase:'plan'},f.outputs.plan,execution('plan'),now);const candidates=planned.proposals.map((p,i)=>({id:id(30+i),businessId:f.intent.businessId,concept:p.concept,audience:p.audience,productType:'original_pod_tshirt',originalDesign:true,rightsStatus:'unclear'}));const query=planned.queries[0];const persisted={artifactId:id(20),businessId:f.intent.businessId,workflowRunId:id(21),queryId:query.queryId,collectedForIntentId:f.intent.id,question:query.question,sourceDomains:query.sourceDomains,evidencePack:pack,lineage:{status:'completed',executionMode:'r12.discovery',provider:'openrouter.exa',sourceArtifactId:id(22),providerRequestId:execution('search').providerRequestId,workerRequestId:execution('select').providerRequestId,qualifiedSource:{version:'r12.discovery-adaptive-source.1',actionIntentId:f.intent.id,actionHash:f.pins.actionHash,scopeId:f.pins.scopeId,scopeHash:f.pins.scopeHash,searchCandidateHash:'e'.repeat(64),selectorCandidateHash:'f'.repeat(64),searchRoute:execution('search').qualifiedRoute,selectorRoute:execution('select').qualifiedRoute}}};const pins={...f.pins,evidenceManifest:[{artifactId:persisted.artifactId,packHash:hash(pack),queryId:query.queryId,collectedForIntentId:f.intent.id,scopeId:f.pins.scopeId,scopeHash:f.pins.scopeHash,actionHash:f.pins.actionHash}],activeEvidenceArtifactIds:[persisted.artifactId]};const binding=bind(f.intent,pins,now);const dossier={version:'pod-discovery-2.0',intentId:f.intent.id,businessId:f.intent.businessId,comparisonRationale:planned.comparisonRationale,shortlist:candidates,packRefs:[{artifactId:persisted.artifactId,sha256:hash(pack),origin:'new',query:{id:query.queryId,question:query.question,sourceDomains:query.sourceDomains}}]};const references=pack.evidence.map(e=>{const s=pack.sources.find(s=>s.id===e.sourceId);return{artifactId:persisted.artifactId,evidenceId:e.id,sourceId:s.id,sourceContentHash:s.contentHash,start:0,end:Array.from(e.quote).length};});const validation={knowledge:f.knowledge,packs:new Map([[persisted.artifactId,persisted]]),candidates:new Map(candidates.map(c=>[c.id,c])),committedMicrousd:0,ownerAdaptive:binding};const prepared=prepareDiscoveryWorkerContextV2(f.intent,dossier,validation,references,now);return{binding,prepared,collection,dossier,persisted,references,validation};}
test('adaptive10USD context does not relax legacy2USD or conflate root and run costs',()=>{const f=fixture();assert.throws(()=>validateDiscoveryIntentV2(f.intent,now));assert.doesNotThrow(()=>validateDiscoveryIntentV2(f.intent,now,undefined,undefined,f.binding));assert.equal(f.binding.finance.rootCommittedMicrousd,265736);assert.equal(f.binding.finance.runCommittedMicrousd,0);const changed=structuredClone(f.binding);changed.finance.rootCommittedMicrousd=0;assert.throws(()=>assertValidatedAdaptiveResearchIntent(f.intent,changed));});
test('full initial five phases use actual shared builders and denied-admission serializer with zero transport',()=>clock(async()=>{const f=fixture(),a=analysis(f),quote=qualifyAdaptiveResearchQuote(catalogs(),now);const strategy=projectAdaptivePhaseOutput({...a,knowledge:f.knowledge,phase:'strategy'},{assessment:f.outputs.strategy,measurement:null},execution('strategy'),now);const reviewContext={proposalHash:strategy.proposalHash,proposedTest:null,allowedEvidenceRefs:a.prepared.evidencePool.map(e=>e.key),currentInputRefs:[],missingProposalRequirements:['measurable_plan'],inheritedQuestions:strategy.assessment.missingQuestions,producerModelId:'openai/gpt-5.6-luna',reviewerModelId:'anthropic/claude-haiku-4.5'};for(const phase of ['plan','search','select','strategy','review']){const c={...a,knowledge:f.knowledge,phase,strategy,reviewContext};const request=buildAdaptivePhaseRequest(c,now);const wire=await inspectAdaptiveResearchWire(request,phase,quote,now);assert.ok(wire.wireBytes>100);assert.equal(JSON.parse(wire.wire.body).provider.allow_fallbacks,false);if(phase==='review'){assert.deepEqual(routeAdaptiveResearchRequest(request,phase,quote,now).outputSchema,adaptiveReviewerResponseSchema());assert.match(request.messages[1].content,/observation|proposedTest/);}}}));
test('adaptive active evidence cannot be dropped, relabeled new or substituted under the archive hash',()=>clock(()=>{const f=fixture(),a=analysis(f);for(const change of [d=>d.packRefs=[],d=>d.packRefs[0].origin='prior',d=>d.packRefs[0].sha256='0'.repeat(64)]){const d=structuredClone(a.dossier);change(d);assert.throws(()=>prepareDiscoveryWorkerContextV2(f.intent,d,a.validation,a.references,now));}}));
test('adaptive strategy requires genuine measurement extension without manufactured defaults',()=>clock(()=>{const f=fixture(),a=analysis(f),c={...a,knowledge:f.knowledge,phase:'strategy'};assert.throws(()=>projectAdaptivePhaseOutput(c,{assessment:f.outputs.strategy},execution('strategy'),now));assert.throws(()=>projectAdaptivePhaseOutput(c,{assessment:f.outputs.strategy,measurement:{observationWindow:'A bounded approved observation window',inconclusiveCriterion:'Insufficient observations distinguish the proposed outcomes'}},execution('strategy'),now));assert.equal(projectAdaptivePhaseOutput(c,{assessment:f.outputs.strategy,measurement:null},execution('strategy'),now).proposedTest,null);}));
test('adaptive quote verifies each phase, recomputed amounts, fixed models and fresh time',()=>{const q=qualifyAdaptiveResearchQuote(catalogs(),now);assert.ok(q.ceilings.strategy>50451);assert.doesNotThrow(()=>validateAdaptiveResearchQuote(q,now));for(const change of [q=>delete q.ceilings.plan,q=>q.ceilings.extra=1,q=>q.ceilings.plan=1,q=>q.luna.endpoint='other/us']){const v=structuredClone(q);change(v);const{quoteHash,verifiedAt,validUntil,...body}=v;void quoteHash;void verifiedAt;void validUntil;v.quoteHash=hash(body);assert.throws(()=>validateAdaptiveResearchQuote(v,now));}assert.throws(()=>validateAdaptiveResearchQuote(q,now+300000));});
test('wire refuses legacy reviewer grammar and unsupported stronger model',()=>clock(async()=>{const f=fixture(),q=qualifyAdaptiveResearchQuote(catalogs(),now),request=buildAdaptivePhaseRequest({binding:f.binding,knowledge:f.knowledge,phase:'plan'},now);request.model={...request.model,providerModelId:'openai/unsupported'};assert.throws(()=>routeAdaptiveResearchRequest(request,'plan',q,now));}));

test('runtime review projection preserves selected identity, all unknowns and no authority',()=>clock(()=>{const f=fixture(),a=analysis(f),strategy=projectAdaptivePhaseOutput({...a,knowledge:f.knowledge,phase:'strategy'},{assessment:f.outputs.strategy,measurement:null},execution('strategy'),now);const reviewContext={proposalHash:strategy.proposalHash,proposedTest:null,allowedEvidenceRefs:a.prepared.evidencePool.map(e=>e.key),currentInputRefs:[],missingProposalRequirements:['measurable_plan'],inheritedQuestions:strategy.assessment.missingQuestions,producerModelId:'openai/gpt-5.6-luna',reviewerModelId:'anthropic/claude-haiku-4.5'};const output={version:'r12.adaptive-review.1',proposalHash:strategy.proposalHash,outcome:'NEEDS_MORE_EVIDENCE',ratings:Object.fromEntries(['evidence','learningValue','testDesign','feasibility'].map(k=>[k,{score:0,rationale:'The bounded collected context does not resolve this specific proposal requirement.',evidenceRefs:[]}])),proposalConcerns:[],executionPrerequisites:['Separate exact approval before future creative execution'],additionalQuestions:[],sufficiencyRationale:'No candidate or geographic market has been selected and no bounded experiment has been proposed.'};const result=projectAdaptivePhaseOutput({...a,knowledge:f.knowledge,phase:'review',strategy,reviewContext},output,execution('review'),now);assert.equal(result.outcome,'NEEDS_MORE_EVIDENCE');assert.equal(result.candidateId,null);assert.equal(result.adaptiveActionHash,f.pins.actionHash);assert.equal(result.executionAuthorized,false);assert.equal(result.publicationAllowed,false);assert.deepEqual(result.inheritedQuestions,strategy.assessment.missingQuestions);assert.equal(result.nextActionStatus,'pause_no_reviewed_action');}));
