'use server';
import{randomUUID}from'node:crypto';import{redirect}from'next/navigation';import{revalidatePath}from'next/cache';
import{requireOwnerUiContext}from'@/lib/core-ui/data';
import{readDirectResearchCatalog,prepareDirectResearchTest,confirmDirectResearchTest,stopDirectResearchTest,prepareDirectEtsyAccess,prepareDirectResearchCycle,confirmAndStartDirectResearch,resumeDirectResearch}from'@/products/discovery-r12-public-owner-server';
import{publicResearchCriteriaHash,publicResearchQuestionHash}from'@/products/discovery-r12-public-contracts';
const field=(f:FormData,k:string)=>typeof f.get(k)==='string'?String(f.get(k)):'';
const object=(x:unknown):x is Record<string,unknown>=>!!x&&typeof x==='object'&&!Array.isArray(x);
function finish(businessId:string,goalId:string,envelopeId:string,result:string):never{revalidatePath('/dashboard/products/etsy-research');redirect(`/dashboard/products/etsy-research?${new URLSearchParams({business:businessId,goal:goalId,...(envelopeId?{envelope:envelopeId}:{}),result})}`);}
export async function prepareEtsyTest(form:FormData){const context=await requireOwnerUiContext(),businessId=field(form,'businessId'),goalId=field(form,'goalId');let id='';
 try{const c=await readDirectResearchCatalog(context,businessId,goalId),grantId=field(form,'grantId'),usd=field(form,'maximumUsd'),amount=/^(?:0|[1-9][0-9]*)(?:\.[0-9]{1,2})?$/.test(usd)?(BigInt(usd.split('.')[0])*BigInt(1000000)+BigInt((usd.split('.')[1]??'').padEnd(6,'0'))).toString():'',attempts=Number(field(form,'maximumAttempts'));if(!/^\d{1,8}$/.test(amount)||BigInt(amount)<=BigInt(0)||BigInt(amount)>BigInt(10000000)||!Number.isInteger(attempts)||attempts<1||attempts>10||!object(c.funding)||!object(c.predecessor)||!object(c.predecessor.closure))throw Error('invalid');
 const cap=(kind:'business'|'root')=>{const x=c.funding as Record<string,unknown>,v=x[kind];if(!object(v)||typeof v.revision!=='number'||typeof v.currentLimitMicrounits!=='string'||typeof v.conservativeExposureMicrounits!=='string')throw Error('invalid');const next=BigInt(v.conservativeExposureMicrounits)+BigInt(amount),old=BigInt(v.currentLimitMicrounits);return{currentRevision:v.revision,currentLimitMicrounits:v.currentLimitMicrounits,proposedLimitMicrounits:(next>old?next:old).toString()};};
 const r=await prepareDirectResearchTest(context,{version:'r12.owner-direct-test-input.1',businessId,goalId,grantId,predecessorScopeId:c.predecessor.closure.predecessorScopeId,predecessorScopeHash:c.predecessor.closure.predecessorScopeHash,maximumAttemptsInWindow:attempts,maximumRunMicrounits:amount,capProposal:{version:'r12.public-cap-proposal.1',business:cap('business'),root:cap('root')},submissionId:randomUUID()});id=r.testEnvelopeId;
 }catch{finish(businessId,goalId,'','preparation-unavailable');}finish(businessId,goalId,id,'prepared');}
export async function confirmEtsyTest(form:FormData){const c=await requireOwnerUiContext(),b=field(form,'businessId'),g=field(form,'goalId'),e=field(form,'envelopeId');if(field(form,'confirmBudget')!=='on')finish(b,g,e,'confirmation-required');try{await confirmDirectResearchTest(c,b,g,e,field(form,'envelopeHash'));}catch{finish(b,g,e,'confirmation-unavailable');}finish(b,g,e,'confirmed');}
export async function prepareEtsyAccess(form:FormData){const c=await requireOwnerUiContext(),b=field(form,'businessId'),g=field(form,'goalId'),e=field(form,'envelopeId');let op='';try{op=(await prepareDirectEtsyAccess(c,b,g,e,field(form,'expectedShopName').trim())).operationId;}catch{finish(b,g,e,'access-preparation-unavailable');}redirect(`/dashboard/accounts/etsy-research?${new URLSearchParams({business:b,operation:op})}`);}
export async function prepareEtsyCycle(form:FormData){const c=await requireOwnerUiContext(),b=field(form,'businessId'),g=field(form,'goalId'),e=field(form,'envelopeId'),query=field(form,'query').trim(),namedGap=field(form,'namedGap').trim();try{await prepareDirectResearchCycle(c,b,g,e,{kind:'targeted',criteriaHash:publicResearchCriteriaHash('search_terms',query),questionHash:publicResearchQuestionHash(namedGap),query,namedGap,expectedInformationGain:field(form,'expectedInformationGain').trim(),opposingCheck:field(form,'opposingCheck').trim(),changedCriterion:null});}catch{finish(b,g,e,'research-preparation-unavailable');}finish(b,g,e,'research-prepared');}
export async function startEtsyCycle(form:FormData){const c=await requireOwnerUiContext(),b=field(form,'businessId'),g=field(form,'goalId'),e=field(form,'envelopeId');if(field(form,'confirmResearch')!=='on')finish(b,g,e,'research-confirmation-required');try{await confirmAndStartDirectResearch(c,b,g,e,field(form,'setupId'),field(form,'setupHash'));}catch{finish(b,g,e,'start-unconfirmed');}finish(b,g,e,'started');}
export async function stopEtsyTest(form:FormData){const c=await requireOwnerUiContext(),b=field(form,'businessId'),g=field(form,'goalId'),e=field(form,'envelopeId');try{await stopDirectResearchTest(c,b,g,e);}catch{finish(b,g,e,'stop-unconfirmed');}finish(b,g,e,'stopped');}

export async function resumeEtsyResearch(form:FormData){const c=await requireOwnerUiContext(),b=field(form,'businessId'),g=field(form,'goalId'),e=field(form,'envelopeId');try{await resumeDirectResearch(c,b,g,e);}catch{finish(b,g,e,'recovery-unconfirmed');}finish(b,g,e,'reconciliation-requested');}
