import{notFound}from'next/navigation';
import Link from 'next/link';
import{AppShell,PageHeader}from'@/components/stage7/app-shell';
import{ConsoleRetainedWorkspace}from'@/components/console/console-retained-workspace';
import{requireOwnerUiContext}from'@/lib/core-ui/data';
import{readDirectResearchCatalog}from'@/products/discovery-r12-public-owner-server';
import{validatePublicResearchOwnerTestReceipt}from'@/products/discovery-r12-public-preparation';
import{publicUuid}from'@/products/discovery-r12-public-utils';
import{prepareEtsyTest,confirmEtsyTest,prepareEtsyAccess,prepareEtsyCycle,startEtsyCycle,stopEtsyTest,resumeEtsyResearch}from'./actions';
export const dynamic='force-dynamic';export const revalidate=0;export const maxDuration=300;
const object=(x:unknown):x is Record<string,unknown>=>!!x&&typeof x==='object'&&!Array.isArray(x);
const usd=(x:string)=>/^\d+$/.test(x)?`$${BigInt(x)/BigInt(1000000)}.${(BigInt(x)%BigInt(1000000)).toString().padStart(6,'0')} USD`:'unconfirmed';
export default async function DirectEtsyResearchPage({searchParams}:{searchParams:Promise<Record<string,string|string[]|undefined>>}){
 const q=await searchParams,b=typeof q.business==='string'?q.business:'',g=typeof q.goal==='string'?q.goal:'',e=typeof q.envelope==='string'?q.envelope:undefined;if(!publicUuid(b)||!publicUuid(g)||e&&!publicUuid(e))notFound();
 const context=await requireOwnerUiContext();let catalog:Record<string,unknown>|null=null;try{catalog=await readDirectResearchCatalog(context,b,g,e);}catch{}
 let receipt:ReturnType<typeof validatePublicResearchOwnerTestReceipt>|null=null;try{if(catalog?.current)receipt=validatePublicResearchOwnerTestReceipt(catalog.current,{businessId:b,goalId:g});}catch{}
 const research=object(catalog?.research)?catalog.research:null,preview=object(research?.preview)?research.preview:null,quote=object(preview?.quote)?preview.quote:null,inference=object(quote?.inference)?quote.inference:null;
 const access=object(catalog?.ownerAccess)?catalog.ownerAccess:null;
 const state=object(catalog?.researchState)?catalog.researchState:null;
 const cost=object(catalog?.testExposure)?catalog.testExposure:null;
 const exposure=cost&&receipt&&cost.version==='r12.direct-test-exposure.1'&&cost.testEnvelopeId===receipt.testEnvelopeId&&cost.testEnvelopeHash===receipt.testEnvelopeHash&&['knownActualMicrounits','boundedPendingMicrounits','committedMicrounits','maximumMicrounits'].every(k=>typeof cost[k]==='string'&&/^\d{1,20}$/.test(String(cost[k])))&&typeof cost.hasUnknownOrUnbounded==='boolean'&&typeof cost.allBillingFinal==='boolean'?cost:null;
 const fields=<><input type="hidden" name="businessId" value={b}/><input type="hidden" name="goalId" value={g}/><input type="hidden" name="envelopeId" value={receipt?.testEnvelopeId??''}/></>;
 return <AppShell active="products" context={context} navigationBusinessId={b}><ConsoleRetainedWorkspace ownerId={context.userId} secure header={<PageHeader eyebrow="Research" title="Etsy research test" description="A bounded learning cycle under your existing Goal, with a separate evidence-quality review."/>} panels={[{id:'test',label:'Etsy research',content:<section className="coreCard" aria-label="Etsy research test">
 {typeof q.result==='string'&&['preparation-unavailable','confirmation-required','confirmation-unavailable','access-preparation-unavailable','research-preparation-unavailable','research-confirmation-required','start-unconfirmed','stop-unconfirmed','recovery-unconfirmed'].includes(q.result)&&<p role="alert">The requested change was not confirmed. Check the saved state below before retrying; any pending provider liability remains held.</p>}
 <p>This test can finish a research stage. It does not establish profit or complete the broader Goal.</p>
 {!catalog&&<p role="alert">Research authority is unavailable. No provider call has been started.</p>}
 {catalog&&!receipt&&<><p>{String(catalog.reason??'Reviewed test authority is available.').replaceAll('_',' ')}</p>{catalog.eligible===true&&<form action={prepareEtsyTest}>{fields}<label>Reviewed grant <select name="grantId" required>{(catalog.grants as unknown[]).filter(object).map(x=><option key={String(x.grantId)} value={String(x.grantId)}>{String(x.grantId)}</option>)}</select></label><label>Combined test ceiling (USD)<input name="maximumUsd" type="number" min="0.01" max="10" step="0.01" defaultValue="10" required/></label><label>Total test attempts<input name="maximumAttempts" type="number" min="1" max="10" defaultValue="10" required/></label><button type="submit">Prepare exact test review</button></form>}</>}
 {receipt&&<><h2>Saved test envelope</h2><p>Combined ceiling: {usd(receipt.preview.maximumMicrounits)}. Up to {receipt.preview.maximumAttemptsInWindow} total attempt units in this test. Login, verification, research, models and repair costs share this ceiling.</p><p>Previous Business exposure: {usd(receipt.preview.funding.business.conservativeExposureMicrounits)}. Previous funding-root exposure: {usd(receipt.preview.funding.root.conservativeExposureMicrounits)}. These overlap and are not added together or reset.</p><p>Reviewed cumulative limits: Business {usd(receipt.preview.capProposal.business.proposedLimitMicrounits)}, root {usd(receipt.preview.capProposal.root.proposedLimitMicrounits)}.</p><p>Expires {receipt.expiresAt}. The original Goal remains unchanged.</p>
 {receipt.confirmed&&<section aria-label="Current test costs"><h3>Current test costs</h3>{exposure?<><p>Confirmed actual: {usd(String(exposure.knownActualMicrounits))}. Still reserved for pending charges: {usd(String(exposure.boundedPendingMicrounits))}. Combined exposure: {usd(String(exposure.committedMicrounits))} against {usd(String(exposure.maximumMicrounits))}.</p><p>Pending reservations are not actual charges or available budget. {exposure.allBillingFinal?'All recorded billing is final.':'Final provider billing is still outstanding.'}</p>{exposure.hasUnknownOrUnbounded&&<p role="alert">A provider liability is unknown or unbounded. New paid work is blocked pending reconciliation.</p>}</>:<p>Current cost reconciliation is unavailable; do not infer that reserved funds are free.</p>}</section>}
 {!receipt.confirmed&&<form action={confirmEtsyTest}>{fields}<input type="hidden" name="envelopeHash" value={receipt.testEnvelopeHash}/><label><input name="confirmBudget" type="checkbox" required/> Confirm this exact bounded test and displayed cumulative funding amendments.</label><button type="submit">Confirm test envelope</button></form>}
 {receipt.confirmed&&!receipt.stopped&&<>{access&&publicUuid(access.operationId)?<><p>Saved Etsy access setup: {String(access.status)}.</p><Link className="coreButton" href={`/dashboard/accounts/etsy-research?${new URLSearchParams({business:b,operation:String(access.operationId)})}`}>Open this exact connection setup</Link></>:<form action={prepareEtsyAccess}>{fields}<label>Exact Etsy shop name<input name="expectedShopName" maxLength={120} autoComplete="off" required/></label><button type="submit">Review recorded sign-in and persistent access</button></form>}<p>Connection setup requires a separate exact access confirmation. Credentials are entered only by you in the private handoff.</p>
 <form action={prepareEtsyCycle}>{fields}<h2>Prepare the first research question</h2><label>Initial Etsy search<input name="query" maxLength={1000} required/></label><label>Unresolved question<textarea name="namedGap" maxLength={1000} required/></label><label>What new information would answer it?<textarea name="expectedInformationGain" maxLength={1000} required/></label><label>Opposing explanation to check<textarea name="opposingCheck" maxLength={1000} required/></label><button type="submit">Prepare research and data-sharing review</button></form></>}
 {research&&preview&&<><h2>Exact saved research preview</h2>{object(preview.scope)&&object(preview.scope.initialCommand)&&<dl><dt>Saved Etsy query</dt><dd>{String(preview.scope.initialCommand.query)}</dd><dt>Question</dt><dd>{String(preview.scope.initialCommand.namedGap)}</dd><dt>Expected information gain</dt><dd>{String(preview.scope.initialCommand.expectedInformationGain)}</dd><dt>Opposing check</dt><dd>{String(preview.scope.initialCommand.opposingCheck)}</dd></dl>}<p>Setup {String(research.setupId)}. Scope {String(research.scopeHash)}.</p><p>Only selected visible Etsy aggregate evidence, the research question, and relevant Goal/history findings are sent for analysis. Full audit evidence stays retained. A screenshot is stored privately for provenance.</p><p>Inference route: {inference&&object(inference.luna)?String(inference.luna.modelId):'unconfirmed'}; independent reviewer: {inference&&object(inference.reviewer)?String(inference.reviewer.modelId):'unconfirmed'} via OpenRouter. Steel provides the recorded browser session.</p><p>Configured inference retention: {inference&&object(inference.retention)?String(inference.retention.inference):'unconfirmed'}. Browser retention: {quote&&object(quote.browser)?String(quote.browser.retentionDisclosure):'unconfirmed'}.</p>
 <p>Evidence quality must reach 80/100 and pass every hard gate. Commercial readiness is separate. Missing critical facts remain unresolved, and an evidence-backed rejection is a valid stage result.</p><p>Insufficient-evidence responses 1–3 request fresh targeted queries; response 4 pivots to new criteria. The finite window ends honestly if no concrete result is reached.</p>
 {research.confirmed!==true&&!receipt.stopped&&<form action={startEtsyCycle}>{fields}<input type="hidden" name="setupId" value={String(research.setupId)}/><input type="hidden" name="setupHash" value={String(research.setupHash)}/><label><input type="checkbox" name="confirmResearch" required/> Approve the exact source, recipient, quoted route and bounded research preview.</label><button type="submit">Confirm and start research</button></form>}</>}
 {state&&<><h2>Recorded progress</h2><form action={resumeEtsyResearch}>{fields}<button type="submit">Reconcile saved receipts and resume</button></form><p>Attempt units reserved: {String(state.unitsReserved??state.windowAttemptsStarted??'unknown')}. Paid units consumed: {String(state.unitsConsumed??state.windowAttemptsStarted??'unknown')}. Logical research cycles: {String(state.logicalCyclesStarted??state.windowAttemptsStarted??'unknown')}. Model calls: {String(state.modelDispatchesUsed??'unknown')}. Source operations: {String(state.sourceOperationsStarted??'unknown')}.</p><p role="status">{receipt.stopped?'This test is stopped. Existing receipts may still settle; no new paid work is authorized.':state.nextAction==='source_paused'?'Source access is paused and requires reconciliation. No replacement browser session is authorized.':state.nextAction==='receipt_only'?'Waiting for the existing request’s qualified receipt; no replacement is authorized.':String(state.terminal??'Research is active or awaiting a qualified receipt.').replaceAll('_',' ')}</p>{(Array.isArray(state.logicalCycles)?state.logicalCycles:Array.isArray(state.attempts)?state.attempts:[]).filter(object).map(a=>{const review=object(a.review)?a.review:null,quality=object(review?.quality)?review.quality:null;return <details key={String(a.logicalCycleId??a.attemptId)}><summary>Attempt {String(a.ordinal)} · {String(a.status)}{quality&&typeof quality.qualityBasisPoints==='number'?` · Evidence quality ${quality.qualityBasisPoints/100}/100`: ''}</summary><p>{review?String(review.conclusion):'No accepted independent review yet.'}</p>{quality&&Array.isArray(quality.failures)&&<p>Hard-gate findings: {quality.failures.map(String).join(', ')||'none'}</p>}{review&&<pre>{JSON.stringify({quality:review.quality,command:review.proposedCommand,contraryEvidenceRefs:review.contraryEvidenceRefs,missingCriticalRequirements:review.missingCriticalRequirements},null,2)}</pre>}</details>;})}</>}
 <form action={stopEtsyTest}>{fields}<button type="submit">Stop this test</button></form></>}
 </section>}]} /></AppShell>;
}
