import { ConsoleRetainedWorkspace, ConsoleRecentRows } from "@/components/console/console-retained-workspace";
import { randomUUID } from "node:crypto";
import Link from "next/link";
import { notFound, redirect } from "next/navigation";
import { AppShell, PageHeader } from "@/components/stage7/app-shell";
import { ProductSubmitButton } from "@/components/stage13/products-workspace";
import { loadCreativeWorkspace, loadProductionCandidates } from "@/creative/data";
import { CREATIVE_COST_COMMITMENT_EXPLANATION, creativeCostStatus, qualifyCreativeCost, summarizeCreativeCosts } from "@/creative/cost-display";
import { FLUX_KLEIN_PROVIDER_TERMS, TECHNICAL_PRINT_SPECIFICATION } from "@/creative/proposal";
import { FLUX_KLEIN_PNG_POLICY } from "@/creative/image-provider";
import { SCREEN_CATEGORIES } from "@/creative/types";
import { requireOwnerUiContext } from "@/lib/core-ui/data";
import { approveCreativeCandidate, approveProductionCreativeCandidate, closeExpiredCreativeRun, startCreativeRun } from "./actions";
import "./artifacts.css";

export const dynamic = "force-dynamic";
const utc = (date: string) => `${new Date(date).toISOString().replace("T", " ").replace(".000Z", " UTC").replace("Z", " UTC")}`;
const usd = (micro: number) => `US$${(micro / 1e6).toFixed(6)}`;
export default async function ArtifactsPage({ searchParams }: { searchParams: Promise<Record<string, string | string[] | undefined>> }) {
  const context = await requireOwnerUiContext(), query = await searchParams;
  const first = (v: string | string[] | undefined) => Array.isArray(v) ? v[0] : v;
  const requestedBusiness = first(query.business);
  const selectedBusiness = context.businesses.find(business => business.id === requestedBusiness);
  if (requestedBusiness && !selectedBusiness && !context.businessesUnavailable) notFound();
  const exactRun=first(query.creativeRun);
  if(query.creativeRun){if(Array.isArray(query.creativeRun) || !/^[a-f0-9]{8}-[a-f0-9]{4}-[1-8][a-f0-9]{3}-[89ab][a-f0-9]{3}-[a-f0-9]{12}$/i.test(exactRun ?? ""))notFound();redirect(`/dashboard?view=library&type=designs${selectedBusiness ? `&business=${selectedBusiness.id}` : ""}&creativeRun=${exactRun}`);}
  const scopedContext = selectedBusiness ? { ...context, businesses: [selectedBusiness] } : context;
  const [loadedData, production] = await Promise.all([loadCreativeWorkspace(scopedContext), loadProductionCandidates(scopedContext)]);
  const data=context.businessesUnavailable ? {...loadedData,costsAvailable:false,errors:["Business records unavailable"]} : loadedData;
  return <AppShell toolDestination="artifacts" active="artifacts" context={context} navigationBusinessId={selectedBusiness?.id}><ConsoleRetainedWorkspace ownerId={context.userId}  notice={<p className="coreNotice">Recent window: 50 approvals and 100 assets. Linked run status is checked for each loaded approval. Older records and exact receipts remain available in <Link href={`/dashboard?view=library${selectedBusiness ? `&business=${selectedBusiness.id}` : ""}`}>Library</Link>; complete tool history remains pending R06.</p>} header={<><PageHeader eyebrow="Saved outputs" title="Library" description="Keep the brief, original pixels, versions and independent review together." />
{selectedBusiness ? <p className="coreNotice">Business: {selectedBusiness.name} · <Link href="/dashboard/artifacts">View all businesses</Link></p> : null}
{first(query.message) ? <p className="coreNotice coreNotice-success" role="status">{first(query.message)}</p> : null}
{first(query.error) ? <p className="coreNotice coreNotice-danger" role="alert">{first(query.error)}</p> : null}
{data.errors.length ? <p className="coreNotice coreNotice-danger" role="alert">Creative registry is unavailable. No provider action can start until its approved schema is ready.</p> : null}</>} panels={[{ id: "receipts", label: "Approvals & receipts", content: <><section aria-labelledby="creative-approvals"><h2 id="creative-approvals">Approved scope & run history</h2><div className="creativeRunGrid"><ConsoleRecentRows label="Recent loaded artifacts records" rows={data.approvals.map(a => {
      const run = data.runs.find(r => r.approval_id === a.id), costs = data.costs.filter(c => c.creative_run_id === run?.id), totals = summarizeCreativeCosts(costs);
      return <details className="creativePanel creativeRun" id={run ? `creative-run-${run.id}` : `creative-approval-${a.id}`} key={a.id}><summary><strong>{a.snapshot.concept}</strong><span>{run?.status ?? (data.costsAvailable ? "Approved · not started" : "Run status unavailable")} · {totals.uncertainCalls} unknown charge(s)</span></summary><div className="creativeTagRow"><span className="creativeTag">{a.purpose.replaceAll("_", " ")}</span><span className="creativeTag">{run?.status ?? (data.costsAvailable ? "Approved · not started" : "Run status unavailable")}</span></div><h3>{a.snapshot.concept}</h3><p>{a.snapshot.audience}</p><p>Allowance: {usd(a.maximum_microusd)} · Reported: {!data.costsAvailable ? "Unavailable" : totals.recordedCalls > totals.uncertainCalls ? usd(totals.reportedMicrousd) : totals.recordedCalls ? "No charge reported; charge unknown" : "No calls recorded"}</p>
        {!data.costsAvailable ? <p role="alert">The cost ledger could not be fully loaded. Any receipts below are incomplete; do not assume zero spend or start another attempt.</p> : <>
          {totals.uncertainCalls ? <p role="status">{totals.uncertainCalls} charge(s) remain unknown · {totals.hasMissingReservation ? "At least " : ""}{usd(totals.uncertainReservedMicrousd)} reserved for those attempts. Missing receipts do not prove zero spend or permit another attempt.</p> : null}
          {totals.recordedCalls ? <p className="creativeMuted">{totals.hasMissingReservation ? "Known conservative budget commitment" : "Conservative budget committed"}: {usd(totals.committedMicrousd)}. {CREATIVE_COST_COMMITMENT_EXPLANATION}{totals.hasMissingReservation ? " Some reservation details are unavailable; refresh before relying on this total." : ""}</p> : null}
        </>}
        <p>Saved image model: {a.quote?.generatorModel ?? "Provider binding unavailable"} via OpenRouter</p>
        {a.quote?.generatorModel === FLUX_KLEIN_PNG_POLICY.modelId ? <p className="creativeMuted">Native PNG requested at 1024 × 1024; original provider bytes and markings are retained. Data-use disclosure: {String(a.quote.providerBinding?.disclosureVersion ?? "Unavailable")} · {a.quote.providerBinding?.ownerAcknowledged === true ? "Owner acknowledged" : "Acknowledgement unavailable"}. This does not establish a privacy guarantee.</p> : null}
        <p>Image limit: {a.snapshot.maximumGenerations} · {a.snapshot.maximumGenerations === 1 ? "No repair; a failed review stops for owner review" : "At most one repair"} · Up to {2 + 2 * a.snapshot.maximumGenerations} provider calls · No automatic retries</p>
        <p className="creativeMuted">Approved {utc(a.approved_at)} · Expires {utc(a.expires_at)}</p>
        {run ? <><p>{run.productionReady ? "Passed the saved production approval at completion; recheck current eligibility before use" : "No candidate production or publication authority"}</p><Link className="coreButton" href={`/dashboard?view=library&type=designs&business=${run.business_id}&creativeRun=${run.id}`}>Exact provider receipts</Link><Link className="coreButton" href={`/dashboard/workflows/${run.workflow_run_id}?business=${run.business_id}`}>Open workflow</Link></> : <form action={startCreativeRun}><input type="hidden" name="approvalId" value={a.id} /><ProductSubmitButton pendingText="Reserving creative run…" disabled={!data.costsAvailable || data.errors.length > 0}>Start approved creative run</ProductSubmitButton></form>}
        {run && ["queued", "running"].includes(run.status) && run.capabilityExpired ? <form action={closeExpiredCreativeRun}><input type="hidden" name="creativeRunId" value={run.id} /><ProductSubmitButton pendingText="Closing expired run…">Close expired run for review</ProductSubmitButton></form> : null}
        {run ? data.retainedSources?.filter(source => source.creativeRunId === run.id).map(source => <div className="coreNotice" key={source.callKey}>
          <p><strong>Unvalidated provider source retained after failure</strong></p><p>{source.mediaType} · {source.bytes.toLocaleString("en-US")} bytes · {source.downloadVerified ? "Stored bytes were downloaded and hash-verified" : "Read-back verification was not confirmed"}</p>
          <p>This is evidence of the paid response, not a validated design or review PASS. Opening it does not retry generation.</p><p className="creativeHash">SHA-256: {source.sha256}</p>
          {source.signedUrl ? <a href={source.signedUrl} target="_blank" rel="noopener noreferrer">Open retained unvalidated source ↗</a> : <p>Private source access unavailable; refresh before use.</p>}
        </div>) : null}
        {costs.length ? <details><summary>Provider receipts & reservations</summary><ul>{costs.map(c => { const qualified = qualifyCreativeCost(c); return <li key={c.call_key}>{c.call_key}: {creativeCostStatus(c, run?.capabilityExpired ?? false)}{qualified.reportedMicrousd === null ? "" : ` · ${usd(qualified.reportedMicrousd)}`} · Reserved: {c.reserved_microusd === null ? "Detail unavailable" : usd(c.reserved_microusd)} · {utc(c.created_at)}{c.settled_at ? ` · Receipt ${utc(c.settled_at)}` : ""}{qualified.unverifiedMicrousd !== null ? <p>Unverified saved amount: {usd(qualified.unverifiedMicrousd)} · excluded from reported charges</p> : null}</li>; })}</ul></details> : null}</details>;
    })} /></div>{!data.approvals.length ? <p className="creativeEmpty">No approvals were returned in this loaded window. Older approvals may exist.</p> : null}</section></> },
{ id: "production", label: "Production approval", content: <><section aria-labelledby="production-creative-approval" className="creativePanel creativeApprovalBody">
      <h2 id="production-creative-approval">Approve a researched candidate for design</h2>
      <p>A current reviewed TEST with nine source-linked qualitative or legacy assessments makes a candidate eligible for a separate creative approval. Its evidence must still be fresh. Neither this approval nor a design PASS authorizes publication or proves sales.</p>
      {production.errors.length ? <p role="alert">Candidate evidence could not be checked. Production approval is unavailable.</p> : !production.candidates.length ? <p className="creativeMuted">No current evidence-backed TEST candidates are eligible. <Link href={`/dashboard/products${selectedBusiness ? `?business=${selectedBusiness.id}` : ""}`}>Review missing evidence in Products</Link>. Technical approvals below do not waive this gate.</p> : null}
      {!data.errors.length ? production.candidates.map(({ candidate, decision, experiment, maximumGenerations: reviewedLimit=2 }) => <details className="creativeProductionChoice" key={candidate.id}>
        <summary><strong>{candidate.concept}</strong><span>{context.businesses.find(b => b.id === candidate.business_id)?.name} · {"scoringVersion" in decision.assessment?`TEST ${decision.assessment.totalScore}/100`:"Independent qualitative TEST"}</span></summary>
        <p>Audience: {candidate.audience}</p><p className="creativeMuted">Reviewed {utc(decision.created_at)} · {experiment.discovery_version==="pod-discovery-2.0"?"The exact source dossier and latest decision are rechecked when saving and before production completes.":`Evidence expires ${utc(new Date(Math.min(...experiment.evidence_pack!.sources.map(source => Date.parse(source.retrievalExpiresAt)))).toISOString())}`}</p>
        <p>This approval uses Bella + Canvas 3001, size L, large front: an intentional opaque 6.5 × 6.5 in design, PNG, sRGB, at least 150 effective DPI. <a href={TECHNICAL_PRINT_SPECIFICATION.sourceUrl} target="_blank" rel="noopener noreferrer">Printful placement source ↗</a> · <a href="https://www.printful.com/creating-dtg-file" target="_blank" rel="noopener noreferrer">Print file guidance ↗</a>. Specification checked {utc(TECHNICAL_PRINT_SPECIFICATION.verifiedAt)}. The request explicitly selects PNG and 1024 × 1024; acceptance requires actual dimensions of at least 975 × 975 and at most 7 MB, with original PNG bytes and any provider marking retained.</p>
        <form action={approveProductionCreativeCandidate} className="creativeForm">
          <input type="hidden" name="approvalId" value={randomUUID()} /><input type="hidden" name="candidateId" value={candidate.id} /><input type="hidden" name="decisionId" value={decision.id} />
          <label className="creativeTextField">Exact original design instructions<textarea name="designInstructions" required minLength={50} maxLength={1500} rows={4} placeholder="Describe this candidate’s original composition and intended opaque square background. Do not add brands, characters, likenesses or third-party references." /></label>
          <label className="creativeTextField">Concept-specific originality and rights statement<textarea name="rightsStatement" required minLength={30} maxLength={1500} rows={3} placeholder="Explain the basis for your original design and rights declaration. If rights are unclear, stop and resolve them before approving." /></label>
          <fieldset className="creativePolicyScreens"><legend>Owner IP and policy review</legend><p>For each category, explain why this exact concept is clear and cite 1–4 relevant HTTPS source URLs, one per line. A generic policy link alone is not proof about your design. Any uncertainty needs review before approval.</p>
            {SCREEN_CATEGORIES.map(category => <div key={category} className="creativePolicyScreen"><h4>{category.replaceAll("_", " ")}</h4>
              <label className="creativeTextField">Clear-screen rationale: {category.replaceAll("_", " ")}<textarea name={`rationale_${category}`} required minLength={15} maxLength={800} rows={2} /></label>
              <label className="creativeTextField">Source URLs: {category.replaceAll("_", " ")}<textarea name={`sources_${category}`} required maxLength={6003} rows={2} /></label>
            </div>)}
          </fieldset>
          <label className="creativeTextField">Image provider and output contract<select name="generatorModel" required defaultValue=""><option value="" disabled>Select a provider for this new approval</option><option value={FLUX_KLEIN_PNG_POLICY.modelId}>BFL FLUX.2 Klein 4B via OpenRouter · native PNG · request 1024 × 1024</option></select></label>
          <label className="creativeTextField">Image generation limit<select name="maximumGenerations" required defaultValue="1"><option value="1">One image, no repair (up to 4 provider calls)</option><option value="2" disabled={reviewedLimit<2}>One image plus at most one repair (up to 6 provider calls)</option></select></label>
          <label className="creativeTextField">Total creative allowance (USD)<input name="budgetUsd" type="number" min="0.01" max="1" step="0.01" required placeholder="Explicitly approved total" /></label>
          <label><input type="checkbox" name="confirmOriginalIntent" required />I approve this candidate’s exact original instructions and rights statement; this is not a guarantee of universal non-infringement</label>
          <label><input type="checkbox" name="confirmPolicyScreen" required />I have reviewed all eight categories for this exact design and none is unclear</label>
          <label><input type="checkbox" name="confirmProductionScope" required />I separately approve design production against this current reviewed TEST; I am not approving listing, selling or publishing</label>
          <label><input type="checkbox" name="confirmPrintSpec" required />I approve the named garment, print size and intentional opaque-square background</label>
          <label><input type="checkbox" name="confirmTerms" required />I accept the <a href={FLUX_KLEIN_PROVIDER_TERMS[0]} target="_blank" rel="noopener noreferrer">BFL developer terms</a> and <a href={FLUX_KLEIN_PROVIDER_TERMS[1]} target="_blank" rel="noopener noreferrer">BFL FLUX API terms</a> for this provider and understand AI provenance must be preserved</label>
          <label><input type="checkbox" name="confirmDataUse" required />I acknowledge that my design prompt goes to OpenRouter and Black Forest Labs. OpenRouter lists Black Forest Labs as not training on requests and retaining data for 30 days. A per-request data-collection denial, zero-data-retention route and override of BFL’s API contract have not been verified. BFL’s API terms include a training license; the route metadata is not a privacy guarantee</label>
          <label><input type="checkbox" name="confirmBudget" required />I approve the stated total for the brief, independent IP screen, image and pixel review, within the selected image limit. One image allows no repair; two allow at most one repair. No automatic retries</label>
          <p className="creativeMuted">BFL FLUX.2 Klein 4B generates through OpenRouter; Luna writes the brief and Claude reviews it. Current pricing and the evidence decision are checked again before execution and final production readiness. Saving does not call a paid provider.</p>
          <ProductSubmitButton pendingText="Rechecking evidence and quote…">Save candidate creative approval</ProductSubmitButton>
        </form>
      </details>) : null}
    </section></> },
{ id: "technical", label: "Technical approval", content: <><details className="creativePanel" open><summary><strong>Approve the bounded technical design</strong><span>No generation until you start the saved approval</span></summary>
      <div className="creativeApprovalBody"><h3>One original design, one explicit approval</h3><p>Enter the concept and art direction privately. This technical run uses an intentional opaque background. Do not include brands, logos, protected characters, celebrity likenesses, copied artwork, artist imitation or third-party reference images.</p><dl className="creativeFacts"><div><dt>Intended placement</dt><dd>6.5 × 6.5 in, large front</dd></div><div><dt>Garment</dt><dd>Bella + Canvas 3001, size L</dd></div><div><dt>File acceptance</dt><dd>PNG, sRGB, at least 150 effective DPI</dd></div><div><dt>Bound</dt><dd>Choose one image with no repair, or at most one repair</dd></div></dl>
      <p><a href={TECHNICAL_PRINT_SPECIFICATION.sourceUrl} target="_blank" rel="noopener noreferrer">Printful placement source ↗</a> · <a href="https://www.printful.com/creating-dtg-file" target="_blank" rel="noopener noreferrer">Print file guidance ↗</a> · <a href={FLUX_KLEIN_PROVIDER_TERMS[1]} target="_blank" rel="noopener noreferrer">BFL FLUX API terms ↗</a></p>
      <p className="creativeMuted">Print specification checked {utc(TECHNICAL_PRINT_SPECIFICATION.verifiedAt)}. The request explicitly selects PNG and 1024 × 1024; acceptance requires actual dimensions of at least 975 × 975 and at most 7 MB, with original PNG bytes and any provider marking retained. Actual returned dimensions and visual quality are checked before any PASS. The square background is intentional, not transparent.</p>
      {context.businesses.length && !data.errors.length ? <form action={approveCreativeCandidate} className="creativeForm">
        <input type="hidden" name="approvalId" value={randomUUID()} />
        <label className="creativeTextField">Original design concept<input name="concept" required minLength={3} maxLength={160} placeholder="Name your original design concept" /></label>
        <label className="creativeTextField">Intended audience<input name="audience" required minLength={3} maxLength={160} placeholder="Describe the intended adult audience" /></label>
        <label className="creativeTextField">Exact design instructions<textarea name="designInstructions" required minLength={50} maxLength={1500} rows={4} placeholder="Describe the original composition, colors and intentional opaque square background. Exclude text, brands, protected characters and reference artwork." /></label>
        <label className="creativeTextField">Image provider and output contract<select name="generatorModel" required defaultValue=""><option value="" disabled>Select a provider for this new approval</option><option value={FLUX_KLEIN_PNG_POLICY.modelId}>BFL FLUX.2 Klein 4B via OpenRouter · native PNG · request 1024 × 1024</option></select></label>
        <label className="creativeTextField">Image generation limit<select name="maximumGenerations" required defaultValue="1"><option value="1">One image, no repair (up to 4 provider calls)</option><option value="2">One image plus at most one repair (up to 6 provider calls)</option></select></label>
        <div className="creativeFormRow"><label>Business<select name="businessId" required>{scopedContext.businesses.map(b => <option key={b.id} value={b.id}>{b.name}</option>)}</select></label><label>Total allowance (USD)<input name="budgetUsd" type="number" min="0.01" max="1" step="0.01" defaultValue="0.55" required /></label></div>
        <label><input type="checkbox" name="confirmOriginalIntent" required />I approve the original concept and exact instructions above with no third-party references or protected elements; this is not a guarantee of universal non-infringement</label>
        <label><input type="checkbox" name="confirmTechnicalOnly" required />This is a technical creative test, not a market-validated product or publication approval</label>
        <label><input type="checkbox" name="confirmPrintSpec" required />I approve the named garment, physical print size and intentional opaque-square background</label>
        <label><input type="checkbox" name="confirmTerms" required />I accept the <a href={FLUX_KLEIN_PROVIDER_TERMS[0]} target="_blank" rel="noopener noreferrer">BFL developer terms</a> and <a href={FLUX_KLEIN_PROVIDER_TERMS[1]} target="_blank" rel="noopener noreferrer">BFL FLUX API terms</a> for this provider and understand AI provenance must be preserved</label>
        <label><input type="checkbox" name="confirmDataUse" required />I acknowledge that my design prompt goes to OpenRouter and Black Forest Labs. OpenRouter lists Black Forest Labs as not training on requests and retaining data for 30 days. A per-request data-collection denial, zero-data-retention route and override of BFL’s API contract have not been verified. BFL’s API terms include a training license; the route metadata is not a privacy guarantee</label>
        <label><input type="checkbox" name="confirmBudget" required />I approve this total allowance for the brief, IP screen, image and independent pixel review within the selected image limit. One image allows no repair; two allow at most one repair</label>
        <p className="creativeMuted">BFL FLUX.2 Klein 4B generates the image through OpenRouter; Luna writes the brief, and Claude reviews it. Fresh pricing is checked and each call reserved first. No automatic provider retries. Current declared estimate is checked against your allowance; it is not a provider-enforced invoice guarantee.</p>
        <ProductSubmitButton pendingText="Checking quote and saving…">Save specific approval</ProductSubmitButton>
      </form> : <p>Choose an available Business and resolve registry errors before approving a run.</p>}</div>
    </details></> },
{ id: "gallery", label: "Gallery", content: <><section aria-labelledby="creative-gallery"><h2 id="creative-gallery">Design gallery</h2><div className="creativeGallery"><ConsoleRecentRows label="Recent loaded artifacts records" rows={data.assets.map(asset => {
      const review = data.reviews.find(r => r.asset_id === asset.id), run = data.runs.find(r => r.id === asset.creative_run_id), approval = data.approvals.find(a => a.id === run?.approval_id);
      return <article className="creativePanel creativeAsset" key={asset.id}><div className="creativeImage">{asset.signedUrl ? <>
        {/* Private signed URLs must not enter a shared image-optimization cache. */}
        {/* eslint-disable-next-line @next/next/no-img-element */}
        <img src={asset.signedUrl} alt={`Generated version ${asset.version} of ${approval?.snapshot.concept ?? "original design"}`} loading="lazy" />
      </> : <p>Image preview unavailable; reload to refresh private access.</p>}</div><div className="creativeAssetBody"><div className="creativeTagRow"><span className="creativeTag">Version {asset.version}</span><span className="creativeTag">{review?.review.outcome ?? "Awaiting visual review"}</span><span className="creativeTag">{approval?.purpose.replaceAll("_", " ")}</span></div><h3>{approval?.snapshot.concept ?? "Generated design"}</h3><p>{asset.inspection.width} × {asset.inspection.height}px · {Math.floor(asset.inspection.effectiveDpi)} effective DPI · {asset.inspection.colorSpace}</p><p className="creativeMuted">{asset.model} via {asset.provider} · {utc(asset.generated_at)}</p>
        {asset.inspection.failedCriteria.length ? <p className="coreNotice coreNotice-danger">Binary gate: {asset.inspection.failedCriteria.join(", ")}</p> : null}
        {review ? <div className="creativeReview"><h4>Independent visual review</h4><ul>{review.review.checks.map(c => <li key={c.criterion}><strong>{c.outcome} · {c.criterion.replaceAll("_", " ")}</strong><p>{c.rationale}</p></li>)}</ul>{review.review.repairInstruction ? <p><strong>{approval?.snapshot.maximumGenerations === 1 ? "Reviewer repair suggestion (not authorized by this one-image approval):" : "Exact repair:"}</strong> {review.review.repairInstruction}</p> : null}<p className="creativeMuted">{review.reviewer_model} · {utc(review.created_at)}</p></div> : null}
        <details><summary>Prompt & immutable provenance</summary><pre>{asset.prompt}</pre><dl><dt>Asset SHA-256</dt><dd className="creativeHash">{asset.asset_hash}</dd><dt>Source brief SHA-256</dt><dd className="creativeHash">{asset.brief_hash}</dd></dl>
          {asset.provenance ? <><p>{asset.provenance.conversion === "lossless_webp_to_png" ? "Provider returned lossless WebP. This PNG is a derived print/review representation with identical decoded pixels and alpha; no resizing or upscaling was performed." : "Provider PNG retained byte-for-byte."}</p>
            <dl><dt>Original provider media type</dt><dd>{asset.provenance.detectedMediaType}</dd><dt>Original SHA-256</dt><dd className="creativeHash">{asset.provenance.originalSha256}</dd><dt>Normalization</dt><dd>{asset.provenance.version} · {asset.provenance.verification}</dd><dt>Decoder</dt><dd>{asset.provenance.decoder}</dd>{asset.provenance.encoder ? <><dt>PNG encoder</dt><dd>{asset.provenance.encoder}</dd></> : null}</dl>
            {asset.sourceSignedUrl ? <a href={asset.sourceSignedUrl} target="_blank" rel="noopener noreferrer">Open original provider file ↗</a> : <p>Original file access unavailable; refresh private access before use.</p>}
            <p className="creativeMuted">The original retains its embedded metadata. Pixel equality does not claim that the derived PNG retains embedded provenance or metadata.</p></> : <p>Historical asset: no normalization provenance was recorded.</p>}
        </details>
        <p className="creativeMuted">{approval?.purpose === "candidate_production" ? "Candidate design PASS records review against its saved approval and named print specification. Recheck current eligibility before use; publication requires separate authority." : "Technical PASS is a reviewable design artifact. It does not clear market evidence or authorize selling a product."}</p>
      </div></article>;
    })} /></div>{!data.assets.length ? <p className="creativeEmpty">No validated images were returned in this loaded gallery window. Review run history and provider receipts above; a failed validation may still have incurred a charge and retained an unvalidated source.</p> : null}</section></> },
{ id: "scope", label: "Design scope", content: <><section className="creativeIntro"><p className="coreEyebrow">Original design, bounded execution</p><h2>Every image keeps its source and verdict</h2><p>Technical qualification checks the creative pipeline. It does not prove product demand or change an earlier research decision. Candidate production requires a separate evidence-backed TEST and creative approval. Assets remain private to their Business.</p><Link href={`/dashboard/products${selectedBusiness ? `?business=${selectedBusiness.id}` : ""}`}>Review product evidence →</Link></section></> }]} /></AppShell>;
}
