import { validatePublicResearchRepairPolicy, type PublicResearchRepairPolicy } from "./discovery-r12-public-repair";
import { validatePublicResearchPolicy,type PublicResearchPolicy,type PublicResearchPhase } from "./discovery-r12-public-contracts";
import { publicResearchModelRequestBytes,validatePublicResearchQuote,type PublicResearchQuote } from "./discovery-r12-public-preparation";
import { exactPublicKeys as exact,publicHash as hash,publicInteger as integer,publicMoney as money,publicResearchFail as fail,publicResearchHash,publicTime as time,publicUuid as uuid,verifyPublicSelfHash } from "./discovery-r12-public-utils";
export type PublicResearchExecutionQuoteBinding={attemptOrdinal:number;windowAttemptOrdinal:number;phase:PublicResearchPhase;phaseAttemptId:string};
export type PublicResearchExecutionQuoteProof=PublicResearchExecutionQuoteBinding & {version:"r12.public-execution-quote-proof.1";policyHash:string;scopeHash:string;originDirectRunId:string;windowId:string;windowOrdinal:number;approvedQuoteHash:string;executionQuoteHash:string;routeEvidenceHash:string;authoritySnapshotHash:string;verifiedAt:string;validUntil:string;compatibilityHash:string};
export type PublicResearchExecutionQuoteAuthority={version:"r12.public-execution-authority.1";businessId:string;goalId:string;authorityRootId:string;envelopeHash:string;policyHash:string;phaseAttemptId:string;knownActualMicrounits:string;heldMaximumMicrounits:string;windowMaximumMicrounits:string;rootHeadroomMicrounits:string;businessHeadroomMicrounits:string;allocationHeadroomMicrounits:string;hasUnknownLiability:boolean;authorityActive:boolean;stopped:boolean;expiresAt:string;snapshotHash:string};
const same=(a:unknown,b:unknown)=>publicResearchHash(a)===publicResearchHash(b);
/** Quote identity stays immutable. Current catalogs are separately authenticated
 * by private server records. This comparator does not fetch or authorize them. */
export function validatePublicResearchExecutionQuoteCompatibility(approved:PublicResearchQuote,current:PublicResearchQuote,policy:PublicResearchPolicy|PublicResearchRepairPolicy,now=Date.now()):void{
 const p=(policy.version==="r12.direct-etsy-attempt-policy.2"?validatePublicResearchRepairPolicy(policy):validatePublicResearchPolicy(policy));validatePublicResearchQuote(approved,time(approved.verifiedAt));validatePublicResearchQuote(current,now);
 if(current.version!==approved.version||!same(publicResearchModelRequestBytes(current),publicResearchModelRequestBytes(approved))||p.quoteHash!==approved.quoteHash||approved.originalRunMaximumMicrounits!==p.originalRunMaximumMicrounits||current.originalRunMaximumMicrounits!==p.originalRunMaximumMicrounits||approved.maximumAttemptsInWindow!==p.window.maximumAttemptsInWindow||current.maximumAttemptsInWindow!==approved.maximumAttemptsInWindow||current.maximumModelDispatches!==approved.maximumModelDispatches||current.maximumSourceOperations!==approved.maximumSourceOperations||!same(current.inference.requestBytes,approved.inference.requestBytes)||!same(current.inference.outputTokens,approved.inference.outputTokens)||!same(current.inference.retention,approved.inference.retention)||money(current.maximumWindowMicrounits)>money(approved.maximumWindowMicrounits)||money(current.maximumAttemptMicrounits)>money(approved.maximumAttemptMicrounits))return fail("r12_public_execution_quote_expansion");
 for(const phase of ["plan","source","strategy","review"]as const)if(money(current.phaseMaximumMicrounits[phase])>money(approved.phaseMaximumMicrounits[phase])||money(approved.phaseMaximumMicrounits[phase])>money(p.phaseMaximumMicrounits[phase]))return fail("r12_public_execution_quote_phase_expansion");
 for(const key of ["luna","reviewer"]as const){const a=approved.inference[key],c=current.inference[key];for(const pin of ["modelId","canonicalModelId","endpoint","providerName","acceptedResponseModelIds"]as const)if(!same(a[pin],c[pin]))return fail("r12_public_execution_route_changed");if(c.priceLimit.prompt>a.priceLimit.prompt||c.priceLimit.completion>a.priceLimit.completion||c.priceLimit.request!==a.priceLimit.request)return fail("r12_public_execution_rate_limit_expansion");}
 for(const key of ["provider","category","providerProjectId","routeHash","tariffHash","qualificationHash","settlementContractHash","retentionDisclosure","zeroCostQualificationHash"]as const)if(current.browser[key]!==approved.browser[key])return fail("r12_public_execution_browser_terms_changed");
 if(current.browser.qualified!==true||approved.browser.providerProjectId!==p.browserAccountingPins.providerProjectId||approved.browser.routeHash!==p.browserAccountingPins.routeHash||approved.browser.tariffHash!==p.browserAccountingPins.tariffHash||approved.browser.qualificationHash!==p.browserAccountingPins.qualificationHash)return fail();
}
function validateBinding(b:PublicResearchExecutionQuoteBinding,p:PublicResearchPolicy|PublicResearchRepairPolicy):void{if(!exact(b,"attemptOrdinal,windowAttemptOrdinal,phase,phaseAttemptId")||!uuid(b.phaseAttemptId)||!["plan","source","strategy","review"].includes(b.phase)||!integer(b.windowAttemptOrdinal,1,p.window.maximumAttemptsInWindow)||b.attemptOrdinal!==p.window.baseAttemptsStarted+b.windowAttemptOrdinal)return fail();}
/** This snapshot must come from the complete locked private ledger. Includes
 * setup, all source/model failures and bounded pending maxima without refunds. */
export function qualifyPublicResearchExecutionQuote(approved:PublicResearchQuote,current:PublicResearchQuote,policy:PublicResearchPolicy|PublicResearchRepairPolicy,binding:PublicResearchExecutionQuoteBinding,authority:PublicResearchExecutionQuoteAuthority,routeEvidenceHash:string,now=Date.now()):PublicResearchExecutionQuoteProof{
 const p=(policy.version==="r12.direct-etsy-attempt-policy.2"?validatePublicResearchRepairPolicy(policy):validatePublicResearchPolicy(policy));validateBinding(binding,p);validatePublicResearchExecutionQuoteCompatibility(approved,current,p,now);
 if(!exact(authority,"version,businessId,goalId,authorityRootId,envelopeHash,policyHash,phaseAttemptId,knownActualMicrounits,heldMaximumMicrounits,windowMaximumMicrounits,rootHeadroomMicrounits,businessHeadroomMicrounits,allocationHeadroomMicrounits,hasUnknownLiability,authorityActive,stopped,expiresAt,snapshotHash")||authority.version!=="r12.public-execution-authority.1"||authority.phaseAttemptId!==binding.phaseAttemptId||authority.policyHash!==p.policyHash||authority.hasUnknownLiability!==false||authority.authorityActive!==true||authority.stopped!==false||time(authority.expiresAt)<=now||!hash(routeEvidenceHash))return fail("r12_public_execution_authority_unqualified");
 for(const key of ["businessId","goalId","authorityRootId","envelopeHash"]as const)if(authority[key]!==p[key])return fail();verifyPublicSelfHash(authority as unknown as Record<string,unknown>,"snapshotHash");
 const exposure=money(authority.knownActualMicrounits)+money(authority.heldMaximumMicrounits),next=money(p.phaseMaximumMicrounits[binding.phase]),window=money(authority.windowMaximumMicrounits);
 if(window<=BigInt(0)||window>money(p.originalRunMaximumMicrounits)||exposure+next>money(p.originalRunMaximumMicrounits)||exposure+next>window||[authority.rootHeadroomMicrounits,authority.businessHeadroomMicrounits,authority.allocationHeadroomMicrounits].some(x=>money(x)<next))return fail("r12_public_execution_budget_blocked");
 const body={version:"r12.public-execution-quote-proof.1"as const,policyHash:p.policyHash,scopeHash:p.scopeHash,originDirectRunId:p.originDirectRunId,windowId:p.window.windowId,windowOrdinal:p.window.windowOrdinal,...binding,approvedQuoteHash:approved.quoteHash,executionQuoteHash:current.quoteHash,routeEvidenceHash,authoritySnapshotHash:authority.snapshotHash,verifiedAt:new Date(now).toISOString(),validUntil:new Date(Math.min(time(current.validUntil),time(authority.expiresAt))).toISOString()};return{...body,compatibilityHash:publicResearchHash(body)};
}
export function validatePublicResearchExecutionQuoteProof(raw:unknown,approved:PublicResearchQuote,current:PublicResearchQuote,policy:PublicResearchPolicy|PublicResearchRepairPolicy,binding:PublicResearchExecutionQuoteBinding,expected:{routeEvidenceHash:string;authoritySnapshotHash:string},now=Date.now()):PublicResearchExecutionQuoteProof{
 if(!exact(raw,"version,policyHash,scopeHash,originDirectRunId,windowId,windowOrdinal,attemptOrdinal,windowAttemptOrdinal,phase,phaseAttemptId,approvedQuoteHash,executionQuoteHash,routeEvidenceHash,authoritySnapshotHash,verifiedAt,validUntil,compatibilityHash"))return fail();const v=raw as unknown as PublicResearchExecutionQuoteProof,p=(policy.version==="r12.direct-etsy-attempt-policy.2"?validatePublicResearchRepairPolicy(policy):validatePublicResearchPolicy(policy));validateBinding(binding,p);validatePublicResearchExecutionQuoteCompatibility(approved,current,p,now);
 if(v.version!=="r12.public-execution-quote-proof.1"||v.policyHash!==p.policyHash||v.scopeHash!==p.scopeHash||v.originDirectRunId!==p.originDirectRunId||v.windowId!==p.window.windowId||v.windowOrdinal!==p.window.windowOrdinal||v.approvedQuoteHash!==approved.quoteHash||v.executionQuoteHash!==current.quoteHash||v.routeEvidenceHash!==expected.routeEvidenceHash||v.authoritySnapshotHash!==expected.authoritySnapshotHash||![v.routeEvidenceHash,v.authoritySnapshotHash].every(hash)||time(v.verifiedAt)>now||time(v.verifiedAt)<time(current.verifiedAt)||time(v.validUntil)<=now||time(v.validUntil)>time(current.validUntil))return fail("r12_public_execution_quote_proof_unverified");for(const key of ["attemptOrdinal","windowAttemptOrdinal","phase","phaseAttemptId"]as const)if(v[key]!==binding[key])return fail();verifyPublicSelfHash(raw,"compatibilityHash");return structuredClone(v);
}
