import { PUBLIC_RESEARCH_PHASES,validatePublicResearchPolicy,validatePublicResearchHistory,validatePublicResearchCommand,validatePublicResearchSourceProof,type PublicResearchPolicy,type PublicResearchHistory,type PublicResearchPhase,type PublicResearchAcquisitionCommand,type PublicResearchSourceProof,type PublicResearchTerminal } from "./discovery-r12-public-contracts";
import { validatePublicResearchReviewedResult,assertPublicResearchFreshFollowup,type PublicResearchReviewedResult } from "./discovery-r12-public-review";
import { validatePublicResearchContinuation,type PublicResearchContinuation } from "./discovery-r12-public-window";
import { exactPublicKeys as exact,publicHash as hash,publicInteger as integer,publicMoney as money,publicResearchFail as fail,publicResearchHash,publicUuid as uuid,publicBoundedJson,verifyPublicSelfHash } from "./discovery-r12-public-utils";
export type PublicResearchDispatch={phase:PublicResearchPhase;attemptId:string;requestHash:string;executionQuoteHash:string;executionQuoteProofHash:string;receiptHash:string|null};
export type PublicResearchAttempt={ordinal:number;windowAttemptOrdinal:number;attemptId:string;kind:"initial"|"targeted"|"pivot"|"technical_retry";epochOrdinal:number;command:PublicResearchAcquisitionCommand;dispatches:PublicResearchDispatch[];sourceProof:PublicResearchSourceProof|null;status:"running"|"completed"|"technical_failed";review:PublicResearchReviewedResult|null;failureHash:string|null};
export type PublicResearchState={version:"r12.direct-etsy-attempt-state.1";policyHash:string;inherited:PublicResearchHistory;history:PublicResearchHistory;windowId:string;windowOrdinal:number;maximumAttemptsInWindow:number;windowAttemptsStarted:number;questComplete:false;researchWindowComplete:boolean;researchStageOutcome:null|"RESEARCH_PASSED_SUPPORTS_TEST"|"RESEARCH_PASSED_REJECTS_HYPOTHESIS"|"RESEARCH_FAILED_QUALITY"|"INSUFFICIENT_EVIDENCE"|"INVALID_RESEARCH";requiresReviewedRenewal:boolean;windowOutcome:null|"RESEARCH_FAILED_QUALITY"|"INSUFFICIENT_EVIDENCE"|"INVALID_RESEARCH";nextAttemptKind:PublicResearchAttempt["kind"]|null;pendingCommand:PublicResearchAcquisitionCommand|null;seenCriteriaHashes:string[];attempts:PublicResearchAttempt[];totalAttemptsStarted:number;modelDispatchesUsed:number;sourceOperationsStarted:number;cumulativeChildrenUsed:number;cumulativeDispatchesUsed:number;repairs:number;pivots:number;epochOrdinal:number;epochCriteriaHash:string|null;nmeCountInEpoch:number;terminal:PublicResearchTerminal|null;stateHash:string};
export type PublicResearchCapacity={approvedWindowHash:string;approvedMaximumAttemptsInWindow:number;cumulativeDispatchesCeiling:number;authorityActive:boolean;stopped:boolean;expired:boolean;hasUnknownLiability:boolean;liveGate:{quoteQualified:boolean;providerAccessQualified:boolean;sourcePurposeApproved:boolean;ownerApprovalBound:boolean;browserSettlementQualified:boolean};runCommittedMicrounits:string;rootHeadroomMicrounits:string;businessHeadroomMicrounits:string;activationAllocationHeadroomMicrounits:string};
const same=(a:unknown,b:unknown)=>publicResearchHash(a)===publicResearchHash(b);
const merge=(a:string[],b:string[])=>[...new Set([...a,...b])].sort();
function acquisition(raw:unknown):PublicResearchAcquisitionCommand{const x=validatePublicResearchCommand(raw);return x.kind==="finish"?fail():x;}
function derive(p:PublicResearchPolicy,inherited:PublicResearchHistory,attempts:PublicResearchAttempt[],initialCommand:PublicResearchAcquisitionCommand):PublicResearchState{
  const c=p.continuation,w=p.window;let epochOrdinal=c.epochOrdinal,epochCriteriaHash=c.epochCriteriaHash,nmeCountInEpoch=c.nmeCountInEpoch;
  let nextAttemptKind:PublicResearchState["nextAttemptKind"]=c.nextAttemptKind,pendingCommand:PublicResearchState["pendingCommand"]=c.nextCommand??initialCommand;
  let terminal:PublicResearchTerminal|null=null,windowOutcome:PublicResearchState["windowOutcome"]=null;
  let seenCriteriaHashes=[...c.seenCriteriaHashes],modelDispatchesUsed=c.modelDispatchesUsed,sourceOperationsStarted=c.sourceOperationsStarted,dispatches=0,repairs=p.baseRepairs,pivots=p.basePivots;
  const history=structuredClone(inherited);const ids=new Set<string>(),requests=new Set<string>(),operations=new Set<string>(),receipts=new Set<string>();
  if(publicResearchHash(inherited)!==p.inheritedStateHash||publicResearchHash(initialCommand)!==p.initialCommandHash)return fail();
  if(attempts.length>w.maximumAttemptsInWindow)return fail();
  for(const[i,a]of attempts.entries()){
    if(terminal||!exact(a,"ordinal,windowAttemptOrdinal,attemptId,kind,epochOrdinal,command,dispatches,sourceProof,status,review,failureHash")||a.ordinal!==w.baseAttemptsStarted+i+1||a.windowAttemptOrdinal!==i+1||!uuid(a.attemptId)||ids.has(a.attemptId)||a.kind!==nextAttemptKind||!pendingCommand||!same(a.command,pendingCommand)||!Array.isArray(a.dispatches)||a.dispatches.length<1||a.dispatches.length>4||!["running","completed","technical_failed"].includes(a.status))return fail();
    ids.add(a.attemptId);acquisition(a.command);
    if(a.kind==="initial"){if(i!==0||w.windowOrdinal!==1||epochCriteriaHash!==null||a.command.kind!=="targeted")return fail();epochCriteriaHash=a.command.criteriaHash;seenCriteriaHashes=[epochCriteriaHash];}
    else if(a.kind==="pivot"){if(nmeCountInEpoch!==4||a.command.kind!=="pivot"||seenCriteriaHashes.includes(a.command.criteriaHash))return fail();epochOrdinal++;epochCriteriaHash=a.command.criteriaHash;nmeCountInEpoch=0;pivots++;seenCriteriaHashes=merge(seenCriteriaHashes,[epochCriteriaHash]);}
    else{if(a.command.criteriaHash!==epochCriteriaHash)return fail();if(a.kind==="technical_retry")repairs++;}
    if(a.epochOrdinal!==epochOrdinal)return fail();
    for(const[j,d]of a.dispatches.entries()){
      if(!exact(d,"phase,attemptId,requestHash,executionQuoteHash,executionQuoteProofHash,receiptHash")||d.phase!==PUBLIC_RESEARCH_PHASES[j]||!uuid(d.attemptId)||![d.requestHash,d.executionQuoteHash,d.executionQuoteProofHash].every(hash)||(d.receiptHash!==null&&!hash(d.receiptHash))||ids.has(d.attemptId)||requests.has(d.requestHash)||(d.receiptHash!==null&&receipts.has(d.receiptHash))||j>0&&a.dispatches[j-1].receiptHash===null)return fail();
      ids.add(d.attemptId);requests.add(d.requestHash);if(d.receiptHash)receipts.add(d.receiptHash);dispatches++;if(d.phase==="source")sourceOperationsStarted++;else modelDispatchesUsed++;
    }
    if(a.dispatches.length>=3&&!a.sourceProof)return fail();
    if(a.sourceProof){const s=validatePublicResearchSourceProof(a.sourceProof,p),d=a.dispatches[1];if(!d||s.sourceAttemptId!==d.attemptId||s.requestHash!==d.requestHash||s.receiptHash!==d.receiptHash||s.executionQuoteHash!==d.executionQuoteHash||s.executionQuoteProofHash!==d.executionQuoteProofHash||s.attemptOrdinal!==a.ordinal||s.criteriaHash!==a.command.criteriaHash||s.questionHash!==a.command.questionHash||operations.has(s.operationId))return fail();operations.add(s.operationId);
      // Fresh navigation alone is not novelty; both literal and typed identities
      // must add information beyond all archived and earlier selected sources.
      if(!s.witnesses.some(x=>!history.seenEvidenceIdentityHashes.includes(x.evidenceIdentityHash)&&!history.seenFactIdentityHashes.includes(x.factIdentityHash)))return fail("r12_public_source_repetition");
      history.seenEvidenceIdentityHashes=merge(history.seenEvidenceIdentityHashes,s.witnesses.map(x=>x.evidenceIdentityHash));history.seenFactIdentityHashes=merge(history.seenFactIdentityHashes,s.witnesses.map(x=>x.factIdentityHash));
    }
    history.seenQuestionHashes=merge(history.seenQuestionHashes,[a.command.questionHash]);
    nextAttemptKind=null;pendingCommand=null;
    if(a.status==="running"){if(i!==attempts.length-1||a.review!==null||a.failureHash!==null)return fail();}
    else if(a.status==="technical_failed"){
      if(a.review!==null||!hash(a.failureHash)||a.dispatches.some(d=>d.receiptHash===null))return fail();history.consecutiveNonprogress++;nextAttemptKind="technical_retry";pendingCommand=a.command;windowOutcome="INVALID_RESEARCH";
    }else{
      if(!a.review||a.failureHash!==null||a.dispatches.length!==4||a.dispatches.some(d=>d.receiptHash===null)||!a.sourceProof)return fail();const r=validatePublicResearchReviewedResult(a.review,p);
      if(r.attemptOrdinal!==a.ordinal||r.criteriaHash!==a.command.criteriaHash||r.questionHash!==a.command.questionHash||r.strategyReceiptHash!==a.dispatches[2].receiptHash||r.reviewReceiptHash!==a.dispatches[3].receiptHash)return fail();
      if(r.outcome!=="NME"){terminal=r.terminal;history.consecutiveNonprogress=0;windowOutcome=null;}
      else{nmeCountInEpoch++;history.consecutiveNonprogress++;windowOutcome=r.quality.passed?"INSUFFICIENT_EVIDENCE":"RESEARCH_FAILED_QUALITY";
        const command=acquisition(r.proposedCommand);assertPublicResearchFreshFollowup(command,history.seenQuestionHashes,attempts.slice(0,i+1).map(x=>x.command.query));if(nmeCountInEpoch===4){if(command.kind!=="pivot"||seenCriteriaHashes.includes(command.criteriaHash)||command.changedCriterion===null)return fail("r12_public_fourth_nme_requires_pivot");nextAttemptKind="pivot";}
        else{if(command.kind!=="targeted"||command.criteriaHash!==epochCriteriaHash)return fail("r12_public_targeted_followup_required");nextAttemptKind="targeted";}pendingCommand=command;
      }
    }
  }
  if(p.baseDispatches+dispatches>p.cumulativeDispatchesCeiling||modelDispatchesUsed-c.modelDispatchesUsed>p.maximumModelDispatches||sourceOperationsStarted-c.sourceOperationsStarted>p.maximumSourceOperations)return fail();
  const exhausted=attempts.length===w.maximumAttemptsInWindow&&attempts.at(-1)?.status!=="running"&&terminal===null;
  if(exhausted)terminal="RESEARCH_INSUFFICIENT_AT_WINDOW_LIMIT";
  const body={version:"r12.direct-etsy-attempt-state.1"as const,policyHash:p.policyHash,inherited,history,windowId:w.windowId,windowOrdinal:w.windowOrdinal,maximumAttemptsInWindow:w.maximumAttemptsInWindow,windowAttemptsStarted:attempts.length,questComplete:false as const,researchWindowComplete:terminal!==null,researchStageOutcome:terminal==="RESEARCH_PASSED_SUPPORTS_TEST"||terminal==="RESEARCH_PASSED_REJECTS_HYPOTHESIS"?terminal:exhausted?windowOutcome:null,requiresReviewedRenewal:exhausted,windowOutcome:exhausted?windowOutcome:null,nextAttemptKind,pendingCommand,seenCriteriaHashes,attempts,totalAttemptsStarted:w.baseAttemptsStarted+attempts.length,modelDispatchesUsed,sourceOperationsStarted,cumulativeChildrenUsed:p.cumulativeChildrenCeiling,cumulativeDispatchesUsed:p.baseDispatches+dispatches,repairs,pivots,epochOrdinal,epochCriteriaHash,nmeCountInEpoch,terminal};
  return{...body,stateHash:publicResearchHash(body)};
}
export function createPublicResearchState(policy:PublicResearchPolicy,inherited:PublicResearchHistory,initialCommand:PublicResearchAcquisitionCommand):PublicResearchState{return derive(validatePublicResearchPolicy(policy),validatePublicResearchHistory(inherited),[],acquisition(initialCommand));}
export function validatePublicResearchState(raw:unknown,policy:PublicResearchPolicy):PublicResearchState{
  if(!exact(raw,"version,policyHash,inherited,history,windowId,windowOrdinal,maximumAttemptsInWindow,windowAttemptsStarted,questComplete,researchWindowComplete,researchStageOutcome,requiresReviewedRenewal,windowOutcome,nextAttemptKind,pendingCommand,seenCriteriaHashes,attempts,totalAttemptsStarted,modelDispatchesUsed,sourceOperationsStarted,cumulativeChildrenUsed,cumulativeDispatchesUsed,repairs,pivots,epochOrdinal,epochCriteriaHash,nmeCountInEpoch,terminal,stateHash"))return fail();publicBoundedJson(raw);const s=raw as unknown as PublicResearchState,p=validatePublicResearchPolicy(policy);
  if(!Array.isArray(s.attempts)||!s.pendingCommand&&!s.attempts.length)return fail();const first=s.attempts[0]?.command??s.pendingCommand!;
  const derived=derive(p,validatePublicResearchHistory(s.inherited),s.attempts,first);if(!same(s,derived))return fail("r12_public_state_replay_mismatch");return structuredClone(derived);
}
export function startPublicResearchAttempt(policy:PublicResearchPolicy,state:PublicResearchState,input:{expectedStateHash:string;attemptId:string;planAttemptId:string;planRequestHash:string;executionQuoteHash:string;executionQuoteProofHash:string;command:PublicResearchAcquisitionCommand;capacity:PublicResearchCapacity}):PublicResearchState{
  const p=validatePublicResearchPolicy(policy),s=validatePublicResearchState(state,p),c=input.capacity;
  if(input.expectedStateHash!==s.stateHash||s.terminal||s.attempts.at(-1)?.status==="running"||!s.pendingCommand||!same(s.pendingCommand,input.command)||!s.nextAttemptKind)return fail("r12_public_attempt_not_admitted");
  if(p.window.windowOrdinal!==1)return fail("r12_public_renewal_activation_unqualified");
  if(p.sourceAccess.allowedSource==="etsy_authenticated_insights")return fail("r12_public_insights_source_adapter_unqualified");
  if(c.approvedWindowHash!==publicResearchHash(p.window)||!integer(c.approvedMaximumAttemptsInWindow,1,32)||p.window.maximumAttemptsInWindow>c.approvedMaximumAttemptsInWindow||!integer(c.cumulativeDispatchesCeiling)||s.cumulativeDispatchesUsed+4>Math.min(c.cumulativeDispatchesCeiling,p.cumulativeDispatchesCeiling)||c.authorityActive!==true||c.stopped!==false||c.expired!==false||c.hasUnknownLiability!==false||!exact(c.liveGate,"quoteQualified,providerAccessQualified,sourcePurposeApproved,ownerApprovalBound,browserSettlementQualified")||Object.values(c.liveGate).some(x=>x!==true))return fail("r12_public_authority_or_capacity_blocked");
  const maximum=PUBLIC_RESEARCH_PHASES.reduce((n,k)=>n+money(p.phaseMaximumMicrounits[k]),BigInt(0));
  if(money(c.runCommittedMicrounits)+maximum>money(p.originalRunMaximumMicrounits)||[c.rootHeadroomMicrounits,c.businessHeadroomMicrounits,c.activationAllocationHeadroomMicrounits].some(x=>money(x)<maximum))return fail("r12_public_budget_blocked");
  const a:PublicResearchAttempt={ordinal:p.window.baseAttemptsStarted+s.attempts.length+1,windowAttemptOrdinal:s.attempts.length+1,attemptId:input.attemptId,kind:s.nextAttemptKind,epochOrdinal:s.epochOrdinal+(s.nextAttemptKind==="pivot"?1:0),command:input.command,dispatches:[{phase:"plan",attemptId:input.planAttemptId,requestHash:input.planRequestHash,executionQuoteHash:input.executionQuoteHash,executionQuoteProofHash:input.executionQuoteProofHash,receiptHash:null}],sourceProof:null,status:"running",review:null,failureHash:null};
  return derive(p,s.inherited,[...s.attempts,a],s.attempts[0]?.command??input.command);
}
function mutate(policy:PublicResearchPolicy,state:PublicResearchState,change:(a:PublicResearchAttempt)=>void):PublicResearchState{const p=validatePublicResearchPolicy(policy),s=validatePublicResearchState(state,p),a=s.attempts.at(-1);if(!a||a.status!=="running"||s.terminal)return fail();change(a);return derive(p,s.inherited,s.attempts,s.attempts[0].command);}
export function markPublicResearchDispatch(p:PublicResearchPolicy,s:PublicResearchState,d:PublicResearchDispatch):PublicResearchState{return mutate(p,s,a=>{if(d.receiptHash!==null)return fail();a.dispatches.push(d);});}
export function recordPublicResearchReceipt(p:PublicResearchPolicy,s:PublicResearchState,phase:PublicResearchPhase,receiptHash:string,sourceProof?:PublicResearchSourceProof):PublicResearchState{return mutate(p,s,a=>{const d=a.dispatches.at(-1);if(!d||d.phase!==phase||d.receiptHash!==null||!hash(receiptHash))return fail();d.receiptHash=receiptHash;if(sourceProof){if(phase!=="source")return fail();a.sourceProof=sourceProof;}});}
export function completePublicResearchAttempt(p:PublicResearchPolicy,s:PublicResearchState,review:PublicResearchReviewedResult):PublicResearchState{return mutate(p,s,a=>{a.review=review;a.status="completed";});}
export function failPublicResearchAttempt(p:PublicResearchPolicy,s:PublicResearchState,failureHash:string):PublicResearchState{return mutate(p,s,a=>{a.failureHash=failureHash;a.status="technical_failed";});}
export function publicResearchNextStep(p:PublicResearchPolicy,raw:PublicResearchState){const s=validatePublicResearchState(raw,p);return{terminal:s.terminal,questComplete:s.questComplete,researchWindowComplete:s.researchWindowComplete,researchStageOutcome:s.researchStageOutcome,requiresReviewedRenewal:s.requiresReviewedRenewal,nextAttemptKind:s.nextAttemptKind,command:s.pendingCommand,remainingAttempts:p.window.maximumAttemptsInWindow-s.windowAttemptsStarted};}
export function publicResearchContinuationFromState(policy:PublicResearchPolicy,state:PublicResearchState):PublicResearchContinuation{
  const p=validatePublicResearchPolicy(policy),s=validatePublicResearchState(state,p);if(!s.requiresReviewedRenewal||!s.nextAttemptKind||!s.pendingCommand)return fail();
  const body={version:"r12.research-window-continuation.1"as const,originDirectRunId:p.originDirectRunId,previousWindowStateHash:s.stateHash,historyHash:publicResearchHash(s.history),totalAttemptsStarted:s.totalAttemptsStarted,modelDispatchesUsed:s.modelDispatchesUsed,sourceOperationsStarted:s.sourceOperationsStarted,epochOrdinal:s.epochOrdinal,epochCriteriaHash:s.epochCriteriaHash,nmeCountInEpoch:s.nmeCountInEpoch,seenCriteriaHashes:s.seenCriteriaHashes,nextAttemptKind:s.nextAttemptKind,nextCommand:s.pendingCommand};return validatePublicResearchContinuation({...body,continuationHash:publicResearchHash(body)});
}
export function validatePublicResearchRenewalProjection(previousPolicy:PublicResearchPolicy,previousState:PublicResearchState,nextPolicy:PublicResearchPolicy):void{
  const old=validatePublicResearchPolicy(previousPolicy),s=validatePublicResearchState(previousState,old),next=validatePublicResearchPolicy(nextPolicy),continuation=publicResearchContinuationFromState(old,s);
  for(const k of ["businessId","goalId","authorityRootId","originDirectRunId","originalSemanticGoalHash","envelopeHash","originalRunMaximumMicrounits","businessLifetimeLimitMicrounits","rootLifetimeLimitMicrounits"]as const)if(next[k]!==old[k])return fail();
  if(!same(continuation,next.continuation)||next.window.windowOrdinal!==old.window.windowOrdinal+1||next.window.windowId===old.window.windowId||next.inheritedStateHash!==publicResearchHash(s.history)||next.baseChildren!==s.cumulativeChildrenUsed||next.baseDispatches!==s.cumulativeDispatchesUsed||next.baseRepairs!==s.repairs||next.basePivots!==s.pivots||money(next.baseKnownMicrounits)<money(old.baseKnownMicrounits))return fail("r12_public_renewal_reset_rejected");
  verifyPublicSelfHash(next as unknown as Record<string,unknown>,"policyHash");
}
